### ISSUE TITLE
Easy Mode

### ISSUE THREAD

**Issue by JadeGrey** [Prodigy-Hacking/ProdigyMathGameHacking#1]
breaks battles

**Comment by PatheticMustan** [comment]
```
// TODO: Investigate why easy mode breaks battles
PIXI.game.prodigy.debugMisc.easyMode(1, 100); // Easy mode, 100% correct
```

Yeah, I know about this issue. I'm not exactly sure why this happens. Maybe I'm missing something important. I'll look into this issue. In the meantime, do you have any suggestions for hacks?

**Comment by bruh5000** [comment]
i have a suggestion
we could find out how to get past enemies w/o getting attacked
and
find out how to fully complete quest w/o just quest requirements

**Comment by bruh5000** [comment]
i tried the `PIXI.game.prodigy.debugQuests.completeQuestRequirements("")` with the area in the quotes but takes a while to just complete one job and not all jobs can be completed

**Comment by PatheticMustan** [comment]
@bruh5000, you can complete quests with the function you just said.

Here's a list of all the possible zones:
```
forest
shiverchill
skywatch
lamplight
dyno
bonfire_spire
house
toyzone
shipwreck_shore
darktower
academy
archives
earthtower
tower_town
```

Make sure you type the zone EXACTLY as it is. It's case sensitive, and if you mis-type it, it won't work.

**Comment by Avn1114** [comment]
Well, we now have Teleport.js, so this matter is a little less pressing at this point...

**Comment by Avn1114** [comment]
I noticed, that as @bruh5000 said earlier, the `PIXI.game.prodigy.debugQuests.completeQuestRequirements("")` script does NOT work for all quests. We should try and look into this, and see whether different quests function in different ways...

**Comment by PatheticMustan** [comment]
What quests don't work?

**Comment by Avn1114** [comment]
Boss fight quests, and occasionally ones that involve picking up items.
Other than that, there's no exact pattern.

**Comment by PatheticMustan** [comment]
Until we find gameconstants, this will be closed.

**Comment by Avn1114** [comment]
OK

**Comment by Avn1114** [comment]
I may have found an alternative to `easyMode`... possibly `PIXI.game.prodigy.player.modifiers.miss` would be effective in this case? Because as I see it, whenever you get a question wrong, it sets `miss` to one, or a hundred, or whatever. If we were able to just set `miss` back to 0, than even though you get the question wrong, you never miss???

**Comment by iamtheone12345** [comment]
This isn't related but you can get out of multiplayer battles using the escape hack. The battle won't count as a loss. I do it all the time to stallers.

**Comment by iamtheone12345** [comment]
However, you won't get any points.

**Comment by Avn1114** [comment]
That would make sense. Thanks for figuring that out.

**Comment by GyarGG** [comment]
when i use escapeBattle in multiplayer, it marks that as a loss for me... and i still dont get points ;0

**Comment by TehVegasPro763-22** [comment]
Use this, buddy: javascript:(function()%7BPIXI.game.prodigy.debugMisc.escapeBattle()%7D)()%3B

**Comment by Diveodile** [comment]
> @bruh5000, you can complete quests with the function you just said.
> 
> Here's a list of all the possible zones:
> 
> ```
> forest
> shiverchill
> skywatch
> lamplight
> dyno
> bonfire_spire
> house
> toyzone
> shipwreck_shore
> darktower
> academy
> archives
> earthtower
> tower_town
> ```
> 
> Make sure you type the zone EXACTLY as it is. It's case sensitive, and if you mis-type it, it won't work.

What's the toy zone

**Comment by QWERTYUIOP-a11y** [comment]
> > @bruh5000, you can complete quests with the function you just said.
> > Here's a list of all the possible zones:
> > ```
> > forest
> > shiverchill
> > skywatch
> > lamplight
> > dyno
> > bonfire_spire
> > house
> > toyzone
> > shipwreck_shore
> > darktower
> > academy
> > archives
> > earthtower
> > tower_town
> > ```
> > 
> > 
> > Make sure you type the zone EXACTLY as it is. It's case sensitive, and if you mis-type it, it won't work.
> 
> What's the toyzone?
>:(

**Comment by QWERTYUIOP-a11y** [comment]
> @bruh5000, you can complete quests with the function you just said.
> 
> Here's a list of all the possible zones:
> 
> ```
> forest
> shiverchill
> skywatch
> lamplight
> dyno
> bonfire_spire
> house
> toyzone
> shipwreck_shore
> darktower
> academy
> archives
> earthtower
> tower_town
> ```
> 
> Make sure you type the zone EXACTLY as it is. It's case sensitive, and if you mis-type it, it won't work.

"PIXI.game.prodigy" parts are required but I'm confused and angry but I know the zone names >:(

**Comment by Avn1114** [comment]
Finally, done! Run 
```
e=await (await fetch("https://api.prodigygame.com/game-api/status")).json();CryptoJS.MD5 = () => ({ toString: () => e.data.prodigyGameFlags.debugPassword });enableDebug('',!0)
easyMode()
```
to enable `easyMode` without breaking battles!

**Comment by PatheticMustan** [comment]
Bookmarklet
```
javascript:console=0;e=await (await fetch("https://api.prodigygame.com/game-api/status")).json();CryptoJS.MD5=_=>({toString:_=>e.data.prodigyGameFlags.debugPassword });enableDebug('',!0);easyMode();
```

**Comment by PatheticMustan** [comment]
Now all we have to do is update the existing hacks

**Comment by Robo-Ren** [comment]
Pathetic is their a code for we could level up all our pets to level 100?

**Comment by PatheticMustan** [comment]
```javascript
let x = hack.modules[0].exports.a.instance.prodigy.player.kennel.data;
for (let i=0; i<x.length; i++) { 
    x[i].level=100;
};
```

**Comment by Avn1114** [comment]
Alright, we've found a possible method using `hack.constants`, but we need to look into it further.

**Comment by Avn1114** [comment]
We should still research this, it was possible with `enableDebug` awhile back, so we know it is accessible.

**Comment by Avn1114** [comment]
Stop that, will >,<

**Comment by TNThacker2015** [comment]
we could use gameConstants to enable easy mode.

**Comment by kayla-hue** [comment]
Question people does this still works 
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/3247f89b059de1cafc4fda6e981ecda9a9d092ba/willsCheatMenu/src/hacks/misc.ts

**Comment by kayla-hue** [comment]
Is the hack patched?

**Comment by ooo788** [comment]
![image](https://user-images.githubusercontent.com/62513880/89305595-b2315b80-d623-11ea-90a5-d176b96b472d.png)

**Comment by ooo788** [comment]
HOW?!

**Comment by PatheticMustan** [comment]
@ooo788, instead of polluting our Github issue threads, you should join our official Discord server.

https://discord.gg/XQDfbfq

**Comment by PatheticMustan** [comment]
whatever, easymode doesn't exist anymore.

**Comment by NX721** [comment]
The first issue...

**Comment by PatheticMustan** [comment]
indeed, I don't know if we ever finished it....

**Comment by NX721** [comment]
Lmao

**Comment by NX721** [comment]
Hmm I can try finding this...

**Comment by GokuUltraInstict13** [comment]
Hey, maybe you can have a Use an older version hack to use easy mode.
Maybe...

**Comment by GokuUltraInstict13** [comment]
but I'm guessing it would break/crash the game.

**Comment by LeoBadeaux** [comment]
this happening or what, it is on our TODO (#800)?

**Comment by ArcerionDev** [comment]
it's more difficult than it looks lmao, we're looking into it

**Comment by technobyteongithub** [comment]
I love how this is the first ticket and it's still open

**Comment by ArcerionDev** [comment]
it's impossibleeeeeeeeee stfuuu asodhasjdkahs

**Comment by PatheticMustan** [comment]
Pain

**Comment by ArcerionDev** [comment]
eternal pain

**Comment by BETPRODIGYHACKER** [comment]
yep a big big big pain

**Comment by hostedposted** [comment]
Not sure if this helps but I found this
```js
            }, i.prototype.handleEasyMode = function() {
                p.b.get("GameConstants.Debug.EDUCATION_ENABLED") || (this.questionOpened = !0)
            },
```

**Comment by hostedposted** [comment]
it was in this
```js
        cb = function(t) {
            function i(i, n) {
                var e = t.call(this) || this;
                return e.questionInterface = null, e.questionOpened = !1, e.logger = null, e.lastLogTime = Date.now(), e.questionInterface = i, i.OnQuestionOpened.add(e.markQuestionOpened, e), i.OnQuestionAnswered.add(e.handleEasyMode, e), e.logger = n, e
            }
            return Object(o.__extends)(i, t), Object.defineProperty(i.prototype, "NextState", {
                get: function() {
                    return Ka.AnsweringQuestion
                },
                enumerable: !1,
                configurable: !0
            }), i.prototype.shouldTransition = function() {
                var t = Date.now();
                if (this.questionOpened || t - this.lastLogTime > 3e3) {
                    this.lastLogTime = t;
                    var i = "OpenQuestionInterfaceDecision\nTransition to " + this.NextState + "? " + (this.questionOpened ? "YES" : "NO") + "\n";
                    i += "\t - Interface is open? " + (this.questionOpened ? "YES" : "NO") + "\n", this.logger.logMessage(i)
                }
                return this.questionOpened
            }, i.prototype.markQuestionOpened = function() {
                this.questionOpened = !0
            }, i.prototype.handleEasyMode = function() {
                p.b.get("GameConstants.Debug.EDUCATION_ENABLED") || (this.questionOpened = !0)
            }, i.prototype.destroy = function() {
                this.questionInterface.OnQuestionOpened.remove(this.markQuestionOpened, this), this.questionInterface.OnQuestionAnswered.remove(this.handleEasyMode, this)
            }, i
        }(Yf),
```

**Comment by hostedposted** [comment]
## I think easy mode's impossible now.

I decoded the map file for prodigy.

In prodigy's code there is a DEBUG_CODE variable that is undefined. But using the [Define Plugin](https://webpack.js.org/plugins/define-plugin/) for webpack they could set it for dev only.

They use it for lots of things in the game. But the functions that use DEBUG_CODE don't have it in the game. So the only way we would be able to do it is build the prodigy game file with the debug code.

We can get the debug code in the game status:
```py
import prodigy
prodigy.gameStatus()["prodigyGameFlags"]["debugPassword"]
```

But after decoding the source map not all files are there.

This code ![image](https://user-images.githubusercontent.com/70211235/126875403-220b1927-66a1-4063-aa8b-53b94c90138a.png) in ``4-21-0/src/feature/mathTower/MathTower.ts`` does not work because ``4-21-0/src/systems/injection/EProdigyInjectionIdentifiers.ts`` does not exist
![image](https://user-images.githubusercontent.com/70211235/126875474-3241a447-b98e-4bec-a3c6-25c83d758fb1.png)

### If we build the gamefile with DEBUG_CODE.

This code is the code executed when a question is popped up.
```ts
    /**
     * Opens a question for the player to answer
     */
    public answerQuestion(): void {
        if (DEBUG_CODE) {
            if (!GameConstants.get('GameConstants.Debug.EDUCATION_ENABLED')) {
                const wasCorrect: boolean = Math.random() < GameConstants.get('GameConstants.Debug.AUTO_ANSWER_CORRECT_PERCENT');
                this.onQuestionAnswered.dispatch(wasCorrect, 0, null);
                if (wasCorrect) {
                    this.onQuestionAnsweredCorrectly.dispatch(0, null);
                } else {
                    this.onQuestionAnsweredIncorrectly.dispatch(0, null);
                }
                return;
            }
        }

        if (!this._isOpen) {
            this._isOpen = true;
            const input: Input = App.instance.game.input;
            const inputEnabled: boolean = input.enabled;
            input.enabled = false;
            const notifications: NotificationController = App.instance.prodigy.notifications;
            notifications.pause(this);
            notifications.clearNotifications();
            App.instance.prodigy.education.question(
                (wasCorrect: boolean, responseTime?: number, nFactor?: number, awardPrize?: boolean, awardInstantWin?: boolean, skill?: SkillDataSchema) => {
                    this._isOpen = false;
                    input.enabled = inputEnabled;
                    notifications.resume(this);
                    this.onQuestionAnswered.dispatch(wasCorrect, responseTime, skill);
                    if (wasCorrect) {
                        this.onQuestionAnsweredCorrectly.dispatch(responseTime, skill);
                    } else {
                        this.onQuestionAnsweredIncorrectly.dispatch(responseTime, skill);
                    }
                },
                undefined,
                undefined,
                undefined,
                undefined,
                false
            );
        }
    }
```

So if we run 
```js
_.constants.constants["GameConstants.Debug.EDUCATION_ENABLED"] = true
_.constants.constants["GameConstants.Debug.AUTO_ANSWER_CORRECT_PERCENT"] = 1
```
it will enable easy mode but we will need to rebuild prodigy's gamefile every update with a new debug code.
We probably won't even be able to build it once.

**Comment by JeaIousy** [comment]
hosted why arnt u on discord?

**Comment by hostedposted** [comment]
Trying to get into my account forgot the password.

**Comment by JeaIousy** [comment]
cant you use forgot password?

**Comment by hostedposted** [comment]
I'm also on vacation now

**Comment by JeaIousy** [comment]
ohh ok

**Comment by hostedposted** [comment]
I just remembered my password

**Comment by ArcerionDev** [comment]
> ## I think easy mode's impossible now.
> I decoded the map file for prodigy.
> 
> In prodigy's code there is a DEBUG_CODE variable that is undefined. But using the [Define Plugin](https://webpack.js.org/plugins/define-plugin/) for webpack they could set it for dev only.
> 
> They use it for lots of things in the game. But the functions that use DEBUG_CODE don't have it in the game. So the only way we would be able to do it is build the prodigy game file with the debug code.
> 
> We can get the debug code in the game status:
> 
> ```python
> import prodigy
> prodigy.gameStatus()["prodigyGameFlags"]["debugPassword"]
> ```
> 
> But after decoding the source map not all files are there.
> 
> This code ![image](https://user-images.githubusercontent.com/70211235/126875403-220b1927-66a1-4063-aa8b-53b94c90138a.png) in `4-21-0/src/feature/mathTower/MathTower.ts` does not work because `4-21-0/src/systems/injection/EProdigyInjectionIdentifiers.ts` does not exist
> ![image](https://user-images.githubusercontent.com/70211235/126875474-3241a447-b98e-4bec-a3c6-25c83d758fb1.png)
> 
> ### If we build the gamefile with DEBUG_CODE.
> This code is the code executed when a question is popped up.
> 
> ```ts
>     /**
>      * Opens a question for the player to answer
>      */
>     public answerQuestion(): void {
>         if (DEBUG_CODE) {
>             if (!GameConstants.get('GameConstants.Debug.EDUCATION_ENABLED')) {
>                 const wasCorrect: boolean = Math.random() < GameConstants.get('GameConstants.Debug.AUTO_ANSWER_CORRECT_PERCENT');
>                 this.onQuestionAnswered.dispatch(wasCorrect, 0, null);
>                 if (wasCorrect) {
>                     this.onQuestionAnsweredCorrectly.dispatch(0, null);
>                 } else {
>                     this.onQuestionAnsweredIncorrectly.dispatch(0, null);
>                 }
>                 return;
>             }
>         }
> 
>         if (!this._isOpen) {
>             this._isOpen = true;
>             const input: Input = App.instance.game.input;
>             const inputEnabled: boolean = input.enabled;
>             input.enabled = false;
>             const notifications: NotificationController = App.instance.prodigy.notifications;
>             notifications.pause(this);
>             notifications.clearNotifications();
>             App.instance.prodigy.education.question(
>                 (wasCorrect: boolean, responseTime?: number, nFactor?: number, awardPrize?: boolean, awardInstantWin?: boolean, skill?: SkillDataSchema) => {
>                     this._isOpen = false;
>                     input.enabled = inputEnabled;
>                     notifications.resume(this);
>                     this.onQuestionAnswered.dispatch(wasCorrect, responseTime, skill);
>                     if (wasCorrect) {
>                         this.onQuestionAnsweredCorrectly.dispatch(responseTime, skill);
>                     } else {
>                         this.onQuestionAnsweredIncorrectly.dispatch(responseTime, skill);
>                     }
>                 },
>                 undefined,
>                 undefined,
>                 undefined,
>                 undefined,
>                 false
>             );
>         }
>     }
> ```
> 
> So if we run
> 
> ```js
> _.constants.constants["GameConstants.Debug.EDUCATION_ENABLED"] = true
> _.constants.constants["GameConstants.Debug.AUTO_ANSWER_CORRECT_PERCENT"] = 1
> ```
> 
> it will enable easy mode but we will need to rebuild prodigy's gamefile every update with a new debug code.
> We probably won't even be able to build it once.

thanks for looking into this, but
> We probably won't even be able to build it once

why is this

**Comment by hostedposted** [comment]
some of the imports import from files that don't exist

**Comment by ArcerionDev** [comment]
> some of the imports import from files that don't exist

oh I see

**Comment by hostedposted** [comment]
I was able to add easy mode by making some changes in p-np which allow education enabled to be set to false without crashing the game. WCM commit: https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/75fdbc8f981edc465816306657d47941dafa18e5. P-NP commit: https://github.com/Prodigy-Hacking/P-NP/commit/847f0a02ec8c08f7bffc97db027509a2877513d2

**Comment by LeoBadeaux** [comment]
🎉🎉🎉
