### ISSUE TITLE
PMGH is blocked

### ISSUE THREAD

**Issue by Bruceq3456** [Prodigy-Hacking/ProdigyMathGameHacking#1006]
Each time I try to get into prodigygame.com,it says the school is blocking the hacks.

More info:TypeError: Failed to fetch.

**Comment by BoredFishRE** [comment]
Can you visit https://prodigyhacking.com or is it blocked.

**Comment by Bruceq3456** [comment]
I can vist it.

**Comment by jakedasnake1** [comment]
It's doing the same for me and I'm on my own server that has not blocks.

**Comment by jakedasnake1** [comment]
It's working again.

**Comment by da638** [comment]
wait you can do the hacks on a school computer?

**Comment by LeoBadeaux** [comment]
> It's working again.

D'accord, fermé.
