### ISSUE TITLE
i heard you can do the hacks on school computer!

### ISSUE THREAD

**Issue by da638** [Prodigy-Hacking/ProdigyMathGameHacking#1009]
i heard you can do the hacks on a school computer and i really want to try that so someone plz send me a video plzzzzz

**Comment by da638** [comment]
also developer mode is blocked on chrome extensions so i dont know what to do about that

**Comment by SakuraKitsunee** [comment]
@da638 i'm pretty sure you can't, unless you can access a web proxy or something else like that

**Comment by da638** [comment]
but there have been some comments and people doing it on school computer

**Comment by LeoBadeaux** [comment]
You can't
