### ISSUE TITLE
can i coallb with you guys!!!!!!!

### ISSUE THREAD

**Issue by da638** [Prodigy-Hacking/ProdigyMathGameHacking#1010]
i wanna collab with  you

**Comment by AGR-DEVS** [comment]
You wanting to collaborate is a bug.

**Comment by da638** [comment]
well i its hard to explain

**Comment by BETPRODIGYHACKER** [comment]
lol

**Comment by da638** [comment]
really :l

**Comment by ProdigyCookie** [comment]
I wanna collab with you :3

**Comment by BoredFishRE** [comment]
wdym "collab"

**Comment by ProdigyCookie** [comment]
Nvm

**Comment by ProdigyCookie** [comment]
I mean the title said "Can i collab with u guys!!"

**Comment by BoredFishRE** [comment]
i'm asking @da638

**Comment by ProdigyCookie** [comment]
Oh okay sorry

**Comment by da638** [comment]
i mean help with the hacks and you can also join prodigy cookie

**Comment by ProdigyCookie** [comment]
I am playing prodigy right now and I am in Animalia

**Comment by da638** [comment]
oh whats your username

**Comment by AGR-DEVS** [comment]
@da638 to "collab" you need to know how to code (JavaScript in perticular), do you have any experience?

**Comment by da638** [comment]
no... just a little

**Comment by YamaHacks** [comment]
How would you be any help to us at all, may i ask?

**Comment by ArcerionDev** [comment]
I mean

**Comment by ArcerionDev** [comment]
valid

**Comment by ArcerionDev** [comment]
@da638 if you have anything to contribute, list it here I guess

**Comment by ProdigyCookie** [comment]
what

**Comment by LeoBadeaux** [comment]
What do you mean?

**Comment by hostedposted** [comment]
I think he wants to become a collaborator

**Comment by LeoBadeaux** [comment]
Judging by the grammar I'm assuming they're <13 and don't know how to code?

**Comment by hostedposted** [comment]
Probably.

**Comment by ProdigyCookie** [comment]
I know how to code
