### ISSUE TITLE
@da638 i'm pretty sure you can't, unless you can access a web proxy or something else like that

### ISSUE THREAD

**Issue by da638** [Prodigy-Hacking/ProdigyMathGameHacking#1012]
@da638 i'm pretty sure you can't, unless you can access a web proxy or something else like that

_Originally posted by @SakuraKitsunee in https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/issues/1009#issuecomment-854002431_

**Comment by hostedposted** [comment]
why did you make this?
