### ISSUE TITLE
[BUG] I don't think PvP health or uncap player level are working. I've been trying for a while.

### ISSUE THREAD

**Issue by Battlez1** [Prodigy-Hacking/ProdigyMathGameHacking#1014]
***Description***:  I tried using PvP health to do rune runs, when it didn't work. I tried Uncap level to get more health but that didn't work. I don't have any images. Anybody think they know why this is?

**Comment by ArcerionDev** [comment]
battle hacks don't work on harmony island

**Comment by ArcerionDev** [comment]
also 
![image](https://user-images.githubusercontent.com/60945964/121095095-ae2f1680-c7bd-11eb-8383-f638125e54b1.png)
