### ISSUE TITLE
[BUG] Not receiving all arena prizes in item stacker 

### ISSUE THREAD

**Issue by LittleboyJames** [Prodigy-Hacking/ProdigyMathGameHacking#1015]
***Description***:
The hack obtains all items except the arena prize sets (helps obtain only rainbow mount) from bronze, silver, and gold

***Replication***:
1. Go to prodigy with enabled extension
2. Go into a world
3. Press the item stacker hack
3(alternate). Do the item stacker manually

***Additional Errors/Questions***:
This is the only error, however it is possible that some of the arena prize items from the item list (not outfit, boots, weapon, or hat) could have also not have been added while doing the hack.

Is it possible to find the hat/outfit/boots/weapon id’s for the bronze, silver, and gold set?

**Comment by LittleboyJames** [comment]
I think the id of those items have not been found and is why the hack is not working, but I could be wrong

**Comment by NX721** [comment]
Bruh, those items aren't even in the game yet, they were just images of the future items.

**Comment by ArcerionDev** [comment]
they aren't coded in yet, they'll be coded into the game at the end of the season
