### ISSUE TITLE
"Toggle membership" hack crashes game when opening member chest

### ISSUE THREAD

**Issue by Hestia2504** [Prodigy-Hacking/ProdigyMathGameHacking#1021]
***Description***
While using the "Toggle membership" hack, when opening a member chest (specifically, the member chests from the Arena), you get signed out due to "inactivity".

Other member-only things such as purchasing member-only items from shops work fine.

***Replication***:
Turn on "toggle membership" and open a member chest from the Arena. (making sure you don't have a legitimate membership)

**Comment by PatheticMustan** [comment]
Cannot replicate...? @Hestia2504, can you send a screenshot of the error?

**Comment by Hestia2504** [comment]
Of course, hold on

**Comment by Hestia2504** [comment]
![error](https://user-images.githubusercontent.com/85859923/121911714-27ef7300-cd6f-11eb-8e39-420559e650dc.png)
Here you go

**Comment by Hestia2504** [comment]
Sorry for the bad quality

**Comment by Bruceq3456** [comment]
Same 4 me!

**Comment by PatheticMustan** [comment]
thanks for the screenshot! WIll look into this :D

**Comment by Phenomenon1337** [comment]
actually, this is because u used win battle.

**Comment by Hestia2504** [comment]
aa right that makes sense thanks :)

**Comment by Hestia2504** [comment]
is this due to me client-side having enough trophies, but in the server I don't? or some other reason

**Comment by Hestia2504** [comment]
and also, is there a way to fix this? apart from resetting the account or using another one i mean

**Comment by PatheticMustan** [comment]
When it crashes, can you share a screenshot of that error?

**Comment by Hestia2504** [comment]
When I click on the chest, there are two errors, this is the first;
![error1](https://user-images.githubusercontent.com/85859923/122141098-cb35aa80-ce8b-11eb-8079-798ff48eaff6.png)
This only appears for a second before being covered by this one;
![error2](https://user-images.githubusercontent.com/85859923/122141192-f1f3e100-ce8b-11eb-8be0-1dfbad7bd249.png)

**Comment by Hestia2504** [comment]
Also, I just opened the third chest (a non-member one), so this seems to only apply to member chests, or the second chest specifically.

**Comment by da638** [comment]
did you keep repeditly use the hacks

**Comment by LeoBadeaux** [comment]
> Also, I just opened the third chest (a non-member one), so this seems to only apply to member chests.
> 
> Update: I gave this account a membership, and I could open the chest with no problems

erm, only open member chests if you are a member? closed?
