### ISSUE TITLE
[HR]Add That We Can Choose any type of hair not in Prodigy

### ISSUE THREAD

**Issue by Jeremiah66268** [Prodigy-Hacking/ProdigyMathGameHacking#1027]
We Could Just add different hair styles Just by in the menu so it could be easier
Just for Hair styles

**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**Nope

**Comment by Jeremiah66268** [comment]
Well it is in prodigy but that not in any shop

**Comment by ArcerionDev** [comment]
Duplicate issue
