### ISSUE TITLE
[BUG]your account is broken when you try to battle what is broken stuck at loading screen when you are tryingto battle make that come along with fix battle crash

### ISSUE THREAD

**Issue by iamgodpog** [Prodigy-Hacking/ProdigyMathGameHacking#1032]
stuck at loading screen when trying to battle

set stuffs to high and then activate pdg anticheat

stuck at loading screen when trying to battle ARC try it for your self

nah

**Comment by hostedposted** [comment]
Could you please make this readable english?

**Comment by ArcerionDev** [comment]
r/ihadastroke

**Comment by Protuber** [comment]
i cant even read this

**Comment by hostedposted** [comment]
I am going to close this until you make it readable.
