### ISSUE TITLE
Error in the rune run

### ISSUE THREAD

**Issue by JordanCOOLBOI** [Prodigy-Hacking/ProdigyMathGameHacking#1040]
***Description***:

Its like sayin there was a problem starting your rune run please press back and try again later
***Replication***:

***Images***:
<img width="1040" alt="Screen Shot 2021-07-01 at 10 27 59 AM" src="https://user-images.githubusercontent.com/86790024/124143159-e17d6200-da58-11eb-8e37-6f52e5f14cc4.png">

***Additional Errors***:

**Comment by Protuber** [comment]
oof

**Comment by PatheticMustan** [comment]
Try opening console (ctrl shift i) and screenshoting any errors there! Thanks

**Comment by LeoBadeaux** [comment]
> Try opening console (ctrl shift i) and screenshoting any errors there! Thanks

Bug Reporter did not reply with more information regarding errors, account has been inactive ever since. Issue is now invalid unless somebody else can replicate and if so they make a new issue.
