### ISSUE TITLE
[HR] Change Grade without teacher/parent account

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1042]
**Describe your hack:**

Change your grade using just js
**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**
This hack is available. I will help you start it. You can create the buttons.
```
_.player.grade=1
_.player.grade=2
_.player.grade=3
```
And so on.

**Comment by hostedposted** [comment]
We already have this

**Comment by donaldli2020** [comment]
It's not in the cheat menu.

**Comment by donaldli2020** [comment]
Maybe add it?

**Comment by hostedposted** [comment]
It's not?

**Comment by donaldli2020** [comment]
There's no question hack section.

**Comment by hostedposted** [comment]
Added it.

**Comment by donaldli2020** [comment]
Thanks. I will update.

**Comment by donaldli2020** [comment]
Okay, now it's good.
