### ISSUE TITLE
[HR] Choose Infinity

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1045]
**Describe your hack:**

Choose Infinity for gold, levels, etc.
**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes, I can't type "Infinity" when I set gold, levels, etc.

**Comment by Phenomenon1337** [comment]
_.player.data.gold = Infinity

**Comment by Phenomenon1337** [comment]
nvm, it doesnt save

**Comment by hostedposted** [comment]
Infinity would not save.
