### ISSUE TITLE
[BUG] Get all runes not working

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1047]
***Description***:
I don't get any runes with this hack. No change in rune inventory

***Replication***:

***Images***:

***Additional Errors***:

**Comment by Phenomenon1337** [comment]
its broken rn

**Comment by Phenomenon1337** [comment]
prodigy has made harmony island more secure

**Comment by donaldli2020** [comment]
Okay.

**Comment by da638** [comment]
so what are you gonna do be it said the get all runes was beta

**Comment by LeoBadeaux** [comment]
Get all runes and Prodigy's entire rune system is in beta as @da638 explained. Closed.
