### ISSUE TITLE
[BUG] Disable Inactivity Kick works but shops closed after some inactivity

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1049]
***Description***:
I used Disable Inactivity Kick. It works. The problem is that when I get inactive, I can't go to shops.

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/74021676/124358546-d0665980-dbee-11eb-9684-dd95c4a04984.png)
![image](https://user-images.githubusercontent.com/74021676/124358571-f12eaf00-dbee-11eb-9139-83adc70ec619.png)

***Additional Errors***:

**Comment by LeoBadeaux** [comment]
similar to #1087

**Comment by LeoBadeaux** [comment]
In #1087 HostedPosted could not replicate and issue was closed. Merging that action to here.
