### ISSUE TITLE
[BUG] Set Grade not working

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1050]
***Description***:
Set grade doesn't work because I have grade override. The variable below should work.
```
_.player.educationData.gradeOverride=1
_.player.educationData.gradeOverride=2
_.player.educationData.gradeOverride=3
_.player.educationData.gradeOverride=4
_.player.educationData.gradeOverride=5
_.player.educationData.gradeOverride=6
_.player.educationData.gradeOverride=7
_.player.educationData.gradeOverride=8
```
***Replication***:

***Images***:

***Additional Errors***:

**Comment by hostedposted** [comment]
We are using ``_.player.grade`` if you have grade override disable grade override

**Comment by donaldli2020** [comment]
My teacher probably set me a grade override.

**Comment by donaldli2020** [comment]
I won't be able to change it.
