### ISSUE TITLE
[HR] Get actual membership refer to #1052

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1053]
**Describe your hack:**

Actual membership hack (refer to #1052)
**(Optional) Additional information**
It probably has to do with ```_.player.memberStartDate``` and ```_.player.memberEndDate```, but we don't know what the format of the dates are.
**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes.

**Comment by hostedposted** [comment]
The formats of the dates are javascript dates.
```js
new Date(_.player.memberStartDate)
```

**Comment by donaldli2020** [comment]
I think we can make this a medium priority. I will get a membership and see the formats of the dates. We can also add the label Research

**Comment by donaldli2020** [comment]
Can someone assign me?

**Comment by AgrTheDev** [comment]
There’s no way of getting membership permanently. I’ve learned this after doing a fair amount of API work (basically where prodigy stores permanent data).

**Comment by donaldli2020** [comment]
I will explore and see how to get a free membership.

**Comment by Phenomenon1337** [comment]
yu could uses proodigy's refereal proogram

**Comment by hostedposted** [comment]
> There’s no way of getting membership permanently. I’ve learned this after doing a fair amount of API work (basically where prodigy stores permanent data).

Yes. It's impossible.
