### ISSUE TITLE
[HR] Focus Mode

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1054]
**Describe your hack:**

Enable/Disable Focus Mode
**(Optional) Additional information**
```_.player.isFocusModeEnabled=true``` and ```_.player.isFocusModeEnabled=false```
**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by hostedposted** [comment]
I though ``isFocusModeEnabled`` was readonly

https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/bbece04de26e1e71dcf9b487c7e32c8aaca0e066/typings/player.d.ts#L61

**Comment by 4evera1one** [comment]
can you make a pull request?

**Comment by LeoBadeaux** [comment]
> I thought `isFocusModeEnabled` was readonly
> 
> https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/bbece04de26e1e71dcf9b487c7e32c8aaca0e066/typings/player.d.ts#L61

yes, this will just make an error happen. closed.
