### ISSUE TITLE
[BUG] Walk speeds with e don't work

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1055]
***Description***:
When I use e inside a walk speed, it changes it to 1.

***Replication***:

***Images***:

***Additional Errors***:

**Comment by hostedposted** [comment]
Enter ``2.7182818284590452353602874713526624977572470936999595749669676277240766303535475945713821785251664274`` it's the first 100 digits of e.

**Comment by donaldli2020** [comment]
I mean writing a googol as 1e100.
I also made a pause game pull request.

**Comment by hostedposted** [comment]
We will not be adding 1e100 as 1000 does basically the same thing

I know you made the pause game pull and I will not merge it until you fix the error.

**Comment by PatheticMustan** [comment]
interesting bug report, for sure
