### ISSUE TITLE
[HR] Walk speeds less than 1

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1056]
**Describe your hack:**

Use decimal walk speeds like 0.5. It would be easier not to type ```_.player._playerContainer.walkSpeed=0.5```.
**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by hostedposted** [comment]
I added this and next time if you have the code you can make a pull request.

**Comment by donaldli2020** [comment]
Thanks
