### ISSUE TITLE
[BUG] Not getting items

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1058]
***Description***:
Selector (Advanced) doesn't give me water balloons.
I used Selector (Advanced) > Select... > Items > OK > Select... > (Scroll down) > Water Balloons > 99 > OK.
***Replication***:

***Images***:

***Additional Errors***:

**Comment by LeoBadeaux** [comment]
Can anyone confirm? This issue needs to be dealt with.

**Comment by HestiaHearth** [comment]
I can confirm. After some testing, I've found that you can only give/remove an item once. I also can't remove things that I earnt legitimately, such as relics from quests. (which is quite annoying as I want to organize my relics by removing and re adding them, (before anyone says anything, yes, not on my main acc, on my hacking one))

**Comment by JeaIousy** [comment]
lol

**Comment by afkvido** [comment]
# Close this
This has been fixed.
From my testing, I can get as many items as I want with Selector (Advanced).
Selector (Advanced) has been the least glitchy hack that I've seen so far.
