### ISSUE TITLE
[BUG] URGENT: Error in hacks code

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1059]
***Description***:
I got an error when loading the game.
DevTools failed to load source map: Could not parse content for https://hacks.prodigyhacking.com/game.min.js.map: Unexpected token u in JSON at position 3
***Replication***:

***Images***:

***Additional Errors***:

**Comment by Protuber** [comment]
ok thanks for telling

**Comment by Phenomenon1337** [comment]
thats not a bug.

**Comment by Phenomenon1337** [comment]
and how is it urgent -_-

**Comment by hostedposted** [comment]
it's a map file that prodigy has but we don't. It does not change anything though

**Comment by donaldli2020** [comment]
It causes the hacks to not work anymore. The cheat menu doesn't show up.

**Comment by AgrTheDev** [comment]
Please don’t comment on this closed issue. The hacks are down. Please refer to [this](https://prodigyhackingstatus.com) before commenting/opening a new issue.
