### ISSUE TITLE
Walkspeed on loadup throws error, doesn't pause game

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#1060]
![image](https://user-images.githubusercontent.com/35382971/124685374-29f4af80-de9f-11eb-9958-582924588e36.png)

No clean way around it, not sure we have hooks for this type of stuff. Maybe just check if it exists in the first place, and stick it in a setInterval

**Comment by donaldli2020** [comment]
@PatheticMustan What hack did you use?

**Comment by donaldli2020** [comment]
Is it walkspeed?
I also got an error.
![image](https://user-images.githubusercontent.com/74021676/124687463-f156d500-dea2-11eb-99d9-9b17b685495f.png)

**Comment by hostedposted** [comment]
@Phenomenon1337 gave me the code for walkspeed and at first it didn't work as ``_.player._playerContainer`` was null but then once I loaded the game it did work

**Comment by hostedposted** [comment]
so we could do some optional chaining to prevent the error

**Comment by hostedposted** [comment]
Fixed this in https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/fb46fa1da8df2bcb0ab8686c7056ddfdb530b996.
