### ISSUE TITLE
Walking into invalid room bricks account unless you manually teleport away

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#1061]
![image](https://user-images.githubusercontent.com/35382971/124685471-56103080-de9f-11eb-9f05-848ed1a44a2a.png)

In this case, I used the get all keystones, and went into one of the towers that wasn't implemented yet. Oops!

**Comment by PatheticMustan** [comment]
```
_.player.data.zone = "lamplight-B3"
```
fix

**Comment by hostedposted** [comment]
I encountered something like this a couple weeks ago. When I went to harmony island I got an error and I was only able to fix it when I teleported away.

**Comment by da638** [comment]
actullay this is true

**Comment by donaldli2020** [comment]
I can't teleport also.

**Comment by LeoBadeaux** [comment]
We should disable going into towers that aren't implemented yet to fix this. Doesn't sound like something that should be too difficult?

**Comment by donaldli2020** [comment]
You can't teleport to lamplight town.

**Comment by PatheticMustan** [comment]
> We should disable going into towers that aren't implemented yet to fix this. Doesn't sound like something that should be too difficult?

Sorry I had the fix above, but never bothered to put it in a button. Will do now :P

**Comment by 32n** [comment]
@PatheticMustan What exactly do you mean by "bricks your account"

**Comment by PatheticMustan** [comment]
game crash upon login

**Comment by 32n** [comment]
If I reproduce this issue, will my profile be stuck in an infinite crash loop, or can I stop this from happening by just turning off the hacks?
