### ISSUE TITLE
cant battle monsters i used latest update to

### ISSUE THREAD

**Issue by da638** [Prodigy-Hacking/ProdigyMathGameHacking#1065]
i cant battle any single monster when i wallk towards them they just come towards me and stay there

also rune run isnt working

**Comment by donaldli2020** [comment]
Use fix battle crash

**Comment by Protuber** [comment]
it stuck on loading for me

**Comment by 4evera1one** [comment]
@Protuber are hacks down? check https://prodigyhackingstatus.com/, if its on, try to uninstall the extension and try again.

**Comment by hostedposted** [comment]
that means you broke your account. reset it and **don't** use skip tutorial when you start it again
