### ISSUE TITLE
[BUG]can't battle monsters

### ISSUE THREAD

**Issue by Alexowu** [Prodigy-Hacking/ProdigyMathGameHacking#1067]
***Description***
The monster walked to me but didn't battle

***Replication***:

***Images***:
<img width="1280" alt="Screen Shot 2021-07-08 at 4 23 05 PM 1" src="https://user-images.githubusercontent.com/87109398/124862112-e74ee680-e008-11eb-9773-f6b6be4fa30e.png">

***Additional Errors***:

**Comment by hostedposted** [comment]
Create a new account, complete the tutorial without using skip tutorial and your new account will be fixed.
