### ISSUE TITLE
[BUG] is stuck on loading

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#1068]
***Description***:
I don't know why 

***Replication***:
join prodigy with the hack and it will say its outdated
***Images***:

***Additional Errors***:
still happens

**Comment by hostedposted** [comment]
Could you please elaborate?

**Comment by 4evera1one** [comment]
this usually happens if hacks are down. try again later :)

**Comment by donaldli2020** [comment]
This is caused by either:
A. the extension being incorrectly installed. Please reinstall the extension
B. https://prodigyhacking.ml is blocked. Please check if you can visit it
C. Hacks are temporarily down. If this is the case, we will let everyone know, please wait while we get them back up.

**Comment by Protuber** [comment]
ok thank

**Comment by 4evera1one** [comment]
does it work now?

**Comment by da638** [comment]
hey protuber remeber me and also if its loading halfway did you update the hacks

**Comment by Protuber** [comment]
it didn't work i don't know why

**Comment by donaldli2020** [comment]
All services are operational. See if you can go to https://hacks.prodigyhacking.com/

**Comment by Protuber** [comment]
i can

**Comment by donaldli2020** [comment]
Can you delete and install the extension?

**Comment by Protuber** [comment]
I did and it works i just had to click cancel and it worked all of a sudden thank you so much
