### ISSUE TITLE
[HR] Have same friends that another user has

### ISSUE THREAD

**Issue by ShawnC32** [Prodigy-Hacking/ProdigyMathGameHacking#1070]
**Describe your hack:**
Get same friends like another user

**(Optional) Additional information**
Get someone else's friends 
**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by donaldli2020** [comment]
That would be controlled by the server, so it might be impossible.

**Comment by ArcerionDev** [comment]
> That would be controlled by the server, so it might be impossible.

this is correct, if a friend is added, it has to be on both ends I believe

**Comment by ShawnC32** [comment]
Players who look like my characters now have a girlfriend called Harmony the W12-4RD!

**Comment by ShawnC32** [comment]
David Wildgirl has 2 girlfriends (wives) in his friends list 
1. Crystal Clearvoice
2. Harmony the W12-4RD
