### ISSUE TITLE
Hack idea

### ISSUE THREAD

**Issue by Timed-kitty-cat** [Prodigy-Hacking/ProdigyMathGameHacking#1075]
## Describe your hack:
Gives you debug item Morph Marble Number One
## Have you made sure this hack isn't available yet? (Yes/No)
No, but Number One can be obtained (with other Morph Marbles) from the get item hack.

**Comment by donaldli2020** [comment]
Can you explain more?

**Comment by Timed-kitty-cat** [comment]
@donaldli2020 Morph Marble Number One is a debug item to morph into Terromite

**Comment by donaldli2020** [comment]
It's right in the menu. Morph Player (DEV).

**Comment by Timed-kitty-cat** [comment]
Morph Player is perma-morph and people may not want permamorph into Terromite

**Comment by donaldli2020** [comment]
For how long do you want?

**Comment by donaldli2020** [comment]
Is it a pet?

**Comment by donaldli2020** [comment]
Please give me some information:
Type: Pet, Furniture, Follow
ID: Pet ID, Furniture ID, Follow ID
Morph Time: Use a unit; I'll convert into milliseconds.

**Comment by donaldli2020** [comment]
Okay, I found Terromite is a pet ID 125. How long do you want to morph in any time unit?

**Comment by donaldli2020** [comment]
How about 15 minutes?

**Comment by Timed-kitty-cat** [comment]
No, 10 or 1

**Comment by donaldli2020** [comment]
Okay, for 10
```
	_.player.getPlayerData().playerTransformation = {
		transformType: pet,
		transformID: 125,
		maxTime: 600000,
		timeRemaining: 600000
	};
	_.player.appearanceChanged = true;
```
For 1
```
	_.player.getPlayerData().playerTransformation = {
		transformType: pet,
		transformID: 125,
		maxTime: 60000,
		timeRemaining: 60000
	};
	_.player.appearanceChanged = true;
```

**Comment by donaldli2020** [comment]
If it works, can you close the issue?

**Comment by Timed-kitty-cat** [comment]
> If it works, can you close the issue?

I don't have PHEx. My school blocks Chrome extensions.

**Comment by donaldli2020** [comment]
That's sad...

**Comment by donaldli2020** [comment]
What computer are you using?

**Comment by Timed-kitty-cat** [comment]
> What computer are you using?

Chromebook

**Comment by donaldli2020** [comment]
Do you have other non-school accounts?

**Comment by Timed-kitty-cat** [comment]
> Do you have other non-school accounts or other computers?

Nope.

**Comment by donaldli2020** [comment]
Can you make a personal account in an incognito window (Ctrl Shift N)?

**Comment by Timed-kitty-cat** [comment]
> Can you make a personal account in an incognito window (Ctrl Shift N)?

Nope. School blocked incognito too.

**Comment by donaldli2020** [comment]
Can you make a personal account in a normal window?

**Comment by Timed-kitty-cat** [comment]
> Can you make a personal account in a normal window, like in manage accounts?

school blocked that

**Comment by donaldli2020** [comment]
The only way to get PHEx is to use a personal account or another computer.

**Comment by Timed-kitty-cat** [comment]
> The only way to get PHEx is to use a personal account or another computer.

this is my only computer

**Comment by donaldli2020** [comment]
It's also okay if you have a mobile device to make an account.

**Comment by Timed-kitty-cat** [comment]
> It's also okay if you have a mobile device to make an account.

I have no mobile devices

**Comment by donaldli2020** [comment]
I'm sorry, all that's important is to make a personal account on Google. I also need to have lunch.

**Comment by 4evera1one** [comment]
I might add the morph hack into the [online dashboard](https://prodigy-dashboard.hostedposted.com) today, ill see if i have time, ill let you know if I do.

**Comment by donaldli2020** [comment]
How do I log in?

**Comment by 4evera1one** [comment]
on the dashboard?

**Comment by donaldli2020** [comment]
Yeah

**Comment by 4evera1one** [comment]
put your prodigy username and pass in /login

**Comment by donaldli2020** [comment]
Okay

**Comment by donaldli2020** [comment]
I can't put in my GitHub username, and how do I know that hostedposted won't steal my info?

**Comment by 4evera1one** [comment]
its open source, also its ur prodigy name and password, https://github.com/hostedposted/Prodigy/tree/dashboard is the dashboard code :D

**Comment by 4evera1one** [comment]
its also hosted with github pages soo

**Comment by donaldli2020** [comment]
How do I know that hostedposted won't steal my info?

**Comment by ArcerionDev** [comment]
> How do I know that hostedposted won't steal my info?

if we wanted to steal your info we could easily do it, and as your account is safe, don't worry about it

**Comment by donaldli2020** [comment]
Thanks

**Comment by 4evera1one** [comment]
if you look [here](https://github.com/hostedposted/Prodigy/runs/3049848466), you will see that the code is deployed onto the website. and the code is open source, so feel free to look at it for  yk

**Comment by hostedposted** [comment]
> Morph Player is perma-morph and people may not want permamorph into Terromite

no it's not. it lasts ``3600000`` milliseconds. going to be closing this because we already have it

**Comment by AgrTheDev** [comment]
Hosted you’re alive!!!!!
