### ISSUE TITLE
[HR] Harmony Island Hacks

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1080]
**Describe your hack:**

Add a section called Harmony Island Hacks
**(Optional) Additional information**
I will make PRs for Harmony Island Hacks in the repository.
**Have you made sure this hack isn't available yet?* (Yes/No)**
This is actually a type of hack.

**Comment by 4evera1one** [comment]
may i have a little hack? it seems like nothing works in harmony island

**Comment by donaldli2020** [comment]
I have one, but I copied the code from another computer.

**Comment by donaldli2020** [comment]
`_.player.state.data.elementalGuardian.global.torchesLit` is the number of torches lit

**Comment by donaldli2020** [comment]
so _.player.state.data.elementalGuardian.global.torchesLit = 6 should light all torches

**Comment by donaldli2020** [comment]
& idk if it works

**Comment by JeaIousy** [comment]
dooesnt work :(

**Comment by donaldli2020** [comment]
Okay, I'll try to find another one, hopefully a variable that stores runes.

**Comment by JeaIousy** [comment]
if you are familiar with prodigy's api, i found playerData.inventory.orb

**Comment by ArcerionDev** [comment]
we already know about this, there is a "get all runes" hack, you know

**Comment by donaldli2020** [comment]
I'll look into this.

**Comment by JeaIousy** [comment]
@ArceionDev it doesnt work .-.

**Comment by donaldli2020** [comment]
Yeah, I'll look at this.

**Comment by LeoBadeaux** [comment]
alright you can make some PRs for harmony island I will close this issue for now

**Comment by donaldli2020** [comment]
ok
