### ISSUE TITLE
[BUG] Loading weird stuff lol

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1082]
![image](https://user-images.githubusercontent.com/74021676/125848215-dcf9c036-1335-4cc2-8b62-2416eab3da42.png)
![image](https://user-images.githubusercontent.com/74021676/125848308-63a9d8fe-4bce-47fe-99dd-55a568e2db96.png)
![image](https://user-images.githubusercontent.com/74021676/125848390-6286a96d-ff0e-409b-8c59-cba039586949.png)
![image](https://user-images.githubusercontent.com/74021676/125848504-f698c4bf-3de0-4675-a7e8-1cc9335c73c6.png)
![image](https://user-images.githubusercontent.com/74021676/125848564-dba23cda-c3e7-434f-a21e-da84d5dc0224.png)
![image](https://user-images.githubusercontent.com/74021676/125848629-d2c6f8ef-6d16-4546-ae00-83c1b62bb704.png)
![image](https://user-images.githubusercontent.com/74021676/125848668-773bb7fa-44bd-4e40-84bc-57472b7c0ba2.png)
![image](https://user-images.githubusercontent.com/74021676/125848980-f21de0c0-366c-4251-85aa-2f3dbaff6642.png)
![image](https://user-images.githubusercontent.com/74021676/125849090-1a7f8464-6aab-4418-9f44-e185ea666439.png)

**Comment by JeaIousy** [comment]
did you use owo?

**Comment by donaldli2020** [comment]
I didn't use OwO, but they are dialogue IDs, so en-us.json didn't load successfully.

**Comment by donaldli2020** [comment]
yeah status failed cdn.prodigygame.com/game/data/production/880/en-us.json

**Comment by AgrTheDev** [comment]
Reload and see if it loads successfully

**Comment by ArcerionDev** [comment]
> yeah status failed https://cdn.prodigygame.com/game/data/production/880/en-us.json

that's why, https://cdn.prodigygame.com/game/data/production/880/en-us.json replaces all of the sprite names with the ingame names.

**Comment by LeoBadeaux** [comment]
Hello, is this issue still occuring?

**Comment by donaldli2020** [comment]
No
