### ISSUE TITLE
[HR] Get questions correct without answering

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1083]
**Describe your hack:**

Correct questions hack
**(Optional) Additional information**
When I answer a question, they console.logged
```
Action: submit, Custom Fields: {"answer":["b"],"isValid":true,"isCorrect":true,"generation":1}
```
**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by AgrTheDev** [comment]
Interesting

**Comment by JeaIousy** [comment]
yea... but u cant do anything with that. should i close this?

**Comment by donaldli2020** [comment]
No, this is a hack request.

**Comment by JeaIousy** [comment]
the first issue is basically this. check issue #1
