### ISSUE TITLE
[BUG] Getting numbers and symbols all over the place

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1084]
***Description***:

***Replication***:
Used
```
_.player.modifiers.damage = 1e303
```

***Images***:
![image](https://user-images.githubusercontent.com/74021676/126223743-697088c1-0a7e-4770-92ab-c80f35fdab8a.png)

***Additional Errors***:

**Comment by JeaIousy** [comment]
bcus the number is too big.
