### ISSUE TITLE
[BUG] Negative Negative damage

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1085]
***Description***:
I did damage starting with - - and - * - = +, so I gave the monster health.

***Replication***:

***Images***:
![Screenshot 2021-07-19 16 42 01](https://user-images.githubusercontent.com/74021676/126224965-f0b8a44d-0de7-47e1-a136-021447a9b48e.png)

***Additional Errors***:

**Comment by AgrTheDev** [comment]
just dont do damage starting with - - and - * - = + then

**Comment by donaldli2020** [comment]
In math, double negative equals positive, so I gave the monster health.

**Comment by donaldli2020** [comment]
And see that the damage starts with --?

**Comment by AgrTheDev** [comment]
mhm
