### ISSUE TITLE
[HR] Set game speed

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1086]
**Describe your hack:**

Make game graphics go faster/slower using set game speed
**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by AgrTheDev** [comment]
FPS (Frames per second) is the speed of graphics (If you are talking about this). Right now many browsers like chrome limit FPS to 60. If you want to uncap this, try making a client for prodigy using (electron)[https://www.electronjs.org/].

**Comment by JeaIousy** [comment]
yes.
