### ISSUE TITLE
[BUG] 403

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1087]
***Description***:
Getting 403 errors and not saving progress when inactive.

***Replication***:
Used disable inactivity kick.

***Images***:

***Additional Errors***:

**Comment by Protuber** [comment]
for me when I join it doesn't show the drop menu.

**Comment by da638** [comment]
that is true

**Comment by LeoBadeaux** [comment]
Hello, is this issue still occuring?

**Comment by donaldli2020** [comment]
yes

**Comment by hostedposted** [comment]
I cannot replicate.
