### ISSUE TITLE
[BUG] Pets are not being recognized when trying to switch my team

### ISSUE THREAD

**Issue by Mausien** [Prodigy-Hacking/ProdigyMathGameHacking#1092]
When I click the Paw Print icon to change the pets on my team the window for "your team" comes up blank.
<img width="1668" alt="Screen Shot 2021-07-24 at 2 05 38 PM" src="https://user-images.githubusercontent.com/66150982/126877411-09c54f56-22a5-4587-96a2-78b446743ddf.png">

When I try to click the "Petbook" tab I can see all my rescued pets, 
<img width="1617" alt="Screen Shot 2021-07-24 at 1 58 44 PM" src="https://user-images.githubusercontent.com/66150982/126877423-99fe963d-2251-4ddb-ba24-c34e924938d8.png">

but if I try to click any of I get an error stating that I have not rescued any pets. 
<img width="1591" alt="Screen Shot 2021-07-24 at 1 58 25 PM" src="https://user-images.githubusercontent.com/66150982/126877437-ce4cbfa4-5c8f-4c57-a304-90203f19b035.png">

then I try to click back on "your team" tab" and get this message
<img width="1591" alt="Screen Shot 2021-07-24 at 1 58 25 PM" src="https://user-images.githubusercontent.com/66150982/126877456-9017853d-8f7c-42aa-979e-da8e2b3a551f.png">

I've tried this with several accounts and always the same result.

Thanks for having a look 😊

**Comment by donaldli2020** [comment]
Take a screenshot of the console.

**Comment by Mausien** [comment]
<img width="538" alt="Screen Shot 2021-07-25 at 12 07 04 PM" src="https://user-images.githubusercontent.com/66150982/126905722-780064f1-7e82-40b4-9ce9-a3bbc5ed9b1f.png">

**Comment by donaldli2020** [comment]
It also happens to me. There are errors in the game code https://code.prodigygame.com/js/load-identity-face7d5541.min.js?v=1. There's nothing we can do.

**Comment by donaldli2020** [comment]
The game is broken #1094

**Comment by Mausien** [comment]
It's working again. Not sure who fixed it, but thanks 😊

**Comment by donaldli2020** [comment]
Can you close the issue?
