### ISSUE TITLE
[BUG] The game is broken

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1094]
***Description***:

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/74021676/126914762-1225b033-4f68-44ba-8f11-db11ed914016.png)

***Additional Errors***:

**Comment by donaldli2020** [comment]
CORS blocked all the game code from execting. I'm also in Chrome.

**Comment by hostedposted** [comment]
It works fine for me.
