### ISSUE TITLE
[HR] prodigy wills cheat menu

### ISSUE THREAD

**Issue by Xkman-272** [Prodigy-Hacking/ProdigyMathGameHacking#1095]
**Describe your hack:**

**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**

**Comment by JeaIousy** [comment]
tf?

**Comment by LeoBadeaux** [comment]
> tf?

seems like a PEBKAC issue

**Comment by donaldli2020** [comment]
lol
