### ISSUE TITLE
report this is not an actual bug read to understand 

### ISSUE THREAD

**Issue by da638** [Prodigy-Hacking/ProdigyMathGameHacking#1099]
hello prodigy hacking i would like to request something that is not hack but i hope you will do could you find a way to do it in a school computer without extensions or manual install because the adminstrator blocks the devloper mode and it restrictes me from being able to download it so if you have time plz do this

***Replication***:

***Additional Errors***:

**Comment by LeoBadeaux** [comment]
PMGH does not have any way to bypass GSuite Policy-enforced restrictions on extensions.
