### ISSUE TITLE
report this is not a actual bug read to understand 

### ISSUE THREAD

**Issue by da638** [Prodigy-Hacking/ProdigyMathGameHacking#1100]
i dont know if this is possbile because for the pelope who only have a school computer can you add it on school computer because the school blocks developer mode  and block the manual install and chrome install so if you have time plz do this for us if you think this is uncesseary i understand thank you
![Screenshot 2021-08-29 7 31 22 PM](https://user-images.githubusercontent.com/84422902/131269039-1772e5c7-1e4c-404a-a4e6-a84be8fbd919.png)

***Replication***:

***Images***:

***Additional Errors***:

**Comment by hostedposted** [comment]
PMGH does not have any way to bypass GSuite Policy-enforced restrictions on extensions.
