### ISSUE TITLE
[BUG] Hacks not loading

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1104]
***Description***:
https://hacks.prodigyhacking.com/game.min.js says
```
Invalid version specified.
```
***Replication***:

***Images***:

***Additional Errors***:

**Comment by hostedposted** [comment]
Prodigy switched versions to decimals this should be fixed now.

**Comment by donaldli2020** [comment]
It's working.
