### ISSUE TITLE
[BUG] oops some togglers break

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#1107]
***Description***:
oops lmao some togglers break because it doesn't actually have the stuff it needs. maybe we should just stick it in a setInterval and double check it has the things it needs

***Replication***:
member toggler, reload

***Images***:
![image](https://user-images.githubusercontent.com/35382971/132104370-868db714-57b2-466b-bfa1-8317e0bbffaf.png)

***Additional Errors***:
no

**Comment by hostedposted** [comment]
I guess it takes some time for everything to load.

**Comment by PatheticMustan** [comment]
Yeah, like #member is only available after loading into the world

**Comment by ArcerionDev** [comment]
perhaps we could go back to the old method of redirecting the member endpoint, that seems more reliable

**Comment by donaldli2020** [comment]
no thanks

**Comment by afkvido** [comment]
You could just make togglers reset on reload, so it doesn't instantly load in when you load prodigy, that could help.

Togglers don't work if you log into prodigy with them already on, anyways.

**Comment by ArcerionDev** [comment]
> You could just make togglers reset on reload, so it doesn't instantly load in when you load prodigy, that could help.
> 
> Togglers don't work if you log into prodigy with them already on, anyways.

yeah they do..???

**Comment by ArcerionDev** [comment]
all togglers have been fixed, I've tested all of them and none seem to have issues.

**Comment by afkvido** [comment]
same :)

**Comment by PatheticMustan** [comment]
> > You could just make togglers reset on reload, so it doesn't instantly load in when you load prodigy, that could help.
> > 
> > Togglers don't work if you log into prodigy with them already on, anyways.
> 
> yeah they do..???

The issue is for some toggles like membership hacks, the entire prodigy object or whatever object it needs isn't loaded yet

**Comment by afkvido** [comment]
Membership doesn't work on harmony island sometimes
