### ISSUE TITLE
[BUG] Item stacker does not work it gives error and dosnt save, even if you cant replicate its because you use an account you have used hacks on before. Try creating a new account and see what happens, it dosnt work.

### ISSUE THREAD

**Issue by Linxhacks** [Prodigy-Hacking/ProdigyMathGameHacking#1111]
***Description***:

***Replication***:

***Images***:

***Additional Errors***:

**Comment by donaldli2020** [comment]
Create an account, use like a level 100 hack, and then use item stacker.

**Comment by Linxhacks** [comment]
I already tried that

**Comment by Linxhacks** [comment]
it didnt work

**Comment by donaldli2020** [comment]
Reload.
If not working, use Selector (Basic).

**Comment by hostedposted** [comment]
I created a new account and it worked. So again I can't replicate this.

**Comment by Linxhacks** [comment]
it dosnt save
