### ISSUE TITLE
[HR] refactoring hacks

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#1116]
basically just delete hacks and rewrite, hopefully won't be too hard

pls don't comment on this issue, I'm just going to use it to reference in commits

**Comment by ConnorAhern** [comment]
> no, it's consistent. Get All XYZ usually triggers it

its possible that when you obtain a shit ton of things at once that it fucks stuff up and stuff

**Comment by afkvido** [comment]
[proceeds to comment on issue]

Mustan: 😡

**Comment by PatheticMustan** [comment]
i only get annoyed when people make unrelated comments for no reason...?? You could just ask if there are any updates

**Comment by afkvido** [comment]
Oh, ok.

So, how's refactoring the hacks going?

**Comment by afkvido** [comment]
This is still pinned btw @PatheticMustan
