### ISSUE TITLE
[BUG] When I use Item Stacker now it would do an error before Item Stacker would work

### ISSUE THREAD

**Issue by windsweptgold** [Prodigy-Hacking/ProdigyMathGameHacking#1120]
***Description***: pls help

***Replication***:

***images***: [
![bugprodigy](https://user-images.githubusercontent.com/90929437/133836013-bb07b6ed-5b79-40bb-8e9e-7263c9363a26.png)

***Additional Errors***:

**Comment by loan-up** [comment]
it does that bc epic buddies crash it and i really want epic buddies so lets hope they fix it

**Comment by hostedposted** [comment]
I cannot replicate.
