### ISSUE TITLE
[BUG] game crash

### ISSUE THREAD

**Issue by Pizza20** [Prodigy-Hacking/ProdigyMathGameHacking#1132]
Why does prodigy always crash when using item stacker
And I have tried on 3 different computers and 10 different prodigy accounts

All I get is error 418 after using item stacker

**Comment by PatheticMustan** [comment]
hacks are poopy, we'll fix it eventually!

**Comment by Pizza20** [comment]
ok

**Comment by afkvido** [comment]
# Potential Causes

### You may be stacking too many items
Maybe some items, like **key items**, can't be stacked above 1.

### Otherwise,
the hack might be trying to spawn in bugged items, like epic buddies.

**Comment by Pizza20** [comment]
Also when I try to spawn more than 10 million coins I get error 418

**Comment by AgrTheDev** [comment]
Cuz 10 mil is max

**Comment by Pizza20** [comment]
Ah ok

**Comment by afkvido** [comment]
this is a duplicate issue, see #1272 and #1154 for the originals

**Comment by ArcerionDev** [comment]
this is fixed now, weeding out outdated issues rn
