### ISSUE TITLE
[BUG] Loading takes Forever

### ISSUE THREAD

**Issue by colwynyeun** [Prodigy-Hacking/ProdigyMathGameHacking#1133]
***Description***:
When I signed into prodigy I chosed a world and then its just loading forever.

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/92054354/136265077-dbc63cbd-5ea4-4999-b23e-84dcad92168e.png)

***Additional Errors***:

**Comment by ConnorAhern** [comment]
try again or something idk how many times did it happen also are there errors in console

**Comment by PatheticMustan** [comment]
open console with [ctrl shift i], make it crash, then screenshot your screen

**Comment by colwynyeun** [comment]
I had no pets there

**Comment by colwynyeun** [comment]
yea like dat

**Comment by ConnorAhern** [comment]
ok so i dont know but i think this thing happened called prodigy started caring so 🎉🎉🎉🎉 wooooo

**Comment by LeoBadeaux** [comment]
mate why do you have soo many browsers? c'est fou!

**Comment by colwynyeun** [comment]
No in a computer

**Comment by colwynyeun** [comment]
just a regular computer

**Comment by PatheticMustan** [comment]
> ![image](https://user-images.githubusercontent.com/92054354/136417404-b91258d0-8cfb-4711-a518-e8958d2fb3f2.png)
> 
> First my wizard is like dis

this doesn't look like it's loading forever. can you open console, right click it, and click "Save As..."? Send the file here

**Comment by afkvido** [comment]
Probably, this was fixed. Wasn't the reason for this an outage or other hack server issue? 


BoredFish in #support-announcements:
> If someone says that prodigy is stuck loading, ask them if there's a message at the top. If there isn't, ask them what > version of the extension they have. If they say anything under whatever the latest version is, tell them to update (you can check that at https://prodigyhacking.com/version. The current one at the time of writing is 2.0.3). If there is a message, ask them to send a screenshot. If the message looks like this, that means prodigyhacking.ml is blocked. Just tell them that their school blocked the hacks, and a VPN can solve that problem. If the "TypeError" spot says anything about a bad gateway, hacks are down.

Also, since the last major outage where we had to lock down the server, we haven't had this issue. Even the last comment on the issue is on November third 2021. Is this really still a problem?

**Comment by PatheticMustan** [comment]
assuming issue is fixed until OP responds otherwise

**Comment by donaldli2020** [comment]
> assuming issue is fixed until OP responds otherwise

6ed61e0
