### ISSUE TITLE
[BUG] Buddies can't be cheated in right.

### ISSUE THREAD

**Issue by Erisfiregamer1** [Prodigy-Hacking/ProdigyMathGameHacking#1142]
***Description***: Trying to cheat in buddies crashes the game with error 418.

***Replication***: Try to cheat in a buddy.

***Images***: (none)

***Additional Errors***: If you close the popup, trying to do anything else causes you to get inactivity kicked because of your session being invalidated.

**Comment by ConnorAhern** [comment]
known bug, prodigy has done some patching, some things arent working

**Comment by Erisfiregamer1** [comment]
Well, yes. But that doesn't solve the fact that it doesn't save.

**Comment by ConnorAhern** [comment]
> Yesterday I and my little brother found out clicking "close all popups" will bypass error 418

you should create another issue for this

**Comment by afkvido** [comment]
> This issue has not received any activity in a while and is considered stale. Has this issue been solved? If so, request for it to be closed.

shut

**Comment by alanadiamondpearl** [comment]
This is because of the toy code buddies

**Comment by PatheticMustan** [comment]
#1242

**Comment by YourOrdinaryProdigyHacker** [comment]
HHHHHHHHHHHHHH

**Comment by Erisfiregamer1** [comment]
Some things to note:
- Unsure if normal buddies work again. Must check later.
- Epic buddies (NOT the new ones, those work) cause 418 immediately.
- 418 is an anticheat. Prodigy can probably set a flag that makes the game crash if those items are obtained by any means other then the Epic Egg / developers.

**Comment by afkvido** [comment]
@Erisfiregamer1 

- Normal buddies work just fine, through Selector (Advanced)
- Old Epics cause 418
- Mythical epics do not cause 418


> 418 is an anticheat. Prodigy can probably set a flag that makes the game crash if those items are obtained by any means other then the Epic Egg / developers.

- Yes.

**Comment by afkvido** [comment]
I think this issue should be closed.

- Cheating in normal buddies works
- #1253 has a detailed description of the issue with epics

**Comment by ArcerionDev** [comment]
again, fixed

**Comment by 9B3S** [comment]
I got the 418 error for no reason and I did nothing wrong.

**Comment by 9B3S** [comment]
They say it's an anticheat but I was not cheating in the first place

**Comment by SUPERKING12345678** [comment]
hi

**Comment by SUPERKING12345678** [comment]
9B3S same
