### ISSUE TITLE
[BUG] when i put the code in it dose not pop up in 15 to 20 seconds 

### ISSUE THREAD

**Issue by christopher11400180** [Prodigy-Hacking/ProdigyMathGameHacking#1148]
***Description***:help me plese

***Replication***:
i need these hacks

***Images***:

***Additional Errors***:

**Comment by hostedposted** [comment]
Do you have the extension installed?

**Comment by PatheticMustan** [comment]
can't replicate with latest PHEx, and HTTPS everywhere. OP hasn't responded in over a week, so closed until OP elaborates on what extensions/extension version they have
