### ISSUE TITLE
[BUG] I cant delete the stuff I got with the hacks and it usually dosn't let me in because the hacks

### ISSUE THREAD

**Issue by Nightmare323** [Prodigy-Hacking/ProdigyMathGameHacking#1168]
***Description***:FIX IT

***Replication***

***Images***:

***Additional Errors***:

**Comment by PatheticMustan** [comment]
wow thanks for the super detailed bug report, but would it be possible to attach a screenshot of the errors in console?
xoxo <3 <3

**Comment by 32n** [comment]
It states in the hacks that many cannot be undone, and you are being too vague with your description of your problem.

**Comment by 32n** [comment]
@PatheticMustan told me irl not to close issues, and let the bot close them if people don't respond, but I personally do not see the point of keeping this issue. It's unbelievably vague and

**Comment by afkvido** [comment]
> @PatheticMustan told me irl not to close issues, and let the bot close them if people don't respond, but I personally do not see the point of keeping this issue. It's extremely vague, and the author clearly has put no effort in documenting their issue.

YOU KNOW MUSTAN IRL!?!?

**Comment by 32n** [comment]
> > @PatheticMustan told me irl not to close issues, and let the bot close them if people don't respond, but I personally do not see the point of keeping this issue. It's extremely vague, and the author clearly has put no effort in documenting their issue.
> 
> YOU KNOW MUSTAN IRL!?!?

Yes, I see him every day. What a nerd!

**Comment by PatheticMustan** [comment]
2 months and no response from OP. sad!

**Comment by donaldli2020** [comment]
> 2 months and no response from OP. sad!

Remember 6ed61e0?

**Comment by PatheticMustan** [comment]
you're asking if I remember a commit I made a week ago..?

**Comment by donaldli2020** [comment]
> you're asking if I remember a commit I made a week ago..?

the "gactions stale bot" removal.

**Comment by afkvido** [comment]
> ***Description***:FIX IT
> 
> 
> 
> 
> 
> ***Replication***
> 
> 
> 
> 
> 
> ***Images***:
> 
> 
> 
> 
> 
> ***Additional Errors***:
> 
> 

you can use **Reset Account**
