### ISSUE TITLE
click teleport hacks are broken, again

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#1173]
jeez, why can't they just stay fixed

open to anyone who wants to take the issue

**Comment by Undefineduser2** [comment]
It only breaks when you go to another section on the map.
For example, in firefly forest where flora is and going to the firefly collector area.

**Comment by 32n** [comment]
Is this similar to #1158? I might try to fix this, but not this weekend.

**Comment by PatheticMustan** [comment]
this is unrelated to 1158.
