### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ThatLegend** [Prodigy-Hacking/ProdigyMathGameHacking#1183]
***Description***:
if you set your gold to 10,000,001+ your game crashes.

***Replication***:

***Images***:

***Additional Errors***:

**Comment by 32n** [comment]
I was able to replicate this issue, and I believe prodigy will return error 418 when a player has more than 10,000,000 gold, as after giving myself 10,000,000 gold and winning a battle, the same thing happened. I guess a good fix would just be to not allow a user to give themselves more than 10,000,000 gold.

**Comment by 32n** [comment]
Thank you for submitting this issue! In the future, it would be even more helpful to us if you could include screenshots of the game or your console, and give us a more detailed description of your bug :)

**Comment by ThatLegend** [comment]
ok

**Comment by PatheticMustan** [comment]
i was also able to replicate.
it may be helpful to artificially limit the gold to 9 million instead, since you can still trigger the 10m limit through setting it to 10m and battling, as @32n said.

**Comment by 32n** [comment]
That's a bad idea. The 418 isn't that annoying, and most people are probably setting their gold that high just to buy something expensive.

**Comment by 32n** [comment]
Honestly it also just feels uncomfortable to limit the hacks when there's not necessarily a real need to.

**Comment by actualethan** [comment]
Agreed

**Comment by 32n** [comment]
Who are you? You made a new account a minute before you commented on this closed issue.

**Comment by actualethan** [comment]
I wouldnt worry about that

**Comment by ThatLegend** [comment]
I am who i am
