### ISSUE TITLE
Error 418 every single time I use the hacks. Holy moly.Also,are you updating the hacks?It won't let me in to Prodigy.[BUG] 

### ISSUE THREAD

**Issue by YourOrdinaryProdigyHacker** [Prodigy-Hacking/ProdigyMathGameHacking#1192]
***Description***:

***Replication***:

***Images***:

***Additional Errors***:

**Comment by donaldli2020** [comment]
This is also a problem for me. Try again in a few minutes, so disable the extension.

**Comment by YourOrdinaryProdigyHacker** [comment]
How do I do that?

**Comment by donaldli2020** [comment]
chrome://extensions and turn off the PHEx switch.

**Comment by donaldli2020** [comment]
https://hacks.prodigyhacking.com is error 502 so hacks won't load.

**Comment by 32n** [comment]
Please help us research the exact hacks that cause 418 errors by posting them in #1154. I assume by not being "let in" to prodigy, you mean that you are unable to login. This seems to be a common issue, join the [Official PMGH Discord Server](https://discord.gg/XQDfbfq) and check out #common-errors for help. If you are still having trouble logging in, ask for help in #support.

This is too vague and describes known problems with the hacks, so I'll be closing this issue.

**Comment by YourOrdinaryProdigyHacker** [comment]
I have a picture.

**Comment by donaldli2020** [comment]
turn on the extension and try fix morph crash

**Comment by 32n** [comment]
Still, this is not something you should be making an issue about, as it appeared to be a very common problem, and it's formatted as asking for support, which is better done on the discord. Also, given your description, I don't think this is an issue with the hacks.
