### ISSUE TITLE
Rune Run Bug

### ISSUE THREAD

**Issue by er509** [Prodigy-Hacking/ProdigyMathGameHacking#1194]
***Description***: I can't start rune run after using hack!

***Replication***:None

***Images***: None

***Additional Errors***:None

**Comment by donaldli2020** [comment]
1. Change your team to valid pets (not Crystal Monster).
2. Fix battle crash
3. Try without the extension.
4. Try another account.
5. Use another browser.

**Comment by 32n** [comment]
Please send the console error/output when you try to start rune run. Also try the stuff @donaldli2020 posted.

**Comment by afkvido** [comment]
This bug happens to literally everyone. (y'all should add the confirmed bug label, admins)

**Comment by er509** [comment]
thx guys

**Comment by er509** [comment]
donaldli2020's method worked!

**Comment by 32n** [comment]
> This bug happens to literally everyone. (y'all should add the confirmed bug label, admins)

ok

**Comment by LeoBadeaux** [comment]
donaldi2020's method reportedly works. If you experience any more issues, refer to #407.
