### ISSUE TITLE
[BUG] lotsa random images

### ISSUE THREAD

**Issue by AuraProgramming** [Prodigy-Hacking/ProdigyMathGameHacking#1197]
***Description***: ;-;

***Replication***: Ice island place or whatever

***Images***: 
![image](https://user-images.githubusercontent.com/83914971/142299493-4887d15f-8704-4ac6-8695-b622692c8c49.png)

***Additional Errors***: idk what it is, and when i click on them they dont do anything

**Comment by AuraProgramming** [comment]
Error: Cannot set frameName: store for sprite with key: atlas-21 and frameData total: 204"

**Comment by ConnorAhern** [comment]
[solution](https://youtu.be/zL19uMsnpSU)

**Comment by 32n** [comment]
Sorry, I'm don't really play prodigy much, could you explain what exactly is out of place? Are you sure this issue is caused by the hacks?

**Comment by ConnorAhern** [comment]
i know what is out of place so the icons are in random places up at the top which is not good

**Comment by In4init3** [comment]
> Error: Cannot set frameName: store for sprite with key: atlas-21 and frameData total: 204"

this literally means the atlas sprite sheet is configured incorrectly so it shows all icons on the atlas, this could be due to hacks or some other bug made by them and prodigy

**Comment by LeoBadeaux** [comment]
can we confirm this is still happening, and if so, confirm this is a bug with hacks?

**Comment by afkvido** [comment]
I don't think this still happens
