### ISSUE TITLE
[BUG]Prodigy won't load with extension on.

### ISSUE THREAD

**Issue by kjhgtfrtdyu** [Prodigy-Hacking/ProdigyMathGameHacking#1206]
***Description***:

Prodigy won't load with the extension on.
***Replication***:

Go in prodigy with extension on.
***Images***:
None

***Additional Errors***:
None

**Comment by donaldli2020** [comment]
Make sure https://hacks.prodigyhacking.com is not down.

**Comment by 32n** [comment]
This is an extremely common issue that appears to happen for a variety of reasons. You should ask for help with this on the (PMGH discord server)[https://discord.gg/XQDfbfq] instead.
