### ISSUE TITLE
[BUG]Skip tutorial doesn't work.

### ISSUE THREAD

**Issue by hellonearth311** [Prodigy-Hacking/ProdigyMathGameHacking#1207]
***Description***:
I clicked skip tutorial and it didn't work.

***Replication***:
Make a new account and press skip tutorial in the cheat menu.

***Images***:
None

***Additional Errors***:
None

**Comment by ConnorAhern** [comment]
@PatheticMustan someone reply to this

**Comment by PatheticMustan** [comment]
secretly rewriting hacks shshshsh

**Comment by alanadiamondpearl** [comment]
This also happened to me

**Comment by afkvido** [comment]
> This also happened to me

It didn't happen to me.
Make sure to clear your cache and reload prodigy

then make a new prodigy acc and try

**Comment by ArcerionDev** [comment]
fixed, can confirm
