### ISSUE TITLE
[BUG] broken achievements

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1212]
***Description***:

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/74021676/143780521-de671c20-2c8b-474c-900e-b0305f6118f9.png)

***Additional Errors***:

**Comment by donaldli2020** [comment]
#1211

**Comment by PatheticMustan** [comment]
98078201547332a3b3fd40dedfbdf9e0554bd304
