### ISSUE TITLE
[BUG] Almost All Pet Hacks Broken

### ISSUE THREAD

**Issue by 32n** [Prodigy-Hacking/ProdigyMathGameHacking#1216]
***Description***:
Most of the pet hacks are completely broken, and either return 418, or are just non-functional. I have a list somewhere, I'll edit this issue and paste it here.

**Comment by afkvido** [comment]
Wdym?

I can get any pets just fine, and EDIT PET (BETA) works perfectly!

**Comment by 32n** [comment]
This issue was fixed earlier, I forgot to close it, my bad.

**Comment by afkvido** [comment]
oh ok :)
