### ISSUE TITLE
[BUG] Broke Bonfire Spire

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1217]
***Description***:
Bonfire Spire map broken

***Replication***:
Complete current task in quest but some locations are still locked because the levers aren't pulled

***Images***:

***Additional Errors***:

**Comment by afkvido** [comment]
FOR NOW, you can use this to get the levers:

- Turn on `Disable Monster Encounters` to prevent spawning into a mob
- use Location Hacks => `Teleport to map (Interactive)`
- Select `Bonfire Spire`
- then idk which zones, try them all, youll get the levers eventually

**Comment by donaldli2020** [comment]
ok, i'll close this for #1269
