### ISSUE TITLE
[HELP] School Computers kill you

### ISSUE THREAD

**Issue by GokuUltraInstict13** [Prodigy-Hacking/ProdigyMathGameHacking#1224]
**Please** help me. can you make a way to download it like the old way? Because that worked for the school Chromebook

**(Optional) Additional information** E

**Comment by 32n** [comment]
Unfortunately, the way we hack prodigy requires you to either receive modified game files from our proxy, or host it yourself. Alternatively, you could host it yourself, but I'm not sure how it'd all work on ChromeOS.
