### ISSUE TITLE
[HR] Ultimate Membership

### ISSUE THREAD

**Issue by afkvido** [Prodigy-Hacking/ProdigyMathGameHacking#1234]
**Describe your hack:**
We only have the basic membership hack right now. Please add an ultimate membership toggler.

**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes. we only have basic membership

**Comment by donaldli2020** [comment]
We've reached #1234! What a cool number!

**Comment by donaldli2020** [comment]
Ok, I think think this can be possible because you have the basic membership.

**Comment by afkvido** [comment]
> We've reached #1234! What a cool number!

ayyyyy

**Comment by afkvido** [comment]
> Ok, I think think this can be possible because you have the basic membership.

wonderful!

**Comment by donaldli2020** [comment]
sorry for 2 thinks

**Comment by donaldli2020** [comment]
Maybe try:
```
_.instance.prodigy.gameContainer.get("98e-4ed0").data.membership.active = true;
_.instance.prodigy.gameContainer.get("98e-4ed0").data.egInfo.tier = 3;
```

**Comment by donaldli2020** [comment]
We have a dupe of #1174

**Comment by afkvido** [comment]
> We have a dupe of #1174 

oops

**Comment by 32n** [comment]
duplicate.

**Comment by afkvido** [comment]
> Maybe try:
> 
> ```
> _.instance.prodigy.gameContainer.get("98e-4ed0").data.membership.active = true;
> _.instance.prodigy.gameContainer.get("98e-4ed0").data.egInfo.tier = 3;
> ```

just pasting that doesn't work.
