### ISSUE TITLE
[BUG] most hacks on https://prodigy-dashboard.hostedposted.com are broken

### ISSUE THREAD

**Issue by SakuraKitsunee** [Prodigy-Hacking/ProdigyMathGameHacking#1235]
***Description***: most hacks on https://prodigy-dashboard.hostedposted.com are broken (ex.you can't get only one pet with it popping up an error) 

***Replication***: try to get any one pet on the website 

***Images***:

***Additional Errors***: it also does not work if it's a new account even after the tutorial

**Comment by ArcerionDev** [comment]
feel free to use the https://hacks.prodigyhacking.com domain ,  i'm not sure if the secondary domain is updating automatically.

**Comment by ArcerionDev** [comment]
wait nevermind i'm stupid that's the dashboard

i'll reach out to the dashboard developers about this

**Comment by ArcerionDev** [comment]
cc @AgrTheDev , @hostedposted , @TheFinality

**Comment by LeoBadeaux** [comment]
@ArcerionDev can we start not accepting issues about the panel since it's really just hostedposted's panel?

**Comment by hostedposted** [comment]
fixed
