### ISSUE TITLE
[BUG] Buddy Game Crash

### ISSUE THREAD

**Issue by alanadiamondpearl** [Prodigy-Hacking/ProdigyMathGameHacking#1242]
***Description***:
When I try to give myself the toy buddies, the game crashes when I press the "OK" button next to "Buddy Added!".

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/90733707/147974108-3d15e28e-046c-4833-a152-67521cd9e117.png)

![image](https://user-images.githubusercontent.com/90733707/147974405-fb7f38a6-bbb3-4fd3-8f23-dc76f6c3d1bc.png)

![image](https://user-images.githubusercontent.com/90733707/147974277-164ca00f-2def-4715-896f-77597c3bbf7a.png)

***Additional Errors***:
It also crashes when I try to give myself all the buddies.

**Comment by alanadiamondpearl** [comment]
Magmayhem and arcturion don't cause the problem though

**Comment by donaldli2020** [comment]
It's for hack prevention

**Comment by PatheticMustan** [comment]
??? not sure what "hack prevention" is but it's not for that

for now, just try using the advanced selector. we're aware basic selector is broken.
