### ISSUE TITLE
[HR] Chat Hacks

### ISSUE THREAD

**Issue by alanadiamondpearl** [Prodigy-Hacking/ProdigyMathGameHacking#1243]
**Describe your hack:**
The ability to type anything you want in chat.

**(Optional) Additional information**
Maybe swear words and stuff would filter out or something.

**Have you made sure this hack isn't available yet? (Yes/No)**
Yes

**Comment by donaldli2020** [comment]
There was this hack but people typed swears.
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/issues/19#issuecomment-591557641
Comment by Exoticc: "I was in animalia on prodigy and i saw someone named Addison curse on the chat"

**Comment by afkvido** [comment]
> There was this hack but people typed swears.
> [#19 (comment)](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/issues/19#issuecomment-591557641)
> Comment by Exoticc: "I was in animalia on prodigy and i saw someone named Addison curse on the chat"

WAIT PLEASE LET US GET CUSTOM CHAT, I WANT TO CURSE IN PRODIGY CHAT

**Comment by afkvido** [comment]
PLEASE I PAY YOU MONEY IF HACK

**Comment by afkvido** [comment]
> https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/23bfe3186727877d445f1e204b9c74fb25c87df1/Experimental/AddCustomChat.js

tysm<3

**Comment by afkvido** [comment]
@alanadiamondpearl this hack is not possible to implement, please close your issue.
