### ISSUE TITLE
[HR] Get all buddies instead of the epic ones

### ISSUE THREAD

**Issue by alanadiamondpearl** [Prodigy-Hacking/ProdigyMathGameHacking#1244]
**Describe your hack:**
A hack where you get every buddy instead of the epic ones.

**(Optional) Additional information**
This is because the epic buddies crash your game.

**Have you made sure this hack isn't available yet? (Yes/No)**
Yes

**Comment by afkvido** [comment]
@alanadiamondpearl Please close this.

You can use this:
- Inventory Hacks: `Selector (Basic)`
- Select `Buddies`
- Type `1`

You now have all non-epic buddies

**Comment by afkvido** [comment]
@alanadiamondpearl @32n  please close

This was added in https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/db49f601bd5faa102f38ea4739879e1cc8fcd899

**Comment by 32n** [comment]
As you wish.
