### ISSUE TITLE
[BUG] Dashboard doesn't even show up.

### ISSUE THREAD

**Issue by afkvido** [Prodigy-Hacking/ProdigyMathGameHacking#1261]
***Description***:
https://prodigy-dashboard.hostedposted.com
There's literally nothing there, except the dark gray background

***Replication***:
1. Go to https://prodigy-dashboard.hostedposted.com
2. There's literally nothing there, except the dark gray background

***Images***:
![image](https://user-images.githubusercontent.com/69060894/148849983-af37c003-f09b-4bba-b2d2-85f1bbec271b.png)

***Additional Errors***:
Last known time when the dashboard actually loaded properly, the hacks didn't work. #1235

**Comment by donaldli2020** [comment]
#1237
