### ISSUE TITLE
[BUG] I can't go past Miscellaneous Hacks,and it's ANNOYING ME.

### ISSUE THREAD

**Issue by YourOrdinaryProdigyHacker** [Prodigy-Hacking/ProdigyMathGameHacking#1264]
***Description***: For some reason,I can't get past Miscellaneous Hacks. It worked yesterday,but now it just STOPPED. Do you know how to fix it? Thanks.

***Replication***:

***Images***:

***Additional Errors***:

**Comment by donaldli2020** [comment]
me too

**Comment by 32n** [comment]
Please send relevant screenshots/console errors.

**Comment by 32n** [comment]
Resolved by latest commit. It was a problem with @donaldli2020's latest pull request. My bad, I should have tested it before merging, it was just pretty small so I didn't think he could've messed it up.

**Comment by donaldli2020** [comment]
I didn't know how the toggler thing worked

**Comment by ArcerionDev** [comment]
> I didn't know how the toggler thing worked

how are you creating bundle.js @donaldli2020

**Comment by donaldli2020** [comment]
so i tried changing onclick or something to setEnabled and added .setDisabled and the code

**Comment by donaldli2020** [comment]
i think it would be a good idea to format the code

**Comment by 32n** [comment]
It wasn't an issue with the toggler. Next time, please update webpack and build with the official build script.

**Comment by donaldli2020** [comment]
because everything is hard to read

**Comment by ArcerionDev** [comment]
> so i tried changing onclick or something to setEnabled and added .setDisabled and the code

that's not how you bundle the menu, you need to install & run webpack

**Comment by donaldli2020** [comment]
what's webpack

**Comment by donaldli2020** [comment]
i don't know how to use webpack

**Comment by 32n** [comment]
*sigh*
```
sudo npm install -g webpack
```
and when building from /ProdigyMathGameHacking
```
cd willsCheatMenu
npm run build
```

**Comment by YourOrdinaryProdigyHacker** [comment]
Is this fixed?

**Comment by afkvido** [comment]
Yes
