### ISSUE TITLE
[BUG] Something from bug#1264(I posted it yesterday)

### ISSUE THREAD

**Issue by YourOrdinaryProdigyHacker** [Prodigy-Hacking/ProdigyMathGameHacking#1266]
***Description***:Is this fixed?

***Replication***:

***Images***:

***Additional Errors***:

**Comment by afkvido** [comment]
@32n 
duplicate/spam post, please close

**Comment by 32n** [comment]
@YourOrdinaryProdigyHacker please refrain from making spammy/useless issues. This isn't a place to have a discussion or spam.
