### ISSUE TITLE
Teleport hack[BUG]

### ISSUE THREAD

**Issue by LMAWESOME** [Prodigy-Hacking/ProdigyMathGameHacking#1267]

**Comment by afkvido** [comment]
Please provide a description and screenshots.
Maybe expected/actual behavior, too?

We can't understand your bug report if it's just two words

**Comment by afkvido** [comment]
@32n 

invalid bug report, pls close uwu

**Comment by donaldli2020** [comment]
yeah

**Comment by 32n** [comment]
> @32n
> 
> invalid bug report, pls close uwu

Patience, young one.

**Comment by afkvido** [comment]
ok :)

**Comment by donaldli2020** [comment]
@LMAWESOME
- Where are you teleporting to?
- Browser?
- OS?
Does this work on other...
- Accounts?
- Browsers?
- OS?
- Locations?

**Comment by 32n** [comment]
Whoops, I didn't realize this was 7 days old. Maybe closing it would be justified. I've been on an issue-closing streak recently tho, and don't wanna overstep bounds, so I'll let the maintainers decide what to do.

**Comment by donaldli2020** [comment]
I found out that this person joined 7 days ago, probably just for this issue.

**Comment by afkvido** [comment]
> Whoops, I didn't realize this was 7 days old. Maybe closing it would be justified. I've been on an issue-closing streak recently tho, and don't wanna overstep bounds, so I'll let the maintainers decide what to do.

ok! :)

**Comment by afkvido** [comment]
> I found out that this person joined 7 days ago, probably just for this issue.

lmao

**Comment by afkvido** [comment]
## Update

I just found that he updated his message, it used to say this:
> Teleport hack is not working but yesterday it was is there anything to fix that?

This is the issue that can be fixed by clearing the cache, so this issue doesn't belong open on the repo.

**Comment by ArcerionDev** [comment]
issues without sufficient info will be closed after a period of no response from the creator.

**Comment by LMAWESOME** [comment]
Sorry, I accidentally sent something.
So sry
