### ISSUE TITLE
[BUG] None of the FUCKING hacks work. HELP.

### ISSUE THREAD

**Issue by YourOrdinaryProdigyHacker** [Prodigy-Hacking/ProdigyMathGameHacking#1275]
***Description***: The hacks for some reason aren't working. Either the hacks are down,or the hacks are outdated. H. E. L. P.

***Replication***:

***Images***:

***Additional Errors***:

**Comment by afkvido** [comment]
What do you see?
Do you see a TypeError, failed to fetch?

or do the hacks just say "success" but nothing happens?

**Comment by donaldli2020** [comment]
I think I know what's going on. I'll open a new issue.

**Comment by afkvido** [comment]
> I think I know what's going on. I'll open a new issue.

ty. this issue is scuffed, and not really describing the problem

**Comment by donaldli2020** [comment]
ok, opened

**Comment by afkvido** [comment]
> ok, opened

yay!

**Comment by afkvido** [comment]
> _**Description**_: The hacks for some reason aren't working. Either the hacks are down,or the hacks are outdated. H. E. L. P.
> 
> _**Replication**_:
> 
> _**Images**_:
> 
> _**Additional Errors**_:

are you retarded
