### ISSUE TITLE
[BUG] Reload to work

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1276]
***Description***:
I think this is what @yourordinaryprodigyhacker is trying to say in #1275.
If you open Prodigy, the hacks don't work. They require a reload.
***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
reloading won't change anything unless reloading clears the cache,
![image](https://user-images.githubusercontent.com/60945964/149580801-77dbaf9d-4e4f-4b46-80ad-0d6aabe9c62d.png)


PSB logged a new update 4 hours ago and I don't think anyone has restarted the VPS, so I'm assuming that's the issue mentioned in #1276

**Comment by afkvido** [comment]
@donaldli2020 fixed

**Comment by donaldli2020** [comment]
...not fixed

**Comment by ArcerionDev** [comment]
it is, actually.

we made the cache for the site update itself so this issue won't happen anymore. 

We also disabled caching for hacks.prodigyhacking so this shouldn't happen anymore.

**Comment by afkvido** [comment]
HELL YEAAAA

**Comment by afkvido** [comment]
NO MORE CLEAR THE CAHCE AND CLOSE PRODIGY?
