### ISSUE TITLE
[BUG] Dashboard refuses new sign-ins

### ISSUE THREAD

**Issue by Erisfiregamer1** [Prodigy-Hacking/ProdigyMathGameHacking#1278]
***Description***:
The dashboard refuses the sign-in of new accounts, even after tutorial completion.

***Replication***:
Try to log into the dashboard with an account never used on it before.

***Images***:
(I'm not leaking my account info!!)

***Additional Errors***:
Console reports 500 from token access.

**Comment by Erisfiregamer1** [comment]
@hostedposted go fix your dashboard

**Comment by ArcerionDev** [comment]
@hostedposted fyi this is a tokenify issue, I need to contact the tokenify creator about this or actually get around to fixing it myself

**Comment by Erisfiregamer1** [comment]
FYI: If this is happening to you, verify your home email. It fixes it... After a while...

**Comment by AgrTheDev** [comment]
I thought email confirmation was only a feature on sign up endpoints instead of login?

**Comment by afkvido** [comment]
> I thought email confirmation was only a feature on sign up endpoints instead of login?
> 
> 

it's weird

**Comment by donaldli2020** [comment]
you can get email confirmation during log in
it warns you before confirming
then confirms after a days or so

**Comment by afkvido** [comment]
oh

**Comment by afkvido** [comment]
@hostedposted bro respond to this issue pls

**Comment by hostedposted** [comment]
I'll try to fix tokenify

**Comment by hostedposted** [comment]
fixed this
