### ISSUE TITLE
[BUG] Editing pets on dashboard causes a crash

### ISSUE THREAD

**Issue by Erisfiregamer1** [Prodigy-Hacking/ProdigyMathGameHacking#1281]
***Description***:
Editing pets on the dashboard causes the dashboard to delete itself.

***Replication***:
Try to edit a pet on the dashboard.

***Images***:
(blank grey screen)

***Additional Errors***:
Unknown, no access to console

**Comment by donaldli2020** [comment]
Happened to me on some accounts. Just don't search or click on white stuff.

**Comment by hostedposted** [comment]
fixed
