### ISSUE TITLE
[BUG] Winterfest doesn't show up

### ISSUE THREAD

**Issue by afkvido** [Prodigy-Hacking/ProdigyMathGameHacking#1282]
***Description***:
Winterfest doesn't show up with hacks on

***Replication***:
- Have PHEX installed
- go to lamplight
- there is no winterfest

***Images***:
Hacks off:
https://media.discordapp.net/attachments/728777699279110214/933179272095469568/unknown.png
Hacks on:
https://media.discordapp.net/attachments/728777699279110214/933179550123307099/unknown.png

***Additional Errors***:
hanz doesn't show up, but that's because only normal lamplight works.

**Comment by afkvido** [comment]
this is fixed..... at least

**Comment by donaldli2020** [comment]
me too, fixed
