### ISSUE TITLE
[BUG] Can't login to a new account on the dashboard 

### ISSUE THREAD

**Issue by 0BunnySenpai0** [Prodigy-Hacking/ProdigyMathGameHacking#1286]
***Description***: when you try to login to the dashboard on a NEW ACCOUNTS (it works fine for account that have been active for about a week, which is weird) it just loads 

***Replication***: 

1. go to https:/prodigy-dashboard.hostedposted.com/
2. make a new account 
3. complete the tutorial
4. TRY to login to the dashboard

***Images***: ![Screenshot 2022-01-21 8 31 59 AM](https://user-images.githubusercontent.com/96202635/150564343-063c52c2-23ac-4963-b31d-142536821106.png) (has been loading for about 25 min)

***Additional Errors***: N/A

**Comment by ArcerionDev** [comment]
this is a known error, prodigy added another screen to their login page (email conf page) so the process we use to convert the account credentials into an account token no longer works.

**Comment by 0BunnySenpai0** [comment]
ok, have a great day! :)

**Comment by donaldli2020** [comment]
@0BunnySenpai0 Just confirm any email and the thing will work

**Comment by afkvido** [comment]
> 

you can use 10 minute mail

**Comment by donaldli2020** [comment]
@0BunnySenpai0 already has an inbox bc of the github account
github signup requires email verification

**Comment by afkvido** [comment]
> @0BunnySenpai0 already has an inbox bc of the github account
> github signup requires email verification

yeah, but to **avoid** spam/bullshit from prodigy, you can use 10m mail

also, I don't want a megacorp collecting my email, FU prodigy

**Comment by donaldli2020** [comment]
sending emails to an address that doesn't exist anymore lol

**Comment by afkvido** [comment]
> sending emails to an address that doesn't exist anymore lol

EXACTLY

**Comment by afkvido** [comment]
prodigy would have a bunch of dead emails on their list if we all used 10 min mail
