### ISSUE TITLE
[BUG] extension version

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1293]
***Description***:
https://hacks.prodigyhacking.com/version
hacks are "outdated" because the "current version" is 2.1.7 but the version i'm using is 2.1.8
***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
will fix this when we push this to the webstore, until then we're keeping it so that the support server isn't flooded with people all asking why their extensions are outdated.
