### ISSUE TITLE
[HR]

### ISSUE THREAD

**Issue by bdshksdsxfsd** [Prodigy-Hacking/ProdigyMathGameHacking#1297]
get mythical epics

**Comment by afkvido** [comment]
> get mythical epics

You can get mythical epics with `Selector (Advanced)` for now.

**Comment by donaldli2020** [comment]
> > get mythical epics
> 
> You can get mythical epics with `Selector (Advanced)` for now.

i think add pet

**Comment by afkvido** [comment]
> > > get mythical epics
> > 
> > 
> > You can get mythical epics with `Selector (Advanced)` for now.
> 
> i think add pet

Selector for buddies, Add Pet for pets

**Comment by donaldli2020** [comment]
yes
