### ISSUE TITLE
Hack List

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#13]
We should make a list of all the hacks, so that they can be accessed easily.

Each hack would require

```
## [HackName](LinkToHackFile)
Hack Description
```

Example:

## [Membership](https://github.com/PatheticMustan/ProdigyMathGameHacking/blob/master/hacks/Membership.js)
This hack temporarily gives you Membership. You can access Member restricted places, get the monthly member box, and buy items/pets only a member would be able to buy. Membership is reset to it's previous value when you refresh the tab, but any items/pets/stars earned will not be removed.

**Comment by Avn1114** [comment]
We could possibly also leave that in a comment in the script, or make it an alert. So I think that that takes more work than is really necessary at this point.

**Comment by GyarGG** [comment]
The "get all buddies" hack doesnt work for me, but i put javascript: in front of the code. if there something else i need to do?

**Comment by Avn1114** [comment]
Hacks with multiple lines don't always work with a bookmarklet. Idk why. 😞

**Comment by PatheticMustan** [comment]
You need to make sure there are semi-colons after every line. That's just a JS thing.

**Comment by PatheticMustan** [comment]
@GyarGG, I added semicolons after each line. You can also try this:
```
javascript:PIXI.game.prodigy.player.backpack.data.follow=[];x=PIXI.game.state.states.Boot._gameData.follow;for(i in x){PIXI.game.prodigy.player.backpack.data.follow[i]={"ID":x[i].ID,"N":1}}
```
Also next time, if you want attention on an issue, just make a new issue!

**Comment by GyarGG** [comment]
Got it, i saw that you or someone just updated the getAllBuddies script. Thanks!

**Comment by GyarGG** [comment]
yeah, you're right, i just don't have that much experience with Github issues tbh.

**Comment by DaChickenKing** [comment]
Also, I've already investigated adminLogin
It's a district thing, not OP powers that developers have
[https://school-leaders.prodigygame.com/](https://school-leaders.prodigygame.com/)

**Comment by Avn1114** [comment]
Ohh ok

**Comment by Magmischief** [comment]
Hey can i add the hack list in the wiki?

**Comment by Avn1114** [comment]
Yes, please do!

**Comment by Magmischief** [comment]
So, like only the hacks in the Hack folder or all the hacks in all the folders?

**Comment by Avn1114** [comment]
Whatever you think is necessary. Also maybe include the Everything.js

**Comment by Magmischief** [comment]
Okay

**Comment by Dell666** [comment]
can someone mod me prodigy account

**Comment by RubberDuck55** [comment]
Sorry, but we are not sure about our stance on hacking others accounts.

**Comment by Dell666** [comment]
I met hack as in mod my account.

**Comment by Dell666** [comment]
I don't have a pic which is why I asked mustan

**Comment by PatheticMustan** [comment]
I literally made a script that does everything for you, we're not gonna spoon feed y'all

**Comment by Dell666** [comment]
I done have a computer just a phone

**Comment by RubberDuck55** [comment]
use a bookmarklet

**Comment by PatheticMustan** [comment]
stick javascript: in front of the hack, then put the result into the URL area of a bookmark

**Comment by TehVegasPro763-22** [comment]
umm...

**Comment by TehVegasPro763-22** [comment]
I have ALMOST every Prodigy hack. 
In this link: https://gist.github.com/TehVegasPro763-22/e660ded7c78e20557636a5724c24f4d7
I bet some of you guys already saw it.

**Comment by TehVegasPro763-22** [comment]
> The "get all buddies" hack doesnt work for me, but i put javascript: in front of the code. if there something else i need to do?
Here buddy, use this:
javascript:(function()%7B%2F%2F Gives you all buddies.%0APIXI.game.prodigy.player.backpack.data.follow%3D%5B%5D%0Ax %3D PIXI.game.state.states.Boot._gameData.follow%0Afor (i in x) %7B%0A    PIXI.game.prodigy.player.backpack.data.follow%5Bi%5D %3D %7B"ID"%3A x%5Bi%5D.ID%2C "N"%3A 1%7D%0A%7D%7D)()%3B

**Comment by Diveodile** [comment]
https://gist.github.com/Diveodile/8f4b41b5181b5cdb380581de59c84f61

**Comment by Diveodile** [comment]
Hello?

**Comment by Dell666** [comment]
dont know how to use this javascript but i guess ill try

**Comment by RtypeX** [comment]
U know where teleport hack is?

**Comment by Dell666** [comment]
No but I'm pretty sure a while ago the console was turned off due to alot
of people leaking hacks on YouTube. There might be a new method to
doing that. But I will check it out later today because I have online
school classes.
Thanks, I will email you later

**Comment by JamesD11738** [comment]
can somebody give me all pets and temporarily give me free membership

**Comment by JamesD11738** [comment]
hellooo

**Comment by ree124** [comment]
hi

**Comment by Nightsnake763** [comment]
> We should make a list of all the hacks, so that they can be accessed easily.
> 
> Each hack would require
> 
> ```
> ## [HackName](LinkToHackFile)
> Hack Description
> ```
> 
> Example:
> 
> ## [Membership](https://github.com/PatheticMustan/ProdigyMathGameHacking/blob/master/hacks/Membership.js)
> This hack temporarily gives you Membership. You can access Member restricted places, get the monthly member box, and buy items/pets only a member would be able to buy. Membership is reset to it's previous value when you refresh the tab, but any items/pets/stars earned will not be removed.

**Comment by Nightsnake763** [comment]
Could you try to do a hack for helmet heroes? Because it's an online game and it has more security

**Comment by Prodigymathgame** [comment]
Is it possible to hack to open the other warden towers?

**Comment by luckysaini** [comment]
Guys I need Lazaros tool 
But I don't have link to download anybody know 
Please help me 
+380635658649

**Comment by liyuanrui841** [comment]
How long are you rate limited if you use more than 1 arena point hack per minute?

**Comment by connnywilmeringBA** [comment]
https://www.youtube.com/watch?v=uFYQv9HDAXk

**Comment by Prodigymathgame** [comment]
Can you hack my account with membership, and allow me to battle, coz it
just freezes.
Username is elipollardatspedhead.com@gmail.com
Password is rocky

**Comment by PatheticMustan** [comment]
@luckysiani and @Prodigyhacker17625, read #170 

@Prodigyhacker17625, the rate limit is 1 win (100 arena points) per minute.

**Comment by PatheticMustan** [comment]
@connnywilmeringBA, spam. Please don't post on our issues again.

**Comment by Prodigymathgame** [comment]
Can you please hack my  account with membership?
Username is elipollardatspedhead.com@gmail.com
Password is rocky

**Comment by Abhijot123** [comment]
who can give me working hacks im new here.

please

**Comment by Dell666** [comment]
If you want me to put infinite currency and everything in the game just
email me your info, i have working hacks.

**Comment by Prodigymathgame** [comment]
Please get me membership.
Email me at natsudragoneeljim@gmail.com please

**Comment by Prodigyhacker17625** [comment]
It didn’t work!

**Comment by Prodigyhacker17625** [comment]
The arena point hack!

**Comment by Prodigyhacker17625** [comment]
My arena points stays at 5700 point even if I do the hack over and over and over! I think I accidently used it for more than once in a minute. But can I fix that?

**Comment by Prodigyhacker17625** [comment]
I’ll show you a pic later...

**Comment by Prodigymathgame** [comment]
My pets list is broken. I cant find crystal monster, and I have it. I have
2 sets of epics, and other stuff. Please can you fix that. Also please get
me membership if possible
Username is elipollardatspedhead.com@gmail.com
Password is rocky

**Comment by bigjango360** [comment]
so do you have to ctrl-shift-i and paste the code in the console?

**Comment by Prodigymathgame** [comment]
Yeah i think so. I cant coz i have a crappy chromebook. Also i cant battle.
My pets just freeze please fix this too

**Comment by PatheticMustan** [comment]
@Prodigymathgame read #170, never post your account info again.

**Comment by PatheticMustan** [comment]
@Prodigyhacker17625 try refreshing.

If the problem persists, explain the issue with details and screenshots on the discord server.
The invite link is in the github description.

**Comment by Prodigymathgame** [comment]
Why cant i mention my account. If you can hack it for me, this will be the
last time i post my account, plz

**Comment by TheRealCaroleBaskin** [comment]
@Dell666 whats your email.. if you still have working hacks for everything in the game and infinite currency

**Comment by Prodigymathgame** [comment]
Is there a way to get the hacks working again?

**Comment by Prodigymathgame** [comment]
Also I never get anything good in conjure cubes, Is there a way to make
sure I get an item, not just potions/

**Comment by PatheticMustan** [comment]
[ItemStacker](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/hacks/Stacker/itemStacker.js)

Run that, and it'll give you every item.

**Comment by Prodigymathgame** [comment]
Ye, but prodigy doesn't load when redirector is enabled. So it doesn't work

**Comment by taiyamj27** [comment]
How do we put that hack in? ( Where do we put the link in for the mods?)

**Comment by PatheticMustan** [comment]
In console. Press [Control + Shift + I].
