### ISSUE TITLE
HELP i cant switch back to a normal character pls make it so i can switch back

### ISSUE THREAD

**Issue by SUSSYbaka9999** [Prodigy-Hacking/ProdigyMathGameHacking#1300]
***Description***:

***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
can we have more info please

**Comment by afkvido** [comment]
the account @SUSSYbaka9999  was made 6 hours ago

**Comment by afkvido** [comment]
@SUSSYbaka9999 

Please provide a valid description of the bug, how to replicate the bug, and any screenshots.

If you just need help using the hack, ask in our [discord server](https://discord.gg/XQDfbfq)

**Comment by afkvido** [comment]
tbh, lmfao. this issue really reminds me of #1275

**Comment by donaldli2020** [comment]
> the account @SUSSYbaka9999 was made 6 hours ago

(so they probably joined just to issue)

**Comment by afkvido** [comment]
yup
