### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by keldyne** [Prodigy-Hacking/ProdigyMathGameHacking#1302]
So i am sorry but this is not an issue but can i please get help becuase i have never done this and i would like if someone could send a free membership hack and tell me what to do with it sorry for any problems I am causing i just need help PLS.

**Comment by afkvido** [comment]
You can ask for help in our discord server: https://discord.gg/S7qCXRnNre

Also,  please close your issue.

**Comment by keldyne** [comment]
i am on a school computer btw i can not go on discord.

**Comment by afkvido** [comment]
> i am on a school computer btw i can not go on discord.

Dammit.


If you need help getting and using the hack, just get it from the Chrome Web Store, log in to prodigy, and in the top left of the screen you'll find an arrow. Click the arrow to reveal the cheat menu.



When using the hacks, if your hacks just saying `Success` but nothing happens, follow the steps here: https://gist.github.com/afkvido/122d00d787003950210500f8fd9d3e7c
might help

**Comment by keldyne** [comment]
i also can not download that is there anything i can do with hacks without the chrome web store

**Comment by afkvido** [comment]
> i also can not download that is there anything i can do with hacks without the chrome web store

You can get it from zip.



Go to `chrome://extensions`, in the top right enable **Developer Mode**

Download PHEx here: https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/PHEx/build/extension.zip

Drag and drop the downloaded `extension.zip` into `chrome://extensions`

**Comment by keldyne** [comment]
you cant the school disabled it anything else?

**Comment by donaldli2020** [comment]
> you cant the school disabled it anything else?

https://prodigy-dashboard.hostedposted.com/
