### ISSUE TITLE
[BUG] Prodigy Dashboard bug

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1304]
***Description***:
Prodigy Dashboard throws err 500 on login because of the math or english selection

***Replication***:
Go to https://prodigy-dashboard.hostedposted.com/ and type in the login

***Images***:
![image](https://user-images.githubusercontent.com/74021676/151722916-c1b083cd-030b-4ef5-99e2-697099e320ec.png)
![image](https://user-images.githubusercontent.com/74021676/151722923-ee604823-fbab-4f50-9efb-b68a0c5914ac.png)
![image](https://user-images.githubusercontent.com/74021676/151722941-e4b9ec1b-1e29-4cbc-a534-6a4f4a05c43d.png)

***Additional Errors***:

**Comment by ArcerionDev** [comment]
We are aware of this, prodigy has changed the way to obtain a token from the username and password, we're already looking at it
