### ISSUE TITLE
[BUG]Hacks are not working.

### ISSUE THREAD

**Issue by hellonearth311** [Prodigy-Hacking/ProdigyMathGameHacking#1305]
***Description***:
It says failed to fetch.

***Replication***:

***Images***:
![Screenshot (31)](https://user-images.githubusercontent.com/79378144/151729877-97439434-0302-48fd-be85-02cd05762ba0.png)

***Additional Errors***:

**Comment by 32n** [comment]
The VPS is down.

**Comment by donaldli2020** [comment]
error 502
