### ISSUE TITLE
Customizable Arrow Size [Feature Request]

### ISSUE THREAD

**Issue by afkvido** [Prodigy-Hacking/ProdigyMathGameHacking#1309]
Well......

Skids are too dumb to notice a small arrow, but students will be caught by teachers if there's a large arrow.
Please add an option in the extension to change the arrow size.

**Comment by AgrTheDev** [comment]
Or we could just up the size and then have a visibility toggler with a key.

**Comment by AgrTheDev** [comment]
Hide arrow and menu completely

**Comment by afkvido** [comment]
> Hide arrow and menu completely

That's a good idea, too!

**Comment by LeoBadeaux** [comment]
Going to add a feature where you can press `shift` to show/hide the menu later.

**Comment by afkvido** [comment]
> Going to add a feature where you can press `shift` to show/hide the menu later.

Yes!

**Comment by 32n** [comment]
> Going to add a feature where you can press `shift` to show/hide the menu later.

Toggling the menu with keybinds vs a custom arrow should be an option still.

**Comment by afkvido** [comment]
;)

**Comment by LeoBadeaux** [comment]
> > > > Going to add a feature where you can press `shift` to show/hide the menu later.
> > > 
> > > 
> > > Toggling the menu with keybinds vs a custom arrow should be an option still.
> > 
> > 
> > if somebody wants that then they can add it in later but I am going to just have `shift` close/hide the menu because I do not get paid to do this.
> 
> Can you do either the WASD controls or this? I feel like doing one or the other.

I won't, but someone else can.

**Comment by 32n** [comment]
So... you'll do the controls?

**Comment by afkvido** [comment]
;)

**Comment by LeoBadeaux** [comment]
> So... you'll do the controls?

i'll do the shift keybind to show/hide, but someone else can add a resizer.

**Comment by afkvido** [comment]
sounds good!

**Comment by 32n** [comment]
> > So... you'll do the controls?
> 
> i'll do the shift keybind to show/hide, but someone else can add a resizer.

no, just don't do that, I can do it with my resize PR.

**Comment by LeoBadeaux** [comment]
> > > So... you'll do the controls?
> > 
> > 
> > i'll do the shift keybind to show/hide, but someone else can add a resizer.
> 
> no, just don't do that, I can do it with my resize PR.

If you want to add it, feel free to make it and create a PR, just make sure you remember to bundle, and I'll merge it once I add the shift hide function just to make sure there are no merge conflicts.
