### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1313]
**Describe your feature request:**

The logo is white as the background is, so maybe make it black

**Comment by ArcerionDev** [comment]
which logo, and which background

**Comment by 32n** [comment]
He means from the README, because he doesn't use Github Dark Mode. Leo made 2 commits that changed the logo.

**Comment by afkvido** [comment]
> **Describe your feature request:**
> 
> The logo is white as the background is, so maybe make it black

UR USING LITE MODE?

**Comment by afkvido** [comment]
cmon man

**Comment by LeoBadeaux** [comment]
I'll fix this

**Comment by afkvido** [comment]
thank you!

**Comment by donaldli2020** [comment]
> > **Describe your feature request:**
> > The logo is white as the background is, so maybe make it black
> 
> UR USING LITE MODE?

i changed to dark

**Comment by afkvido** [comment]
;)
