### ISSUE TITLE
[Feature/Needs Approval] Menu to choose hack which menu to use

### ISSUE THREAD

**Issue by LeoBadeaux** [Prodigy-Hacking/ProdigyMathGameHacking#1317]
When I release Léo's Cheat Menu, I want to give users the option to choose between using Will's Cheat Menu and Léo's Cheat Menu. Once somebody makes their choice, it will be saved in localStorage and their chosen cheat menu will load. In both of these menus, there will be a button to switch to the other menu.

I can program this myself, I just want approval to make this change once I feel Léo's Cheat Menu has enough features to be used as a primary cheat menu.

**Comment by LeoBadeaux** [comment]
Perhaps, in the future, Will's cheat menu could be phased out and replaced with Léo's Cheat Menu?

**Comment by afkvido** [comment]
> Perhaps, in the future, Will's cheat menu could be phased out and replaced with Léo's Cheat Menu?

NO NO NO

**Comment by afkvido** [comment]
Make it select every time

**Comment by LeoBadeaux** [comment]
> > Perhaps, in the future, Will's cheat menu could be phased out and replaced with Léo's Cheat Menu?
> 
> NO NO NO

What's with your fanboying of Will's cheat menu? It's old and it's getting harder to maintain. If we switch to only maintaining Léo's Cheat Menu, we could save a lot of time coding along with the great UI enhancements the menu offers. If we did this, we could have a button to switch to Will's Cheat Menu, but we could make a note that it isn't maintained anymore.

**Comment by PatheticMustan** [comment]
> When I release Léo's Cheat Menu, I want to give users the option to choose between using Will's Cheat Menu and Léo's Cheat Menu. 

If you do make a viable alternative, it would need to be moved under the ProdigyHacking org so that other maintainers can also modify it.
Currently WCM is partially included in P-NP, but it would be simple to move it to PHEx instead.

> Once somebody makes their choice, it will be saved in localStorage and their chosen cheat menu will load. In both of these menus, there will be a button to switch to the other menu.

Like with the "custom p-np" URL, it should be simple to add a "custom cheat menu" field. One danger that comes with this is that it would be trivial to trick other people into running malicious menus, so maybe a whitelist of supported cheat menus would be better.

**Comment by PatheticMustan** [comment]
> Perhaps, in the future, Will's cheat menu could be phased out and replaced with Léo's Cheat Menu?

we'll see ;)

**Comment by afkvido** [comment]
> One danger that comes with this is that it would be trivial to trick other people into running malicious menus, so maybe a whitelist of supported cheat menus would be better.

damn

**Comment by LeoBadeaux** [comment]
> > When I release Léo's Cheat Menu, I want to give users the option to choose between using Will's Cheat Menu and Léo's Cheat Menu.
> 
> If you do make a viable alternative, it would need to be moved under the ProdigyHacking org so that other maintainers can also modify it. Currently WCM is partially included in P-NP, but it would be simple to move it to PHEx instead.
I'll move it to this repository soon, additionally, I have noticed there is a cheat menu URL field in P-NP, I'll change that to the cheat picker URL.
> 
> > Once somebody makes their choice, it will be saved in localStorage and their chosen cheat menu will load. In both of these menus, there will be a button to switch to the other menu.
> 
> Like with the "custom p-np" URL, it should be simple to add a "custom cheat menu" field. One danger that comes with this is that it would be trivial to trick other people into running malicious menus, so maybe a whitelist of supported cheat menus would be better.
If we are going to have custom cheat menu be a whitelist system, why not just add those approved cheat menus as options themselves.

**Comment by PatheticMustan** [comment]
Ah, before doing anything, please do it on a separate branch, and submit a PR. I'd like to review anything before anything is submitted.

> If we are going to have custom cheat menu be a whitelist system, why not just add those approved cheat menus as options themselves.

I'm not sure I understand what you mean. I'm thinking of a drop down of a list of the different cheat menus..?

**Comment by afkvido** [comment]
then we could just whitelist WCM and LCM

**Comment by afkvido** [comment]
> I'm not sure I understand what you mean. I'm thinking of a drop down of a list of the different cheat menus..?

No..... LCM isn't a dropdown + transparent overlay like WCM
LCM is on the side

**Comment by PatheticMustan** [comment]
cc @ArcerionDev, what do you think?

> > I'm not sure I understand what you mean. I'm thinking of a drop down of a list of the different cheat menus..?
> 
> No..... LCM isn't a dropdown + transparent overlay like WCM LCM is on the side

that's not what I meant..? In the options page, alongside the text field "custom pnp url" would be a drop down allowing you to select from a whitelist of cheat menus. Is that what you meant?

**Comment by LeoBadeaux** [comment]
> Ah, before doing anything, please do it on a separate branch, and submit a PR. I'd like to review anything before anything is submitted.
> 

My current cheat menu is LCM in the organization.
> > If we are going to have custom cheat menu be a whitelist system, why not just add those approved cheat menus as options themselves.
> 
> I'm not sure I understand what you mean. I'm thinking of a drop down of a list of the different cheat menus..?

Pretty much just a cheat menu picker, and a requirement for each cheat menu is it must have a button to go back to the picker to load a different cheat menu.

**Comment by LeoBadeaux** [comment]
> cc @ArcerionDev, what do you think?
> 
> > > I'm not sure I understand what you mean. I'm thinking of a drop down of a list of the different cheat menus..?
> > 
> > 
> > No..... LCM isn't a dropdown + transparent overlay like WCM LCM is on the side
> 
> that's not what I meant..? In the options page, alongside the text field "custom pnp url" would be a drop down allowing you to select from a whitelist of cheat menus.

It would be easier for the dropdown to be within the prodigy game page instead. Rather than PNP being configured to load wills cheat menu, we configure it to load a cheat menu picker

**Comment by PatheticMustan** [comment]
I would be against loading a cheat menu picker in-game, I think it would be too confusing for players who barely even know how to open one menu. It's also unnecessary..??

**Comment by LeoBadeaux** [comment]
> I would be against loading a cheat menu picker in-game, I think it would be too confusing for players who barely even know how to open one menu. It's also unnecessary..??

What do you mean unnecessary, do you want to have an option to use other menus or not?

**Comment by afkvido** [comment]
Then.. maybe we should have an option to switch to WCM in the developer options in the extension

**Comment by afkvido** [comment]
@LeoBadeaux ^^^^

**Comment by PatheticMustan** [comment]
> What do you mean unnecessary, do you want to have an option to use other menus or not?

what.

> It would be easier for the dropdown to be within the prodigy game page instead. Rather than PNP being configured to load wills cheat menu, we configure it to load a cheat menu picker

I'm just against injecting it in-game. I'm not sure why you're against just putting it in the PHEx options menu?

**Comment by LeoBadeaux** [comment]
> > What do you mean unnecessary, do you want to have an option to use other menus or not?
> 
> what.
> 
> > It would be easier for the dropdown to be within the prodigy game page instead. Rather than PNP being configured to load wills cheat menu, we configure it to load a cheat menu picker
> 
> I'm just against injecting it in-game. I'm not sure why you're against just putting it in the PHEx options menu?

Most people never look at the PHEx options menu, so there would be a higher chance of people using my panel if they are directly asked. If we were to have the options be in the PHEx options menu, we would have to have a default menu set.

**Comment by afkvido** [comment]
I'd say that LCM should be primary, but people could use WCM if they know what they're doing and they need it.

**Comment by afkvido** [comment]
if they know what they're doing INCUDES navigating through the new and improved PHEX popup

**Comment by ArcerionDev** [comment]
> > > Perhaps, in the future, Will's cheat menu could be phased out and replaced with Léo's Cheat Menu?
> > 
> > 
> > NO NO NO
> 
> What's with your fanboying of Will's cheat menu? It's old and it's getting harder to maintain. If we switch to only maintaining Léo's Cheat Menu, we could save a lot of time coding along with the great UI enhancements the menu offers. If we did this, we could have a button to switch to Will's Cheat Menu, but we could make a note that it isn't maintained anymore.

it's not hard to maintain at all, my only issue with it is how many buttons there are on the screen, dropdowns would probably be good.

To answer your question, I think we should probably do one or the other.

also, I'm not quite sure why you're making a new one from scratch, you could probably overhaul wcm and change the visual design with much less effort.

Also I don't know what the obsession is with branding the cheat menus with the name of the original creator. cus ok, will's cheat menu is all well and good but will hasn't worked on it since fall of 2020

I think if it's maintained by the community, it should be branded as such, but this isn't the largest relevancy.

Also, adding a menu picker is a bad idea in my opinion, as i said before, because it's just another thing to confuse our increasingly unintelligent userbase.

All in all, before we decide if your cheat menu will be used as a primary menu, you should probably finish it first, then we'll pick this back up.

**Comment by LeoBadeaux** [comment]
> Also, adding a menu picker is a bad idea in my opinion, as i said before, because it's just another thing to confuse our increasingly unintelligent userbase.

Speaking of, we have a lot of users that are under 13. If they run into problems, they can't *legally* use Discord, and we don't provide support on Github either. There is no current legal way for them to get support for the hacks.

**Comment by LeoBadeaux** [comment]
Closed to be discussed once the menu is finished.

**Comment by ArcerionDev** [comment]
> > Also, adding a menu picker is a bad idea in my opinion, as i said before, because it's just another thing to confuse our increasingly unintelligent userbase.
> 
> Speaking of, we have a lot of users that are under 13. If they run into problems, they can't _legally_ use Discord, and we don't provide support on Github either. There is no current legal way for them to get support for the hacks.

they can't legally but action can't be taken against them unless it is proven

**Comment by PatheticMustan** [comment]
> Most people never look at the PHEx options menu, so there would be a higher chance of people using my panel if they are directly asked. If we were to have the options be in the PHEx options menu, we would have to have a default menu set.

you literally have nothing, why are you pushing so hard to replace WCM already??? can't you just wait until you have a basic implementation at least

**Comment by afkvido** [comment]
Name the menu `Hacks`

**Comment by LeoBadeaux** [comment]
> > Most people never look at the PHEx options menu, so there would be a higher chance of people using my panel if they are directly asked. If we were to have the options be in the PHEx options menu, we would have to have a default menu set.
> 
> you literally have nothing, why are you pushing so hard to replace WCM already??? can't you just wait until you have a basic implementation at least

I'm not pushing so hard to replace WCM already. I'm just saying if my panel gets good enough in the future that is a possibility.

**Comment by 32n** [comment]
Don't associate your panel to this repo then... you don't have say over major changes to the core functionality of PMGH. In fact, nobody does, 'tis a democratic process among the co-owners.

**Comment by LeoBadeaux** [comment]
> Don't associate your panel to this repo then... you don't have say over major changes to the core functionality of PMGH. In fact, nobody does, 'tis a democratic process among the co-owners.

I do not, never have I said that I do. That's kind of the whole "Feature/Needs Approval" thing

**Comment by 32n** [comment]
You made a README commit listing your cheat menu as one of the options to use along with the PMGH extension. Is that not association to you? This is on top of the fact that it's not even close to done. You still have to steal WCM's hacks and paste them on your menu under you name.

**Comment by PatheticMustan** [comment]
> I do not, never have I said that I do.

uh

> Perhaps, in the future, Will's cheat menu could be phased out and replaced with Léo's Cheat Menu?

> What's with your fanboying of Will's cheat menu? It's old and it's getting harder to maintain. If we switch to only maintaining Léo's Cheat Menu, we could save a lot of time coding along with the great UI enhancements the menu offers.

> Most people never look at the PHEx options menu, so there would be a higher chance of people using my panel if they are directly asked.

**Comment by LeoBadeaux** [comment]
> You made a README commit listing your cheat menu as one of the options to use along with the PMGH extension.

I planned to add the other cheat menus that have been created throughout the years, I was working on finding all of them and seeing if they don't work.

> This is on top of the fact that it's not even close to done. 

While I realize now I probably shouldn't have added it, I put a notice saying it's in ultra alpha.

> You still have to steal WCM's hacks and paste them on your menu under you name.

I'm not exactly going to just be copying and pasting from WCM. I planned to see which hacks still work, as I know for a fact some of them don't work at all and haven't been removed from the menu. Afterwards, I would design the UI components for each type, and make them reactive towards whichever object variable is being changed. If anything, the only thing similar would be the object variables being changed, but that's a given because things that provide the same function would obviously be modifying the same object.

**Comment by LeoBadeaux** [comment]
Do you or do you guys not want me to make my cheat panel? I'm fine with just not doing it and not contributing to PMGH at all if you want that, your choice.

**Comment by PatheticMustan** [comment]
I think it would be great if you made a cheat menu, but you're inserting it a little too quickly... I just think advertising it when it's not yet ready would be a bit hasty. There have been many rewrites attempted (meow menu, oldguard, rus's menu arcerion's rewrite), but none of them are actually finished.

**Comment by LeoBadeaux** [comment]
Unassigned because I am not wanted here. This issue will not be reopened.

**Comment by 32n** [comment]
> Do you or do you guys not want me to make my cheat panel? I'm fine with just not doing it and not contributing to PMGH at all if you want that, your choice.

bruh classic false dilemma fallacy. if you're going to be so childish that you'll refuse to contribute to PMGH unless your cheat menu is embraced by us, good riddance honestly.

**Comment by PatheticMustan** [comment]
> Unassigned because I am not wanted here. This issue will not be reopened.

?????????? ok

**Comment by LeoBadeaux** [comment]
It's more of I don't feel useful here, that my contributions aren't needed. I am not needed here, since it seems like you all are content with the way things already are.

**Comment by PatheticMustan** [comment]
all i said was "maybe you shouldn't try pushing your cheat menu when it's not even done yet", and "I'm against an in-game menu picker". Of course we always welcome new things, but only after it's properly reviewed by other developers. Like putting your cheat menu in the README was just a tiny tiny bit strange when it's not usable yet, idk

**Comment by 32n** [comment]
> It's more of I don't feel useful here, that my contributions aren't needed. I am not needed here, since it seems like you all are content with the way things already are. I am not needed here, or anywhere.

It's common knowledge that on any project of any decent size, you shouldn't be trying to make your own opinionated major changes that affect how the project works in a fundamental way. Of course the maintainers are going to disapprove of that.
