### ISSUE TITLE
[BUG] shift show/hide not working

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1319]
***Description***:

***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
try clearing your cache and reloading, it works fine on my end

**Comment by donaldli2020** [comment]
still not working

**Comment by donaldli2020** [comment]
Working!

**Comment by Ruito1** [comment]
How do you get crystals in a prodigy game?

**Comment by PatheticMustan** [comment]
iirc finishing all the world's quests
