### ISSUE TITLE
[BUG] Location => Player?

### ISSUE THREAD

**Issue by donaldli2020** [Prodigy-Hacking/ProdigyMathGameHacking#1325]
***Description***:
The location hack "Get Map Location" apparentlygot to the Player section

***Replication***:

***Images***:

***Additional Errors***:

**Comment by afkvido** [comment]
Screenshot?

**Comment by donaldli2020** [comment]
just load the hacks

**Comment by 32n** [comment]
A result of you not testing your code at all before pushing it, a very irresponsible thing to do. The maintainers of the repo used to trust that you've double checked and tested your code for mistakes before making a pull request.
