### ISSUE TITLE
? idk what happened

### ISSUE THREAD

**Issue by ReScratcher** [Prodigy-Hacking/ProdigyMathGameHacking#1328]
***Description***:
HACKS WORK ON MY OLD ACCOUNT (i used pixi)
And for some reason I have legimate real membership (I DIDNT PAY)

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/99366697/153683756-b95f2798-1b6d-4ea6-b57a-bed50e4c7003.png)

***Additional Errors***:

**Comment by ReScratcher** [comment]
![image](https://user-images.githubusercontent.com/99366697/153683906-6a95eccc-ae47-476a-82fe-43ab654b5acd.png)

**Comment by 1603191909** [comment]
thats not an issue, please do this in the disscussions and close this
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/discussions/new
