### ISSUE TITLE
cant battle

### ISSUE THREAD

**Issue by besthackerever** [Prodigy-Hacking/ProdigyMathGameHacking#152]
when i try to battle it either crashes or wont let me

**Comment by PatheticMustan** [comment]
Please provide screenshots of your issue, and be more specific.

**Comment by besthackerever** [comment]
heres me going into a monster battle it frezzes and wont unfreeze untill i log out

**Comment by besthackerever** [comment]
https://drive.google.com/open?id=1I398mFOBLJ1TxhGIiIZWF2-FfItEOvbj

**Comment by besthackerever** [comment]
also i cant battle titan

https://drive.google.com/file/d/12akps5ZHGhsHFsZHEu5UOD5wA0weqlZo/view

**Comment by Exoticc** [comment]
We do not take responsibility for any broken/bugged accounts.
