### ISSUE TITLE
how do you add hacks to redirector??

### ISSUE THREAD

**Issue by wertyu2053** [Prodigy-Hacking/ProdigyMathGameHacking#153]
I have no idea how to add other hacks like account stacker to redirector. if you could tell me how to do that, that would be amazing!!! thanks so much for the membership.

**Comment by TNThacker2015** [comment]
check the hacks folder

**Comment by wertyu2053** [comment]
i meant how do you add them to redirector. do u use bookmarklet? or do u
use modules?

**Comment by wertyu2053** [comment]
can u like walk me through the process of how to add hacks to redirector?
if so , that would be great.
thanks. i checked the hacks folder, but i dont know how to add them to
redirector

**Comment by PatheticMustan** [comment]
REDIRECTOR IS USED TO MODIFY THE GAME FILES.
You don't "add" hacks to the redirector. After you get the modified game files, you can open console, and put the hacks in there.
