### ISSUE TITLE
Update SkipTutorial.js

### ISSUE THREAD

**Issue by FelixN0324** [Prodigy-Hacking/ProdigyMathGameHacking#155]
hack.functions.completeTutorial();

**Comment by Diveodile** [comment]
Umm... what?

**Comment by Exoticc** [comment]
@FelixN0324 next time you discover a new hack dont make an issue, just say your discovery here! https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/issues/25

**Comment by Exoticc** [comment]
> @FelixN0324 next time you discover a new hack just comment the hack you discovered here: #25

**Comment by PatheticMustan** [comment]
@FelixN0324, you can just join the discord, and say what you find there. We can discuss it more in depth there!
