### ISSUE TITLE
Gets all pets hack is bugged 

### ISSUE THREAD

**Issue by Blazefire1236** [Prodigy-Hacking/ProdigyMathGameHacking#156]
I am not hundred percent certain why crashes the game but it could be that most pets have shadow blast

**Comment by Exoticc** [comment]
@Blazefire1236 The get all pets hack lags the game a lot and it freezes your game. Simply just go to a new tab and open up prodigy again.

**Comment by ktad2721** [comment]
Most of the pets added via GetAllPets.js are freezing/hanging the game when you initiate a battle. I have found a few of the pets added don't cause this freeze problem. Which pets that cause the freeze/hang is not consistent with each account that has run GetAllPets.js.
