### ISSUE TITLE
Using pets made with getAllPets freezes all battles.

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#160]
***Description***:
~~If you use an epic in your fight team, the game freezes before the battle screen opens.~~
If you use getAllPets, using any of the pets in your team will crash all battles.

***Replication***:
1) Redirector hack
2) hack.functions.getAllPets()
3) Place an epic in your team
4) Battle with a monster.

***Images***:
![image](https://user-images.githubusercontent.com/35382971/79939315-ce224000-842c-11ea-8e7a-b646fc8a3c91.png)

***Additional Errors***:
![image](https://user-images.githubusercontent.com/35382971/79939149-5ce28d00-842c-11ea-9cc3-93114129b22f.png)

**Comment by PatheticMustan** [comment]
ALL pets, not just epics.

**Comment by scvdss** [comment]
Hey can u help me how to use the PIXI hacks

**Comment by divinelemon** [comment]
> Hey can u help me how to use the PIXI hacks

Prodigy updated this, follow the instructions.

**Comment by divinelemon** [comment]
> _**Description**_:
> ~If you use an epic in your fight team, the game freezes before the battle screen opens.~
> If you use getAllPets, using any of the pets in your team will crash all battles.
> 
> _**Replication**_:
> 
> 1. Redirector hack
> 2. hack.functions.getAllPets()
> 3. Place an epic in your team
> 4. Battle with a monster.
> 
> _**Images**_:
> ![image](https://user-images.githubusercontent.com/35382971/79939315-ce224000-842c-11ea-8e7a-b646fc8a3c91.png)
> 
> _**Additional Errors**_:
> ![image](https://user-images.githubusercontent.com/35382971/79939149-5ce28d00-842c-11ea-9cc3-93114129b22f.png)

However, using Will's Cheat Menu to get all pets does NOT freeze.

**Comment by Blazefire1236** [comment]
Make the pets spawn at level one that might fix it

**Comment by Blazefire1236** [comment]
That would ensure that they would spawn with their default move set

**Comment by PatheticMustan** [comment]
hmm, ok

**Comment by PatheticMustan** [comment]
Confirmed, replacing magmischief's foreign spells with peeko's foreign spells fixes the problems

![image](https://user-images.githubusercontent.com/35382971/80288298-17141600-8705-11ea-86f3-a75760181c3c.png)

**Comment by PatheticMustan** [comment]
Solution, each pet has method `.assignRandomSpells()`, which we can use to assign random valid attacks.
Yay!

**Comment by Himeanoob** [comment]
How

**Comment by PatheticMustan** [comment]
To fix your current pet team:
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/hacks/Misc/FixPetTeam.js

**Comment by NotInterested11** [comment]
so if I use the add pet option, will it crash?
because I don't want pets if I cant battle with them

**Comment by PatheticMustan** [comment]
@NotInterested11 please don't comment on closed issues.
This issue was fixed in April. You can use getAllPets just fine.

**Comment by vertexxongithub** [comment]
Using Wills Cheat Menu I tried all hacks then went to a battle and it froze before it even started I'm guessing it's all pets hack doing that but idk how to fix it I also does this on all my other devices.

**Comment by vertexxongithub** [comment]
It's still happening

**Comment by vertexxongithub** [comment]
Am I on a wrong version or smth?

**Comment by PatheticMustan** [comment]
Use the pet hacks first, then "Fix Pet Team"

If that still doesn't work, screenshot errors in console and send it to us

**Comment by vertexxongithub** [comment]
Ok

**Comment by poIarbear** [comment]
feel like im getting pounded in the ass

>

**Comment by PatheticMustan** [comment]
inappropriate
