### ISSUE TITLE
Bug: FixPetTeam error

### ISSUE THREAD

**Issue by FelixN0324** [Prodigy-Hacking/ProdigyMathGameHacking#167]
***Description***:
The FixPetTeam.js isn't working.

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/63550317/80527372-44a9cb00-8962-11ea-82e8-f70475b87eed.png)

***Additional Errors***:

**Comment by TNThacker2015** [comment]
I know why it's doing this.

**Comment by Prodigymathgame** [comment]
Please hack my account with all pets.
Username is elipollardatspedhead.com@gmail.com
Password is ineedhacks

**Comment by PatheticMustan** [comment]
Make sure when you execute the hack that you're not in the loading screen.
You have to actually be in a world.

**Comment by Prodigymathgame** [comment]
Can you do it for me please??

**Comment by FelixN0324** [comment]
I'm not in the loading screen when I did this.

**Comment by JamesD11738** [comment]
and i need all epics too i will tell you my account later ok

**Comment by Prodigymathgame** [comment]
Do the same for me please. All pets and epics. Username is
elipollardatspedhead.com@gmail.com
Password is ineedhacks

**Comment by FelixN0324** [comment]
Also, I fixed the bug when you get into the kennel. For me, it exits me out by saying: "You have been inactive for too long! Log in again." (Use the hack to get into the kennel, but it doesn't fix the whole get all pets bug.
hack.constants.constants["GameConstants.Battle.MAX_NUM_PETS"]=Infinity

**Comment by Prodigymathgame** [comment]
Can you still do it for me please?

**Comment by FelixN0324** [comment]
And to speed up the battle process, use this:
hack.constants.constants["GameConstants.Battle.AUTO_ATTACK_ENABLED"]=true
and turn on the button. (Is this part of a hack?...)

**Comment by Prodigymathgame** [comment]
Can you still hack my account please?

**Comment by Prodigymathgame** [comment]
Thank you for hacking my acciunt. Please is there a way to alow me into
battles, as it just freezes
Username is elipollardatspedhead.com@gmail.com
Password is ineedhacks

Thank you

**Comment by Kayla162** [comment]
> And to speed up the battle process, use this:
> hack.constants.constants["GameConstants.Battle.AUTO_ATTACK_ENABLED"]=true
> and turn on the button. (Is this part of a hack?...)

Hello Felix can u hack my account for me?

**Comment by Kayla162** [comment]
Or can someone hack my account for me plz?

**Comment by ktad2721** [comment]
One additional find is that not only does GetAllPets cause hangs but so does bounty hacks. Bounty hacks is now causing the Bounty Board to be empty as well as hang when you try to access it. Seems like this might be yet another way Prodigy is preventing hacks.

**Comment by Imahacker39** [comment]
Description:
The FixPetTeam.js isn't working.

Replication:

Images:
image

Additional Errors:

**Comment by Avn1114** [comment]
I doubt it. These are normally just errors in the debug functions, if Prodigy wanted to prevent them, they would just get rid of them. Sent from Mail for Windows 69 From: ktad2721Sent: Thursday, April 30, 2020 3:08 PMTo: Prodigy-Hacking/ProdigyMathGameHackingCc: SubscribedSubject: Re: [Prodigy-Hacking/ProdigyMathGameHacking] Bug: FixPetTeam error (#167) One additional find is that not only does GetAllPets cause hangs but so does bounty hacks. Bounty hacks is now causing the Bounty Board to be empty as well as hang when you try to access it. Seems like this might be yet another way Prodigy is preventing hacks.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avg.com

**Comment by ktad2721** [comment]
Should I start a new thread for the crash/hang behavior related to Bounties?

**Comment by TNThacker2015** [comment]
solved.

**Comment by Prodigymathgame** [comment]
Please hack my account with membership
Username is elipollardatspedhead.com@gmail.com
Password is rocky

**Comment by PatheticMustan** [comment]
#170
