### ISSUE TITLE
Fix commenting

### ISSUE THREAD

**Issue by TNThacker2015** [Prodigy-Hacking/ProdigyMathGameHacking#168]
We need to change all the hacks to have a consistent title/description comment.
```js
//> Title Here (ex: Gold Hack)
//>> A description, preferably descriptive.
```

**Comment by TNThacker2015** [comment]
do this

**Comment by PatheticMustan** [comment]
ok

**Comment by DaChickenKing** [comment]
i did this

**Comment by DaChickenKing** [comment]
Could someone add proper labels to this, and close it, now that it's done? (reporting my comment to make someone read this)
