### ISSUE TITLE
Keep the folder and filenames camelCase!

### ISSUE THREAD

**Issue by TNThacker2015** [Prodigy-Hacking/ProdigyMathGameHacking#169]
I'm seeing PascalCase too much in hacks. Make sure the first letter is lowercase

**Comment by Kayla162** [comment]
Hello TNT I wanted to know if u could hack my account?

**Comment by TNThacker2015** [comment]
OK FUCK THIS NO ONE IS FORMATTING THEIR FILES RIGHT

**Comment by TNThacker2015** [comment]
PASCAL CASE IS FOR FOLDERS

**Comment by TNThacker2015** [comment]
CAMEL CASE IS FOR FILES

**Comment by TNThacker2015** [comment]
IM NOT HAVING ANY OF THAT "SPACE" FORMATTING GET THE SPACES OUT WE ARE NOT IN SPACE WE ARE ON EARTH SO GET THE SPACES OUT AND START USING PROPER CASING

**Comment by ArcerionDev** [comment]
already done

**Comment by PatheticMustan** [comment]
![image](https://user-images.githubusercontent.com/35382971/94578559-e2713100-0245-11eb-95d6-d583e2d6d741.png)
???

**Comment by PatheticMustan** [comment]
this will break a few links

**Comment by marchenryisidore** [comment]
bro

**Comment by marchenryisidore** [comment]
it hard i what to become a membemer so im new

**Comment by PatheticMustan** [comment]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/Redirect-Hack

**Comment by JonathanA8883** [comment]
hack member for me like give me member forever

**Comment by JonathanA8883** [comment]
in prodigy
