### ISSUE TITLE
Our stance on hacking accounts for others.

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#170]
# We do not, and will not, hack your account for you

The goal of this repository is to host a large amount of hacks, so that Prodigy can fix the bugs, and make itself the best that it can be.

Not only do we not care about your accounts, but we really don't want to spend time hacking some random stranger's account.

We made it as easy as possible to hack, with [very simple instructions], and even a discord server to ask for help, should you get stuck on any part.
Not only is it annoying, and bothers us, but it ***also puts your account in danger of being trolled***.
If you put your credentials online, somebody may reset your account, delete your pets/items, change your name/appearance, give negative infinity gold, give glitched pets so that it's impossible to battle, change your password, or even log into your actual email. (List not exhaustive.)

Please do not share your account.

**Comment by XxelitescriptsxX** [comment]
Nice

**Comment by BoredFishRE** [comment]
Yes. Please stop asking. It's getting very annoying.

**Comment by RtypeX** [comment]
verY tRuE

**Comment by thereturnofdespacitospider** [comment]
EEEEEEEEEEEEEE
E
E
EEEEEEEEEEEEEE
E
E
EEEEEEEEEEEEEE

**Comment by SwxtchCode** [comment]
> EEEEEEEEEEEEEE
> E
> E
> EEEEEEEEEEEEEE
> E
> E
> EEEEEEEEEEEEEE

@PatheticMustan can you delete the spam reply cause im on mobile and cant find the report to repo admins button

**Comment by UntrustableRus** [comment]
Going to close this so that it won't count as an actual issue (since it's just meta). You may still reply to this issue.

**Comment by PatheticMustan** [comment]
misclick :|
