### ISSUE TITLE
Bug: setBountyScore.js resulted in Bounty Board freezing when being accessed

### ISSUE THREAD

**Issue by ktad2721** [Prodigy-Hacking/ProdigyMathGameHacking#173]
***Description***: Bounty hack setBountyScore.js results in game freeze when accessing the Bounty Board

***Replication***: Not easily replicated. In my case I used getAllPets.js that causes the freeze on battles but do not have any of the pets acquired by the script in my team at this time. I then used Redirector to run setBountyScore.js and set to any value. Then went into LampLight Town and clicked on the bounty board.

***Images***:
![bounty freeze 1](https://user-images.githubusercontent.com/64032153/80831507-f8a49380-8bb8-11ea-86e6-bfa5e9fc67c4.PNG)

![bounty freeze 2](https://user-images.githubusercontent.com/64032153/80831525-ff330b00-8bb8-11ea-8d34-7a49f9f30e2f.PNG)

![bounty freeze 3](https://user-images.githubusercontent.com/64032153/80831539-035f2880-8bb9-11ea-862d-fd2e557b8b3a.PNG)

***Additional Errors***: Results in ERR_CONNECTION_CLOSED after Cannot Read property 'monsters' of load-identity.min.js:1

**Comment by chungus-tech** [comment]
HI










K













K
































K




























K























K




















G

**Comment by chungus-tech** [comment]
JJ










;
















;


















































































































P















































































O
