### ISSUE TITLE
chat hack

### ISSUE THREAD

**Issue by chungus-tech** [Prodigy-Hacking/ProdigyMathGameHacking#174]
chat hack you get to say what ever you want

**Comment by KryptoCrash** [comment]
Not an issue.

**Comment by Prodigymathgame** [comment]
Can you hack my account with membership please
Username is elipollardatspedhead.com@gmail.com
Password is rocky

**Comment by PatheticMustan** [comment]
#170 please don't post your account ever again

**Comment by Prodigymathgame** [comment]
How come?
