### ISSUE TITLE
[BUG] [and a hack req]

### ISSUE THREAD

**Issue by Nova-Legendshadow** [Prodigy-Hacking/ProdigyMathGameHacking#179]
every time i go to console to hack prodigy it sends me to a 404 page not found page.  On my other computer when i go to console it crashes prodigy.          

hack request: make it so i can change my First name, not my last.  I want to change my name to nova but its a girl name so i cant get it withought being a girl in prodigy

**Comment by Prodigymathgame** [comment]
Have you installed redirector. It did the same to me, until i installed
redirector. If it isnt working email me at natsudragoneeljim, and tell me
what you need me to do, with ur username and password, and ill do it for
you, if you want

**Comment by Prodigymathgame** [comment]
The email is natsudragoneeljim@gmail.com

**Comment by Nova-Legendshadow** [comment]
I dont wanna give you my password and second yes i have installed redirector.  its still not working tho :(

**Comment by Prodigymathgame** [comment]
Have you imported the files you need to for it to work?

**Comment by TNThacker2015** [comment]
Read the instructions

**Comment by Nova-Legendshadow** [comment]
thanks it worked :D
