### ISSUE TITLE
[BUG] ChatManager.rt is undefined:

### ISSUE THREAD

**Issue by FelixN0324** [Prodigy-Hacking/ProdigyMathGameHacking#180]
***Description***:
The Chat Hack doesn't work anymore.

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/63550317/81502573-c8da4780-92ac-11ea-9467-087e46e86291.png)

***Additional Errors***:

**Comment by PatheticMustan** [comment]
ChatManager.rt has been renamed to ChatManager.Y, thank you for bringing this to our attention.
