### ISSUE TITLE
teleport

### ISSUE THREAD

**Issue by uuuuuuuu88** [Prodigy-Hacking/ProdigyMathGameHacking#215]
hi can you make the teleport hack. not sure if it is avalible

**Comment by nonumbershere** [comment]
it kinda is ut its glitchy

**Comment by nonumbershere** [comment]
theres one but it dosent work so good

**Comment by uuuuuuuu88** [comment]
were is it

**Comment by TNThacker2015** [comment]
Use the cheat menu, or check the hacks folder.

**Comment by nonumbershere** [comment]
what
