### ISSUE TITLE
redirector

### ISSUE THREAD

**Issue by uuuuuuuu88** [Prodigy-Hacking/ProdigyMathGameHacking#223]
Ok so i do not think the redirector to open element page is notworking

**Comment by RtypeX** [comment]
Yep, the redirector doesn't work anymore.

**Comment by Avn1114** [comment]
Run this as a bookmarklet to fix: `javascript:console = []`

**Comment by Avn1114** [comment]
Or go to https://prodigy-cheat-dashboard.herokuapp.com/download , because we unpatched it.

**Comment by Avn1114** [comment]
so there's a new redirect script

**Comment by PatheticMustan** [comment]
Fix: delete everything in redirector, and follow the instructions again.

You can download the new redirector json at https://prodigy-cheat-dashboard.herokuapp.com/download
