### ISSUE TITLE
[BUG] Prodigy Hack Scripts Broken - Prodigy may have removed .player option

### ISSUE THREAD

**Issue by ktad2721** [Prodigy-Hacking/ProdigyMathGameHacking#229]
***Description***:
All scripts with hack.instance.prodigy.player.* are failing. This occurs despite deleting all Redirects and then new import into Redirector.

***Replication***:
Go to any world and CRL+Shift+I then paste scripts from the itemStacker.js

***Images***:
![Stacker script fail](https://user-images.githubusercontent.com/64032153/82495477-25154680-9ab9-11ea-92aa-967cddd5e6f3.PNG)

![Set Player Level fail](https://user-images.githubusercontent.com/64032153/82495494-2c3c5480-9ab9-11ea-9fc8-b6823802e89c.PNG)

![FixPets fail](https://user-images.githubusercontent.com/64032153/82495514-32323580-9ab9-11ea-8229-cac26865c420.PNG)

***Additional Errors***:
VM85941:8 Uncaught TypeError: Cannot read property 'backpack' of undefined
    at <anonymous>:8:50
    at <anonymous>:41:3

**Comment by PatheticMustan** [comment]
For now, you can get around this by using `hack.player`.
The hack menu is also being updated. Thanks for reporting this!

(btw if you have a discord account, you can get the cool bughunter role)

**Comment by ktad2721** [comment]
> For now, you can get around this by using `hack.player`.
> The hack menu is also being updated. Thanks for reporting this!
> 
> (btw if you have a discord account, you can get the cool bughunter role)

FYI...the following code in the accountStaker.js breaks bounties in Prodigy:
	Object.entries(player.backpack.data).forEach(([x, y]) =>
		// @ts-ignore
		y.splice(0, 1e69, ...gameData[x].map(z => ({ ID: z.ID, N: 1e69 })))
	);

If you run this then you can no longer find bounties and the bounty board will no longer update.

**Comment by PatheticMustan** [comment]
Hmm, a fix would be to manually remove the bounty items....

**Comment by PatheticMustan** [comment]
Bounty Items are ID 84, 85, and 86.

**Comment by PatheticMustan** [comment]
Try using [itemStacker.js](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/hacks/Stacker/itemStacker.js) instead. It'll give you all the items properly, then remove the bounty items.
