### ISSUE TITLE
redirector not working

### ISSUE THREAD

**Issue by uuuuuuuu88** [Prodigy-Hacking/ProdigyMathGameHacking#235]

**Comment by FelixN0324** [comment]
True. Prodigy patched the Redirector game files.

**Comment by uuuuuuuu88** [comment]
is there any way to hack

**Comment by FelixN0324** [comment]
Yes there is `uuuuuuuu88`
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/archived/HowToHack.md
Use the Bookmarklet.

**Comment by FelixN0324** [comment]
This method works but the detective scripts aren't working. And Prodigy text looks broken.

**Comment by FelixN0324** [comment]
Uh oh. This method works for the "temp1" hacks by using "{Boot}" in the console but the normal hacks are not good.

**Comment by FelixN0324** [comment]
Ok. So the redirector needs to work now. It's almost impossible to hack with only the console debugger. Very hard. The redirector needs to be on from the beginning, but the thing is, it slows down the entrance to Prodigy, leaving no way to get in and hack it.

**Comment by FelixN0324** [comment]
Hopefully, you stored up materials this time. It's going to be a while until we can hack again.

**Comment by FelixN0324** [comment]
By the way, did you post this Bug in the Discord yet?

**Comment by FelixN0324** [comment]
Yeah. I tried on Chrome and Brave. Doesn't work in both?? ☹

**Comment by FelixN0324** [comment]
🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠
----------------------------------------------------------------------------------------------------------------
🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠🦠

**Comment by PatheticMustan** [comment]
@FelixN0324 
> True. Prodigy patched the Redirector game files.

Actually, no. Redirector still works, it's just down until heroku gives us more free hours.

It's fixed 6/1/2020. Please don't spread false information.
