### ISSUE TITLE
[BUG] redirector bug

### ISSUE THREAD

**Issue by UsernameNotAvalible** [Prodigy-Hacking/ProdigyMathGameHacking#246]
***Description***:
The link at https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/Redirect-Hack goes to https://prodigy-cheat-dashboard.herokuapp.com/download
when using that file as the redirector config, i get an "OUTDATED REDIRECTOR CONFIG" message on prodigy. 

***Replication***:
use The link  https://prodigy-cheat-dashboard.herokuapp.com/download link.
when using that file as the redirector config, i get an "OUTDATED REDIRECTOR CONFIG" message on prodigy. 

***Images***:
[Here](https://user-images.githubusercontent.com/63057630/83816776-2c2f7d80-a691-11ea-831c-b8dd048ce587.png
)
***Additional Errors***:
"OUTDATED REDIRECTOR CONFIG"

**Comment by UsernameNotAvalible** [comment]
nevermind, fixed!

**Comment by PatheticMustan** [comment]
New download link is 
https://prodigyhacking.ml/download
