### ISSUE TITLE
Add in-depth instructions to use JavaScript scripts

### ISSUE THREAD

**Issue by DaChickenKing** [Prodigy-Hacking/ProdigyMathGameHacking#274]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like there to be clear, in-depth, and concise instructions for JavaScript codes.

**Describe alternatives you've considered**
N/A; I am submitting this for another user. I do not have issues myself, as I have experience with web programming.

**Additional context**
Submitting for @ProdigyHacking2020

**Comment by TNThacker2015** [comment]
we have typescript typings

**Comment by TNThacker2015** [comment]
they can read that

**Comment by PatheticMustan** [comment]
> we have typescript typings

it's both outdated (PIXI?????), and not very easy for beginners to read.

**Comment by PatheticMustan** [comment]
1) Copy paste the entire script (make sure not to accidentally copy extra bits! Also copy EVERYTHING in the script. I mean everything.)

2) Open Prodigy. If you followed the [redirector instructions](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/Redirect-Hack), you should be able to open console with [Control + Shift + I]

3) On the top bar of the devtools, click on "Console".

4) Paste in the script, and hit enter. Remember, some scripts may need a little tinkering before usage, (Custom currency script has some examples on what to tweak)

5) Profit?
