### ISSUE TITLE
unminify vps redirect files to make them easier to read

### ISSUE THREAD

**Issue by DaChickenKing** [Prodigy-Hacking/ProdigyMathGameHacking#275]
**Is your feature request related to a problem? Please describe.**
the vps redirect files could be unminifed to make them easier to read

**Describe the solution you'd like**
re-read the first thing

**Describe alternatives you've considered**
N/A

**Comment by TNThacker2015** [comment]
its not minified

**Comment by DaChickenKing** [comment]
their minified because prodigy minified them by default i mean

**Comment by TNThacker2015** [comment]
what do you mean? the redirect source code isn't minified

**Comment by DaChickenKing** [comment]
i mean these: https://prodigyhacking.ml/game.min.js
etc

**Comment by TNThacker2015** [comment]
the source code is not stored as a file in any way, shape or form at any point

**Comment by DaChickenKing** [comment]
oh
