### ISSUE TITLE
Prodigy Loading

### ISSUE THREAD

**Issue by WallyWest909** [Prodigy-Hacking/ProdigyMathGameHacking#280]
***Without Redirector***:
Loads in about 17 seconds

***With Redirector**:
Doesn't load

***Problem***:
I can not access prodigy with Redirector on it works with just csp but doesn't allow inspection. When prodigy fixed previous times it worked does anyone know how to fix this?

**Comment by PatheticMustan** [comment]
Can't replicate. I suggest following the instructions in the wiki again.
[Instructions](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/Redirect-Hack).

**Comment by WallyWest909** [comment]
I logged out (of computer) created new account computer account logged in as same prodigy account and it worked (I tried reseting computer earlier didn't work). Thank you!

**Comment by WallyWest909** [comment]
account on*

**Comment by WallyWest909** [comment]
Is there a way I comment on anything else?

**Comment by DaChickenKing** [comment]
Well, you can comment on anything you have knowledge about.

**Comment by DaChickenKing** [comment]
Also, I am going to close this, as it has been resolved.
