### ISSUE TITLE
Player State Saving [HR]

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#283]
**Describe the hack in 5 words or less:**
Save player+inventory to LocalStorage

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

Being able to save the player's state and inventory would allow users to undo hacks, and restore their account to it's initial state. It's also relatively easy to implement.

**Comment by PatheticMustan** [comment]
whatever

**Comment by SwxtchCode** [comment]
`var playerStates = [];`

then save with
```saveState = (state) => {
  playerStates.push(state);
}`

input into `saveState` is `_.player.data`

ik this is pretty basic, i don't have access to my laptop tho so I cant do much

**Comment by PatheticMustan** [comment]
the idea is to load/save into and from localStorage.

We'd also need to get some things outside of _.player.data, but it shouldn't be too hard.

I'll try doing this over the weekend, haha

**Comment by SwxtchCode** [comment]
Hmm ok-

`localStorage.setItem(JSON.Stringify(playerState))`

**Comment by ArcerionDev** [comment]
unfortunately, the only things that are saved globally are things under `_.player`, everything else doesn't work. Also, JSON.stringify isn't necessary, since a lot of the game data is circular. Just do
```js
localStorage.state = _
```
then when we load in the hacked gamemin, do something like
```js
_ = localStorage.state
```
Just a thought.

**Comment by PatheticMustan** [comment]
Arc, that's horrible... you should use `localStorage.setItem`

**Comment by ArcerionDev** [comment]
it doesn't matter tbh

**Comment by ArcerionDev** [comment]
Look, 
```js
localStorage.setItem('owo','uwu')
```
is 33 chars long, 
```js
localStorage.owo = 'uwu'
```
is 24. 



May I ask

**Comment by SwxtchCode** [comment]
Alr, I'm on my Linux machine now (my laptop is still broken).

I'm going to work on this for a bit, gimme some time.

**Comment by SwxtchCode** [comment]
```
saveState = () => {
  playerStateHistory = localStorage.getItem("playerStateHistory") || [];
  
  if(typeof state == "object") {
      playerStateHistory.push(_.player.data);
  } else {
    throw new TypeError(`Invalid state data. Expected object, got ${state}.`);
  }
}
```

We'll need to add something to prevent Prodigy from screwing it up and wiping the player, of course.

**Comment by SwxtchCode** [comment]
Also, this should totally be a part of #318 in my opinion (or is it there and I didn't realize it?), because this will be another WCM thing.

**Comment by ArcerionDev** [comment]
dont wanna be technical but do 
```js
Expected object, got ${typeof state}.
```
Instead of 
```js
Expected object, got ${state}.
```
lmao

**Comment by SwxtchCode** [comment]
Lmao- thanks.

**Comment by SwxtchCode** [comment]
K, so, there might be stuff we don't want to save (temporary values or something), I'll look into that soon.

**Comment by SwxtchCode** [comment]
Another thing:

We'll either have to save this locally in the extension or add some kind of verification hash (explained how to do that in DMs with Arc) to prevent Prodigy from tampering with this.

**Comment by SwxtchCode** [comment]
commenting to remind people to help

**Comment by poIarbear** [comment]
math game hack men on the loose

**Comment by PatheticMustan** [comment]
I promise I'll try doing it today.
While we wait, a list of what to save would be nice.

- Player data
- player backpack
- player name
- kennel
- quest progression

**Comment by poIarbear** [comment]
sounds good, was about to ask what about progression in different islands
but you already mentioned it

**Comment by ArcerionDev** [comment]
[x] Player data
[x] player backpack
[x] player name
[x] kennel
[ ] quest progression

**Comment by ArcerionDev** [comment]
this is what we have done for now

**Comment by ArcerionDev** [comment]
these things all SHOULD save, but sometimes they don't, idk why

**Comment by ArcerionDev** [comment]
anyway, prob better to save locally instead of saving on server

**Comment by SwxtchCode** [comment]
@ArcerionDev yep agreed

**Comment by SwxtchCode** [comment]
> these things all SHOULD save, but sometimes they don't, idk why

The point of this is to store a history of the player state so the user can restore past history.

**Comment by requestx** [comment]
Didn’t i make this ummmmmm.... like a month ago? @PatheticMustan chheck message history with divinelemon

**Comment by ArcerionDev** [comment]
hold up are you @divinelemon @requestx

**Comment by ArcerionDev** [comment]
and it was opened by @PatheticMustan

**Comment by PatheticMustan** [comment]
> Didn’t i make this ummmmmm.... like a month ago? @PatheticMustan chheck message history with divinelemon

it wasn't enough

**Comment by ArcerionDev** [comment]
This has been fixed in [9904c07](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/9904c07ceebf8fd4632f60b370acb03f858c777d).

**Comment by PatheticMustan** [comment]
Arc... I don't think you read the issue

**Comment by PatheticMustan** [comment]
> the idea is to load/save into and from localStorage.
> 
> We'd also need to get some things outside of _.player.data, but it shouldn't be too hard.
> 
> I'll try doing this over the weekend, haha

Pain

**Comment by NX721** [comment]
Lmao

**Comment by ArcerionDev** [comment]
I just implemented this lol
