### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by Harini2009** [Prodigy-Hacking/ProdigyMathGameHacking#284]
The Membership Hack is not working.

**Comment by Avn1114** [comment]
Make sure you have the correct `redirector.json` file. A new one can be found [here](https://prodigyhacking/ml/download).

**Comment by Avn1114** [comment]
@Harini2009

**Comment by Harini2009** [comment]
@Avn1114 Thanks

**Comment by Harini2009** [comment]
@Avn1114 Thanks, but it still doesn't work. It worked before and all the other features are working, but the Membership is the only one that doesn't work. What should I do?

**Comment by Avn1114** [comment]
Alright. In that case, run `hack.player.I = true` to get temporary membership. This will have to be rerun every time you reload.

**Comment by Harini2009** [comment]
@Avn1114 where can I find that? Sorry I am new to this.

**Comment by Avn1114** [comment]
Run it in the Chrome console, accessible by using the keys `Ctrl + Shift+ J`

**Comment by Harini2009** [comment]
@Avn1114 Thanks! It worked!
