### ISSUE TITLE
Fixing Old Hacks [BUG]

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#285]
We really need to fix all of our hacks.
Everything in the cheat menu should work, and have error handling.
Everything in /hack should also work. We'll need to update/remove those too.

**Comment by BoredFishRE** [comment]
We should prob make a private repo for all the broken or experimental hacks so we don't get people complaining about those hacks not working. And then periodically give out those hacks to server boosters.
