### ISSUE TITLE
[HR] Dreambox Hack

### ISSUE THREAD

**Issue by kaddisemu** [Prodigy-Hacking/ProdigyMathGameHacking#286]
**Describe the hack in 5 words or less:**
A hack for dreambox

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

Prodigy may have a problem with cheats but Dreambox also has hacks for it that are sorta easy to find. Please expose these, thank you.

**Comment by Avn1114** [comment]
This is for Prodigy hacking, and nothing else. If you want these hacks, and they are "easy to find", then find them yourself.

**Comment by DaChickenKing** [comment]
Also:
If you want these exposed, then you could do that yourself? We're ProdigyMathGameHacking, not DreamboxHacking.

**Comment by Avn1114** [comment]
@DaChickenKing I like how you say "we" when you aren't in it

**Comment by DaChickenKing** [comment]
yea ik
