### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheExplorerForUhSomething** [Prodigy-Hacking/ProdigyMathGameHacking#290]
***Description***:
hack GUI is not showing

***Replication***:
Have the redirect extension enabled, with the config with the X frame extension. Load prodigy and the hack GUI does not show.

***Images***:

![](https://c00lkidd.is-a.fail/knj4Yd.png)

***Additional Errors***:
Will show its loaded in console. No where to be seen.

**Comment by PatheticMustan** [comment]
Look at the top left corner...

**Comment by TheExplorerForUhSomething** [comment]
Thanks. Im dumb.
