### ISSUE TITLE
[BUG] Noot ate my foreskin. Please help.

### ISSUE THREAD

**Issue by DaChickenKing** [Prodigy-Hacking/ProdigyMathGameHacking#291]
***Description***:
Noot ate my foreskin.

***Replication***:
I mean it.

***Images***:
Really.

***Additional Errors***:
It's true.

**Comment by DaChickenKing** [comment]
sorry lmao

**Comment by BoredFishRE** [comment]
v e r y  n i c e

**Comment by DaChickenKing** [comment]
lmao
