### ISSUE TITLE
Edit Inventory

### ISSUE THREAD

**Issue by KyleTheMan4444** [Prodigy-Hacking/ProdigyMathGameHacking#292]
I feel like you should edit your inventory, as in you can individually get any number of items you want, or you should input the option to delete stuff in your inventory. I feel like that would be an awesome feature if you have too much stuff or get disorganized. Also, with coins like Florans or Shivers, if you have too much of them, you can't actually access some shops, so I feel like the edit/delete inventory option should solve that.

**Comment by DaChickenKing** [comment]
smort

**Comment by KyleTheMan4444** [comment]
Ok

**Comment by KyleTheMan4444** [comment]
OkSent from my T-Mobile 4G LTE Device
-------- Original message --------From: DaChickenKing <notifications@github.com> Date: 9/2/20  8:23 AM  (GMT-07:00) To: Prodigy-Hacking/ProdigyMathGameHacking <ProdigyMathGameHacking@noreply.github.com> Cc: KyleTheMan4444 <kvo54636@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Prodigy-Hacking/ProdigyMathGameHacking] Edit Inventory (#292) 
smort

**Comment by 86109** [comment]
how do you apply the hacks?
________________________________

**Comment by DaChickenKing** [comment]
@86109 It's best to not make random comments. Anyways, see https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/Redirect-Hack

**Comment by KyleTheMan4444** [comment]
will it help me get what i want

**Comment by DaChickenKing** [comment]
@KyleTheMan4444, What I linked to @86109 is the standard Redirector Hack. Your request needs to be handled by the admins, moderators, and collaborators of ProdigyMathGameHacking.

**Comment by KyleTheMan4444** [comment]
how will i know if it gets through

**Comment by DaChickenKing** [comment]
The admins _should_ comment here.

**Comment by DaChickenKing** [comment]
The content of the menu is mostly up to @TNThacker2015 and @PatheticMustan, so I'll ping them, too.

**Comment by YamaHacks** [comment]
Adding an edit inventory that detailed would take a while, not to mention kinda pointless. Its a good idea but prob wont happen as that seems like too much. We are making a new menu tho, so we'll see

**Comment by KyleTheMan4444** [comment]
well the main reason i requested this because i gave myself infinite currency, but i can't access shops that require currencies like florans or hot-hots, and i can't change the currency amount, so i am locked from the shops forever

**Comment by DaChickenKing** [comment]
@KyleTheMan4444 You can use scripts. Which currencies do you want to reset?

**Comment by KyleTheMan4444** [comment]
All of them. Put all of the currencies at reasonable amounts.

**Comment by BoredFishRE** [comment]
should be able to be done in scripts

**Comment by DaChickenKing** [comment]
One second @KyleTheMan4444

**Comment by DaChickenKing** [comment]
Okay, run this:

`hack.player.backpack.currency = [];`

Tell me if that works!

**Comment by BoredFishRE** [comment]
also @KyleTheMan4444 next time, label it as a feature request and say it in the discord. you can find this in the readme

**Comment by DaChickenKing** [comment]
@BoredFishRE Actually, I'm not sure how to change labels on my PRs/issues- I'm not sure if it works in this repo if you're not a collab.

**Comment by BoredFishRE** [comment]
I'm going to close this because it's not an issue. Next time either put [Feature Request] in the name or ask it in the discord

**Comment by KyleTheMan4444** [comment]
@DaChickenKing how do i run the code and put it in prodigy

**Comment by BoredFishRE** [comment]
@KyleTheMan4444 put it in the console. Read before you ask

**Comment by PatheticMustan** [comment]
I'll think about doing this

**Comment by DaChickenKing** [comment]
yayayaayyaya

**Comment by divinelemon** [comment]
> Adding an edit inventory that detailed would take a while, not to mention kinda pointless. Its a good idea but prob wont happen as that seems like too much. We are making a new menu tho, so we'll see

actually not true. almost all player data is located in `hack.player.backpack.data`, and if you have access to the arrays of names of [insert what you would like to change here, e.g. boots], it wouldnt be that hard.

**Comment by divinelemon** [comment]
@DaChickenKing or @PatheticMustan, could you look into finding the named arrays of all player data?

**Comment by PatheticMustan** [comment]
it's in gameData

**Comment by divinelemon** [comment]
oh cool
