### ISSUE TITLE
[FEATURE REQUEST] Add some type of FAQ, or if one exists, expand it and make it a lot easier to find.

### ISSUE THREAD

**Issue by DaChickenKing** [Prodigy-Hacking/ProdigyMathGameHacking#293]
**Is your feature request related to a problem? Please describe.**
I commonly refer people to ProdigyMathGameHacking. It's an amazing repository with a good goal. However, I'm commonly by people things like "Isn't that patched?" or "Why isn't my game saving?"

The questions get so repetitive. So, in my opinion, it would definitely be a good idea to include some type of FAQ. 

**Describe the solution you'd like**
As stated above, I think PMGH should have a FAQ, linked near or at the top of the README. It will answer frequent questions, including but not limited to the ones I described above.

**Describe alternatives you've considered**
N/A

**Additional context**
I have no additional context.

**Comment by BoredFishRE** [comment]
We have one and it is extremely easy to find. Its the wiki

**Comment by DaChickenKing** [comment]
link the wiki from the repo README or something and add answers to like why battles dont save in the wiki pages

**Comment by DaChickenKing** [comment]
didnt mean to close

**Comment by BoredFishRE** [comment]
IT IS!

**Comment by DaChickenKing** [comment]
@BoredFishRE well most people cant find it so take that boomer

**Comment by DaChickenKing** [comment]
yay mustan upvoted

**Comment by BoredFishRE** [comment]
![wwww](https://user-images.githubusercontent.com/49598984/92124682-16cf0a00-edcc-11ea-9387-acd36b32aa0c.PNG)
![vrug](https://user-images.githubusercontent.com/49598984/92124686-18003700-edcc-11ea-84a6-f8b9a6780f9e.PNG)

**Comment by DaChickenKing** [comment]
is there an FAQ in the wiki

**Comment by BoredFishRE** [comment]
ima close it because it has been created

**Comment by DaChickenKing** [comment]
yay
