### ISSUE TITLE
Find Morph Hack

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#299]
![image](https://user-images.githubusercontent.com/70917868/92415471-fd5cf380-f126-11ea-8f91-d04d9b1b9eba.png)

^How to do this? Basically they have the ability to morph into anything housing objects, pets, you name it!

_Originally posted by @ACuriousKid in https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/issues/25#issuecomment-688500798_

**Comment by PatheticMustan** [comment]
I suspect the morph hack doesn't require redirector. It'd be interesting to morph into a chair.

As Arc said in the Discord, it probably takes in an asset ID. I guess all we have to do is find the endpoint, and how to pass in the ID

**Comment by Avn1114** [comment]
![image](https://user-images.githubusercontent.com/60945964/92420793-4d49b380-f143-11ea-9a61-a2706f96658c.png)
So essentially, this shows that the gameData of the marble transforms you into a pet, based off of the `ID`. If this is changed, then it's a different pet.

**Comment by Avn1114** [comment]
eg. 
![image](https://user-images.githubusercontent.com/60945964/92420999-69018980-f144-11ea-9cb4-55ab137b2f60.png)

**Comment by Avn1114** [comment]
so you just need the pet's id

**Comment by Avn1114** [comment]
So it takes a bit of work to get the ID of the marble and the pet, but that's how to do it.

**Comment by PatheticMustan** [comment]
Thank you Arc, very cool

Time to weaponize morphs

**Comment by YamaHacks** [comment]
*weaponize*

**Comment by Flame-1** [comment]
I am making script using this thanks.

**Comment by PatheticMustan** [comment]
be careful, invalid morphs will permanently lock an account

**Comment by ArcerionDev** [comment]
rip kira darkshade

**Comment by FlameHacks** [comment]
Sadly script has been cancelled I can find a way to morph automtatically

**Comment by ryirdgibberishgewfh** [comment]
Can somebody put a step by step guide please

Like what program do you need to run the script and things like that

**Comment by ryirdgibberishgewfh** [comment]
I’m desperate

**Comment by PatheticMustan** [comment]
HI DESPERATE I'M MUSTAN

**Comment by ryirdgibberishgewfh** [comment]
Mustan goddamit

**Comment by poIarbear** [comment]
god damn it mustan, what the hell.
