### ISSUE TITLE
[BUG] IT BROKE

### ISSUE THREAD

**Issue by MuffinFalconAdmin** [Prodigy-Hacking/ProdigyMathGameHacking#303]
### ***Description***:
Pls help high priority!!!! it 404 me when i use it

***Replication***:
Plsssssdssssss

***Images***:

![image](https://user-images.githubusercontent.com/58113779/93505734-4a617680-f92c-11ea-9de1-bb8a04a5dbd6.png)

***Additional Errors***:
my teacher will kill me u guys dont sort it out

**Comment by Blazefire1236** [comment]
@MuffinFalconAdmin  disable your redirector for now there probably working on

**Comment by PatheticMustan** [comment]
We're currently working on disabling the anticheat.

**Comment by 86109** [comment]
until the bug is fixed you can still play with the hacks you have but you might have to play in a different browser
