### ISSUE TITLE
[BUG] Battle Crash

### ISSUE THREAD

**Issue by Coder1029** [Prodigy-Hacking/ProdigyMathGameHacking#308]
***Description***:
With redirector hack imported, when you go to into Prodigy battle, it crashes/freezes.

***Replication***:
Import Redirector hack file into Redirector and go battle a monster.
***Images***:
![image](https://user-images.githubusercontent.com/66094570/94293961-13dbbb00-ff2d-11ea-96e9-ac709840b935.png)

***Additional Errors***:
Meanwhile in console:
![image](https://user-images.githubusercontent.com/66094570/94294028-2eae2f80-ff2d-11ea-8e97-859dcc8de5fb.png)

**Comment by DaChickenKing** [comment]
use fix battle crash button

**Comment by PatheticMustan** [comment]
We've seen this bug so often, maybe it'd be a good idea to just automatically run "fix battle crash"?

**Comment by DaChickenKing** [comment]
ye

**Comment by ArcerionDev** [comment]
We can modify the game.min.js in prodigyhacking.ml to do something like 
```js
setInterval(function(){
_.player.kennel.petTeam.forEach(v => {
    if (v && v.assignRandomSpells) {
        v.assignRandomSpells();
    }
});
},1000)
```
Not sure if this might bog down the game, but from what I've seen, for the majority of devices it won't.

**Comment by ArcerionDev** [comment]
Because most people don't know that even editing your kennel a little bit might cause a crap load of errors, so this is the best way to catch errors like these.

**Comment by Coder1029** [comment]
I got it fixed.  I realized that I didn't install the x-frame ignore extension, sorry for the confusion.
