### ISSUE TITLE
[HR]MOBILE HACK

### ISSUE THREAD

**Issue by thereturnofdespacitospider** [Prodigy-Hacking/ProdigyMathGameHacking#309]
**Describe the hack in 5 words or less:**
 Mobile hack

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by thereturnofdespacitospider** [comment]
**pls ### _plsls**_

**Comment by thereturnofdespacitospider** [comment]
_**pls pls pls**_

**Comment by PatheticMustan** [comment]
You can use Script Based hacks. Other than that, it's infeasible to make hacks without redirector. You can find Script Based Hacks in the /hacks folder.
