### ISSUE TITLE
[HR] Cheat Extension

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#321]
It would be a good idea to make a custom chrome extension for Prodigy hacking. It seems like @UntrustableRus is already working on this in the PR #320.

Having a single extension would mean we would be able to release updates without user interaction. It would also give us more control over network requests.

Pros:
- Combine two plugins into a single plugin
- More control over Chrome API
- Less interaction needed from user, no import needed
- Less interaction needed if something breaks

Cons:
- One more thing to maintain
- Lack of Firefox/Safari support???

It shouldn't be too arduous of a task, but here are some things we would need to do.

- [x] Make chrome plugin (duh)
- [x] Allow redirects using a file from our github.
- [x] Ignore CSP

**Comment by ArcerionDev** [comment]
It's not like we're going to need to maintain it, and extensions can be used on Firefox, and nobody uses Safari anyway

**Comment by ArcerionDev** [comment]
like, after it's done, it's done. We're just going to need to update the JSON

**Comment by ArcerionDev** [comment]
or however we redirect requests in a chrome extension

**Comment by PatheticMustan** [comment]
Support is pretty important tho...
And yeah, updating/fixing redirector should be easier than before.

**Comment by ArcerionDev** [comment]
Eh, the majority of people use chrome, and if they use safari, they won't be able to use redirector as it is rn anyway

**Comment by PatheticMustan** [comment]
@UntrustableRus, do you think you would be able to handle the extension yourself? Also do you need/want help, or a point in the right direction?

**Comment by ArcerionDev** [comment]
He's already done with it smh

**Comment by PatheticMustan** [comment]
Wow, completely done with it already? That was fast.

**Comment by ArcerionDev** [comment]
he finished it within 2 hours, I think he knows what he's doing

**Comment by ArcerionDev** [comment]
lol

**Comment by PatheticMustan** [comment]
Every watcher in this repo gets a notification for each comment. >;[
If it's already done, I guess all that's left to be done is to upload the source, bugfix, and publish it.

**Comment by ArcerionDev** [comment]
> Every watcher in this repo gets a notification for each comment. >;[
then they can unwatch it smh

**Comment by UntrustableRus** [comment]
@PatheticMustan Yes, I am handling the entire extension. The extension redirects requests to the same endpoints as the redirector hack. But, if you ever have to change one of the endpoints just let me know and I'll update the extension, and chrome automatically updates extensions in the background iirc so updates will be seamless. The PR is purely to add it to the documentation as well.
