### ISSUE TITLE
#318 WCM UI Updates (becuase I want to help)

### ISSUE THREAD

**Issue by SwxtchCode** [Prodigy-Hacking/ProdigyMathGameHacking#332]
I'll put a checklist here once I have any idea of what I'm doing.

**Comment by SwxtchCode** [comment]
Who likes my button design idea? :DDD

https://imgur.com/i3ftt7l.png

**Comment by PatheticMustan** [comment]
If you're planning on making changes, you can push it directly to #329

**Comment by SwxtchCode** [comment]
Ok! Will do!

**Comment by poIarbear** [comment]
I only exist in github comments now, arc why are you stalking me lol

**Comment by SwxtchCode** [comment]
what lmao

**Comment by SwxtchCode** [comment]
Moving this to my PR, #338.
