### ISSUE TITLE
README doesn't show instructions for installing the Firefox extension on Debian/Kali Linux

### ISSUE THREAD

**Issue by SwxtchCode** [Prodigy-Hacking/ProdigyMathGameHacking#335]
It's a bit different. But idk if anyone cares because no normal script kiddie uses Linux.

**Comment by UntrustableRus** [comment]
If you could, make a PR with instructions for Ubuntu installation and it'll get merged.

**Comment by SwxtchCode** [comment]
> If you could, make a PR with instructions for Ubuntu installation and it'll get merged.

Will probably do that later.
