### ISSUE TITLE
android app

### ISSUE THREAD

**Issue by SwxtchCode** [Prodigy-Hacking/ProdigyMathGameHacking#344]
we need one

may I make

pls

**Comment by UntrustableRus** [comment]
Is that even possible?

**Comment by SwxtchCode** [comment]
Yes. You can make an APK file, and the end user can allow installing from unknown sources.

**Comment by UntrustableRus** [comment]
How is prodigy even played on android? Is there an app?

**Comment by SwxtchCode** [comment]
Yes, there is an app on the Google Play Store.

**Comment by UntrustableRus** [comment]
Actually, the cheats are all in JS, we would have to recreate an entirely new codebase just for the android app.

**Comment by SwxtchCode** [comment]
The Android app embeds the site and injects JS, I think.

**Comment by UntrustableRus** [comment]
Yeah, alright.

**Comment by UntrustableRus** [comment]
We'd have to make a modified version of the app then?

**Comment by SwxtchCode** [comment]
![Screenshot_2020-10-23_200848.png](https://user-images.githubusercontent.com/61570792/97066620-aa6ebc80-156b-11eb-94ce-4efa54b056a7.png)

Prodigy's app from the Play Store

**Comment by SwxtchCode** [comment]
> We'd have to make a modified version of the app then?

Yea

**Comment by UntrustableRus** [comment]
If it just embeds the site, then we'd have to figure out how to implement a redirector for web requests inside of the app.

**Comment by SwxtchCode** [comment]
> If it just embeds the site, then we'd have to figure out how to implement a redirector for web requests inside of the app.

Hmm... true. For now we can just implement script-based hacks.

**Comment by UntrustableRus** [comment]
We have to have the code redirected in some way just to load in the actual scripts (the _)

**Comment by SwxtchCode** [comment]
Also, by embedding the site, I mean it has a custom login and loading that it draws over the site, then logs the user in via the app's login screen or whatever.

**Comment by UntrustableRus** [comment]
That's the only tie in between the app and embed.

**Comment by SwxtchCode** [comment]
> We have to have the code redirected in some way just to load in the actual scripts (the _)
> 

I mean Arc's script-based hacks. All network-based.

**Comment by SwxtchCode** [comment]
> That's the only tie in between the app and embed.

Yes.

**Comment by UntrustableRus** [comment]
We could only do the script based hacks (ones without using _)

**Comment by UntrustableRus** [comment]
I'll decompile the android app.

**Comment by SwxtchCode** [comment]
> We could only do the script based hacks (ones without using _)

Yea, but it's something. Maybe @ArcerionDev could work on it more? The goal is reaching as large of an audience as possible. I personally know at least 10 people who this will help.

**Comment by SwxtchCode** [comment]
> I'll decompile the android app.

I did that like a year ago. It's somewhat obfuscated, but feel free to give it a try.

**Comment by UntrustableRus** [comment]
here ya go
[prodigy.zip](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/files/5432354/prodigy.zip)

**Comment by SwxtchCode** [comment]
> here ya go
> [prodigy.zip](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/files/5432354/prodigy.zip)
> 

Ooh, that's a major change since the last time I tried.

**Comment by SwxtchCode** [comment]
Unrelated, but Prodigy uses Google Analytics? Interesting.
![Screenshot_2020-10-23_202849.png](https://user-images.githubusercontent.com/61570792/97067035-7779f800-156e-11eb-9fc7-c858dda01cab.png)

**Comment by PatheticMustan** [comment]
I suggest not working on an app. Prodigy would probably DMCA us.

**Comment by SwxtchCode** [comment]
> I suggest not working on an app. Prodigy would probably DMCA us.

Why didn't they DMCA the GitHub? Why didn't they report the web store app?

**Comment by SwxtchCode** [comment]
[test #1](https://anonfiles.com/L33eefj7p1/ProdigyMathGameHacking_apk) loads prodigy and alerts "hello world"

havent tested yet but ik it works

**Comment by PatheticMustan** [comment]
> > I suggest not working on an app. Prodigy would probably DMCA us.
> 
> Why didn't they DMCA the GitHub? Why didn't they report the web store app? We might be able to only distribute an APK file, and not put it in the Play Store. If they DMCA the GitHub, GitHub won't take down an entire repository for a single file, they'll just delete the APK file.

We didn't actually use their code, we just inject our own.

With an app, it's more of a gray area, since we're just modifying their existing app

**Comment by SwxtchCode** [comment]
We're not modifying their app. We're embedding the website and injecting code!

**Comment by SwxtchCode** [comment]
ok looks like the app is broken idk how

**Comment by SwxtchCode** [comment]
ok nvm figured it out brb

**Comment by SwxtchCode** [comment]
https://prnt.sc/v616t4

the user agent string is a samsung s8 in chrome to make it look less suspicious

**Comment by SwxtchCode** [comment]
took an hour to get it working and avast says it's making suspicious activity lmfao

**Comment by ArcerionDev** [comment]
:thonk:

**Comment by SwxtchCode** [comment]
it's probs 'cause it's injecting JS into prodigy or something lmao

**Comment by SwxtchCode** [comment]
ah,[ i see ](https://www.reddit.com/r/androiddev/comments/310ux7/avast_detects_my_app_as_apkcloudrep_susp/)

**Comment by SwxtchCode** [comment]
AYYY I SUCCESSFULLY DIDD SOMETHING

![Uploading Screenshot_2020-10-24_102710.png…]()

**Comment by ArcerionDev** [comment]
did you just embed it or what

**Comment by UntrustableRus** [comment]
If you add the hack by only injecting JS then we could create a bookmarklet.

**Comment by ArcerionDev** [comment]
You can already install Chrome extensions on phone with Yandex

**Comment by SwxtchCode** [comment]
WAHOOO ALERTS ARE WORKING
![Screenshot_2020-10-24_104939.png](https://user-images.githubusercontent.com/61570792/97088588-c06d9300-15e6-11eb-809c-9766fba5b07b.png)

**Comment by SwxtchCode** [comment]
> You can already install Chrome extensions on phone with Yandex
> 

idc this is cooler

**Comment by SwxtchCode** [comment]
sketchware (what im using as my laptop is broken and mit app inventor won't work on my Linux machine) link: http://sketchware.io/import.jsp?id=Gzaw

and im uploading the zip file hold on

**Comment by SwxtchCode** [comment]
https://github.com/SwxtchCode/SwxtchCode/blob/main/PMGH.zip

**Comment by SwxtchCode** [comment]
btw, once everyone downloads that, tell me so i can delete the comments

**Comment by SwxtchCode** [comment]
uhh what did i screw up now lmao

https://imgur.com/7K5UcPG.png

**Comment by ArcerionDev** [comment]
cleartext communication

**Comment by ArcerionDev** [comment]
```xml
<platform name="android">
  <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
      <application android:usesCleartextTraffic="true" />
  </edit-config>
</platform>
```

**Comment by ArcerionDev** [comment]
~~I def didn't just look up what was wrong on stackoverflow oh no I'm not like that no no no~~

**Comment by SwxtchCode** [comment]
kk lmao

**Comment by SwxtchCode** [comment]
kk so now it has login, cool colors, auto-clear cache/history/cookies on launch, and a "Hello World" prompt once you login

[![https://imgur.com/SblvBjE.png](https://imgur.com/SblvBjE.png)](https://imgur.com/SblvBjE.png)

its ready for a mobile cheat menu1!!

**Comment by SwxtchCode** [comment]
> https://github.com/SwxtchCode/SwxtchCode/blob/main/PMGH.zip

deleted the ZIP and the sketchware link/ZIP are both outdated anyways. i'll upload the new ZIP once i finish removing all the unused code added by sketchware

**Comment by SwxtchCode** [comment]
ok so im able to get it to like load and login and stuff but then once you like start loading the game the page just goes blank aaaaa

i'll figure it out later ig lmao

**Comment by SwxtchCode** [comment]
ok here's the current app source code https://github.com/SwxtchCode/SwxtchCode/blob/main/app.zip

if someone can figure it out i will be thanccfull

**Comment by SwxtchCode** [comment]
bruh help needed here lmao

**Comment by PatheticMustan** [comment]
why is it in your readme repo???

**Comment by SwxtchCode** [comment]
because I didnt know a better place to put it lmao

**Comment by poIarbear** [comment]
sick

**Comment by SwxtchCode** [comment]
bruh

**Comment by ProBrainPOP** [comment]
> Actually, the cheats are all in JS, we would have to recreate an entirely new codebase just for the android app.

like what programming language are you going to use now? C++, Java, etc.? I know some C++, but only 30% of it.

**Comment by BoredFishRE** [comment]
JS. What else would we use.

**Comment by ProBrainPOP** [comment]
> ok here's the current app source code https://github.com/SwxtchCode/SwxtchCode/blob/main/app.zip
> 
> if someone can figure it out i will be thanccfull

wait that page is a error 404 github page

**Comment by ArcerionDev** [comment]
Android actually includes a NodeJS runtime environment, so we won't need to use anything else

**Comment by ProBrainPOP** [comment]
> JS. What else would we use.

JS?

**Comment by ProBrainPOP** [comment]
NodeJS. Hmm.

**Comment by ProBrainPOP** [comment]
When will your "hacks" be back?

**Comment by ArcerionDev** [comment]
Hacks are fixed @ProBrainPOP

**Comment by ProBrainPOP** [comment]
my account on prodigy is cursed with a eternal member cloud and i can turn it on and off

**Comment by ProBrainPOP** [comment]
and im not even a member anymore

**Comment by ArcerionDev** [comment]
uhhh ok

**Comment by PatheticMustan** [comment]
Closed unless somebody wants to patch the prodigy app for integrity

**Comment by SwxtchCode** [comment]
> Hacks are fixed @ProBrainPOP

WHEN WERE HACKS FIXED WUTT

**Comment by PatheticMustan** [comment]
11-19-2020 lol, we announced on the discord

**Comment by BoredFishRE** [comment]
> > Hacks are fixed @ProBrainPOP
> 
> WHEN WERE HACKS FIXED WUTT

You would know if you were on the discord- oh. Right. You got banned.
