### ISSUE TITLE
Feature Request (allow to work on other devices)

### ISSUE THREAD

**Issue by JesseTheOctoling2963** [Prodigy-Hacking/ProdigyMathGameHacking#346]
**Is your feature request related to a problem? Please describe.**
Yes.
When I go on prodigy on another device, when I go to battle, it crashes. 
**Describe the solution you'd like**
I would like if you guys could fix this. 
**Describe alternatives you've considered**
Maybe hacking enabled on mobile? I don’t know though.
**Additional context**

**Comment by SwxtchCode** [comment]
Use the "fix battle crash button" to fix the battle crash issue.

We might make an Android app (#344), but that's not decided.

iOS is too complicated/expensive, though.
