### ISSUE TITLE
[HUGE BREAKTHROUGH!] Employee Panel Bypass?

### ISSUE THREAD

**Issue by SwxtchCode** [Prodigy-Hacking/ProdigyMathGameHacking#348]
Working on accessing Prodigy employee panel.

Original post:

https://prnt.sc/v6jvlb

**Comment by SwxtchCode** [comment]
I AM VERY EXCITED LEMME EXPIREMENT

**Comment by ArcerionDev** [comment]
this may actually be something

**Comment by ArcerionDev** [comment]
however, it will be hard to forge the requests in-game

**Comment by SwxtchCode** [comment]
also remember `/oauth2/userinfo`

there's a `employee` thing

we should use tampermonkey or something to change it to `"employee": "true"`

also prodigy is still "temporarily offline" for me and i gtg so i cant do more rn

**Comment by ArcerionDev** [comment]
alright, we can work on it

**Comment by SwxtchCode** [comment]
im back kidssss

**Comment by SwxtchCode** [comment]
also we should totally bruteforce this https://sso.prodigygame.com/employee/login

we have a lot of prodigy employee emails

**Comment by SwxtchCode** [comment]
bruh so the `penis` captcha thing doesnt work on employee login but it does on student/parent login

prodigy gives their employees more security on just a basic login screen than they do their actual customers lmfao

**Comment by SwxtchCode** [comment]
also this domain contains resources for prodigy's customer support: https://cs.prodigygame.com/

maybe bruteforce URLs for something interesting??

**Comment by SwxtchCode** [comment]
https://cs.prodigygame.com/index.php doesnt exist so the home is an html file

**Comment by SwxtchCode** [comment]
ok so when you send prodigy an email to support there's this thing where it says like "Press yes if these links solved your issue and we will close the ticket"

"Yes" links to this: https://www.prodigygame.com/actions/resolveZendeskTicket.php?ticketID=923925

the ticket ID is just my "test" ticket

but theoretically we could close every ticket on the zendesk by just going up a number each time

**Comment by SwxtchCode** [comment]
im getting off-topic rn tho ik

**Comment by SwxtchCode** [comment]
yep it works i solved my ticket by ID

[url=https://imgur.com/f2FLNMt.png]
  [img]https://imgur.com/f2FLNMt.png[/img]
[/url]

(ik a way to create an account on any zendesk support page even if the support center in question disallows it but that's a story for another day)

**Comment by UntrustableRus** [comment]
Major breakthrough!!!

**Comment by SwxtchCode** [comment]
i theoritically just marked like 20 tickets as resolved but no way to tell if it worked

**Comment by SwxtchCode** [comment]
> Major breakthrough!!!

yep

**Comment by UntrustableRus** [comment]
Use the dev tools and inspect the data sent when you go to that page, make sure no cookies are sent for verification or anything.

**Comment by SwxtchCode** [comment]
> Use the dev tools and inspect the data sent when you go to that page, make sure no cookies are sent for verification or anything.

kk

**Comment by UntrustableRus** [comment]
I just checked, and nope!!

**Comment by SwxtchCode** [comment]
absolutely nothing

**Comment by SwxtchCode** [comment]
> I just checked, and nope!!

why did you close lmao

**Comment by UntrustableRus** [comment]
Yup.

**Comment by SwxtchCode** [comment]
brb

**Comment by SwxtchCode** [comment]
back, and will hasnt been active on github lately so i unassigned him. if he actually comments here i'll re-assign him

**Comment by SwxtchCode** [comment]
hmm so what if we just find a prodigy employee who's email is in a  data breach exposing plain-text passwords (there are quite a few) and like use that to login to the employee dashboard?

**Comment by UntrustableRus** [comment]
Possibly?

**Comment by SwxtchCode** [comment]
ye hmmm

**Comment by SwxtchCode** [comment]
Ok so Co-CEO email
![Screenshot_2020-10-25_121110.png](https://user-images.githubusercontent.com/61570792/97116567-478c3b00-16bb-11eb-8792-e8d460f10dac.png)

**Comment by SwxtchCode** [comment]
a dev

![Screenshot_2020-10-25_121349.png](https://user-images.githubusercontent.com/61570792/97116610-94701180-16bb-11eb-81b6-70a667066381.png)

**Comment by UntrustableRus** [comment]
Found a list of all the help center API endpoints.

**Comment by UntrustableRus** [comment]
Get all tickets - https://prodigygame.zendesk.com/api/v2/tickets.json

**Comment by UntrustableRus** [comment]
This endpoint is for agents only

**Comment by UntrustableRus** [comment]
Here's the entire API documentation for zendesk support pages, https://developer.zendesk.com/rest_api/docs/support/tickets#list-tickets. The API base URL for Prodigy is https://prodigygame.zendesk.com/api/v2/

**Comment by SwxtchCode** [comment]
More devs
![Screenshot_2020-10-25_121819.png](https://user-images.githubusercontent.com/61570792/97116713-414a8e80-16bc-11eb-95bb-1bd4cf561de1.png)
![Screenshot_2020-10-25_121824.png](https://user-images.githubusercontent.com/61570792/97116725-4f98aa80-16bc-11eb-96f4-8c36b2374112.png)

**Comment by SwxtchCode** [comment]
ok that's everything RocketReach lets me search, feel free to plug the emails into HaveIBeenPwned

**Comment by UntrustableRus** [comment]
I posted a comment, look at it.

**Comment by SwxtchCode** [comment]
oooh ok

**Comment by SwxtchCode** [comment]
fuck i just realized i lost my canva combolist and one of the prodigy employees is in that breach

**Comment by SwxtchCode** [comment]
Nathaniel Groce's Gmail is in a bunch of breaches, which looks pretty useful to me ngl. A lot of the breaches had weak hashing so we might get some passwords from this. Now for the hard part: Finding the breaches.

**Comment by SwxtchCode** [comment]
YESS HES ON NEOPETS BREACH WHICH EXPOSED PLAIN TEXT PASSWORDS

**Comment by SwxtchCode** [comment]
oooh he's on wattpad too

**Comment by SwxtchCode** [comment]
Cracked.to or RaidForums are both good places to look for breaches. I suggest using a VPN, though.

**Comment by SwxtchCode** [comment]
kk so im thinking that if prodigy finds this they'll fix the issues and we're screwed. should we take this to Telegram or something similar?

**Comment by SwxtchCode** [comment]
https://t.me/joinchat/AAAAAFSe3mFvwKnySnBd2w join then add me as a contact and I'll create a "secret" (aka end-to-end encrypted) group dm for the employee hack

**Comment by SwxtchCode** [comment]
also join https://t.me/joinchat/AAAAAES-lpeZXVDVdnzKSg

**Comment by UntrustableRus** [comment]
I'm going to close this, this is just an API endpoint that doesn't give away employee panel access.
