### ISSUE TITLE
tf

### ISSUE THREAD

**Issue by SwxtchCode** [Prodigy-Hacking/ProdigyMathGameHacking#356]
https://github.com/reeeeeeeeeeeeeeeeeeee-g/Prodigy-Hacks

**Comment by PatheticMustan** [comment]
ah yes a skid

**Comment by UntrustableRus** [comment]
@PatheticMustan Is that repo a fork of this one but from a long time ago?

**Comment by PatheticMustan** [comment]
I have no idea, not sure it matters

**Comment by ArcerionDev** [comment]
pixi

**Comment by ArcerionDev** [comment]
it's not forked, it's copy-pasted

**Comment by ArcerionDev** [comment]
there are a lot of those

**Comment by ArcerionDev** [comment]
![image](https://user-images.githubusercontent.com/60945964/98007575-8d36bb00-1dc1-11eb-8eee-1d9b72ba6798.png)
143 forks
![image](https://user-images.githubusercontent.com/60945964/98007618-9f185e00-1dc1-11eb-9803-de4b742830e0.png)
139 prs

There are more forks then prs, ofc these 9 year olds steal shit, not a big surprise
