### ISSUE TITLE
[BUG] I can't do battle after you obtain all pets and epics :(

### ISSUE THREAD

**Issue by Lol1356** [Prodigy-Hacking/ProdigyMathGameHacking#357]
I used the hack to obtain all pets and epics and tried to do battle but it's frozen now.

![Screenshot from 2020-11-03 10-52-17](https://user-images.githubusercontent.com/62572425/98039555-f23ee080-1dc2-11eb-83da-375fb4d5a95d.png)

**Comment by BoredFishRE** [comment]
bro. Use the fix battle crash button in the Cheat menu.

**Comment by Lol1356** [comment]
Actually it's an I*

**Comment by BoredFishRE** [comment]
Could you clarify? No clue what you mean

**Comment by Lol1356** [comment]
Ok so after I used obtain all pets and epics and went to battle a monster. Prodigy froze. So I use the fix battle crash and reload?

**Comment by BoredFishRE** [comment]
no, do everything, then before going into battle, use fix battle crash

**Comment by Lol1356** [comment]
Oh ok thx a lot

**Comment by BoredFishRE** [comment]
np

**Comment by Lol1356** [comment]
U guys have a great hack just to let u know

**Comment by BoredFishRE** [comment]
if you like them, make sure to join our discord!

**Comment by Lol1356** [comment]
Ok!
