### ISSUE TITLE
Hi!! There has been a problem again!(or maybe im just bad at using hacks)

### ISSUE THREAD

**Issue by Lol1356** [Prodigy-Hacking/ProdigyMathGameHacking#362]
***Description***: When I try loading the game it just pauses at halfway. I have tried reinstalling the extension and restarting but it still does it.

![Screenshot from 2020-11-09 09-18-11](https://user-images.githubusercontent.com/62572425/98586423-c1e8bd80-226c-11eb-96ed-9c21428bdae9.png)

**Comment by grandre-exe** [comment]
This happens to me as well. It worked fine a few days ago. Yesterday, in fact.

**Comment by YamaHacks** [comment]
Its an issue on our end, please be patient. We are currently working it out.

**Comment by Lol1356** [comment]
Ok thx :)

**Comment by grandre-exe** [comment]
Thanks :)
By the way, when do you think it will be fixed? No pressure :)

**Comment by ArcerionDev** [comment]
S o o n

**Comment by Lol1356** [comment]
I think it works now!
