### ISSUE TITLE
[BUG] prodigy will not load to home screen

### ISSUE THREAD

**Issue by spityou** [Prodigy-Hacking/ProdigyMathGameHacking#363]
![Screenshot 2020-11-09 at 11 32 53 AM](https://user-images.githubusercontent.com/70118398/98587923-b5ba2b80-227f-11eb-8499-2872556c0b71.png)
for some reason when the hack is on it will not load to the home screen but if you turn the hack off the home screen will load
![Screenshot 2020-11-09 at 11 28 57 AM](https://user-images.githubusercontent.com/70118398/98587460-067d5480-227f-11eb-828f-3b19cda8f0e1.png)

**Comment by Lol1356** [comment]
Oh guys now it keeps on saying it can't connect to prodigy

**Comment by PatheticMustan** [comment]
Please open console with [Control + Shift + I], and screenshot console.

**Comment by spityou** [comment]
> Please open console with [Control + Shift + I], and screenshot console.

why and why and because you cant get the extension anymore sus

**Comment by PatheticMustan** [comment]
use redirector for now

**Comment by spityou** [comment]
ok

**Comment by BoredFishRE** [comment]
Hacks are not working. please be patient.
