### ISSUE TITLE
Redirector hack

### ISSUE THREAD

**Issue by grandre-exe** [Prodigy-Hacking/ProdigyMathGameHacking#364]
The redirector extension downloaded just fine and works perfectly, but both of the links you provided on the page don't work.

**Comment by ArcerionDev** [comment]
it should be up, now.

**Comment by PatheticMustan** [comment]
#365

**Comment by UntrustableRus** [comment]
@PatheticMustan I believe this is related to the outage, as it states that they downloaded the extension.

**Comment by PatheticMustan** [comment]
Sorry, I should have clarified. Further discussion should be continued on issue 365.
