### ISSUE TITLE
Chrome Extension Gone

### ISSUE THREAD

**Issue by UntrustableRus** [Prodigy-Hacking/ProdigyMathGameHacking#365]
## We are aware you are unable to download the chrome extension, please stay patient.

It appears like our chrome extension was taken off the web store.
![image](https://user-images.githubusercontent.com/46432997/98716643-ea9ab100-2359-11eb-858d-99d196186a61.png)
I'm not sure why, I'm at school right now so when I get home I'll check my email, as they usually say why it was taken down.

We may be able to get it back up, this could be related to the outage for PMGH servers yesterday, and they could have taken it down because it doesn't work, but we shall know soon.

**Comment by UntrustableRus** [comment]
Probably got DMCA'd

**Comment by PatheticMustan** [comment]
not DMCA, just taken down

**Comment by UntrustableRus** [comment]
I'll check my email when I get home they usually say why

**Comment by UntrustableRus** [comment]
See #368
