### ISSUE TITLE
[DMCA/Meta] Chrome Extension Takedown By Prodigy Education LLC.

### ISSUE THREAD

**Issue by UntrustableRus** [Prodigy-Hacking/ProdigyMathGameHacking#368]
The chrome extension has been taken down by Prodigy via DMCA. We choose not to republish the extension. Here is the form filled out by someone at Prodigy's legal agency. Note that we have redacted private details.

**Country of residence**
United States

**Full legal name**
[Redacted]

**Company name**
[Redacted]

**Full legal name of the copyright holder you represent**
Prodigy Education Inc.

**Contact email address**
[Redacted]

**Login email**
[Redacted]

**Identify and describe the copyrighted work**
Prodigy Education Inc. is the exclusive owner of the Prodigy Math Game and all related assets including copyrights within the Prodigy Math Game.

**Where can we see an authorized example of the work?**
https://play.prodigygame.com/

**Allegedly infringing URLs**
https://chrome.google.com/webstore/detail/prodigy-math-game-hacking/lpkeloemedafpfkdkbaclmmaokmadced

**Hidden uraw**
Not available

**Signature**
[Redacted]

**Signature date**
Mon, 09 Nov 2020

**Subject lr dmca**
Your Request to Google

**Hidden product**
chromewebstoreextensionsgallery

**Hidden ctx**
Not available

**Geolocation**
US

The chrome extension on the public chrome web store will not make a return. An alternative method will be added soon.

**Comment by BoredFishRE** [comment]
@PatheticMustan @ArcerionDev @YamaHacks this is weird. Didn't even say what part of it was violating it

**Comment by UntrustableRus** [comment]
Yes. More info was in the email, but it was just pre-written stuff about DMCA. We can file a counter notification.

**Comment by BoredFishRE** [comment]
Nah I would just ask what part of it

**Comment by BoredFishRE** [comment]
because all they said was 
Prodigy Education Inc. is the exclusive owner of the Prodigy Math Game and all related assets including copyrights within the Prodigy Math Game.

**Comment by PatheticMustan** [comment]
Maybe it was the front art..?

**Comment by BoredFishRE** [comment]
Nah, then they would have to take down a LOT. The cover art was taken by us, meaning that it's ours, it was NOT taken by them. That would be like taking a picture of a dog and then the owner saying that it's his dog meaning it's his photo and you can't do anything with it.

**Comment by UntrustableRus** [comment]
"That pavement in the background is on Earth, and I live on earth so we should take that down"

**Comment by BoredFishRE** [comment]
lol

**Comment by PatheticMustan** [comment]
well actually if it contained their characters, they could technically do that...

"That's a character from my game, I don't like how you used it without my permission!"
