### ISSUE TITLE
What are you going to do if Prodigy removes it from GitHub?

### ISSUE THREAD

**Issue by Soyokoanis** [Prodigy-Hacking/ProdigyMathGameHacking#369]
^^

**Comment by BoredFishRE** [comment]
They can't really. There's nothing that infringes on copyright. But, if somehow they do, I honestly don't know.

**Comment by UntrustableRus** [comment]
They removed the extension without any good reason, so it's possible.

**Comment by UntrustableRus** [comment]
Off-topic/not what issues are intended for, closing, conversation may continue.

**Comment by PatheticMustan** [comment]
if they take down the repo, we'll just have to private our code, which would be very sad. :(

**Comment by poIarbear** [comment]
yes :c
