### ISSUE TITLE
[BUG] WHEN trying to load in with the hacks its stuck in the middle 

### ISSUE THREAD

**Issue by Robloxgeeksz** [Prodigy-Hacking/ProdigyMathGameHacking#370]
***Description***:
WHAT DO I DO

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/71845671/99026288-7f9ad700-251f-11eb-9300-3c1cc034c706.png)

***Additional Errors***:

**Comment by ArcerionDev** [comment]
Disable redirector/PMGH extension for the time being

**Comment by ArcerionDev** [comment]
We are fixing the hacks

**Comment by Robloxgeeksz** [comment]
the only thing thats working is when i remove ignore x frame  i can load in the game and i get the member but no admin commands

**Comment by poIarbear** [comment]
alright so member works
