### ISSUE TITLE
No Hacks working "VM180:1 Uncaught ReferenceError: hack is not defined"

### ISSUE THREAD

**Issue by aqward** [Prodigy-Hacking/ProdigyMathGameHacking#371]
Description: Whenever I put one of the hacks in the hacks folder into the console, it comes up with the error "VM180:1 Uncaught ReferenceError: hack is not defined"

Directions: Install redirector, put in .JSON. Use any one of the hacks in the hack folder, put it into the console. It should say "VM180:1 Uncaught ReferenceError: the hack is not defined".

***Images***:
![Screenshot (8)](https://user-images.githubusercontent.com/74499165/99188186-9fe9b200-2728-11eb-8e26-b96e0d0fc261.png)
![Screenshot (9)](https://user-images.githubusercontent.com/74499165/99188193-a415cf80-2728-11eb-90f3-68f9a30be7fb.png)

***Additional Errors***: None

**Comment by aqward** [comment]
If anyone knows how to fix that would be greatly appreciated.

**Comment by BoredFishRE** [comment]
Hi! The variable Hack is depreciated. And hacks are not working. If you were to read the README you would know that.
