### ISSUE TITLE
Both redirector hack and firefox hack gets my loading bar stuck in the middle.

### ISSUE THREAD

**Issue by Lol1356** [Prodigy-Hacking/ProdigyMathGameHacking#374]
Does redirector hack work in firefox cus I did all the steps and the loading bar gets stuck in the middle. 

![Screenshot from 2020-11-16 08-27-55](https://user-images.githubusercontent.com/62572425/99292693-aab64c80-27e5-11eb-8e1b-52e24a9bc863.png)

**Comment by PatheticMustan** [comment]
Hacks are temporarily patched. We've announced this in both the readme, in other issues, and in the discord.
