### ISSUE TITLE
REDIRECTOR BUG    

### ISSUE THREAD

**Issue by prodigygam** [Prodigy-Hacking/ProdigyMathGameHacking#375]
***Description***:
redirector hack doesn't led me in the game. if i close redirector, it lets me into the game but everything changed. PLEASE fix the redirector hack

***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
what do you mean "everything changed" @prodigygam

**Comment by PatheticMustan** [comment]
#376
