### ISSUE TITLE
Hacks are patched.

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#376]
The hacks are patched. We know.
We're fixing Redirector right now. Until then, just disable it. If you'd like to receive updates on when we fix the hacks, join [our official discord](https://discord.com/invite/XQDfbfq).

**Comment by prodigygam** [comment]
what is the official discord? i would like to join it and receive the updates

**Comment by BoredFishRE** [comment]
https://discord.com/invite/XQDfbfq

**Comment by RoundEggy** [comment]
> The hacks are patched. We know.
> We're fixing Redirector right now. Until then, just disable it. If you'd like to receive updates on when we fix the hacks, join [our official discord](https://discord.com/invite/XQDfbfq).

Actually, the rediector hack still works...the debugging said don't enable, but when you enable it it works.

**Comment by DerpHacking** [comment]
I can hack by inspecting though...the x-frame header extention doesn't work so can someone tell me where to get the inspect bookmarklet?

**Comment by ArcerionDev** [comment]
@DerpHacking actually, there is a specific variable that we implant into the game, and it is unaccessible unless you use redirector, and the working config. So if you were able to open console, there would be nothing you could do. `_.instance`, `_.player`, etc would be undefined.

**Comment by DerpHacking** [comment]
@ArcerionDev Oh

**Comment by BoredFishRE** [comment]
Don't say things before you know it actually works lol

**Comment by ArcerionDev** [comment]
yes it would be way too much to look down and see the large
<h1><strong>HACKS ARE DOWN</strong></h1>

**Comment by ProBrainPOP** [comment]
The redirector thing is blocked for me..

**Comment by ProBrainPOP** [comment]
I joined the discord.

**Comment by PatheticMustan** [comment]
Hacks have been fixed, will write instructions soon.

**Comment by DerpHacking** [comment]
I just found out try __[tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en)__ it can inject any code easily apparently

**Comment by DerpHacking** [comment]
> Hacks have been fixed, will write instructions soon.

**Where**

**Comment by PatheticMustan** [comment]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/How-to-install-hacks
@DerpHacking
