### ISSUE TITLE
uhhh ok

### ISSUE THREAD

**Issue by ProBrainPOP** [Prodigy-Hacking/ProdigyMathGameHacking#378]
uhhh ok

_Originally posted by @ArcerionDev in https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/issues/344#issuecomment-731220335_
and how do you become a collaborater

**Comment by BoredFishRE** [comment]
By contributing a lot and being very active.

**Comment by ProBrainPOP** [comment]
great
