### ISSUE TITLE
[HR] Websockets exist

### ISSUE THREAD

**Issue by requestx** [Prodigy-Hacking/ProdigyMathGameHacking#379]
Haven’t checked yet but i am pretty sure websockets are a thing. * nah cant be *
Why don’t y’all connect to the webcocket and um... definitely don’t send fake player data.
I don’t know if prodigy uses websockets but i kinda think they do. My computer is getting fixed so I’m gonna check in abt half a week but you could also do it.

**Comment by PatheticMustan** [comment]
We've looked into webhooks. If you would like to continue looking into it, please tell us what you find :)

**Comment by ArcerionDev** [comment]
webhooks????

**Comment by ArcerionDev** [comment]
I've already found a few things. So you require the ID token of the player, which you need to send a handshake packet to the websocket, which gives you access. It sends info on the players in the game, their data, where they move/are in the game, etc.

**Comment by ArcerionDev** [comment]
you can look into it if you want, I was only looking into it for an analytics scraper

**Comment by TayZ118** [comment]
Arcerion
 sorry and I used to be a big fan

**Comment by TayZ118** [comment]
not anymore bitch yeet

**Comment by TayZ118** [comment]
I got a life

**Comment by TayZ118** [comment]
same with bored fish and dyno

**Comment by TayZ118** [comment]
and Natsumi and will

**Comment by RtypeX** [comment]
c

**Comment by ArcerionDev** [comment]
Won't be worked on atm
