### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rxyanlaw** [Prodigy-Hacking/ProdigyMathGameHacking#391]
The game takes a long time to load.

**Comment by PatheticMustan** [comment]
Please read the [new injection method](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/How-to-install-hacks).

**Comment by Rxyanlaw** [comment]
Still doesn't work.

**Comment by ArcerionDev** [comment]
Join our [Discord](https://discord.gg/XQDfbfq) for support.

**Comment by PatheticMustan** [comment]
@Rxyanlaw read the [installation](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/How-to-install-hacks) instructions.
