### ISSUE TITLE
[BUG] edit pet level is client-side only

### ISSUE THREAD

**Issue by imdivesmaintank** [Prodigy-Hacking/ProdigyMathGameHacking#394]
***Description***: When you edit a pet's level, the effect is only in the client

***Replication***: Add a new pet using the plugin. Edit the same pet. Set pet level to 80. Level pet up once. It will be level 2 or 3, not 81. Alternatively, you can just refresh and log back in.

**Comment by PatheticMustan** [comment]
Thanks for the bug report! You were partially right, editing pet levels is not done properly. Pets and players use stars as xp. Edit pet only changed the level, not the stars.

**Comment by PatheticMustan** [comment]
Forgot how levels are calculated 😅
this may take a little bit

**Comment by PatheticMustan** [comment]
bruh I'm such a lazy bum, sorry this took such a long time \:P

**Comment by imdivesmaintank** [comment]
thanks!
