### ISSUE TITLE
[HR]

### ISSUE THREAD

**Issue by yvngKAOS** [Prodigy-Hacking/ProdigyMathGameHacking#414]
**Describe the hack in 5 words or less:**

a arena point hack
**Have you made sure this hack isn't available yet?* (Yes/No)**
no

**Comment by Fe4rlessfan121** [comment]
Hi,I would like to know if you would make a activation hack for epics so i can use them as buddies.

please and thank you

**Comment by josiah1393** [comment]
can you also tell me to please and thank you if you can I would love to have chil and char

**Comment by PatheticMustan** [comment]
Arena point hack is already being worked on, but tmk it already exists in the cheat menu

"Get All Epics" already exists.

**Comment by josiah1393** [comment]
ok
