### ISSUE TITLE
Confirmation on Click of Instant Hacks

### ISSUE THREAD

**Issue by imdivesmaintank** [Prodigy-Hacking/ProdigyMathGameHacking#415]
**Is your feature request related to a problem? Please describe.**
I've clicked something like "obtain all boots" when I had no desire to stack the account that way and there's no undoing it that I can see.

**Describe the solution you'd like**
Something like "are you sure you want to do this?" should pop up and only execute the hack if you say yes. Obviously this only applies to hacks that don't already have a follow-up UI (e.g. edit pet does not need a confirmation).

**Comment by poIarbear** [comment]
good feature yes you deserve a noble prize

or

bad feature please stop

>

**Comment by BoredFishRE** [comment]
Hmmm... Good idea!

**Comment by 3r3r3r3r3r3r3r3r3r** [comment]
the hacks do not work in harmony island

**Comment by ArcerionDev** [comment]
Will add soon

**Comment by NameIsA** [comment]
> the hacks do not work in harmony island

You should've made a seperate issue for that. Anyway, this is a known issue- #459
