### ISSUE TITLE
redirector hack

### ISSUE THREAD

**Issue by llliiimmmeeeGH** [Prodigy-Hacking/ProdigyMathGameHacking#416]
I have been having issues loading Prodigy with the Chrome injector extension method

I would like a link to the hack video in the Injection Methods row you see in the description on the home folder.

I have been thinking about this being re-featured on the official youtube channel.

The data collected by chrome is emptied every week on my Chrome account.

**Comment by PatheticMustan** [comment]
@ArcerionDev may be able to help..?

**Comment by ArcerionDev** [comment]
> The data collected by chrome is emptied every week on my Chrome account.


@llliiimmmeeeGH what do you mean by this, exactly??

**Comment by ArcerionDev** [comment]
As for the video: https://www.youtube.com/watch?v=j4l2RrZ0FRQ
