### ISSUE TITLE
Prodigy Not Loading with the extension 

### ISSUE THREAD

**Issue by bob486** [Prodigy-Hacking/ProdigyMathGameHacking#417]
When I have the extension installed Prodigy will not load at all it will just be stuck halfway. Any way to fix this?

**Comment by ArcerionDev** [comment]
this is a common error, try again later.

**Comment by Lenny-Face** [comment]
That happened to me with the redirector, at first I thought prodigy just wasn’t working on chrome and switched to edge, then I reinstalled Redirector and a uploaded all the packages and then it didn’t work on edge either, then I disabled Redirector. It worked perfectly, so I went on this website to see if they patched it. Then I found out about the new extension, I downloaded it, it worked.
So if you are use it Redirector... don’t. Unless it works for you of course.

**Comment by PatheticMustan** [comment]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/How-to-install-hacks
