### ISSUE TITLE
Mozilla Extension

### ISSUE THREAD

**Issue by qertyuiop12345678** [Prodigy-Hacking/ProdigyMathGameHacking#419]
**Describe the hack in 5 words or less:**
So, recently I've been having problems with Google Chrome and  I decided to switch over to Mozilla from chrome, and I don't think you can use chrome extensions on Mozilla, so it would really help if I could.
**Have you made sure this hack isn't available yet?* (Yes/No)**
No.

**Comment by ProdigyScriptHacker** [comment]
@qertyuiop12345678 Go to extensions press the 3 butons and press debug add on and then press load temporary add on do that every time you open up mozilla and it works but DO NOT USE vpn

**Comment by qertyuiop12345678** [comment]
Thanks!
