### ISSUE TITLE
[BUG] After adding epic pet, can't use its epic attack or enter epic arena with it

### ISSUE THREAD

**Issue by imdivesmaintank** [Prodigy-Hacking/ProdigyMathGameHacking#421]
***Description***:
Using the hack, if you add an epic pet (just one), you don't get access to the things that should come with it, e.g. the epic attack or battling in the epic arena in the epic subspace. Normally, if you have an epic, you don't see it on its pedestal in the epic subspace, but with epics added through the hack they still appear there and it functions as if you don't have it.

***Replication***:
Add epic pet using the browser hack, then attempt to use its epic attack or fight in the epic arena.

**Comment by ArcerionDev** [comment]
Can you add screenshots

**Comment by 3r3r3r3r3r3r3r3r3r** [comment]
The former times applied it to provide epic attacks

**Comment by 3r3r3r3r3r3r3r3r3r** [comment]
Try to press get all epics instead, wait did you use add pet?

**Comment by imdivesmaintank** [comment]
yes, I used add pet since I didn't want every single pet.

**Comment by imdivesmaintank** [comment]
in the short-term is there a way to fix it or re-do the epic add just running the relevant JS in the console? if so, where is that script? the reason I don't want to add them all is that you can't drop/release them and I use the epics as motivation for my child. once they have them all, the motivation is gone.

**Comment by PatheticMustan** [comment]
iirc there should be a pet removal button

**Comment by imdivesmaintank** [comment]
> 
> 
> iirc there should be a pet removal button

If you mean the native one in the game, it's disabled for epics.

**Comment by 3r3r3r3r3r3r3r3r3r** [comment]
remove pet hack remember?

**Comment by PatheticMustan** [comment]
> > iirc there should be a pet removal button
> 
> If you mean the native one in the game, it's disabled for epics.

I meant in the cheat menu....

**Comment by imdivesmaintank** [comment]
> I meant in the cheat menu....

My bad...yes that is a functioning workaround. Thanks!
