### ISSUE TITLE
[BUG] Prodigy still not loading

### ISSUE THREAD

**Issue by bob486** [Prodigy-Hacking/ProdigyMathGameHacking#423]
***Description***:
I am still not able to load the game when the hack extension is on. Fix, please. I am on Microsoft edge; I have no VPNs. How do I figure out the plugin version?  Prodigy works fine without the extension too.

**Comment by PatheticMustan** [comment]
we don't support edge, but if you'd like, we might be able to fix some errors.
Here's a list of what to do:

1. First make sure you follow [the instructions](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/How-to-install-hacks) again. It might have changed!
2. Go to Prodigy, and let it crash. Don't reload the page.
3. Open console with [Control Shift I]
4. Screenshot EVERY SINGLE ERROR.

**Comment by bob486** [comment]
It doesn't really crash it will just stay at the loading page forever.

**Comment by PatheticMustan** [comment]
yeah, can you screenshot it anyways?

**Comment by bob486** [comment]
ok here 
![image](https://user-images.githubusercontent.com/71081357/103172855-7f7f3e00-4824-11eb-9a86-abf6abb1dd2c.png)
![image](https://user-images.githubusercontent.com/71081357/103172871-a50c4780-4824-11eb-8386-0dd5d69acd45.png)

**Comment by ooo788** [comment]
wait how do u just drag a file into the extensions?

**Comment by ooo788** [comment]
i have the file but idk what to do with it

**Comment by PatheticMustan** [comment]
> ok here

we need the (console) errors

> wait how do u just drag a file into the extensions?

drag the file into chrome://extensions/

**Comment by PatheticMustan** [comment]
it should look something like 
![image](https://user-images.githubusercontent.com/35382971/103177923-6db19100-484c-11eb-9b87-f00517f763da.png)

**Comment by bob486** [comment]
![image](https://user-images.githubusercontent.com/71081357/103178121-0e548080-484e-11eb-9a77-f23c8c0974c7.png)
Sorry for the wrong image

**Comment by PatheticMustan** [comment]
hmmm, @TNThacker2015 @BoredFishRE invalid cert...???

**Comment by PatheticMustan** [comment]
@bob486 can you try clearing your cache?

**Comment by bob486** [comment]
I tried but nothing happend.

**Comment by BoredFishRE** [comment]
Investigating SSL on that domain

**Comment by ArcerionDev** [comment]
Could be loading through http instead of https, or vice versa, will look into later

**Comment by ArcerionDev** [comment]
Oh sorry didn't mean to close

**Comment by PatheticMustan** [comment]
after thinking about it for many months, I think it's probably some weird vague issue with what certificates you have installed on your computer.....

I have absolutely no clue on what the issue is, or how to fix it

**Comment by PatheticMustan** [comment]
Just to check, you unistalled redirector, and the PMGH extension is version 1.3.1, right?

**Comment by bob486** [comment]
Yes
