### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ILOVEPRODIGY** [Prodigy-Hacking/ProdigyMathGameHacking#424]
***Description***:
Can't vs anyone in prodigy game crashes when i play and i unistall the hack and i still have the problem pls help me

***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
Use the FixPetTeam.js script in hacks/misc

**Comment by ArcerionDev** [comment]
Or use the fix pet team button on cheat menu

**Comment by ILOVEPRODIGY** [comment]
Ok but also I cant use the epics in battle or ue the op armour Sent from Mail for Windows 10 From: ArcerionSent: December 30, 2020 9:04 PMTo: Prodigy-Hacking/ProdigyMathGameHackingCc: ILOVEPRODIGY; AuthorSubject: Re: [Prodigy-Hacking/ProdigyMathGameHacking] [BUG] (#424) Use the FixPetTeam.js script in hacks/misc—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ArcerionDev** [comment]
Join our discord for support, closing this thread
