### ISSUE TITLE
[BUG] cringe

### ISSUE THREAD

**Issue by requestx** [Prodigy-Hacking/ProdigyMathGameHacking#425]
https://52.55.244.247/

**Comment by BoredFishRE** [comment]
excuse me
![berewrwe](https://user-images.githubusercontent.com/49598984/103316145-8dd08400-49f5-11eb-876f-12701bf99b85.PNG)

**Comment by BoredFishRE** [comment]
Deleted for potentially malicious link.

**Comment by PatheticMustan** [comment]
it was prodigy's IP :|

**Comment by ArcerionDev** [comment]
bruh it's literally just prodigy via the ip address

**Comment by ArcerionDev** [comment]
also who tf are you @requestx

**Comment by PatheticMustan** [comment]
divine simp

**Comment by ArcerionDev** [comment]
???

**Comment by PatheticMustan** [comment]
same profile picture, probably taken from divine. a new account, so I assume it's not the real divine, highly unlikely that it's a coincidence
