### ISSUE TITLE
run in command line kek

### ISSUE THREAD

**Issue by joeymalvinni** [Prodigy-Hacking/ProdigyMathGameHacking#426]
COMMAND:

```
ping play.prodigygame.com
````
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaa

**Comment by BoredFishRE** [comment]
wow man you can use windows that's cool

**Comment by ArcerionDev** [comment]
Tbh these issues are just shitposts from skids
