### ISSUE TITLE
there is a problem when i drag it into extensions it says failed to unzip file

### ISSUE THREAD

**Issue by lfmarinescu** [Prodigy-Hacking/ProdigyMathGameHacking#429]
***Description***:
there is a problem when i drag it into extensions it says failed to unzip file

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/63551218/103460779-1d707e00-4ce7-11eb-937f-a0d940b56207.png)

***Additional Errors***:

**Comment by lfmarinescu** [comment]
pls help

**Comment by PatheticMustan** [comment]
try unzipping the file, clicking "load unpacked", and load the unzipped dir
