### ISSUE TITLE
[HR] new mod menu 

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#431]
**Describe the hack in 5 words or less:**

**Have you made sure this hack isn't available yet?* (Yes i have made sure that there is no one for the code Evaluator so if you could make one for that would be so cool thx)**

**Comment by CRobbins0867** [comment]
could you make the wills cheat menu but make it so you can use the codeEvaluator

**Comment by ArcerionDev** [comment]
interesting idea, may look into down the line
