### ISSUE TITLE
[BUG] and another

### ISSUE THREAD

**Issue by lfmarinescu** [Prodigy-Hacking/ProdigyMathGameHacking#432]
***Description***:
it says this

***Replication***:

***Images***:

![image](https://user-images.githubusercontent.com/63551218/103540826-58e68600-4e68-11eb-8d82-aa37984df139.png)

***Additional Errors***:

**Comment by BoredFishRE** [comment]
DO NOT UNZIP THE EXTENSION! You unzipped the extension. this is why you're seeing this.
