### ISSUE TITLE
Hypotnuse Questions don't render properly

### ISSUE THREAD

**Issue by 3r3r3r3r3r3r3r3r3r** [Prodigy-Hacking/ProdigyMathGameHacking#433]
For some reason, it's probably the extension clogging a question when it's related to hypotenuse questions
it is impossible to submit

**Comment by ArcerionDev** [comment]
uhhhh I don't think the extension influences the education API at all, can you give screenshots to show this, exporting your console would be appreciated as well

**Comment by PatheticMustan** [comment]
Please add more information.

**Comment by PatheticMustan** [comment]
Closed until @3r3r3r3r3r3r3r3r3r adds more information
