### ISSUE TITLE
Please name your issues

### ISSUE THREAD

**Issue by BoredFishRE** [Prodigy-Hacking/ProdigyMathGameHacking#435]
Please god name them. It's not helpful for us when it just says [BUG]. Put in your title the issue you're having!

**Comment by ArcerionDev** [comment]
^^

**Comment by NameIsA** [comment]
help me my son would like prodigy hacks how do i do this i will do anything PLS HELP!!!!!!!!!!!!!!!!!!!!!!!!!!!!! [BUG]
