### ISSUE TITLE
Teleport to anybody's house by User ID

### ISSUE THREAD

**Issue by 1739831** [Prodigy-Hacking/ProdigyMathGameHacking#438]
A method to teleport to somebody's house by inputting the user's ID. This would be added into the cheat menu.

**Comment by BoredFishRE** [comment]
please name the issues.

**Comment by PatheticMustan** [comment]
would actually be pretty cool

**Comment by ArcerionDev** [comment]
maybe not a good idea, wouldn't be ethical to people who don't want their house to be entered

**Comment by ArcerionDev** [comment]
because I personally know that it's possible to visit any house regardless of tha

**Comment by ArcerionDev** [comment]
I figured it out a few months ago but i forget how to do it

**Comment by ArcerionDev** [comment]
eh fuck it sure

**Comment by NameIsA** [comment]
> maybe not a good idea, wouldn't be ethical to people who don't want their house to be entered

i did it a few times to harass my friendos

**Comment by NameIsA** [comment]
bump

**Comment by hugo875** [comment]
@PatheticMustan @ArcerionDev @ChickenOnYT this is a old hack request

**Comment by PatheticMustan** [comment]
1. get the user's house information
2. load it into (what seems to be) some temp house loader thing, not sure how it works
3. teleport to house???

**Comment by BETPRODIGYHACKER** [comment]
please do not say bed words

**Comment by BETPRODIGYHACKER** [comment]
*bad*

**Comment by LeoBadeaux** [comment]
> please do not say bed words

Nobody did?

**Comment by hostedposted** [comment]
I will work on this

**Comment by hostedposted** [comment]
When you go to a house the game sends this in the multiplayer socket:
```
42["joinZone","house-170003438"]
```
so if we can send that in the socket we will be able to do this

**Comment by hostedposted** [comment]
Prodigy uses
```js
null !== this.socketInterface && (this.zone = t, this.socketInterface.emitEvent("joinZone", t))
```
to send the requests, I will try to find this.socketInterface.

**Comment by hostedposted** [comment]
![image](https://user-images.githubusercontent.com/70211235/124034755-9ec07900-d9c9-11eb-897f-dc961d02a2a5.png)
I found something else but it teleports you to your house.

**Comment by PatheticMustan** [comment]
looking around in prodigysource, not sure if this will be useful
```
u.a.instance.prodigy.gameContainer.get("32b-57e1").create("house-visit", "click", "hub", n, e, null, null, this.player.userID).broadcast()
```

**Comment by hostedposted** [comment]
> 1. get the user's house information (easily doable)
> 2. load it into (what seems to be) some temp house loader thing, not sure how it works
> 3. teleport to house???

getting the house data is simple. we can use the endpoint here https://prodigy-api.hostedposted.com/getting_player_data_from_userID/, parse it as a json then do ``data[userID].house`` userID being the user id of the house you want to go to.

Then we could explore ``_.instance.prodigy.world`` for a load function.

Then once we load it we might have to send it on the socket or prodigy would of already send it.

When you go to a house prodigy makes the request from this endpoint https://prodigy-api.hostedposted.com/getting_player_data_from_userID/ (they make the field only house but that does not matter) then they probably load it, and the code you showed above does not work for me so I am going to look around some more in prodigysource.

**Comment by hostedposted** [comment]
I added this in https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/d85648aad7446b90e3d3929dded6af00d56e4f40.

**Comment by PatheticMustan** [comment]
> When you go to a house the game sends this in the multiplayer socket:
> ```
> 42["joinZone","house-170003438"]
> ```
> so if we can send that in the socket we will be able to do this

Unless the multiplayer socket sends the house data back right after, I would assume this is just for the server's sake, keeping track of which house you're in

**Comment by hostedposted** [comment]
yes it is but it allows other people on the same world to see you in the house
