### ISSUE TITLE
 question about wills cheat menu

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#439]
How/Can you use the booklet marker to use will cheat menu? if so how do you do it if someone could put it step by step for me in the comments that would be great!

**Comment by PatheticMustan** [comment]
the bookmarklet is no longer supported. Please read [this](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/How-to-install-hacks)
