### ISSUE TITLE
[BUG] game keeps freezing when i chose a epic pet 

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#441]

**Comment by CJRichardson832** [comment]
make a redirict app thats called prodigy hacks dont comment it as redirect just comment it hacks cause my admin blocked redirect

**Comment by ArcerionDev** [comment]
@CRobbins0867 try using FixPetTeam.js in hacks/misc folder. if this doesn't work, reopen this
