### ISSUE TITLE
Issue With the pets  [BUG]

### ISSUE THREAD

**Issue by GabeKJorli** [Prodigy-Hacking/ProdigyMathGameHacking#442]
When ever i try to get a new pet (by clicking Give All Pets) It logs me out after saying "You have been Inactive for too long!" 

See below the problems i am having.

![Screenshot 2021-01-06 at 7 57 49 AM](https://user-images.githubusercontent.com/77057832/103771013-fa024780-4ff4-11eb-9668-6a712a718e8a.png)

**Comment by 3r3r3r3r3r3r3r3r3r** [comment]
? this has happened to someone I know but only in  the pet inventory

**Comment by ArcerionDev** [comment]
please export your console, as shown [here](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/discussions/437), we can take matters form there

**Comment by ProdigyScriptHacker** [comment]
you can press delete pet and delete all crystal monsters they  are bugged

**Comment by PatheticMustan** [comment]
closed until @GabeKJorli submits console logs, sad
