### ISSUE TITLE
Script based Arena point hack errors [BUG]

### ISSUE THREAD

**Issue by hostedposted** [Prodigy-Hacking/ProdigyMathGameHacking#444]
***Description***:  Script based arena point hacks does not update arena points and errors in console.

***Replication***: Use script based arena point hack.

***Images***: <img width="408" alt="error" src="https://user-images.githubusercontent.com/70211235/103906942-98161080-50ce-11eb-82c4-bb3cc14f606a.PNG">

**Comment by BoredFishRE** [comment]
@PatheticMustan Check API leaderboard location. Probably changed.

**Comment by ArcerionDev** [comment]
@BoredFishRE have you forgotten what 429 means

**Comment by ArcerionDev** [comment]
@hostedposted The arena points script is being used too often, there's a rate limit on the server side. Will fix later

**Comment by BoredFishRE** [comment]
oh i am small brain.

**Comment by ArcerionDev** [comment]
^^
