### ISSUE TITLE
[BUG]Starting a rune run fails 

### ISSUE THREAD

**Issue by ItsStartx** [Prodigy-Hacking/ProdigyMathGameHacking#445]
***Description***:
An error appears that the rune run saying that there was an error starting my rune run.

***Replication***:
Attempt to start a rune run in Harmony Island. Choose someone and start.

***Images***:

![Screen Shot 2021-01-07 at 10 24 58 AM](https://user-images.githubusercontent.com/74609532/103916050-f8f71600-50d9-11eb-9e4e-c538651f92e9.png)

***Additional Errors***:
None

**Comment by BoredFishRE** [comment]
Hi! Could you try disabling the extension and try it again? Prodigy just released an update and we wanna know if that breaks anything.

**Comment by PatheticMustan** [comment]
I'll look into it

**Comment by ItsStartx** [comment]
> Hi! Could you try disabling the extension and try it again? Prodigy just released an update and we wanna know if that breaks anything.

I have tried disabling it, but it still returns the same error.
![Screen Shot 2021-01-08 at 8 30 42 AM](https://user-images.githubusercontent.com/74609532/104020934-f228db80-518b-11eb-8ce6-8860ea46f466.png)

**Comment by ArcerionDev** [comment]
this is an odd issue, will look into more

**Comment by ProdigyScriptHacker** [comment]
Hey @ArcerionDev why havent you released arena points site yet its confusing

**Comment by PatheticMustan** [comment]
> Hey @ArcerionDev why havent you released arena points site yet its confusing

currently arena points is down... we'll fix it shortly!

**Comment by ArcerionDev** [comment]
> Hey @ArcerionDev why havent you released arena points site yet its confusing

asdfghj I'm fixing it

**Comment by ItsStartx** [comment]
> this is an odd issue, will look into more

It may be an issue on prodigy's behalf, maybe they've added something that just breaks my account or something

**Comment by ArcerionDev** [comment]
> > this is an odd issue, will look into more
> 
> It may be an issue on prodigy's behalf, maybe they've added something that just breaks my account or something

no, this is a widespread issue on the discord + github

**Comment by 3r3r3r3r3r3r3r3r3r** [comment]
prodigy probably made that island hacker proof

**Comment by PatheticMustan** [comment]
> prodigy probably made that island hacker proof

no, we just really don't want to update it

**Comment by ItsStartx** [comment]
I’ve read the wiki (although I don’t know how reliable it is) that people that have used hacks on their account are exempt from starting a rune run.

**Comment by NameIsA** [comment]
> I’ve read the wiki (although I don’t know how reliable it is) that people that have used hacks on their account are exempt from starting a rune run.

who tf wrote that... make an account and remove it, that's disinformation.

**Comment by NameIsA** [comment]
disclaimer: i am a prodigy math game wiki moderator

----

the wiki is usually reliable, but it can have false info if some random idiots decide to write things. when in doubt, just contact a wiki mod/admin and they'll try to verify if anything is reliable :-)

**Comment by spacekitten45** [comment]
remove your hacked pets and use fix battle hacks

**Comment by TheSchmede** [comment]
> remove your hacked pets and use fix battle hacks

That does not work.

**Comment by TheSchmede** [comment]
Also this is also a problem when I have the hack uninstalled.

**Comment by PatheticMustan** [comment]
this is why you're only supposed to use hacks on alts

**Comment by TheSchmede** [comment]
On alts? What does alts mean.

**Comment by ChickenOnYT** [comment]
alternate accounts so basically accounts you dont need you could find the ones i use by going to my yt vids i've leaked a bunch of passwords to accounts i dont use

**Comment by ChickenOnYT** [comment]
will be someday but it's not really top priority because people need to learn to not use these hacks on their  main accounts and we have a lot of more serious issues rn

**Comment by ChickenOnYT** [comment]
harmony island is 2.2.0

**Comment by ArcerionDev** [comment]
mf

**Comment by LeoBadeaux** [comment]
You have to leave a new comment for it to count as more activity or it closes after 7 weeks of commenting

**Comment by ArcerionDev** [comment]
duplicate

**Comment by HackProidgy** [comment]
I need help, I used the extension of Prodigy Hacking because the Rune Run won't work when I try to do it. I found that when I use my pets that is all in level 100 It does not seem to work is this a regular issue or do I need to fix I if I do, how?
