### ISSUE TITLE
[BUG] Prodigy wont load

### ISSUE THREAD

**Issue by kinghacker50** [Prodigy-Hacking/ProdigyMathGameHacking#447]
Prodigy will not load 
with the menu on worked yesterday

![Screenshot 2021-01-08 at 11 35 36 AM](https://user-images.githubusercontent.com/77164846/104040481-b13dc080-51a5-11eb-8730-b5f22b7c6135.png)

**Comment by kinghacker50** [comment]
![Screenshot 2021-01-08 at 11 38 08 AM](https://user-images.githubusercontent.com/77164846/104040783-15f91b00-51a6-11eb-9167-acff5d844a1e.png)

**Comment by hostedposted** [comment]
The server is not currently working.
<img width="858" src="https://user-images.githubusercontent.com/70211235/104055131-37650180-51bc-11eb-9287-d13ee88c09a2.PNG">

**Comment by kinghacker50** [comment]
ok man thanks for the response i should join the discord

**Comment by hostedposted** [comment]
anytime, could you close the issue?
