### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by Bjmoney67** [Prodigy-Hacking/ProdigyMathGameHacking#448]
I looked in the code for this and saw that this actually collects your prodigy game data such as usernames, passwords and other game data if your looking for proof read this line of code.
 import { getBigData, updateUser, getGameData } from "../utils/api";
(async () => {
	const gameData = await getGameData();

**Comment by CRobbins0867** [comment]
wait what!!!

**Comment by PatheticMustan** [comment]
uh...? Where...?

**Comment by ArcerionDev** [comment]
> I looked in the code for this and saw that this actually collects your prodigy game data such as usernames, passwords and other game data if your looking for proof read this line of code.
> import { getBigData, updateUser, getGameData } from "../utils/api";
> (async () => {
> const gameData = await getGameData();

yes, we temporarily use your data to get a special access token that allows us to use hacks on your account. We need your login to do this. Don't worry, we don't store the login info and we *won't* sell it on the dark web. 
Hope this clears up any issues

**Comment by PatheticMustan** [comment]
still can't find where this code is used, but the only areas that I can think of that might use your token:
- script based hacks, this obviously needs your token
- tokenify, which literally gives you your auth token given a username/password
- arena points hacks, which definitely needs your token

As Arc said, we never send or share your data. We try our best to be transparent and clear, so if you need clarification on why we need certain things, or what a script does, you can just ask us

**Comment by SwxtchCode** [comment]
1.) you can no longer obtain someone's username/password via js, prodigy did something yay
2.) i am a shitty coderman and i dont see any proof of the data being sent annywhere
3.) it obviously has to use your token like mustardman says

**Comment by PatheticMustan** [comment]
"mustardman" yeah alright ;-;

**Comment by ArcerionDev** [comment]
> 1.) you can no longer obtain someone's username/password via js, prodigy did something yay
> 2.) i am a shitty coderman and i dont see any proof of the data being sent annywhere
> 3.) it obviously has to use your token like mustardman says

why am I mustardman

**Comment by ArcerionDev** [comment]
or is mustan mustardman

**Comment by NameIsA** [comment]
> or is mustan mustardman

mustan is mustardman
