### ISSUE TITLE
teleport [BUG]

### ISSUE THREAD

**Issue by prodigylover** [Prodigy-Hacking/ProdigyMathGameHacking#450]
The teleport hack will not work for me at all on the cheat menu please fix it

**Comment by imdivesmaintank** [comment]
can confirm this does not work

**Comment by monicawink** [comment]
I also confirm this is not working for me either.

**Comment by PatheticMustan** [comment]
Oops, sorry about this

**Comment by prodigylover** [comment]
its ok thanks though

**Comment by PatheticMustan** [comment]
`243521fe5dfaa57364db448a3897af248bf2363f`
