### ISSUE TITLE
Membership issue

### ISSUE THREAD

**Issue by SiIver-L** [Prodigy-Hacking/ProdigyMathGameHacking#451]
I'm trying to get my friend premium (he is on iPad), so I go on his account and it says he has membership now, but when he goes on it on his iPad the membership items are there but the actual subscription isn't there. I was wondering if there was a way to fix this or does he have to have the extension also.

**Comment by BoredFishRE** [comment]
Hi! The membership hack only works if the extension is actively running. Our hacks do not support mobile, and permanent Membership is not possible due to A. Legal issues and B. It's not easy to do.

**Comment by NameIsA** [comment]
> I'm trying to get my friend premium (he is on iPad), so I go on his account and it says he has membership now, but when he goes on it on his iPad the membership items are there but the actual subscription isn't there. I was wondering if there was a way to fix this or does he have to have the extension also.

If you'd like mobile hacks, you can use https://nameisa.github.io/MobileDevice-ProdigyHacking/ - membership hacks are (sadly) impossible.
