### ISSUE TITLE
[BUG] Prodigy cannot load while using Will's Cheat Menu

### ISSUE THREAD

**Issue by coldedgrenade** [Prodigy-Hacking/ProdigyMathGameHacking#454]
***Description***:
While loading into prodigy, with my hacks, it seemed it couldn't load.
I checked the console, and it seems like there's a failed request.
If I remove the extension, then it's perfectly fine.

***Images***:
![bugs](https://user-images.githubusercontent.com/77497008/104738114-1a2bb800-5713-11eb-8c6c-1047b15acd5f.PNG)

**Comment by PatheticMustan** [comment]
sorry, it should be fixed shortly...

https://www.cloudflarestatus.com/

cloudflare is having some problems, so it's not just us
![image](https://user-images.githubusercontent.com/35382971/104739782-244eb600-5715-11eb-911e-b5706435a278.png)

**Comment by coldedgrenade** [comment]
Oh sorry for that

**Comment by PatheticMustan** [comment]
Should be fixed
