### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NameIsA** [Prodigy-Hacking/ProdigyMathGameHacking#456]
![__opt__aboutcom__coeus__resources__content_migration__mnn__images__2017__05__lady-bug-on-leaf-e3cd36cdc3024129b61926ddf6ef386e](https://user-images.githubusercontent.com/61570792/104960223-a7c40d80-5988-11eb-8ba5-d1b5bf208e96.jpg)

**Comment by NameIsA** [comment]
ok sorry i just really wanted to do this

**Comment by ArcerionDev** [comment]
LMAO
