### ISSUE TITLE
DOS issue

### ISSUE THREAD

**Issue by Aurora270** [Prodigy-Hacking/ProdigyMathGameHacking#457]
***Description***:When i try to log into prodigy, it doesn't load. It just stays stuck halfway. When I remove the extension its working fine.

***Images***:
![Annotation 2021-01-19 090234](https://user-images.githubusercontent.com/77679065/105044934-502fab80-5a35-11eb-8202-5c26b465e744.png)

**Comment by ArcerionDev** [comment]
@PatheticMustan @BoredFishRE pls check if prodigyhacking.ml is up correctly

**Comment by BoredFishRE** [comment]
gimme a sec

**Comment by ArcerionDev** [comment]
because I thought that was a cloudflare issue, but it should be fixed by now

**Comment by BoredFishRE** [comment]
Nope it's not. Please go to discord DMs we have a problem.

**Comment by PatheticMustan** [comment]
Heck, maybe the gcloud vps is bad...

**Comment by ArcerionDev** [comment]
in school

**Comment by BoredFishRE** [comment]
not the gcloud, this is the one we pay for

**Comment by PatheticMustan** [comment]
Same unfortunately, this will probably have to wait until after.

**Comment by BoredFishRE** [comment]
someone's trying to bruteforce it so it's really slow rn

**Comment by ArcerionDev** [comment]
> Heck, maybe the gcloud vps is bad...

not gcloud this is prodigyhacking.com

**Comment by ArcerionDev** [comment]
oh I forgot

**Comment by ArcerionDev** [comment]
extension is pointing to prodigyhacking.ml, our vps is prodigyhacking.com

**Comment by BoredFishRE** [comment]
prodigyhacking.ml should be back up

**Comment by BoredFishRE** [comment]
prodigyhacking.ml is proxied to the VPS

**Comment by PatheticMustan** [comment]
> someone's trying to bruteforce it so it's really slow rn

So uhhhh, is it possible to block em or something

**Comment by ArcerionDev** [comment]
> prodigyhacking.ml is proxied to the VPS

oh

**Comment by BoredFishRE** [comment]
nope it's all diff IPs

**Comment by PatheticMustan** [comment]
> nope it's all diff IPs

Depression, maybe we should change the ssh port..?

**Comment by BoredFishRE** [comment]
rn the VPS is getting slammed to the max

**Comment by BoredFishRE** [comment]
> 
> 
> > nope it's all diff IPs
> 
> Depression, maybe we should change the ssh port..?

i'll try, idk if hostinger will let me

**Comment by ArcerionDev** [comment]
you can't proxy it, we need whimpers' vps back

**Comment by ArcerionDev** [comment]
or update the address

**Comment by PatheticMustan** [comment]
Bruhhhhhh blame hostinger

**Comment by BoredFishRE** [comment]
It's back up rn but I need to contact hostinger rn because this is really bad

**Comment by PatheticMustan** [comment]
Are you sure they're trying to DOS the ssh port, or is it a different port..?

**Comment by BoredFishRE** [comment]
fail2ban is at max rn and sshd is at max so I'm guessing they're targeting it

**Comment by PatheticMustan** [comment]
RETRACE THE ROUTE THROUGH THE VPN MAINFRAME THEN HACK INTO THEIR PROXYPASS PACKETS XDXDXD HAXXERMANS

**Comment by BoredFishRE** [comment]
I can send ya'll the audit.log

**Comment by PatheticMustan** [comment]
this is such a pain, maybe we shouldn't have hosted the website and prodigyhacking.ml on the same thing....

**Comment by ArcerionDev** [comment]
> RETRACE THE ROUTE THROUGH THE VPN MAINFRAME THEN HACK INTO THEIR PROXYPASS PACKETS XDXDXD HAXXERMANS

you sound like dck

**Comment by BoredFishRE** [comment]
No, someone's bruteforcing the ssh port

**Comment by PatheticMustan** [comment]
Is it possible to move the website to a not-vps thing maybe possibly

**Comment by ArcerionDev** [comment]
> Is it possible to move the website to a not-vps thing maybe possibly

uhhhhh we could use github pages

**Comment by BoredFishRE** [comment]
nope

**Comment by PatheticMustan** [comment]
> > RETRACE THE ROUTE THROUGH THE VPN MAINFRAME THEN HACK INTO THEIR PROXYPASS PACKETS XDXDXD HAXXERMANS
> 
> you sound like dck

I *am* secretly dck

> No, someone's bruteforcing the ssh port

Dam

**Comment by BoredFishRE** [comment]
bootstrap really doesn't like github pages

**Comment by ArcerionDev** [comment]
> bootstrap really doesn't like github pages

*cough cough my website cough*

**Comment by PatheticMustan** [comment]
Next.js looks nice...?

**Comment by ArcerionDev** [comment]
you don't need to use jekyll or whatever

**Comment by ArcerionDev** [comment]
I'll set it up later

**Comment by ArcerionDev** [comment]
@BoredFishRE so *can* you trace the ip

**Comment by BoredFishRE** [comment]
everything's working rn. the website's working and is like taking up no processes

**Comment by BoredFishRE** [comment]
> 
> 
> @BoredFishRE so _can_ you trace the ip

i just did a whois lol

**Comment by PatheticMustan** [comment]
Jekyll heckll, dos'ing makes me feel sad

maybe we can idk add a whitelist or something

**Comment by ArcerionDev** [comment]
> > @BoredFishRE so _can_ you trace the ip
> 
> i just did a whois lol

alright, can you block the ip

**Comment by PatheticMustan** [comment]
I thought it was many IPs together..?

**Comment by ArcerionDev** [comment]
> I thought it was many IPs together..?

@BoredFishRE is it???

**Comment by ArcerionDev** [comment]
could this be like some minor botnet or sum

**Comment by BoredFishRE** [comment]
many diff IPs

**Comment by ArcerionDev** [comment]
> many diff IPs

greeat

**Comment by PatheticMustan** [comment]
istg if it's DCK i'mma be so mad

**Comment by ArcerionDev** [comment]
I'll ask him @PatheticMustan

**Comment by BoredFishRE** [comment]
> 
> 
> could this be like some minor botnet or sum
I don't think 492 blocked IPs for fail2ban is minor

**Comment by ArcerionDev** [comment]
![image](https://user-images.githubusercontent.com/60945964/105051546-dc919c80-5a3c-11eb-9700-945422d02ad6.png)
perfect

**Comment by BoredFishRE** [comment]
and 3377 failed attempts

**Comment by ArcerionDev** [comment]
> and 3377 failed attempts

how many successful

**Comment by ArcerionDev** [comment]
it could be a ip header spoof

**Comment by PatheticMustan** [comment]
@BoredFishRE it might be just a rando, we should change the ssh port

**Comment by ArcerionDev** [comment]
idk that x-forwarded-for thing does work

**Comment by ArcerionDev** [comment]
> @BoredFishRE it might be just a rando, we should change the ssh port

@BoredFishRE did you say you got a whois

**Comment by PatheticMustan** [comment]
https://securitytrails.com/blog/mitigating-ssh-based-attacks-top-15-best-security-practices

???

**Comment by BoredFishRE** [comment]
I'm trying to change it. Idk what is going on, have to contact hostinger to get it changed. Idk if it can be changed

**Comment by ArcerionDev** [comment]
it appears this issue is fixed, @Aurora270 please confirm
