### ISSUE TITLE
[BUG]Teleport Not Working

### ISSUE THREAD

**Issue by Aurora270** [Prodigy-Hacking/ProdigyMathGameHacking#460]
***Description***: When I try to use the teleport and I click it, nothing happens.

***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
who is fixing this

**Comment by ArcerionDev** [comment]
we know the issue, it's a simple fix

**Comment by ArcerionDev** [comment]
we'll do it soon

**Comment by PatheticMustan** [comment]
> we know the issue, it's a simple fix

bros can somebody other than Will and I do this

**Comment by UntrustableRus** [comment]
why was I and literally everybody else assigned

**Comment by PatheticMustan** [comment]
typescript makes me cry

**Comment by UntrustableRus** [comment]
> typescript makes me cry

same, I'm only a js dev so that's why I never work on the hack because it makes 0 sense
