### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ishanb200** [Prodigy-Hacking/ProdigyMathGameHacking#465]
i was logging in and the prodigy loading menu was not loading.  after a while i removed the extension and i think the hacks are patched

***Replication***:

***Images***:

***Additional Errors***:

**Comment by NX721** [comment]
Same prodigy isn't loading.

**Comment by NX721** [comment]
Actully I just restarted my computer and it loaded with the extension.

**Comment by PatheticMustan** [comment]
will do
