### ISSUE TITLE
[BUG] Outdated Spells on Spell Editor

### ISSUE THREAD

**Issue by The-Anonymous-Chicken** [Prodigy-Hacking/ProdigyMathGameHacking#467]
***Description***
Spells like Royal Roar (and maybe others?)
are outdated. For example: Royal Roar is an outdated spell, but can be updated.
I think it might be the only one that even **can** be fixed

***Replication***:
maybe fix spell ID

***Images***:

***Additional Errors***:
¯\_(⊙_ʖ⊙)_/¯

**Comment by PatheticMustan** [comment]
Needs more information, not sure what "outdated spell" means ;-;

**Comment by PatheticMustan** [comment]
Bump, @The-Anonymous-Chicken, what do you mean by "outdated spell"

**Comment by PatheticMustan** [comment]
closed due to no response

**Comment by ChickenOnYT** [comment]
i think the spells dont work or something is what they mean

**Comment by PatheticMustan** [comment]
but which ones

**Comment by ChickenOnYT** [comment]
royal roar "and maybe others"

**Comment by The-Anonymous-Chicken** [comment]
I think ones that were removed from the game, like zero, batter up, etc.

**Comment by ArcerionDev** [comment]
Prodigy takes out all the spells from being obtainable normally, but they're too lazy to take it out of the actual data, so that's why they show up :p
