### ISSUE TITLE
[BUG]Prodigy not loading again

### ISSUE THREAD

**Issue by Aurora270** [Prodigy-Hacking/ProdigyMathGameHacking#473]
***Description***:Prodigy is stuck loading halfway again.

***Replication***:

***Images***:
![Annotation 2021-01-25 215533](https://user-images.githubusercontent.com/77679065/105794104-51426a80-5f58-11eb-9b42-cdac2c90e086.png)

***Additional Questions***: Is it the same problem as the last time it happened?

**Comment by PatheticMustan** [comment]
#468, we're currently facing problems with our VPS, please be patient...
I'll try to fix it as soon as possible, but this might require us to spend some money

**Comment by PatheticMustan** [comment]
eughhhhhhhhhhhh
maybe we should dist redirector as a binary

**Comment by PatheticMustan** [comment]
fixed
