### ISSUE TITLE
[BUG] Whole screen freezes when trying battle/Unable to battle

### ISSUE THREAD

**Issue by KingPuyoy** [Prodigy-Hacking/ProdigyMathGameHacking#474]
The whole screen freezes when trying battle someone or thing. Can someone explain, or try to help? Thanks.

**Comment by KingPuyoy** [comment]
I'm new to this, but reading other replies, I feel like @ArcerionDev might help.

**Comment by ArcerionDev** [comment]
you called

**Comment by ArcerionDev** [comment]
oh

**Comment by ArcerionDev** [comment]
run the script here:
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/hacks/misc/fixPetTeam.js
in console.
you can open console by using ctrl + shift + j on windows and chromebook, ctrl option j on mac
(make sure you aren't on a school computer when doing this)

**Comment by KingPuyoy** [comment]
Thanks

**Comment by Andrew1644563** [comment]
@ArcerionDev I'm still having this issue, I try to battle with this monster, it just freezes here.
![image](https://user-images.githubusercontent.com/72873557/107229464-dcf1d780-69eb-11eb-92fc-99eda456def1.png)
And when I try to open the console, this shows. 
![image](https://user-images.githubusercontent.com/72873557/107229547-f4c95b80-69eb-11eb-8a15-8a8a3d4e8fa9.png)
Please advise what I should do next.

**Comment by PatheticMustan** [comment]
Oops
