### ISSUE TITLE
Remove this thing that Prodigy added to banish script kiddies?

### ISSUE THREAD

**Issue by NameIsA** [Prodigy-Hacking/ProdigyMathGameHacking#489]
**Is your feature request related to a problem? Please describe.**
I'm assuming that Prodigy succesfuly scared away 10 skids with this:
`This is a browser feature for developers only.  If someone told you to copy-paste something here, it is a scam and may provide others with access to your account and/or your computer.  This may result in your account being deleted and/or you may be banned from Prodigy.`

**Describe the solution you'd like**
Remove it lmao

**Describe alternatives you've considered**
idk

**Additional context**
noot ate my foreskin

**Comment by PatheticMustan** [comment]
no, I think it's fine to leave it as is. It's a good warning, I guess

**Comment by NameIsA** [comment]
> no, I think it's fine to leave it as is. It's a good warning, I guess
> 
> thanks for the suggestion tho

mk

**Comment by ArcerionDev** [comment]
***Banish the script kiddies***
