### ISSUE TITLE
detecting broken pets

### ISSUE THREAD

**Issue by ConnorAhern** [Prodigy-Hacking/ProdigyMathGameHacking#491]
title

**Comment by UntrustableRus** [comment]
#2 has been implemented kinda sorta, and a lot of the support questions are at the user's fault, like an incorrect installation, still using the redirector method, etc. Not so sure about the pets thing, I don't program the cheat menu, so we'll wait for somebody else to reply about that.

**Comment by PatheticMustan** [comment]
I've kinda added an auto-updater starting in 2.0.0, if Redirector detects an outdated extension, it'll just make an alert.

**Comment by ArcerionDev** [comment]
I was personally thinking that we should probably fix a large amount of these, especially #1, we should def detect broken inventories, or at least run the fixBattleCrash script on an interval

**Comment by ChickenOnYT** [comment]
bump

**Comment by PatheticMustan** [comment]
Related to #318

**Comment by UntrustableRus** [comment]
This needs to be worked on, so we can meet the 2.1.0 milestone in time.

**Comment by ArcerionDev** [comment]
ok so there is no true way to detect if they're broken or not, I've found out that much.
I'm going to kill 2 birds with one stone by removing `Edit Pet`, because it really isn't necessary, and doesn't work anyway.
After removing it, we can run assignRandomSpells on an interval.

**Comment by ChickenOnYT** [comment]
bruh it might be possible

**Comment by ChickenOnYT** [comment]
we look at the spells and check if any pets have a spell that isnt there

**Comment by PatheticMustan** [comment]
:| arc... there's a solution

**Comment by UntrustableRus** [comment]
Why was this closed? Honestly seems very possible.

**Comment by NX721** [comment]
...
