### ISSUE TITLE
[BUG] The loading screen is stuck. Is this patched?

### ISSUE THREAD

**Issue by HATNAME101** [Prodigy-Hacking/ProdigyMathGameHacking#495]

**Comment by HATNAME101** [comment]
Please respond as soon as you can. Thank you!

**Comment by HATNAME101** [comment]
![Screenshot 2021-02-03 at 6 07 27 PM](https://user-images.githubusercontent.com/78508227/106821232-be39bc80-664a-11eb-9ecb-f1dcfb58b873.png)

**Comment by HATNAME101** [comment]
![Screenshot 2021-02-03 at 6 08 37 PM](https://user-images.githubusercontent.com/78508227/106821302-e2959900-664a-11eb-9570-93756a2c9af3.png)

**Comment by PatheticMustan** [comment]
@BoredFishRE @ArcerionDev, I have no idea if there are legitimately broken hacks or skids are just not installing it properly. Please investigate..

**Comment by BoredFishRE** [comment]
Not sure, lemme check redirector

**Comment by HATNAME101** [comment]
Is it not working?

**Comment by BoredFishRE** [comment]
it should be working, try it again @HATNAME101

**Comment by HATNAME101** [comment]
ok thanks

**Comment by HATNAME101** [comment]
its still stuck what is going on @BoredFishRE

**Comment by BoredFishRE** [comment]
can you visit https://prodigyhacking.ml

**Comment by KingPuyoy** [comment]
I just visit the console and somehow the freezed loading screen just works. This works, or I'm dumb and it only works for me. Try it.

**Comment by BoredFishRE** [comment]
Have you installed the extension?

**Comment by BoredFishRE** [comment]
oh nevermind, disregard the last post. Didn't read your comment right

**Comment by elikiller** [comment]
Does anyone know what browser I use on iOS for the bookmarklet to work?

**Comment by BoredFishRE** [comment]
Hacks are not supported on mobile, and we no longer really support bookmarklets.

**Comment by HATNAME101** [comment]
maybe my ignore frames is not working

**Comment by AnisopteraN** [comment]
I have the same issue, the loading screen is frozen.

**Comment by elikiller** [comment]
Awwww :(
