### ISSUE TITLE
[BUG] Everyone is member...

### ISSUE THREAD

**Issue by KingPuyoy** [Prodigy-Hacking/ProdigyMathGameHacking#499]
***Description***: It looks like everyone is member, although for some of the players, they seem to not be members. Every time I log in, it says I just recently got member, and it gives me the fluffy cloud. I never bought anything off Prodigy so it makes no sense. Is this normal, or can you fix it? Thanks.

***Images***:

<img width="2560" alt="Screen Shot 2021-02-04 at 8 54 24 AM" src="https://user-images.githubusercontent.com/78117783/106927096-adc72780-66c6-11eb-9096-6fab04451a74.png">

**Comment by KingPuyoy** [comment]
@PatheticMustan @ArcerionDev

**Comment by PatheticMustan** [comment]
Member hacks come automatically with the hacks...
