### ISSUE TITLE
[BUG] Battle screen freezes upon contact with monster

### ISSUE THREAD

**Issue by Andrew1644563** [Prodigy-Hacking/ProdigyMathGameHacking#503]
@ArcerionDev @PatheticMustan @BoredFishRE I'm still having this issue, I try to battle with this monster, it just freezes here.
![image](https://user-images.githubusercontent.com/72873557/107230203-bda77a00-69ec-11eb-94fc-33f220c3f94a.png)
And when I try to open the console, this shows.
![image](https://user-images.githubusercontent.com/72873557/107230163-b41e1200-69ec-11eb-9eda-3038e026775f.png)
Please advise what I should do next.

**Comment by BoredFishRE** [comment]
Use fix battle crash for gods sake

**Comment by PatheticMustan** [comment]
How do we make this more obvious? 
"Ohhh the battle is crashing", so we made a button that said "Fix Battle Crash"...???
Am I missing parts of my brain? How are people still missing this???

**Comment by alvzboys2** [comment]
give me your username and pass let me see what i can do

**Comment by BoredFishRE** [comment]
NO

**Comment by alvzboys2** [comment]
why not i n these stuff

**Comment by BoredFishRE** [comment]
DO NOT GIVE ANYONE YOUR USERNAME AND PASSWORD

**Comment by alvzboys2** [comment]
i gave one of the hackers my acc

**Comment by BoredFishRE** [comment]
gave who

**Comment by alvzboys2** [comment]
him Mustan Pathetic

**Comment by BoredFishRE** [comment]
@PatheticMustan did you ask for his info?

**Comment by alvzboys2** [comment]
here is my acc eduardoa886 pass is 1902723

**Comment by BoredFishRE** [comment]
please don't post personal info like that

**Comment by BoredFishRE** [comment]
easiest way to get your acc stolen

**Comment by alvzboys2** [comment]
who

**Comment by BoredFishRE** [comment]
you

**Comment by alvzboys2** [comment]
oh

**Comment by alvzboys2** [comment]
i dont cear i dnt play prodigy that much any more

**Comment by BoredFishRE** [comment]
doesn't really matter

**Comment by alvzboys2** [comment]
no i just want mem but never got it so no

**Comment by alvzboys2** [comment]
bored can you make an acc that has mem and all plzzz forme

**Comment by alvzboys2** [comment]
boredfishre

**Comment by alvzboys2** [comment]
???????

**Comment by alvzboys2** [comment]
oh

**Comment by BoredFishRE** [comment]
i'm locking this, it's useless. don't make a new issue over accs like that.

**Comment by PatheticMustan** [comment]
Absolute clowns
