### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AnisopteraN** [Prodigy-Hacking/ProdigyMathGameHacking#504]
***Description***: Loading screen is stuck, I don't know why.

***Replication***:

***Images***:
<img width="734" alt="Screen Shot 2021-02-08 at 3 18 03 PM" src="https://user-images.githubusercontent.com/78763184/107282739-02e59f00-6a21-11eb-9e20-042cd82ca9a0.png">

***Additional Errors***:

**Comment by CRobbins0867** [comment]
@AnisopteraN how long did you wait for it to load??

**Comment by AnisopteraN** [comment]
I've been waiting about 5 minutes, maybe.

**Comment by AnisopteraN** [comment]
The page is still open.

**Comment by CRobbins0867** [comment]
@AnisopteraN for me if its stuck i will reload and log back in wait about 5-7 mins and if it does still not work try one more time if  that does not work let me know

**Comment by AnisopteraN** [comment]
I've done that. This is my 2nd reload.

**Comment by CRobbins0867** [comment]
oh did you already hack your account if so uninstall the extension until its fixed it happens to other people to

**Comment by AnisopteraN** [comment]
Oh. Do you know when it'll be fixed?

**Comment by CRobbins0867** [comment]
probably within today-next week, this is off topic also i have been recruiting for a friend group so if you want to join just tell me on this issue

**Comment by CRobbins0867** [comment]
if you are on there discord that's where they put when stuff is fixed and stuff like that

**Comment by PatheticMustan** [comment]
ah, @AnisopteraN, can you try again?

**Comment by PatheticMustan** [comment]
no response, closed until more information is acquired
