### ISSUE TITLE
applying for computer support

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#505]
if there's space I want to apply for computer support i am already helping people on this github repository and also am on your discord server (also has past experience in customer support) so if you need more customer support (on here or on discord OR both) get back to me as soon as possible!

P.S there was a user just a few mins ago that had a question about the hacks and told tried to elp them the best i can (also i told them to go on the discord becuase thats where you guys put pretty much all the announcements about the hacks and pretty much everything else!

hope i'm a good enough person for the job.

Thanks for your time,

CRobbins08677

**Comment by CRobbins0867** [comment]
@PatheticMustan if you could review my application for customer service that would be great thanks!

**Comment by alvzboys2** [comment]
i need a free acc with mem plzzzzzz
________________________________

**Comment by CRobbins0867** [comment]
also sorry for pinging

**Comment by CRobbins0867** [comment]
@alvzboys2 sorry but from what i know the members at ProdigyMathGameHacking are not allow to modify or create accoutns for other people, if this has changed let me know and then i will think about it!

**Comment by alvzboys2** [comment]
ok thanks for bieng so nice
________________________________

**Comment by CRobbins0867** [comment]
no problem just make sure not to ask everyone about a account i can tell you how to get the mod menu tho, if you want!

**Comment by alvzboys2** [comment]
yes plzzz
________________________________

**Comment by CRobbins0867** [comment]
okay so you know where you see the issue and all the other tabs on the main page?

**Comment by alvzboys2** [comment]
no i dont konw
________________________________

**Comment by CRobbins0867** [comment]
actually just click this link and it will tell you how to install the mod-menu 

https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/How-to-install-hacks

**Comment by CRobbins0867** [comment]
okay?

**Comment by CRobbins0867** [comment]
tell me if you have any further questions

**Comment by alvzboys2** [comment]
nvm i will do when i get home ok im in school
________________________________

**Comment by alvzboys2** [comment]
no im good thanks
________________________________

**Comment by CRobbins0867** [comment]
okay

**Comment by CRobbins0867** [comment]
can a mod or someone check my application for computer support?

**Comment by BoredFishRE** [comment]
Excuse me what? You have legit helped one person. We don't need customer support people like that.

**Comment by PatheticMustan** [comment]
ya don't need to be that harsh, ya know ya know ;)
