### ISSUE TITLE
[HR] Bypass Monster Hack

### ISSUE THREAD

**Issue by Andrew1644563** [Prodigy-Hacking/ProdigyMathGameHacking#507]
Could you guys make a hack that bypasses monsters when trying to do quests? They can be very annoying.

I don't exactly know if there is already a hack for this.

**Comment by NX721** [comment]
THERE IS PRESS CTRL SHIFT I IN PRODIGY THEN TYPE THIS:`_.constants.constants["GameConstants.Debug.SCALE_ENCOUNTER_DISTANCE"] = 0;
` Note: Reloading Prodigy Disables this.

**Comment by NX721** [comment]
Can someone close this?

**Comment by NX721** [comment]
@Andrew1644563

**Comment by NX721** [comment]
Thx And also thats the hack

**Comment by Andrew1644563** [comment]
@NX721 There is a problem. Whenever I open the console, the prodigy page becomes a error 404. What should I do?

**Comment by NX721** [comment]
So first copy this URL`javascript:console.log=console.clear=console.dir=_=>{}` 
Then bookmark a new tab then right click and press "edit" and paste the URL into the URL section then if you want to open inspect, click on the bookmark u just made then open console with no stupid error 404

**Comment by Andrew1644563** [comment]
THANKS SO MUCH MAN!

**Comment by NX721** [comment]
No Problem

**Comment by Andrew1644563** [comment]
Still another issue. Hmm. See my photo. I put it in the console, and then this showed: 
![image](https://user-images.githubusercontent.com/72873557/107413830-3850c200-6adf-11eb-9511-562bb35b3889.png)

**Comment by NX721** [comment]
Download the hack first.

**Comment by NX721** [comment]
click on the symbol on the main page

**Comment by Andrew1644563** [comment]
What do you mean?

**Comment by Andrew1644563** [comment]
Download?

**Comment by Andrew1644563** [comment]
How should I download the hack, and which symbol.

**Comment by NX721** [comment]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/How-to-install-hacks

**Comment by Andrew1644563** [comment]
You want me to download the google chrome extension?

**Comment by Andrew1644563** [comment]
But what does that have to do with the code you gave me earlier to put in the console?

**Comment by NX721** [comment]
Do it then open inspect paste the code and no more monster battles!

**Comment by Andrew1644563** [comment]
Oh, I will try it,

**Comment by NX721** [comment]
Ok

**Comment by NX721** [comment]
Did it work?

**Comment by PatheticMustan** [comment]
thanks, @NX721.

**Comment by PatheticMustan** [comment]
![image](https://user-images.githubusercontent.com/35382971/107422638-46a3db80-6ae9-11eb-96ac-c9f6002c9a8e.png)
the hack should work....

**Comment by NX721** [comment]
> thanks, @NX721.

No Problem yeah the hack works I tested the ones in the hack folder

**Comment by Andrew1644563** [comment]
@NX721 I have a question. Is there a way to do any of this by not having the extension? I do have it though on my other computer.

**Comment by NX721** [comment]
Well if you have the extension on another computer, enter Prodigy, open console and put the script in. The no monster battle dosen't work on Crystal Caverns or Harmony Island Though.

**Comment by PatheticMustan** [comment]
> @NX721 I have a question. Is there a way to do any of this by not having the extension? I do have it though on my other computer.

No

**Comment by Andrew1644563** [comment]
Alright, thank you.

**Comment by UntrustableRus** [comment]
@PatheticMustan Thinking we could add that script to WCM as a button?
`_.constants.constants["GameConstants.Debug.SCALE_ENCOUNTER_DISTANCE"] = 0; `

**Comment by Andrew1644563** [comment]
@UntrustableRus I agree, it is easier to access it through there, but if it is to hard to add then that's also fine. I like spending time copying and pasting things around.

**Comment by NX721** [comment]
> @PatheticMustan Thinking we could add that script to WCM as a button?
> `_.constants.constants["GameConstants.Debug.SCALE_ENCOUNTER_DISTANCE"] = 0; `

Yeah I think you should because many peopel don't realy like monster battles and if they're new to the hacks i'm not sure if they'll find the No Monster Battle Hack in the Hack -> Misc. Folder.

**Comment by PatheticMustan** [comment]
what's a cool name for disabling monster encounters? I wanna name it "invisible cloak", but it might seem a bit misleading

**Comment by PatheticMustan** [comment]
watch this

**Comment by ArcerionDev** [comment]
> what's a cool name for disabling monster encounters? I wanna name it "invisible cloak", but it might seem a bit misleading
> 
> I guess I'll just conservatively go with "disable monster encounters"

maybe we should make a wiki page about the functions of all the features that might be unclear..?

**Comment by PatheticMustan** [comment]
that would be a super cool thing!

**Comment by PatheticMustan** [comment]
![image](https://user-images.githubusercontent.com/35382971/107663327-40cd0800-6c59-11eb-83c3-b8fcc05a2694.png)
alright, works if you go into a new scene

**Comment by NX721** [comment]
Nice!

**Comment by divinelemon** [comment]
close

**Comment by NX721** [comment]
Unfortunately teh hack dosen't work on Harmony Island or Crystal Caverns. 😞
