### ISSUE TITLE
[HR] Add only certain items

### ISSUE THREAD

**Issue by AnisopteraN** [Prodigy-Hacking/ProdigyMathGameHacking#508]
I don't like how you can only add ALL items. I'd love for it to be able to add individual items that you can choose, like the pets.

**Comment by CRobbins0867** [comment]
@AnisopteraN  you can just click "add pets"

**Comment by PatheticMustan** [comment]
ah, they meant they wanted to be able to add only certain items.

This is certainly a good feature idea! If we have time, we'll definitely try to add this in

**Comment by NX721** [comment]
hmmm

**Comment by ArcerionDev** [comment]
this is definitely possible, but it would take a lot of work on our end to make it user-friendly. Most people on the repository can't follow simple instructions and need their hand held all the way up to not being able to press a button on a menu. If we were to do this, we would have to develop a UI to do this, on top of the necessary development and WCM additions that we'd need to implement. It's a good idea, but it's a difficult idea. If you're worrying about the game finding out you're hacking, don't. They won't find out, they'd need to find your username and password out of their database, either manually log into your account or generate an account token, and look through your inventory. This is too tiring to do for the 5,000+ users that visit our repository on a daily basis, so again, I wouldn't worry.

**Comment by PatheticMustan** [comment]
I'll think about adding this

**Comment by NX721** [comment]
Can someone close this?

**Comment by ArcerionDev** [comment]
oh yeah
