### ISSUE TITLE
Important: Rune Aquiring

### ISSUE THREAD

**Issue by hugo875** [Prodigy-Hacking/ProdigyMathGameHacking#510]
Hi i have been using your hacks for a long time but I'm looking forward to get all runes in prodigy

**Comment by NX721** [comment]
Ok

**Comment by ArcerionDev** [comment]
@NameIsA you looked into this iirc

**Comment by PatheticMustan** [comment]
wish we didn't ban NameIsA :(

**Comment by ArcerionDev** [comment]
Alright, we need some people on this, it's pretty important.

**Comment by elikiller** [comment]
function getallRunes() {
PIXI.game.prodigy.player.backpack.data.Runes=[]
x = PIXI.game.state.states.Boot._gameData.Runes
for (i in x) {
    PIXI.game.prodigy.player.backpack.data.Runes[i] = {"ID": x[i].ID, "N": 99999999999999}

**Comment by elikiller** [comment]
It’s from another mod menu but i changed the name from spellrelics to Runes

**Comment by NX721** [comment]
> function getallRunes() {
> PIXI.game.prodigy.player.backpack.data.Runes=[]
> x = PIXI.game.state.states.Boot._gameData.Runes
> for (i in x) {
> PIXI.game.prodigy.player.backpack.data.Runes[i] = {"ID": x[i].ID, "N": 99999999999999}

Still won't work Prodigy dosen't qork with PIXI

**Comment by ArcerionDev** [comment]
that won't work

**Comment by ArcerionDev** [comment]
"runes" isn't valid

**Comment by ArcerionDev** [comment]
just changing the name won't work

**Comment by elikiller** [comment]
Oh ok

**Comment by ArcerionDev** [comment]
ok I got it:
```js
const itemify = (item, amount) =>
	item.map(x => ({
		ID: x.ID,
		quantity: amount,
	})).filter(v => v !== undefined);
let module;
Array.from( _.instance.prodigy.gameContainer.inversifyContainer._bindingDictionary._map).forEach(e => {
try{if( _.instance.prodigy.gameContainer.get(e[0]).battleData){module = e[0]}
}catch{console.log(`Error for ${e[0]}`)}
})
_.instance.prodigy.gameContainer.get('737-91e4').battleData._secureCharacterState._data.inventory.orb = itemify(_.gameData.orb, 1)
```

**Comment by ArcerionDev** [comment]
will add to WCM and then close issue

**Comment by ArcerionDev** [comment]
actually I lied I made a few small mistakes
```js
const itemify = (item, amount) =>
    item.map(x => ({
        ID: x.ID,
        quantity: amount,
    })).filter(v => v !== undefined);
let mod;
Array.from( _.instance.prodigy.gameContainer.inversifyContainer._bindingDictionary._map).forEach(e => {
try{if( _.instance.prodigy.gameContainer.get(e[0]).battleData){mod= e[0]}
}catch{console.log(`Error for ${e[0]}`)}
})
_.instance.prodigy.gameContainer.get(mod).battleData._secureCharacterState._data.inventory.orb = itemify(_.gameData.orb, 1)
```
correct version ^^

**Comment by NX721** [comment]
Pls Close this

**Comment by NX721** [comment]
@ArcerionDev  plz close this

**Comment by PatheticMustan** [comment]
no

**Comment by PatheticMustan** [comment]
will close when it's embedded into the menu

**Comment by ArcerionDev** [comment]
Which it is
