### ISSUE TITLE
[BUG] Bypass Monster 

### ISSUE THREAD

**Issue by Andrew1644563** [Prodigy-Hacking/ProdigyMathGameHacking#513]
@PatheticMustan @UntrustableRus  THANK YOU SO MUCH FOR ADDING THE BUTTON FOR THIS. The only problem now is that when the quest requires us to battle with a monster, even when I turn off the feature, I can't battle with the monster. Anyway to fix this?

**Comment by NX721** [comment]
Press Ctrl Shift I and type this in console
`_.constants.constants["GameConstants.Debug.SCALE_ENCOUNTER_DISTANCE"] = 1;`
Or something

**Comment by ArcerionDev** [comment]
until we implement an alternate way, just reload

**Comment by PatheticMustan** [comment]
> @PatheticMustan @UntrustableRus THANK YOU SO MUCH FOR ADDING THE BUTTON FOR THIS. The only problem now is that when the quest requires us to battle with a monster, even when I turn off the feature, I can't battle with the monster. Anyway to fix this?

untoggle the button, and reload the scene
