### ISSUE TITLE
[HR] school cheat menu??

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#515]
**Describe the hack in 5 words or less:**
Are you guys ever going to make a cheat menu/use a existing cheat menu for school?

**Have you made sure this hack isn't available yet?* (Yes/No)**

yes, i wish the answer was no but yes there is no school/mobile prodigy cheat menu

**Comment by CRobbins0867** [comment]
if you are working on it, when is it going to be out?

**Comment by divinelemon** [comment]
@CRobbins0867 Thanks for submitting an issue! I have been working on this, and expect to complete it in about a week. I will let you know when I am done.

**Comment by ArcerionDev** [comment]
wait wait wait

**Comment by ArcerionDev** [comment]
the only hacks that can be used via an administrated computer are the script-based hacks, which are very limited.

if you want full access to all the hacks, an unrestricted menu won't be possible

**Comment by PatheticMustan** [comment]
sadly only possible with an insane amount of effort and development, we don't have enough power
