### ISSUE TITLE
my interview for fixing hacks

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#516]
So I hear you are looking for coders, and I really like coding and am pretty good at it! also before I continue sorry I can not go on discord and to this interview I am not able to go on discord right now. anyways, I have a lot more questions and i dont want this to be like three paragraph so if you want to continue message my email (megagjkiller@gmail.com) or any other way you want to! I hope you will consider me as a candidate for the job!

**Comment by ArcerionDev** [comment]
we require discord contact for this service
