### ISSUE TITLE
Not available on Android MOBILE

### ISSUE THREAD

**Issue by lyricissupercoon** [Prodigy-Hacking/ProdigyMathGameHacking#518]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [people dont make android versions of hacks]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ArcerionDev** [comment]
Sorry, not possible. The chrome extension is required to inject the modifications.
