### ISSUE TITLE
[BUG] harmony island rune runs

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#521]
***Description***: when i try to go in a run run it says "there was a error starting a rune run please choose "back" and try again later" 

***Replication***:

***Images***:
![Screenshot 2021-02-19 at 1 54 56 PM](https://user-images.githubusercontent.com/75956379/108565900-588c3800-72ba-11eb-8b55-274f34a0eb97.png)

***Additional Errors***:

**Comment by ArcerionDev** [comment]
Already exists
