### ISSUE TITLE
[HR] permanent potion effect for mod menu

### ISSUE THREAD

**Issue by SakuraKitsunee** [Prodigy-Hacking/ProdigyMathGameHacking#523]
**Describe the hack in 5 words or less:**

**Have you made sure this hack isn't available yet?* (Yes/No)**
yes  i have

**Comment by ArcerionDev** [comment]
Interesting idea, will look into soon. Currently maintaining other things so this will go on the back burner until further notice

**Comment by PatheticMustan** [comment]
No

**Comment by ArcerionDev** [comment]
bruh since when do we have github actions

**Comment by BETPRODIGYHACKER** [comment]
I guess we do

**Comment by hostedposted** [comment]
Added this.
