### ISSUE TITLE
to everyone who helps the PMGH organization!

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#524]
I just wanted to say I love the PMGH organization and everyone working on it! I have been using your hacks for about 1-3 months and just wanted to let you guys are pretty much the only reason I started coding games and mod menus for games, so thanks for that! also I love how to keep adding to a already great mod menu!

**Comment by divinelemon** [comment]
ok close this issue now, issues are for... well... actual issues.
