### ISSUE TITLE
[BUG]Logged off my account every 15 minutes

### ISSUE THREAD

**Issue by BX161** [Prodigy-Hacking/ProdigyMathGameHacking#525]
***Description***:
Hi,
I am new to here. I don't know why my account is being logged off in every 15 minutes after I installed the extention. Anyone can help? Thank you so much.

***Replication***:

***Images***:

***Additional Errors***:

**Comment by CRobbins0867** [comment]
tbh i really don't know did it say prodigy cannot connect at the top of the screen before it logged you out?

**Comment by CRobbins0867** [comment]
??

**Comment by CRobbins0867** [comment]
@BX161

**Comment by PatheticMustan** [comment]
closed due to inactivity
