### ISSUE TITLE
Loading bar stuck halfway

### ISSUE THREAD

**Issue by IsOnlineUser** [Prodigy-Hacking/ProdigyMathGameHacking#526]
***Description***:
I used this hack for a day, on my account. Today, when I logged on, I saw that the Prodigy Hack Extension was gone, and I put the zip file for the extension in the chrome extensions. When I try to log on to prodigy, it just shows me a white screen with the URL set as https://play.prodigygame.com/. When I remove the extension, I can log on to the prodigy just fine, and that means I can not hack anymore. If I try it on another account, my loading screen is stuck halfway.

***Replication***:

***Images***:

<img width="1427" alt="Screen Shot 2021-02-21 at 10 27 22 PM" src="https://user-images.githubusercontent.com/33985287/108662449-f9821b00-7493-11eb-9c54-841673e9db55.png">

<img width="1406" alt="Screen Shot 2021-02-21 at 10 28 23 PM" src="https://user-images.githubusercontent.com/33985287/108662511-1dddf780-7494-11eb-8ad5-942a1faba162.png">

***Additional Errors***:

**Comment by CRobbins0867** [comment]
@IsOnlineUser how long did you wait when you made the new account with the hack on?

**Comment by ArcerionDev** [comment]
that's really odd

**Comment by ArcerionDev** [comment]
@IsOnlineUser please send a screenshot of your chrome console, if possible

**Comment by IsOnlineUser** [comment]
> @IsOnlineUser how long did you wait when you made the new account with the hack on?

This is my main account, if I get banned on it IDRC, but it's about a year old.

**Comment by IsOnlineUser** [comment]
> @IsOnlineUser please send a screenshot of your chrome console, if possible

 
![Screen Shot 2021-02-24 at 8 07 13 AM](https://user-images.githubusercontent.com/33985287/109012159-4f62e880-7677-11eb-9e6a-ad001de67c22.png)

**Comment by ArcerionDev** [comment]
alright

**Comment by ArcerionDev** [comment]
sorry for not getting back to you

**Comment by ArcerionDev** [comment]
this is resulting from hacks being offline, it should hopefully be fixed now

**Comment by PatheticMustan** [comment]
@IsOnlineUser, need to know if it's still broken. Otherwise, will close in a week for inactivity.

**Comment by PatheticMustan** [comment]
nevermind, i'm not that patient :P
