### ISSUE TITLE
did you mean to take away the buddies? there is no options to get all buddy's and items i remember there being one but it is now gone.[BUG]

### ISSUE THREAD

**Issue by Beetlecats** [Prodigy-Hacking/ProdigyMathGameHacking#527]
***Description***:

***Replication***:

***Images***:

***Additional Errors***:

**Comment by PatheticMustan** [comment]
Can somebody look at the cheat menu rq, it should be under "follows"

**Comment by ArcerionDev** [comment]
![image](https://user-images.githubusercontent.com/60945964/109315335-70af0a80-7818-11eb-90e4-f39af7b31be2.png)
