### ISSUE TITLE
[BUG] Pet inactivity kick, broken spells, harmony island

### ISSUE THREAD

**Issue by CyberXVI** [Prodigy-Hacking/ProdigyMathGameHacking#528]
bug 1:When you try to open the pet menu, it immediately says that you gone inactive, making it so that you can't change pets

**PS** 
it only happens when i use the "Obtain All Pets" hacks

Bug 2: when you go into the dark tower, get into a battle in shiverchill, or try to battle in harmony island, the game freezes

**Comment by PatheticMustan** [comment]
What pets do you have equipped?

**Comment by CyberXVI** [comment]
lv 100 big hex and lv 100 arctursus

**Comment by CRobbins0867** [comment]
the pet thing happens to me to even when i only choose certain pets but not every time

**Comment by PatheticMustan** [comment]
@CyberXVI, before going into a battle, click "fix battle crash". Please tell me if this fixes the problem.

**Comment by CyberXVI** [comment]
Hmm okay

**Comment by CyberXVI** [comment]
Yeah it works

**Comment by CyberXVI** [comment]
also when doing a question the hacks list disappears and the game freezes so look on that too

**Comment by PatheticMustan** [comment]
need more information, please screenshot the error after a crash.

**Comment by PatheticMustan** [comment]
when you do, make a new issue
