### ISSUE TITLE
Monolith Repo

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#529]
Over the past few months I've split the one giant repo into multiple repos, I now realize this was a massive mistake.

I would like to join all the repos back into the main repo, while retaining the commit history, so uhh

- [x] Merge Redirector back
- [x] Merge PHEx back
- [x] Only use npm (yarn bad >:/ )
- [x] Clean up dependencies
- [x] Refactor option to serve WCM from redirector, ideally we would be able to build WCM and test it out without spamming 50 commits (sorry arc)
- [x] Refactor PHEx to also reflect these changes
- [x] Clean up injection code in PHEx, I never meant for "disableIntegrity.js" to last this long

**Comment by BoredFishRE** [comment]
yarn ain't bad >:(

**Comment by ArcerionDev** [comment]
wait wait wait why do we need to join everything into one repo

**Comment by ArcerionDev** [comment]
like I mean yeah ok but isn't it better for everything to be less

**Comment by ArcerionDev** [comment]
idk

**Comment by ArcerionDev** [comment]
***interconnected***

**Comment by PatheticMustan** [comment]
The main motivation behind this is automatically serving the extension from redriector, afaik it's not the latest..? There's also the issue of serving WCM from redirector for testing.

**Comment by ArcerionDev** [comment]
can't you just like

**Comment by ArcerionDev** [comment]
idek

**Comment by ArcerionDev** [comment]
build wcm and then paste the bundled file into console to update the menu for the last one
regardless, if we really want to pursue a locally hosted menu, we can move it to a new issue.

**Comment by PatheticMustan** [comment]
that's so scuffed
