### ISSUE TITLE
[HR] Disable inactivity kick 

### ISSUE THREAD

**Issue by CyberXVI** [Prodigy-Hacking/ProdigyMathGameHacking#530]
No Inactivity Kick

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by CRobbins0867** [comment]
@CyberXVI that would be nice, like REALLY nice (hint hint nudge nudge)

**Comment by CyberXVI** [comment]
Hardy Har Har

**Comment by ArcerionDev** [comment]
shush we have about 10 things we need to fix

**Comment by NX721** [comment]
Just open console and paste this in `_.constants.constants["GameConstants.Inactivity.LOG_OUT_TIMER_SECONDS"] = 0;`

**Comment by ArcerionDev** [comment]
yeah I'll add that actually

**Comment by ArcerionDev** [comment]
thanks @NX721 was trying to find that

**Comment by ArcerionDev** [comment]
done
![image](https://user-images.githubusercontent.com/60945964/109169483-da161700-774d-11eb-8109-b89f9dfd1e41.png)

**Comment by NX721** [comment]
> thanks @NX721 was trying to find that

Np
