### ISSUE TITLE
need help learning to code

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#533]
i know that this has nothing to do with this repository but i need someone to help me learn how to code, even if it's basics, i'm really new to it and not good what so ever so if someone could teach me that would be great thx

here's my email if you want to teach me!

(calebthehufflepuff@gmail.com)

**Comment by divinelemon** [comment]
@CRobbins0867  https://javascript.info

**Comment by CRobbins0867** [comment]
@divinelemon thx!
