### ISSUE TITLE
Question Hacks Menu glitch

### ISSUE THREAD

**Issue by CyberXVI** [Prodigy-Hacking/ProdigyMathGameHacking#534]
***Description***:
When i have a question to do, it doesn't show the hacks menu

***Replication***:
i don't understand

***Images***:

I don't have an image, but i've got a video

https://user-images.githubusercontent.com/75691900/108786345-3e579180-7528-11eb-82eb-f66e334a5e6e.mp4

***Additional Errors***:

**Comment by spacekitten45** [comment]
you can't access the menu while answering a question. do it before clicking an attack

**Comment by CyberXVI** [comment]
ಠ_ಠ

**Comment by ArcerionDev** [comment]
oh yeah

**Comment by ArcerionDev** [comment]
it's not layered correctly

**Comment by ArcerionDev** [comment]
yeah I'll add that

**Comment by CyberXVI** [comment]
Thanks!
