### ISSUE TITLE
[BUG] issue with win battle in harmony island

### ISSUE THREAD

**Issue by spacekitten45** [Prodigy-Hacking/ProdigyMathGameHacking#536]
***Description***:
whenever using win battle in harmony island, you don't get any battle stars, coins, or other rewards from battling.

***Replication***:
just click win battle in harmony island and there will be no rewards

***Images***:
cannot provide any images

***Additional Errors***:
battle crash not fixing, even w/o pets or hacked runes.

**Comment by CyberXVI** [comment]
wow you joined yesterday, congrats! 🥳

You do not need the stars, coins and other rewards from battling because you can generate them yourself

**Comment by PatheticMustan** [comment]
Thanks for submitting this issue! We'll try fixing this, but there're a lot of issues right now...

**Comment by ChickenOnYT** [comment]
harmony island is 2.2.0

**Comment by UntrustableRus** [comment]
Why did they change *everything* for harmony island? Just why? Why prodigy? Why?
