### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jayy113** [Prodigy-Hacking/ProdigyMathGameHacking#537]
***Description***:when the hack is enabled i try to log in but it stops half way from logging in

***Replication***:when the hack is enabled i try to log in but it stops half way from logging in

***Images***:

***Additional Errors***:

**Comment by BoredFishRE** [comment]
please name your issues. Can you visit https://prodigyhacking.ml or is it blocked?

**Comment by jayy113** [comment]
> please name your issues. Can you visit https://prodigyhacking.ml or is it blocked?

its not blocked

**Comment by jayy113** [comment]
what do i do with it

**Comment by BoredFishRE** [comment]
Is the extension installed? Try removing it, and replacing it with https://prodigyhacking.com/extension

**Comment by BoredFishRE** [comment]
remove any older extensions

**Comment by jayy113** [comment]
> remove any older extensions

thank u so much it worked :)

**Comment by BoredFishRE** [comment]
no problem!
