### ISSUE TITLE
All Pets Causes The Game To Crash

### ISSUE THREAD

**Issue by ElonReeveMusket** [Prodigy-Hacking/ProdigyMathGameHacking#543]
When  click give all pets and check my pets, my game crashes. it says ive been inactive for too long,

**Comment by ArcerionDev** [comment]
Run this in your console to close the popup.
```js
_.instance.prodigy.open.menuCloseAll()
```
will add to cheat menu asap

**Comment by ArcerionDev** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/60945964/108913741-631b3a00-75f8-11eb-8422-e7eb3c7e847a.png)
