### ISSUE TITLE
Some things in the inventory editor wont work. For e.g, the furniture one. Doesn't give furniture

### ISSUE THREAD

**Issue by ElonReeveMusket** [Prodigy-Hacking/ProdigyMathGameHacking#544]
Some things in the inventory editor wont work. For e.g, the furniture one. Doesn't give furniture

To make it happen, just try to edit your inv, buddies and furniture etc wont work.

UPDATE: The buddies appear invisible and cant be interacted with in ANY way

**Comment by ArcerionDev** [comment]
will look into

**Comment by ArcerionDev** [comment]
I see the furniture issue, but buddies appear to work fine

**Comment by ElonReeveMusket** [comment]
> will look into

Another thing, My pets arent getting the things i edited in. When i edit a pets attack, it dosent appear for the attack in a battle.

**Comment by ArcerionDev** [comment]
are you using fix battle crash after editing pets

**Comment by ArcerionDev** [comment]
if so, that's why

**Comment by ElonReeveMusket** [comment]
> are you using fix battle crash after editing pets

Yes

**Comment by ArcerionDev** [comment]
yeah, we're trying to solve that as well, we're probably going to remove that feature for that reason

**Comment by ElonReeveMusket** [comment]
remove what feature

**Comment by ArcerionDev** [comment]
the edit pet attack feature

**Comment by ElonReeveMusket** [comment]
Oh, mk. The edit pet attacks works at first then stops working its very buggy

**Comment by ArcerionDev** [comment]
wait didn't mean to close that

**Comment by ArcerionDev** [comment]
ok there we go it should work now @ElonReeveMusket

**Comment by ElonReeveMusket** [comment]
> ok there we go it should work now @ElonReeveMusket

The furniture? Nope wont work for me.

**Comment by PatheticMustan** [comment]
Sad
