### ISSUE TITLE
Show Answer and or Autofarm

### ISSUE THREAD

**Issue by ElonReeveMusket** [Prodigy-Hacking/ProdigyMathGameHacking#547]
**Is your feature request related to a problem? Please describe.**
Its annoying when you don't know that one answer or just want to farm.

**Describe the solution you'd like**
I would like the correct answer of a problem to be shown or automatically done. The Autofarm could have options on what to autofarm. For e.g, Autofarm set on titan. It will keep killing the titan unti you stop it. Or it will automatically do a specific quest you set it to do.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by CRobbins0867** [comment]
@ElonReeveMusket that is a really good idea!

**Comment by CyberXVI** [comment]
@CRobbins0867 You're right

**Comment by jayy113** [comment]
sounds like a pretty lit thing that could be added

**Comment by CyberXVI** [comment]
what is autofarm

**Comment by CRobbins0867** [comment]
@CyberXVI its like where you don't have to do anything but you still get stuff

**Comment by ArcerionDev** [comment]
can't you do that by like

**Comment by ArcerionDev** [comment]
_hacking_

**Comment by ArcerionDev** [comment]
just use the selector

**Comment by ArcerionDev** [comment]
as for the "show answer" that's not possible

**Comment by PatheticMustan** [comment]
Locking was kinda rude but ok

auto answering questions is worth looking into tho
