### ISSUE TITLE
Inventory Editor Wont Work Still

### ISSUE THREAD

**Issue by ElonReeveMusket** [Prodigy-Hacking/ProdigyMathGameHacking#548]
***Description***:
When using the inventory editor, giving yourself furniture or buddies still wont work!

***Replication***:
Use the inventory editor (some things work but some dont like buddies and furniture not working)

**Comment by ElonReeveMusket** [comment]
Update: Some things dont work properly, for example giving currency. It dosent save or work, for Shivers it adds but you cant use them and they dont save.

**Comment by PatheticMustan** [comment]
@ArcerionDev.... I'll look at picker later, but what happened..???

**Comment by ArcerionDev** [comment]
nothing

**Comment by ArcerionDev** [comment]
it's a weird bug

**Comment by ArcerionDev** [comment]
it doesn't happen to anyone else

**Comment by ArcerionDev** [comment]
only them
