### ISSUE TITLE
Loading Freezes. Again.

### ISSUE THREAD

**Issue by CyberXVI** [Prodigy-Hacking/ProdigyMathGameHacking#549]
***Description***:
The loading screen stops loading on the half. Again.

***Replication***:
I don't understand

***Images***:
![image](https://user-images.githubusercontent.com/75691900/109013643-3f8fd800-7668-11eb-8866-8e4318c17aea.png)

***Additional Errors***:

**Comment by jayy113** [comment]
yea this sometimes happens to me but during the day it will start working out of no where

**Comment by jayy113** [comment]
@CyberXVI really don't know how to fix this freezing glitch

**Comment by ArcerionDev** [comment]
when the freezing glitch occurs, hacks are down.

**Comment by ArcerionDev** [comment]
TODO: will make a site that displays hack status.
for now, try going to https://prodigyhacking.ml/status 
if it shows the message:
<hr>
<h1>502 Bad Gateway</h1>
<hr>

then hacks are down

**Comment by jayy113** [comment]
> when the freezing glitch occurs, hacks are down.

i kinda had a feeling it was something like that but i just didnt know to sure if i was correct now i know thank u :)

**Comment by ArcerionDev** [comment]
not a problem

**Comment by CyberXVI** [comment]
@ArcerionDev it shows me alot of code 
Is that good?

**Comment by jayy113** [comment]
> @ArcerionDev it shows me alot of code
> Is that good?

no thats the status of the hack so like he said 

this is how u know the hacks are down if it shows this message


if it shows the message:

502 Bad Gateway
then hacks are down

**Comment by ArcerionDev** [comment]
> @ArcerionDev it shows me alot of code
> Is that good?

yes, it means that it's up

**Comment by CyberXVI** [comment]
@jayy113 i don't understand what you're saying cuz 

> > @ArcerionDev it shows me alot of code
> > Is that good?
> 
> no thats the status of the hack so like he said
> 
> this is how u know the hacks are down
> 
> if it shows the message:
> 
> **502 Bad Gateway**
> 
> then hacks are down

I don't understand it doesn't say bad gateway

**Comment by CyberXVI** [comment]
@ArcerionDev k thanks!
