### ISSUE TITLE
Cheat Extension in Safari

### ISSUE THREAD

**Issue by ldiotHere** [Prodigy-Hacking/ProdigyMathGameHacking#553]
**Is your feature request related to a problem? Please describe.**
I'm a little frustrated when using Safari because it doesn't have all the things Chrome has. But still I say Safari is better than Chrome on _**Mac**_ because it uses less battery and has better performance on it's own hardware. 

**Describe the solution you'd like**
Is there anyway to add this extension in Safari instead of Chrome?

**Describe alternatives you've considered**
[None]

**Additional context**
[None]

**Comment by irhrhd** [comment]
![684D0BAA-668A-42D0-94D5-74972C741EFF](https://user-images.githubusercontent.com/62729648/109189407-d764f300-7748-11eb-808f-ded8c7c49643.png)
![53DE4C5E-3745-43A3-BC75-738BE004FC7B](https://user-images.githubusercontent.com/62729648/109189443-ddf36a80-7748-11eb-9b02-2af51ad2bcd4.png)
Yes

**Comment by ArcerionDev** [comment]
not all extensions are whitelisted on safari

**Comment by ArcerionDev** [comment]
we'll try and work out a solution, but chrome is optimal for the hacks, we'll look into this soon

**Comment by irhrhd** [comment]
@ArcerionDev Do you think i could be a maintainer

**Comment by ArcerionDev** [comment]
of what

**Comment by ArcerionDev** [comment]
the repository?

**Comment by irhrhd** [comment]
Yeah im pretty good at moderating

**Comment by ArcerionDev** [comment]
perhaps, reach out via discord

**Comment by irhrhd** [comment]
Oh then rip i cant use discord school blocked it and i dont have a pc

**Comment by ldiotHere** [comment]
> we'll try and work out a solution, but chrome is optimal for the hacks, we'll look into this soon

Ok, thanks for taking a look.

**Comment by NameIsA** [comment]
tbh if it was possible to reach more devices and browsers more attention would be given to the problem

**Comment by dimitricooper** [comment]
I do not think that there is a way to install an extension in Safari using a file. You would have to make an official extension on the app store but then it would get taken down because it is a hack. **But you could use a random name so that no one knows that it is a hack.** That could work actually.

**Comment by ArcerionDev** [comment]
it's more trouble than it's worth to be honest. if you want the hacks, use them on chrome

**Comment by PatheticMustan** [comment]
After looking into it, it looks like converting Chrome extensions for Safari requires Xcode, and I'm not sure any of us have a Mac. Closing for now, unless somebody wants to volunteer to convert them, we will not support Safari.
