### ISSUE TITLE
[BUG] Selector (Advanced) is kinda wrong

### ISSUE THREAD

**Issue by NX721** [Prodigy-Hacking/ProdigyMathGameHacking#557]
So I wanted to add the new Prismatic Wand so I used the Selector (Advanced) To give it to me. Then in my inventory it gave me  Pool Swords instead. Maybe try updating the menu? (The Selector (Basic) still gives you it though)

**Comment by ArcerionDev** [comment]
Pool swords????

**Comment by NX721** [comment]
Yea weird ik

**Comment by CyberXVI** [comment]
Pool swords are a type of wand.

**Comment by CyberXVI** [comment]
![PoolSword](https://user-images.githubusercontent.com/75691900/109303184-485ee600-77ef-11eb-85b7-f70ba241fc80.png)

**Comment by ArcerionDev** [comment]
oh

**Comment by ArcerionDev** [comment]
will look into

**Comment by ArcerionDev** [comment]
quick question, how do you get the prismatic wand by natural means

**Comment by ArcerionDev** [comment]
because the issue could be that it's not released yet

**Comment by ArcerionDev** [comment]
![image](https://user-images.githubusercontent.com/60945964/109313759-93402400-7816-11eb-8b84-9029a2550726.png)
ok that's really odd, I set the ID to a specific number and it gave me it...???

**Comment by ArcerionDev** [comment]
alright, I see the issue

**Comment by ArcerionDev** [comment]
the "prismatic wand" hasn't been released yet, and there are 8 other wands in between it that haven't gotten assets yet

**Comment by ArcerionDev** [comment]
alright, for now, just use the basic selector, there really isn't anything we can do about it

**Comment by ArcerionDev** [comment]
oh I figured it out
