### ISSUE TITLE
[HR] auto titan kill hack

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#558]
**Describe the hack in 5 words or less:**
one shot titan boss

**Have you made sure this hack isn't available yet?* (Yes/No)**
yes

**Comment by ArcerionDev** [comment]
not possible, sorry

**Comment by ArcerionDev** [comment]
actually scratch that

**Comment by ArcerionDev** [comment]
it could be possible

**Comment by ArcerionDev** [comment]
won't work on as of now but will look into eventually
