### ISSUE TITLE
Not loading fully

### ISSUE THREAD

**Issue by dimitricooper** [Prodigy-Hacking/ProdigyMathGameHacking#559]
When I sign into Prodigy, the bar will load halfway but then never finish. But when I remove the extension, it works. So that means that it is a problem with the extension. I looked in my extensions and it showed that it detected an error. It said that it failed to fetch. I hope that you can fix this soon.

**Comment by NX721** [comment]
Ok can u screenshot the error

**Comment by dimitricooper** [comment]
![Screen Shot 2021-02-27 at 9 16 03 AM](https://user-images.githubusercontent.com/66804076/109394551-6d7d5280-78dc-11eb-9adc-df83d7c0dee2.png)
It just stays like this.

**Comment by PatheticMustan** [comment]
try checking if https://prodigyhacking.ml/version loads, and try it again

**Comment by ElonReeveMusket** [comment]
This is a problem for me to!

**Comment by dimitricooper** [comment]
![Screen Shot 2021-02-27 at 12 26 07 PM](https://user-images.githubusercontent.com/66804076/109399323-0751f900-78f7-11eb-88de-6e613c44a6a3.png)
When I went to that site this is what happened.

**Comment by ArcerionDev** [comment]
that means the site was blocked by your administration

**Comment by dimitricooper** [comment]
hmm

**Comment by dimitricooper** [comment]
I have an idea.

**Comment by ArcerionDev** [comment]
?

**Comment by dimitricooper** [comment]
I was using Exfinity and the router has restrictions built into them, I just had to use a ATT hotspot that we have that has not restrictions, now it is working.

**Comment by ArcerionDev** [comment]
For future reference, VPN installation via chrome extension is [here](https://chrome.google.com/webstore/detail/setupvpn-lifetime-free-vp/oofgbpoabipfcfjapgnbbjjaenockbdp?hl=en-US)

**Comment by dimitricooper** [comment]
Now it is not working and it says something else.
![Screen Shot 2021-02-27 at 12 55 46 PM](https://user-images.githubusercontent.com/66804076/109400019-1d61b880-78fb-11eb-9b1f-a7762082c409.png)

**Comment by ArcerionDev** [comment]
try installing the vpn I mentioned above

**Comment by dimitricooper** [comment]
It is working with the VPN.

**Comment by dimitricooper** [comment]
Uh, This is weird. It is not loading again.

**Comment by PatheticMustan** [comment]
@ArcerionDev, if you're at home, could you log onto the vps, and type `pm2 resurrect`?
I'm unfortunately at school

**Comment by ArcerionDev** [comment]
sure

**Comment by ArcerionDev** [comment]
and @PatheticMustan chrome has a built in ssh client

**Comment by ArcerionDev** [comment]
forget I said that it's not built in but it's here https://chrome.google.com/webstore/detail/secure-shell-app/pnhechapfaindjhompbnflcldabbghjo?hl=en-US

**Comment by ArcerionDev** [comment]
wait hold on are we using tmux or pm2 rn

**Comment by PatheticMustan** [comment]
pm2

**Comment by PatheticMustan** [comment]
> and @PatheticMustan chrome has a built in ssh client

Who said I'm using chrome ;))
