### ISSUE TITLE
Script based hacks are outdated

### ISSUE THREAD

**Issue by hostedposted** [Prodigy-Hacking/ProdigyMathGameHacking#560]
***Description***:
When I run the script based level hack it 404s.

***Replication***:
Go in to prodigy and use the script based level hack.

***Images***:
<img width="415" src="https://user-images.githubusercontent.com/70211235/109369326-f60edb00-7869-11eb-8cf9-915f5088213e.PNG">

**Comment by PatheticMustan** [comment]
it looks like prodigy updated their paths again
@ArcerionDev

**Comment by NX721** [comment]
HMMMMMMM

**Comment by ArcerionDev** [comment]
oh fuck

**Comment by ArcerionDev** [comment]
alright

**Comment by NameIsA** [comment]
Looks like Arc fixed this, yes?
