### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BrittanyG1150** [Prodigy-Hacking/ProdigyMathGameHacking#562]
***Description***: It does not save my progress and every time I try to do something on the cheat menu, it logs me out

***Replication***:

***Images***:

***Additional Errors***:

**Comment by CRobbins0867** [comment]
@PatheticMustan does the disable inactivity kick makes it so you can't log out?

**Comment by BrittanyG1150** [comment]
no because even though I click that, it still logs me out after a while

**Comment by CRobbins0867** [comment]
try making another account that whta i have to do sometimes

**Comment by CRobbins0867** [comment]
does that work??

**Comment by BrittanyG1150** [comment]
still doesn't work. And how do people get the hacking hairstyle as well because it's no where on the cheat menu at all

**Comment by CRobbins0867** [comment]
try making a new account 1 more time and for the hairstyles do you member hairstyles>

**Comment by CRobbins0867** [comment]
?*

**Comment by irhrhd** [comment]
Robbins you home yet

**Comment by PatheticMustan** [comment]
can you be more specific on what happens..? Any errors, or screenshots would be greatly appreciated.

**Comment by NameIsA** [comment]
hello person who made people expose their prodigy username and password on the pmgw so that you could login to their accounts and "hack" the accounts for them

**Comment by ArcerionDev** [comment]
:thonk:

**Comment by dimitricooper** [comment]
?

**Comment by PatheticMustan** [comment]
> hello person who made people expose their prodigy username and password on the pmgw so that you could login to their accounts and "hack" the accounts for them

what

**Comment by NameIsA** [comment]
sorry for calling people out im still salty at britanny tho they wasted so much of my time >:(((((

**Comment by BrittanyG1150** [comment]
how did I waste ur time?

**Comment by BrittanyG1150** [comment]
also its Brittany not brittanny btw

**Comment by NameIsA** [comment]
because i spent like an hour deleting personal information from your message wall

**Comment by BrittanyG1150** [comment]
dude i never asked for people to do that. They all came to me and I tried my best to help them hack their accs since they did not understand how to hack

**Comment by NameIsA** [comment]
> dude i never asked for people to do that. They all came to me and I tried my best to help them hack their accs since they did not understand how to hack

instead of hacking their accounts link them to the prodigy hacking wiki and tell them to not share their personal information

**Comment by BrittanyG1150** [comment]
I tried to give them the most info I could and only a small percentage of them learned how to hack themselves but there was still a bunch of people that really did not know how to hack so I tried my best to help them and with the personal info, I deleted some of it but there was still other info that I just ignored

**Comment by NameIsA** [comment]
> I tried to give them the most info I could and only a small percentage of them learned how to hack themselves but there was still a bunch of people that really did not know how to hack so I tried my best to help them and with the personal info, I deleted some of it but there was still other info that I just ignored

but why did you ignore it? i dont see why they wouldnt understand. there's tons of youtube videos (even ones by prodigymathgamehacking) that you could show to them to give them a visual explanation.

**Comment by PixelMMO** [comment]
stop fighting about that

**Comment by PixelMMO** [comment]
who cares

**Comment by NameIsA** [comment]
> who cares

i care because now it's been reinforced that it's ok to share your password and username and if they keep these habbits later into their life they're gonna end up getting scammed and lose a lot of their money

**Comment by PatheticMustan** [comment]
Continue off topic in discussions please ;-;

**Comment by PatheticMustan** [comment]
@BrittanyG1150 please screenshot errors

**Comment by PatheticMustan** [comment]
closed due to inactivity
