### ISSUE TITLE
Morphing fails

### ISSUE THREAD

**Issue by BrittanyG1150** [Prodigy-Hacking/ProdigyMathGameHacking#563]
***Description***: The cheat menu does not let me morph into anything anymore

***Replication***:

***Images***:

***Additional Errors***:

**Comment by PatheticMustan** [comment]
hmm, it seems like morph may have been broken recently, based on recent reports

**Comment by BrittanyG1150** [comment]
oh okay but when will it be fixed because I have not been able to morph myself into anything lately

**Comment by ArcerionDev** [comment]
@PatheticMustan you need to run the morph crash right after the morph hack

**Comment by BrittanyG1150** [comment]
no whenever I try and morph myself to something, my entire screen freezes and it does not let me press anything else unless I re fresh the page.

**Comment by PatheticMustan** [comment]
I'll need to find the actual error

**Comment by BrittanyG1150** [comment]
ok

**Comment by PixelMMO** [comment]
@ArcerionDev @PatheticMustan i found out why it doesnt work

**Comment by ArcerionDev** [comment]
???

**Comment by PixelMMO** [comment]
I looked at the code in the console after pressing "fix morph crash" and this was in the code (idk how to code but i think red means theres a problem)

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/109703068-0b824e80-7b63-11eb-97d3-ca3b7ff22dc1.png)

**Comment by PixelMMO** [comment]
should that be there?

**Comment by ArcerionDev** [comment]
no but there is an issue, give me a sec

**Comment by PatheticMustan** [comment]
Pain, I'm still at school and can't view any of the images

**Comment by ArcerionDev** [comment]
why can't you view the images...?

**Comment by irhrhd** [comment]
Hey guys can i join the hacking group i know how to code now

**Comment by PixelMMO** [comment]
im not part of the group so dont ask me

**Comment by irhrhd** [comment]
I did the whole first 2 lessons on free code camp and i learndhow

**Comment by ArcerionDev** [comment]
you should join the discord, if you can't access discord, install a vpn

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/109703569-9d8a5700-7b63-11eb-88b4-b9829dc2f331.png)
whats happening here?

**Comment by ArcerionDev** [comment]
it just means that prodigy doesn't have a registered asset for it

**Comment by PixelMMO** [comment]
ok

**Comment by irhrhd** [comment]
Arcy can you guys add the live chat back to prodigyhacking so then i can talk to you also i cant get a vpn im on a schoo ipad and can’t download anything so yeah

**Comment by irhrhd** [comment]
It says the version is 2.0.0

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/109703954-11c4fa80-7b64-11eb-902b-a9274114504e.png)
is this a problem?

**Comment by irhrhd** [comment]
Yeah

**Comment by PixelMMO** [comment]
ok because it wasnt working for me in PVP

**Comment by ArcerionDev** [comment]
> Arcy can you guys add the live chat back to prodigyhacking so then i can talk to you also i cant get a vpn im on a schoo ipad and can’t download anything so yeah

how are you using the hacks then...

**Comment by ArcerionDev** [comment]
> ![image](https://user-images.githubusercontent.com/79719521/109703954-11c4fa80-7b64-11eb-902b-a9274114504e.png)
> is this a problem?

dw about it it's a common error

**Comment by irhrhd** [comment]
Oh uh my online friends

**Comment by irhrhd** [comment]
I just want to code

**Comment by irhrhd** [comment]
For you guys

**Comment by ArcerionDev** [comment]
coding on an iPad isn't really possible for us, we don't need more hacks, we really just need people to maintain the cheat menu, and you can't do that on an iPad

**Comment by irhrhd** [comment]
Oh 😔 sorry

**Comment by irhrhd** [comment]
var denom = [
  { name: "ONE HUNDRED", val: 100.0 },
  { name: "TWENTY", val: 20.0 },
  { name: "TEN", val: 10.0 },
  { name: "FIVE", val: 5.0 },
  { name: "ONE", val: 1.0 },
  { name: "QUARTER", val: 0.25 },
  { name: "DIME", val: 0.1 },
  { name: "NICKEL", val: 0.05 },
  { name: "PENNY", val: 0.01 }
];

function checkCashRegister(price, cash, cid) {
  var output = { status: null, change: [] };
  var change = cash - price;

  // Transform CID array into drawer object
  var register = cid.reduce(
    function(acc, curr) {
      acc.total += curr[1];
      acc[curr[0]] = curr[1];
      return acc;
    },
    { total: 0 }
  );

  // Handle exact change
  if (register.total === change) {
    output.status = "CLOSED";
    output.change = cid;
    return output;
  }

  // Handle obvious insufficient funds
  if (register.total < change) {
    output.status = "INSUFFICIENT_FUNDS";
    return output;
  }

  // Loop through the denomination array
  var change_arr = denom.reduce(function(acc, curr) {
    var value = 0;
    // While there is still money of this type in the drawer
    // And while the denomination is larger than the change remaining
    while (register[curr.name] > 0 && change >= curr.val) {
      change -= curr.val;
      register[curr.name] -= curr.val;
      value += curr.val;

      // Round change to the nearest hundreth deals with precision errors
      change = Math.round(change * 100) / 100;
    }
    // Add this denomination to the output only if any was used.
    if (value > 0) {
      acc.push([curr.name, value]);
    }
    return acc; // Return the current change_arr
  }, []); // Initial value of empty array for reduce

  // If there are no elements in change_arr or we have leftover change, return
  // the string "Insufficient Funds"
  if (change_arr.length < 1 || change > 0) {
    output.status = "INSUFFICIENT_FUNDS";
    return output;
  }

  // Here is your change, ma'am.
  output.status = "OPEN";
  output.change = change_arr;
  return output;
}

**Comment by irhrhd** [comment]
Cash register

**Comment by PixelMMO** [comment]
what dat for?

**Comment by ArcerionDev** [comment]
ok you copied and pasted from a freecodecamp course

**Comment by irhrhd** [comment]
I made that on freecode

**Comment by PixelMMO** [comment]
is it for prodigy?

**Comment by irhrhd** [comment]
Its 1 of the tests

**Comment by PixelMMO** [comment]
all ik how to code is scratch

**Comment by PatheticMustan** [comment]
can't replicate, ahhhhh what did they morph into

**Comment by ChickenOnYT** [comment]
@BrittanyG1150 what did you morph into

**Comment by ArcerionDev** [comment]
I fixed this actually forget this

**Comment by ArcerionDev** [comment]
it was because I made the number for the morph time too high

**Comment by ArcerionDev** [comment]
so it couldn't process it

**Comment by ChickenOnYT** [comment]
mk
