### ISSUE TITLE
Hacking Hairstyles

### ISSUE THREAD

**Issue by BrittanyG1150** [Prodigy-Hacking/ProdigyMathGameHacking#564]
**Describe the hack in 5 words or less:** Hacking Hairstyle Hack 

**Have you made sure this hack isn't available yet?* (Yes/No)** No

**Comment by NX721** [comment]
`_.player.appereance.hairStyle = 25;

_.player.appearancehasChanged.true;` 
Maybe?

**Comment by BrittanyG1150** [comment]
mhm what do I do with that?

**Comment by NX721** [comment]
Put in console (Ctrl Shift J)

**Comment by BrittanyG1150** [comment]
I don't get where im supposed to put that in. Can you send me a screenshot of what im supposed to do or something because i am so confused

**Comment by PatheticMustan** [comment]
On windows, press "Control Shift I". On Mac, it's "Control Shift J"

It should bring up a sidebar. On the bottom, is a text field where you can put the code.

![image](https://user-images.githubusercontent.com/35382971/109444852-327a3c80-7a0c-11eb-8ff4-319b53f5d8d1.png)

**Comment by BrittanyG1150** [comment]
ohhhh okay thank you so much. I was confused where exactly I had to put the code

**Comment by NX721** [comment]
The script i put gives u a secret girl hairstyle change the number for different hairstyles

**Comment by BrittanyG1150** [comment]
okay but whenever i put the code, then it just gives me an error

**Comment by PatheticMustan** [comment]
Prereq before continuing: #565

**Comment by NameIsA** [comment]
add enhancement label

**Comment by PixelMMO** [comment]
when i put the code in the console it just gives an error

**Comment by PixelMMO** [comment]
what do i do?

**Comment by BoredFishRE** [comment]
can you visit https://prodigyhacking.ml

**Comment by PixelMMO** [comment]
yes but its just lots of code

**Comment by PixelMMO** [comment]
what do i do with that

**Comment by BoredFishRE** [comment]
alright hmm

**Comment by BoredFishRE** [comment]
is the extension installed?

**Comment by PixelMMO** [comment]
the PHEx.zip

**Comment by PixelMMO** [comment]
yeah

**Comment by PixelMMO** [comment]
it says that that site cant be reached

**Comment by BoredFishRE** [comment]
hm, can you visit https://proxy.prodigyhacking.com

**Comment by PixelMMO** [comment]
nope

**Comment by PixelMMO** [comment]
it says it has insecure content

**Comment by BoredFishRE** [comment]
hm weird

**Comment by BoredFishRE** [comment]
@ArcerionDev does the extension require the CORS anywhere?

**Comment by ArcerionDev** [comment]
wait no scratch that

**Comment by BoredFishRE** [comment]
Yes or no?

**Comment by ArcerionDev** [comment]
no

**Comment by BoredFishRE** [comment]
alright

**Comment by PixelMMO** [comment]
i disabled the proxy and its still not working

**Comment by PixelMMO** [comment]
i ran diagnostics and it says that there is a problem with local networks

**Comment by BoredFishRE** [comment]
that shouldn't make a difference.

**Comment by PixelMMO** [comment]
would you be able to send the download through this chat?

**Comment by PatheticMustan** [comment]
Please continue this in discussions.... this is what it's for, after all...

**Comment by PatheticMustan** [comment]
(i was the one that wrote that but ok)

the issue is here to put it in WCM

**Comment by NX721** [comment]
Apparently, there isn't any secret male hairstyles, but there are a few for female.

**Comment by PatheticMustan** [comment]
Possibly related
https://gist.github.com/PatheticMustan/8986e95884f78a22da9958624d597019

**Comment by Idk-prog527** [comment]
I think first you ctrl + shift + i (Or ctrl + shift + j for mac) then, click on console, type in some gibberish into the search bar in there so that it will all be cleared, copy/paste in that code you got there, and then it will work. (P.S: if you do not have PHEx and try to do this, it will give you a 404 message, and if you have PHEx, you can do these steps clearly.)

**Comment by Jeremiah66268** [comment]
How do we get different hair but with a chromebook?

**Comment by PatheticMustan** [comment]
control shift i to open console

**Comment by hostedposted** [comment]
https://user-images.githubusercontent.com/70211235/122297867-06ef6500-ceca-11eb-9554-71cc92394d08.mp4

**Comment by Phenomenon1337** [comment]
can.. i close this now?
