### ISSUE TITLE
Spells and level saves not saving

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#566]
***Description***:
when i try to change the spells on my pets it doesnt show the spells i chose when i enter a battle

***Replication***:
to replicate the bug just change the spells on any pet and enter a battle, the spells are the normal spells

***Additional Errors***:
when i try to set my lvl to 1e+100 it justs reverts back to lvl 100 when i re enter the menu

**Comment by CRobbins0867** [comment]
@PixelMMO well i dont know about the other things but the level if you don't have to cheat menu enabled the max is 100

**Comment by ArcerionDev** [comment]
Oh yeah, levels over 100 do revert themselves back to 100 on reloading, will fix

**Comment by PixelMMO** [comment]
ok ty

**Comment by NX721** [comment]
You can set your level to Infinity you know

**Comment by PatheticMustan** [comment]
No

**Comment by PixelMMO** [comment]
you can set it to infinity you just have to add 500 nines

**Comment by PatheticMustan** [comment]
That's not the issue here, changing your level beyond 100 has unexpected side effects.

**Comment by achen6196** [comment]
So y'all gonna fix the levels reverting back to lvl 100?

**Comment by MelonMan101** [comment]
> So y'all gonna fix the levels reverting back to lvl 100?

give them time, they will figure something out.

**Comment by PatheticMustan** [comment]
> So y'all gonna fix the levels reverting back to lvl 100?

no, it's not a bug, it's a feature ;))

**Comment by YamaHacks** [comment]
> > So y'all gonna fix the levels reverting back to lvl 100?
> 
> no, it's not a bug, it's a feature ;))

bugs? in WCM? nah, those are just "fun easter eggs"

**Comment by ArcerionDev** [comment]
> > > So y'all gonna fix the levels reverting back to lvl 100?
> > 
> > 
> > no, it's not a bug, it's a feature ;))
> 
> bugs? in WCM? nah, those are just "fun easter eggs"

why don't you fix them then instead of complaining about them

**Comment by PatheticMustan** [comment]
no but seriously, this is legitimately a feature, we don't want people setting their levels above 100 and complaining when it doesn't work

**Comment by ArcerionDev** [comment]
perhaps we should store the level in localstorage

**Comment by ChickenOnYT** [comment]
if you dont wanna be assigned unassign yourself

**Comment by ArcerionDev** [comment]
this is definitely a serious issue so ye that's cool

**Comment by ArcerionDev** [comment]
I have an ok fix, closing until prodigy updates their apis
