### ISSUE TITLE
[HR] automatic items (without having to click the buttons)

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#567]
**Describe the hack in 5 words or less:**
make it so whenever a new items come out it goes in your inventory automatically

**Have you made sure this hack isn't available yet?* (Yes/No)**

yes

**Comment by ArcerionDev** [comment]
we've literally given you an advanced selector to select specific amounts of items and you're too lazy to _press buttons_ now

**Comment by CRobbins0867** [comment]
oh i did not know that

**Comment by CRobbins0867** [comment]
i have not been using to WCM for awhile

**Comment by ArcerionDev** [comment]
take a look at the "Selector (Advanced)" button on the cheat menu.

I apologize, but these frivolous requests are too bothersome to make, and if you want them, I suggest you figure out how to make them yourself

**Comment by CRobbins0867** [comment]
no worries, i get it
