### ISSUE TITLE
Selector (Advanced) is broken once more.

### ISSUE THREAD

**Issue by NX721** [Prodigy-Hacking/ProdigyMathGameHacking#568]
![image](https://user-images.githubusercontent.com/77288637/109559639-eaf5be00-7aa8-11eb-911d-f6f8f9ef637a.png)
Giant Error and can't add any specific item.

**Comment by ArcerionDev** [comment]
oooops

**Comment by ArcerionDev** [comment]
I'm dumb

**Comment by ArcerionDev** [comment]
just a mo

**Comment by ArcerionDev** [comment]
should be good now
