### ISSUE TITLE
Will not save epics or pets[BUG]

### ISSUE THREAD

**Issue by dimitricooper** [Prodigy-Hacking/ProdigyMathGameHacking#569]
***Description***:
When I click get all pets or epics. I then click save character and when I log in again it does not show them.

**Comment by dimitricooper** [comment]
Ok, I will try that.

**Comment by NX721** [comment]
Ok

**Comment by dimitricooper** [comment]
It worked. Thank you.

**Comment by NX721** [comment]
Np
