### ISSUE TITLE
[BUG] White screen when i try to answer a question 

### ISSUE THREAD

**Issue by irhrhd** [Prodigy-Hacking/ProdigyMathGameHacking#570]
***Description***:
White Screen when i try to awnser any questions 

***Replication***:

***Images***:

***Additional Errors***:

**Comment by dimitricooper** [comment]
I have never had this problem.

**Comment by ArcerionDev** [comment]
please send a screenshot

**Comment by ArcerionDev** [comment]
until then, run this
```js
_.instance.prodigy.education.closeFull()
```

**Comment by irhrhd** [comment]
Fixed it

**Comment by irhrhd** [comment]
Fixed it so
