### ISSUE TITLE
[BUG]Harmony Island bug.

### ISSUE THREAD

**Issue by TheSchmede** [Prodigy-Hacking/ProdigyMathGameHacking#572]
***Description***:
When I go and start a rune run, the button that says start rune run goes grey and clicking does not work. So I can't start it. It is possible that it is a problem with Prodigy because it still happens when I have the extension turned off but I do not know. 

***Replication***:
Go to Harmony Island, then go to the blue diamond. Next chose any monster. Noot will say something and then it freezes.

***Images***:
![Screen Shot 2021-03-01 at 5 35 30 PM](https://user-images.githubusercontent.com/66804076/109583293-893b5100-7ab4-11eb-986f-12dc007ba6bd.png)

***Additional Errors***:
None

**Comment by NX721** [comment]
Try turning on the extension and see if it works.

**Comment by PatheticMustan** [comment]
Ahhhhh! Open console, and screenshot any errors you see.

**Comment by dimitricooper** [comment]
![Screen Shot 2021-03-02 at 8 21 40 AM](https://user-images.githubusercontent.com/66804076/109679320-533bb280-7b30-11eb-984c-533d7f43d547.png)
That is the console when the error happens. Looks like there are a few errors.

**Comment by ArcerionDev** [comment]
uh

**Comment by ArcerionDev** [comment]
please export the console and send it here

**Comment by ArcerionDev** [comment]
export by right clicking, and clicking `Save As...`

**Comment by TheSchmede** [comment]
oh

**Comment by TheSchmede** [comment]
[play.prodigygame.com-1614705221200.log](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/files/6070489/play.prodigygame.com-1614705221200.log)

**Comment by PatheticMustan** [comment]
Continuing this in #459
