### ISSUE TITLE
Some areas can't be teleported to

### ISSUE THREAD

**Issue by NX721** [Prodigy-Hacking/ProdigyMathGameHacking#574]
![image](https://user-images.githubusercontent.com/77288637/109626638-c8968b80-7b0e-11eb-9224-f41bc5a954e9.png)
I used the hack then the screen froze.

**Comment by ArcerionDev** [comment]
@NX721 can't duplicate. Where did you teleport?

**Comment by NX721** [comment]
@ArcerionDev  I went to Shiverchill Mountains

**Comment by NX721** [comment]
Oh and B2 to be exact

**Comment by PatheticMustan** [comment]
Unfortunately can't be fixed, if the assets don't exist we can't fix that, it's nontrivial to see if a scene will work or not
