### ISSUE TITLE
Question UI is hidden

### ISSUE THREAD

**Issue by spacekitten45** [Prodigy-Hacking/ProdigyMathGameHacking#575]
***Description***:
cant answer questions or do anything, menu stuck behind the background

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/79455797/109641760-fc42d700-7b49-11eb-82c2-33caa9abe29e.png)

***Additional Errors***:
i have no pets or armour or anything hacked on my character

**Comment by PatheticMustan** [comment]
You have nothing hacked on your character but still encountered this bug..?

**Comment by ArcerionDev** [comment]
it's a layering issue, prodigy decided to get clever and set the layer of the question UI to the max integer, will make a button to close it on the extension

**Comment by achen6196** [comment]
That happened to me before but it don't because I don't really answer any question because I click win battle most of the time when I battle

**Comment by PatheticMustan** [comment]
ah, are there any  errors in console, or is it all just handy dandy

**Comment by PatheticMustan** [comment]
@ArcerionDev closed this..?

**Comment by achen6196** [comment]
> ah, are there any errors in console, or is it all just handy dandy

Who you talking to?

**Comment by PatheticMustan** [comment]
anybody who had the error, we can't continue without the actual error

**Comment by NameIsA** [comment]
> anybody who had the error, we can't continue without the actual error

battles are fine for me btw

**Comment by ArcerionDev** [comment]
no that was my fault

**Comment by ArcerionDev** [comment]
I tried doing some layering with WCM and that somehow kept it from being able to interact with the question UI

**Comment by ArcerionDev** [comment]
it should be fine now

**Comment by NameIsA** [comment]
okie
