### ISSUE TITLE
[BUG] Battle Team Glitch

### ISSUE THREAD

**Issue by irhrhd** [Prodigy-Hacking/ProdigyMathGameHacking#579]
***Description***:
When i try to change my battle team is says “You’ve Been inactive too long sign in again”
![EE8E31AE-7046-4555-9089-EEF594790FA9](https://user-images.githubusercontent.com/62729648/109679121-25ef0480-7b30-11eb-99bb-6fcd128b7d13.png)

***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
does this happen every single time?

**Comment by irhrhd** [comment]
Yes

**Comment by irhrhd** [comment]
Also Can i join The team on prodigy hacking i cant use discord but i can still help right?

**Comment by ArcerionDev** [comment]
please export and send your console here

**Comment by PixelMMO** [comment]
@irhrhd answer arc

**Comment by irhrhd** [comment]
I cant because my friend did it for me

**Comment by ArcerionDev** [comment]
then I can't help you

**Comment by NX721** [comment]
What is the discord invite link again my friend wants to join

**Comment by PatheticMustan** [comment]
discord.gg/XQDfbfq

**Comment by NX721** [comment]
Thx

**Comment by PixelMMO** [comment]
it doesn't show errors for me, it works perfectly fine when i change my battle team

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/109836171-e7317b00-7c11-11eb-825d-a4ec6bed5d53.png)
look at the top, what does ***fallow path*** have to do with ***battle team*** errors?

**Comment by PixelMMO** [comment]
@ArcerionDev

**Comment by PixelMMO** [comment]
thats **SUS**

**Comment by PatheticMustan** [comment]
closed until OP bothers to get a computer and screenshot the actual errors

**Comment by NX721** [comment]
> ![image](https://user-images.githubusercontent.com/79719521/109836171-e7317b00-7c11-11eb-825d-a4ec6bed5d53.png)
> look at the top, what does _**fallow path**_ have to do with _**battle team**_ errors?
> 
> i think its _**fake**_ tbh
> thats **SUS**

Use, close all popups and press disable inactivity kick

**Comment by ChickenOnYT** [comment]
> closed until OP bothers to get a computer and screenshot the actual errors
> you can't screenshot them on an ipad, ya know?

he has a PC now he told me on discord

**Comment by ChickenOnYT** [comment]
@NX721 i keep thinking you're @irhrhd because you type similar lmao

**Comment by NX721** [comment]
> @NX721 i keep thinking you're @irhrhd because you type similar lmao

Wtf

**Comment by NX721** [comment]
Wdym

**Comment by NX721** [comment]
> @NX721 i keep thinking you're @irhrhd because you type similar lmao

._.

**Comment by PatheticMustan** [comment]
Shut up.

OP, please screenshot errors.
