### ISSUE TITLE
Unable to use hack during a math problem. Feature Request

### ISSUE THREAD

**Issue by dimitricooper** [Prodigy-Hacking/ProdigyMathGameHacking#580]
**Is your feature request related to a problem? Please describe.**
I get pretty frustrated when I cannot use the hacks during a math problem.
**Describe the solution you'd like**
I just want to be able to use the hacks during a math problem.
**Describe alternatives you've considered**
I can sort of see the menu during a question but I can't click on anything.
**Additional context**
Here is what it looks like
![Screen Shot 2021-03-02 at 8 34 43 AM](https://user-images.githubusercontent.com/66804076/109681276-27213100-7b32-11eb-9f18-7f0da6276b28.png)

**Comment by ArcerionDev** [comment]
already reported
