### ISSUE TITLE
[BUG] Teleportation Errors

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#582]
***Description***:
when i try to teleport to places using the interactive teleport map some places everything shows up except the background is beige

***Replication***:
teleport to some places for example i did D4 in lamplight town

***Images***:
![image](https://user-images.githubusercontent.com/79719521/109702390-2b654280-7b62-11eb-9c0f-eca41c40eb0a.png)
![image](https://user-images.githubusercontent.com/79719521/109702453-3fa93f80-7b62-11eb-850f-6556a93603fb.png)

**Comment by ArcerionDev** [comment]
those areas are deleted from the game

**Comment by PixelMMO** [comment]
oh

**Comment by PixelMMO** [comment]
then why not remove them?

**Comment by ArcerionDev** [comment]
because they still count as valid areas, the assets are just deleted
