### ISSUE TITLE
[BUG] Error's on startup, tested multiple times, repeatable.

### ISSUE THREAD

**Issue by MelonMan101** [Prodigy-Hacking/ProdigyMathGameHacking#583]
***Description***:
"Uncaught (in promise) TypeError: Failed to fetch"

(async () => {
	const debug = false;

	const redirectorDomain = debug ? "http://localhost:1337" : "https://prodigyhacking.ml"

	if (!window.abortion) {
		// only run inject script once on the page, even if game.min is requested multiple times
		window.abortion = "Hey, we've injected the thingy";

		// check for outdated plugin
		const pluginVersion = chrome.runtime.getManifest().version;
		const supportedVersion = (await (await fetch(`${redirectorDomain}/version`)).text());

		if (pluginVersion !== supportedVersion) {
			const res = confirm("Outdated plugin version! Hacks are not guaranteed to work! If you would like to update, please click 'OK'");

			if (res) location = "https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/How-to-Update";
		}
	
		// die, integrity
		[...document.getElementsByTagName("script"), ...document.getElementsByTagName("link")].forEach(v => {
			if (v.integrity) {
				console.log(v.integrity);
				v.removeAttribute("integrity");
			}
		});
		// <link rel="preload" href="https://code.prodigygame.com/code/3-13-0/game.min.js?v=3-13-0" as="script" crossorigin="anonymous"></link>
		/*
		const prelly = document.createElement("link");
		prelly.rel = "preload";
		prelly.href = `${redirectorDomain}/game.min.js`;
		*/

		// <script src="https://code.prodigygame.com/code/3-13-0/game.min.js?v=3-13-0" onload="SW.Load.onGameLoad();" crossorigin="anonymous"></script>
		// we cancel the real game.min, and just append ours
		// a messy solution for sure, but this should only be a bandaid on a bulletwound
		const penguin = document.createElement("script");
		penguin.src = `${redirectorDomain}/game.min.js`;

		document.body.append(penguin);
	}
})();

***Replication***:
Startup prodigy, login, the loading with be stopped mid way through.

***Images***:
![image](https://user-images.githubusercontent.com/60020494/109702568-6798a300-7b62-11eb-9fa0-baba10dc74f4.png)

***Additional Errors***: That is all.

**Comment by ArcerionDev** [comment]
what happens when you visit https://prodigyhacking.ml/version?

**Comment by MelonMan101** [comment]
2.0.0

**Comment by PixelMMO** [comment]
reload the extension in chrome://extensions and it should work

**Comment by PixelMMO** [comment]
it was happening to me last week and i did that and it fixed

**Comment by MelonMan101** [comment]
still didnt work ^

**Comment by PixelMMO** [comment]
i can open prodigy just fine

**Comment by MelonMan101** [comment]
i have the same error each time i reload and try, i have no clue why.

**Comment by PixelMMO** [comment]
chrome://extensions/ press reload on the prodigy math game hacking extension

**Comment by PixelMMO** [comment]
send screenshot of the loading page and send another of you extensions in chrome://extensions

**Comment by MelonMan101** [comment]
> chrome://extensions press reload on the prodigy math game hacking extension

Ive already done this like 7 times.

**Comment by PixelMMO** [comment]
or just the prodigy math game hacking extension

**Comment by MelonMan101** [comment]
![image](https://user-images.githubusercontent.com/60020494/109706235-b2b4b500-7b66-11eb-94fc-b488f02bf2e2.png)
![image](https://user-images.githubusercontent.com/60020494/109706248-b811ff80-7b66-11eb-9d59-a53b18a6e880.png)

**Comment by irhrhd** [comment]
Hmm okay okay is the code you submited whats in the console

**Comment by MelonMan101** [comment]
> Hmm okay okay is the code you submited whats in the console

duh

**Comment by PixelMMO** [comment]
delete the extension and reinstall it

**Comment by irhrhd** [comment]
Wow dont be rude

**Comment by MelonMan101** [comment]
> delete the extension and reinstall it

already done that 3 times

**Comment by PixelMMO** [comment]
WELL THEN ITS YOUR PROBLEM

**Comment by MelonMan101** [comment]
> Wow dont be rude

wasnt trying to be

**Comment by irhrhd** [comment]
Lets see

**Comment by MelonMan101** [comment]
> WELL THEN ITS YOUR PROBLEM

not helping

**Comment by PixelMMO** [comment]
shut up

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/109706492-058e6c80-7b67-11eb-9a35-53da9a390fca.png)
works for me

**Comment by MelonMan101** [comment]
> shut up

if you aren't going to help leave.

**Comment by irhrhd** [comment]
Just stop arguing jeez

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/109706568-1d65f080-7b67-11eb-828e-66d6e9e23692.png)

**Comment by irhrhd** [comment]
Try making a new account

**Comment by PatheticMustan** [comment]
Ah! Sorry for pestering you one more time, but could you try uninstalling, and installing a fresh download of the plugin? Just need to be absolutely certain.

**Comment by NameIsA** [comment]
> Ah! Sorry for pestering you one more time, but could you try uninstalling, and installing a fresh download of the plugin? Just need to be absolutely certain.

they already did that, thats why they started telling eachother to shut up

**Comment by MelonMan101** [comment]
I have tried anything, im not the only one who has had the problem
a few friends of mine also tried and got the error.

**Comment by PatheticMustan** [comment]
ah, can you screenshot what browser you're on, and what extensions you have installed? Also, do you have a school filter or anything of that sort..?

**Comment by achen6196** [comment]
This happened to me before

**Comment by MelonMan101** [comment]
> ah, can you screenshot what browser you're on, and what extensions you have installed? Also, do you have a school filter or anything of that sort..?

I am on stock google, my school doesnt have a single restriction on prodigy or anything prodigy related, just youtube and coolmath.

**Comment by NameIsA** [comment]
so do this:

go to downloads delete the extension.zip/phex.zip file

remove the extension from chrome

install [CCleaner](https://www.ccleaner.com/) and make sure to tell it not to install AVG because AVG is like EA but antivirus edition

tell CCleaner to clean chrome cache

[install phex again](https://www.youtube.com/watch?v=AZzgQRV6O4k)

see if it works?

**Comment by MelonMan101** [comment]
> so do this:
> 
> go to downloads delete the extension.zip/phex.zip file
> 
> remove the extension from chrome
> 
> install [CCleaner](https://www.ccleaner.com/) and make sure to tell it not to install AVG because AVG is like EA but antivirus edition
> 
> tell CCleaner to clean chrome cache
> 
> [install phex again](https://www.youtube.com/watch?v=AZzgQRV6O4k)
> 
> see if it works?

Did this, didnt work, also just tried and also didnt work.

**Comment by NameIsA** [comment]
> > so do this:
> > go to downloads delete the extension.zip/phex.zip file
> > remove the extension from chrome
> > install [CCleaner](https://www.ccleaner.com/) and make sure to tell it not to install AVG because AVG is like EA but antivirus edition
> > tell CCleaner to clean chrome cache
> > [install phex again](https://www.youtube.com/watch?v=AZzgQRV6O4k)
> > see if it works?
> 
> Did this, didnt work, also just tried and also didnt work.

ah okay hmm this is very confusing

**Comment by ArcerionDev** [comment]
try installing [this](https://chrome.google.com/webstore/detail/setupvpn-lifetime-free-vp/oofgbpoabipfcfjapgnbbjjaenockbdp?hl=en-US).

**Comment by NameIsA** [comment]
> I have tried anything, im not the only one who has had the problem
> a few friends of mine also tried and got the error.

what internet provider do you use

install setupvpn like arc said

go to chrome://policies and screenshot the result

tell your friends to do the same so we can compare the results

**Comment by ArcerionDev** [comment]
that could be confidential

**Comment by NameIsA** [comment]
> that could be confidential

blackout your school part of the policies then

idrk how an ISP is confidential every website knows your ISP its about as confidential as an IP address

**Comment by MelonMan101** [comment]
> > that could be confidential
> 
> blackout your school part of the policies then
> 
> idrk how an ISP is confidential every website knows your ISP its about as confidential as an IP address

uhhhh, is it normal for my ip to *not* be there?

**Comment by MelonMan101** [comment]
![image](https://user-images.githubusercontent.com/60020494/109825525-e72c7d80-7c07-11eb-80d4-4bccb22a6a7d.png)

**Comment by NameIsA** [comment]
> > > that could be confidential
> > 
> > 
> > blackout your school part of the policies then
> > idrk how an ISP is confidential every website knows your ISP its about as confidential as an IP address
> 
> uhhhh, is it normal for my ip to _not_ be there?

your IP wont be with your ISP or chrome://policies, but chrome://policies might reveal your school (censor it using an image editor) and some ISPs are more common in some states so up to you

**Comment by ArcerionDev** [comment]
it looks ok, nothing restricted

**Comment by NameIsA** [comment]
okie ty for the chrome://policies nothing is restricted i dont need your ISP because that answers my question

**Comment by MelonMan101** [comment]
> > > > that could be confidential
> > > 
> > > 
> > > blackout your school part of the policies then
> > > idrk how an ISP is confidential every website knows your ISP its about as confidential as an IP address
> > 
> > 
> > uhhhh, is it normal for my ip to _not_ be there?
> 
> your IP wont be with your ISP or chrome://policies, but chrome://policies might reveal your school (censor it using an image editor) and some ISPs are more common in some states so up to you

also, its chrome://policy, not policies.

**Comment by ArcerionDev** [comment]
whatever

**Comment by NameIsA** [comment]
> > > > > that could be confidential
> > > > 
> > > > 
> > > > blackout your school part of the policies then
> > > > idrk how an ISP is confidential every website knows your ISP its about as confidential as an IP address
> > > 
> > > 
> > > uhhhh, is it normal for my ip to _not_ be there?
> > 
> > 
> > your IP wont be with your ISP or chrome://policies, but chrome://policies might reveal your school (censor it using an image editor) and some ISPs are more common in some states so up to you
> 
> also, its chrome://policy, not policies.

oh sorry i forgot what its called 😅

**Comment by MelonMan101** [comment]
> whatever

rad B)

**Comment by ArcerionDev** [comment]
I had a case where adblock prevented it from loading

**Comment by NameIsA** [comment]
install setupvpn like arc said to do, then follow my instructions to run the script... also thats true ("i had a case where adblock prevented it from loading") but i also recommend disabling anything like HTTPS Everywhere and all that which would modify requests

**Comment by ArcerionDev** [comment]
@MelonMan101 can you export your console and send the file here pls

**Comment by MelonMan101** [comment]
> @MelonMan101 can you export your console and send the file here pls

how does one do that

**Comment by ArcerionDev** [comment]
oh

**Comment by ArcerionDev** [comment]
open console
right click
click "save as..."
and send the resulting file

**Comment by NameIsA** [comment]
> WELL THEN ITS YOUR PROBLEM

no, it isnt. this is a friendly community and if someone has an issue with an extension, they can ask. if you arent interested in helping theme, you dont need to say that.

**Comment by PatheticMustan** [comment]
uh, I'm not sure if it's an issue with fetching, per se

clearly, they can access prodigyhacking.ml.version

I'm not sure why they can't access game.min, unless they have a school filter that checks for "game"...?

**Comment by PatheticMustan** [comment]
why

**Comment by PatheticMustan** [comment]
this is an actual issue, with multiple confirmers, we should probably try to get as much info from the community as possible

**Comment by ArcerionDev** [comment]
> why

bruh you should read it
these skids are getting a bit too mad at each other

**Comment by NameIsA** [comment]
> uh, I'm not sure if it's an issue with fetching, per se
> 
> clearly, they can access prodigyhacking.ml.version
> 
> I'm not sure why they can't access game.min, unless they have a school filter that checks for "game"...?

or the school blocked prodigy hacks? i mean the tech admninistrator could've been looking at logs and saw all these requests to "prodigyhacking.ml" and thought it was sus and blocked it out of sus

**Comment by NameIsA** [comment]
> > why
> 
> bruh you should read it
> these skids are getting a bit too mad at each other

the argument is old and calmed down tho

**Comment by NameIsA** [comment]
i seriously feel like this is something the school did

**Comment by NameIsA** [comment]
@MelonMan101 what extensions do you use

**Comment by ArcerionDev** [comment]
^^

**Comment by MelonMan101** [comment]
So, for the 70 somethingth time of restarting prodigy, getting console logs, it worked, if it errors again i will just open a new issue.

**Comment by NameIsA** [comment]
> So, for the 70 somethingth time of restarting prodigy, getting console logs, it worked, if it errors again i will just open a new issue.

i think it would be nice to find the cause of this still

**Comment by PatheticMustan** [comment]
I have a feeling the solution has something to do with restarting the browser/clearing cache
Maybe just restarting your computer fixes it...?

**Comment by ArcerionDev** [comment]
yeah because if the site was down at any point, it caches it as down

**Comment by NameIsA** [comment]
> I have a feeling the solution has something to do with restarting the browser/clearing cache
> Maybe just restarting your computer fixes it...?

could be, yes

**Comment by NameIsA** [comment]
> yeah because if the site was down at any point, it caches it as down

smart

**Comment by NameIsA** [comment]
> > yeah because if the site was down at any point, it caches it as down
> 
> smart

actually wait when i told them to use ccleaner to clean any cache on the pc they said they already did that tho

**Comment by ArcerionDev** [comment]
that's why I'd suggest adding a parameter that just has a vale of Date.now(), that's what I did for wcm to handle updates

**Comment by PatheticMustan** [comment]
also smart! Will add now

**Comment by ArcerionDev** [comment]
![image](https://user-images.githubusercontent.com/60945964/109830334-658b1e80-7c0c-11eb-9612-d4826236073e.png)
here's the src

**Comment by PatheticMustan** [comment]
the weirdest part about it is that it's in `disableIntegrity.js`

**Comment by PatheticMustan** [comment]
> ![image](https://user-images.githubusercontent.com/60945964/109830334-658b1e80-7c0c-11eb-9612-d4826236073e.png)
> here's the src

that doesn't do anything, if you want to make sure it's not cached, you'll have to do it from phex

**Comment by BoredFishRE** [comment]
Lmao this is because the extension couldn't reach prodigyhacking.ml. one of the reasons i did https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/52995b39aaded8cfca58af667ad33466d69607e0
