### ISSUE TITLE
[BUG] PRODIGY NOT LOADING

### ISSUE THREAD

**Issue by noa94491** [Prodigy-Hacking/ProdigyMathGameHacking#585]
***Description***:
I installed the extension and now prodigy will not load. Prodigy has been loading for an hour. I tried to reinstall the extension and it didn't work. When the extension was uninstalled prodigy worked fine! Please help me.

***Images***:
![Clipped_Loading_Screen](https://user-images.githubusercontent.com/79106666/109710394-9bc49180-7b6b-11eb-9c22-2290ae7690bc.png)

***Additional Errors***:
None

**Comment by TheSchmede** [comment]
What happens when you go here?
https://prodigyhacking.ml/version

**Comment by noa94491** [comment]
I restarted my router and it works now.

**Comment by TheSchmede** [comment]
Awesome. Can you close the error?

**Comment by TheSchmede** [comment]
@ArcerionDev Can you make me a contributer? I know how to help people with the hack.

**Comment by PatheticMustan** [comment]
we'll think about making a group for github helpers.
