### ISSUE TITLE
I am making super short Prodigy hacking tutorials on YouTube

### ISSUE THREAD

**Issue by NameIsA** [Prodigy-Hacking/ProdigyMathGameHacking#587]
Here's the link: https://www.youtube.com/watch?v=AZzgQRV6O4k

I plan to make more videos about Prodigy, too. I'll probably make some more hacking tutorials as well.

I feel like the short video length helps because all the top results on YT are currently super long to increase ad revenue, but that isn't the best for people trying to learn.

**Comment by irhrhd** [comment]
Whats the name of it? Just tell me please so i can try to search it up

**Comment by irhrhd** [comment]
Its blocked so ima search it up to try to bypass theres hack i know on how to bypass

**Comment by NameIsA** [comment]
> Whats the name of it? Just tell me please so i can try to search it up

https://www.youtube.com/watch?v=AZzgQRV6O4k

**Comment by NameIsA** [comment]
> Its blocked so ima search it up to try to bypass theres hack i know on how to bypass

o ok

btw i recommend a proxy like censordodge, hide.me/en/proxy, etc.

**Comment by irhrhd** [comment]
All the proxys are blocked too ripppppp

**Comment by NameIsA** [comment]
> All the proxys are blocked too ripppppp

https://www.censordodge.com/ ?

**Comment by irhrhd** [comment]
Yep ripppp

**Comment by NameIsA** [comment]
https://yeet-was-here.herokuapp.com/ wait try that one

i know a script kiddie who copied it from a github repository and called it his proxy but its so dead that i doubt any security software knows it yet

**Comment by irhrhd** [comment]
Wholy S*** it works

**Comment by irhrhd** [comment]
Thanks

**Comment by ArcerionDev** [comment]
@NameIsA yknow you need to give us credit unless you want it dmcad

**Comment by ArcerionDev** [comment]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/tree/master/YOUTUBE_ATTRIBUTION.md

**Comment by NameIsA** [comment]
> @NameIsA yknow you need to give us credit unless you want it dmcad

okokok

**Comment by NameIsA** [comment]
ok i added it to the description honestly though the first thing in the video it says is to go to this repository on github lol

**Comment by NameIsA** [comment]
> Thanks

yw

**Comment by ArcerionDev** [comment]
> ok i added it to the description honestly though the first thing in the video it says is to go to this repository on github lol

***rules are rules***

**Comment by irhrhd** [comment]
What the name of ur channel it just shows a monkey with spyglass when i try to go to the video

**Comment by ArcerionDev** [comment]
oh yay it was taken down

**Comment by ArcerionDev** [comment]
wait bruh what

**Comment by NameIsA** [comment]
> What the name of ur channel it just shows a monkey with spyglass when i try to go to the video

my channel's C_On_YT https://www.youtube.com/channel/UCOyliCBOGXoeWsxx6XjQ_Kw/about

**Comment by irhrhd** [comment]
Do you have any ded proxys

**Comment by NameIsA** [comment]
https://tonernews.com/glype/

**Comment by irhrhd** [comment]
Blocked also i cant get apps

**Comment by NameIsA** [comment]
> Blocked also i cant get apps

o damn okay gimme a moment

**Comment by NameIsA** [comment]
ok idrk

**Comment by irhrhd** [comment]
I might be able to get apps of someone downloaded them with my student apple id  because i can get apps that have already been gotten with my appleid but i cant get others

**Comment by NameIsA** [comment]
> I might be able to get apps of someone downloaded them with my student apple id because i can get apps that have already been gotten with my appleid but i cant get others

could you ask your school if you're allowed to install a python coding app because you want to code i would assume they'd be okie with it

**Comment by irhrhd** [comment]
Nope they wont it cost money plus they dont really listen to the students

**Comment by irhrhd** [comment]
I mean my idea would work but i dont have a separate apple device

**Comment by NameIsA** [comment]
> Nope they wont it cost money plus they dont really listen to the students

oh damnit i didnt know it costs money

aaa its very hard to code on an ipad rip

**Comment by irhrhd** [comment]
![54098130-4E8F-4480-8000-25C17B8A2F83](https://user-images.githubusercontent.com/62729648/109737852-a25b0500-7b7b-11eb-9cc0-6682b1b6c165.jpeg)

**Comment by NameIsA** [comment]
ah okie i see

**Comment by irhrhd** [comment]
Yeah if anyone had a apple device then they could do it but no body wants to help prob

**Comment by irhrhd** [comment]
Plus idk if i culd trust anyone with my school apleid

**Comment by irhrhd** [comment]
Or someone could just code to get past it but idk

**Comment by PatheticMustan** [comment]
sad

**Comment by irhrhd** [comment]
Yes very very sad

**Comment by irhrhd** [comment]
@NameIsA you there still

**Comment by NameIsA** [comment]
> @NameIsA you there still

back

**Comment by irhrhd** [comment]
Okay im very very sad

**Comment by irhrhd** [comment]
Because i cant learn how to code or get apps

**Comment by irhrhd** [comment]
And i know everyone is ignoring me now but whatever

**Comment by NameIsA** [comment]
https://cdn.discordapp.com/attachments/723730285539360860/816400531021889576/b54gmts71mk61.gif

**Comment by irhrhd** [comment]
You cow rolled me

**Comment by irhrhd** [comment]
It says 404 when i try to use discord on the proxy

**Comment by NameIsA** [comment]
o wth

**Comment by irhrhd** [comment]
Yeah

**Comment by irhrhd** [comment]
But the cdn discord app thing worked

**Comment by PatheticMustan** [comment]
ty @NameIsA for the video

**Comment by irhrhd** [comment]
Anyone want to help me make a proxie?

**Comment by PatheticMustan** [comment]
no

**Comment by ArcerionDev** [comment]
please keep all issue discussion ON TOPIC

**Comment by ArcerionDev** [comment]
I'm talking to you @irhrhd
