### ISSUE TITLE
Uploading PHEx to Microsoft Web Store

### ISSUE THREAD

**Issue by ChickenOnYT** [Prodigy-Hacking/ProdigyMathGameHacking#592]
**Problem**
I have seen many users on this repository asking for browser extensions for web browsers such as Microsoft Edge.

**Solution**
 [Interestingly, Edge, Opera, and Brave are all based on Chromium](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension). With limited changes, we could expand to Edge, Opera, Brave, and Chrome- all we have to consider is intellectual property (#576).

**Considerations**
[Microsoft Edge does not support all the same APIs as Chrome does for extensions](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/api-support), but it supports most of them.

**Comment by PixelMMO** [comment]
why cant people just change to chrome?

**Comment by NameIsA** [comment]
> why cant people just change to chrome?

school or family could disallow it

**Comment by PatheticMustan** [comment]
I think this would be a really good idea!

**Comment by NameIsA** [comment]
yes

i will look into it more now because today is early release from education jail day

**Comment by NameIsA** [comment]
FINGERS ARE CROSSED
![image](https://user-images.githubusercontent.com/61570792/109884234-7dc16480-7c31-11eb-8716-503b1ba077bd.png)

**Comment by NameIsA** [comment]
next up:
opera, brave, chrome

**Comment by NameIsA** [comment]
let's keep this open until microsoft responds to us

**Comment by PatheticMustan** [comment]
literal god

**Comment by NameIsA** [comment]
![image](https://user-images.githubusercontent.com/61570792/109914168-4324ef80-7c64-11eb-8cd6-fb7c3f089f4b.png)
better screenshots will add to stuff later

**Comment by BoredFishRE** [comment]
Bro i've tried the extension on edge and it works...

**Comment by NameIsA** [comment]
> Bro i've tried the extension on edge and it works...

it does ik

**Comment by NameIsA** [comment]
the whole point of this was trying to get it onto the microsoft web store

**Comment by BoredFishRE** [comment]
oh ye i can see what I can do

**Comment by BoredFishRE** [comment]
@NameIsA ight man it's under review

**Comment by NameIsA** [comment]
bruh I've already submitted it

**Comment by BoredFishRE** [comment]
excuse me what

**Comment by BoredFishRE** [comment]
bruh

**Comment by alvzboys2** [comment]
can i ask you some
________________________________

**Comment by alvzboys2** [comment]
hellooooooooooo
________________________________

**Comment by CyberXVI** [comment]
> Bro i've tried the extension on edge and it works...

im on edge rn

**Comment by alvzboys2** [comment]
do you now to fix stuff

**Comment by alvzboys2** [comment]
im having a hard time

**Comment by alvzboys2** [comment]
ones i want to battle it frezzes

**Comment by NameIsA** [comment]
> excuse me what

bruh i was working on this whole like portability thing i started yesterday when i was bored

just cancel your submission or wait on it because microsoft will deny one and accept one... unless different people see both of our extensions because then we'll have a problem

**Comment by BoredFishRE** [comment]
I know, but we would rather it be on an account linked to our stuff, than just you. We submitted it with the support@prodigyhacking.com address

**Comment by BoredFishRE** [comment]
would be much better if we had it on something we can use for other things and we can have direct access to it at any time.

**Comment by BoredFishRE** [comment]
also I've already submitted it to firefox.

**Comment by CyberXVI** [comment]
> ones i want to battle it frezzes

before you go into a battle, click on "Fix Battle Crash"
it should say **Success!** Fixed Kennel Attack Bug.

**Comment by alvzboys2** [comment]
can you help me plssss
________________________________

**Comment by irhrhd** [comment]
Is it bad that i can see your guys emails and real names

**Comment by NameIsA** [comment]
> I know, but we would rather it be on an account linked to our stuff, than just you. We submitted it with the [support@prodigyhacking.com](mailto:support@prodigyhacking.com) address

bruh

ok

**Comment by BoredFishRE** [comment]
that's not the point...

**Comment by NameIsA** [comment]
> that's not the point...

what is your point? is it that you dont want me to be shown as the developer? because i set the publisher display name to "PMGH". i dont see what your problems are, unless it's just that "omg dck is a super bad guy that will try to destroy prodigy hacking real"

**Comment by BoredFishRE** [comment]
Alright A. Everything will be going to a completely separate email, B. We would not be the owner of the account, and C. We can't afford to have another mike incident. It's better safe than sorry.

**Comment by NameIsA** [comment]
> Alright A. Everything will be going to a completely separate email, B. We would not be the owner of the account, and C. We can't afford to have another mike incident. It's better safe than sorry.

i know you dont want another mike incident, but i had really started this whole project of making prodigy hacking portable across different platforms and then you just listen to me until it's all planned out then tell me i dont have a say in it anymore and take the changes and publish them on your own without my help even though i was the one who had been working on bringing the extension to other browsers

**Comment by NameIsA** [comment]
> B. We would not be the owner of the account, and

I don't care who owns it, I just want partial control over the extension because I've been working on it pretty hard and I want to have a say in this whole portability project

**Comment by NameIsA** [comment]
> A. Everything will be going to a completely separate email

this is just repeating issue B

**Comment by PatheticMustan** [comment]
I kinda agree with both of you, while yeah, DCK did work super hard on the extensions, it's a scary thing to give trust. (I think possibly unbanning dck would be alright, as long as he promises to stop trying to hack skids)

**Comment by NameIsA** [comment]
I haven't hacked skids in a while.

Idrc if you own the extension, I just feel like I made a lot of the new stuff then you take it and upload it all yourself. But yeah I do see the security reasons.

**Comment by BoredFishRE** [comment]
Alright @NameIsA, I can give you credit on the thing, all I want is just to have the extension published by us. That's it.

**Comment by NameIsA** [comment]
okie

**Comment by BoredFishRE** [comment]
So if you could like remove the extension on your end that would be cool ok thank

**Comment by NameIsA** [comment]
> So if you could like remove the extension on your end that would be cool ok thank

okie

**Comment by NameIsA** [comment]
also make sure to reply here once microsoft replies

**Comment by PatheticMustan** [comment]
gg
![image](https://user-images.githubusercontent.com/35382971/110475940-71189280-80af-11eb-84c5-b81e133d208e.png)

**Comment by ArcerionDev** [comment]
ight
