### ISSUE TITLE
[BUG] モーフがクラッシュする

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#594]
***Description***:
モーフィングしようとすると、前にモーフィングがクラッシュした場合に押してもゲームがクラッシュします

***Replication***:
何かに変身してみてください

**Comment by PixelMMO** [comment]
この問題を修正してください

**Comment by NameIsA** [comment]
Yes, I know that happens, it's already been discovered. But please write in English.

**Comment by PixelMMO** [comment]
こんにちは？

**Comment by PixelMMO** [comment]
> Yes, I know that happens, it's already been discovered. But please write in English.

?

**Comment by NameIsA** [comment]
この問題はすでに特定されていますが、英語で書いてください。

**Comment by PixelMMO** [comment]
何を言っている

**Comment by PixelMMO** [comment]
私は英語で書くことができません

**Comment by NameIsA** [comment]
> 何を言っている

繰り返します：

> この問題はすでに特定されていますが、英語で書いてください。

**Comment by PixelMMO** [comment]
like this?

**Comment by PixelMMO** [comment]
write like this?

**Comment by NameIsA** [comment]
> 私は英語で書くことができません

あなたは今日早く英語で書いていました-

**Comment by PixelMMO** [comment]
oh

**Comment by NameIsA** [comment]
> write like this?

Yes. You were writing in English already. Don't randomly use another langugae, please.

**Comment by PixelMMO** [comment]
i didnt know that was english XD

**Comment by PixelMMO** [comment]
Japanese is my main language

**Comment by NameIsA** [comment]
Hm, okay.

**Comment by PixelMMO** [comment]
ッ
