### ISSUE TITLE
Porting the extension to mobile

### ISSUE THREAD

**Issue by ChickenOnYT** [Prodigy-Hacking/ProdigyMathGameHacking#600]
Few ways to do this:

1. <s>Mobile Tampermonkey, which surprisingly exists.</s> only works on android, some people cant install apps
2. A mobile app that modifies requests. not 100% sure if this would be allowed on app stores, but some people might not be able to install apps so idk
3. <s>An app for rooted/jailbroken devices that allows you to modify the Prodigy app to inject a hack into it or something.</s> most users cant jailbreak/root due to school restrictions and old as heck devices and stuff
4. Recode WCM to use script-based hacks and it's injected via a bookmarklet
5. Make a website where people can modify accounts via username + password & create accounts with custom data.

**Comment by NameIsA** [comment]
Honestly, we should just make a website where people tell the website what to put in an account and it generates the account accordingly. This would be great for mobile users.

**Comment by PatheticMustan** [comment]
Another method that (surprisingly) works on mobile is bookmarklets, you can run javascript with bookmarks by prepending javascript:

**Comment by irhrhd** [comment]
> Another method that (surprisingly) works on mobile is bookmarklets, you can run javascript with bookmarks by prepending javascript:
> 
> of course this is limited to script based hacks, but....

Okay so how do i bookmark it and is it possible yet

**Comment by irhrhd** [comment]
Guys i know how to make it work

**Comment by irhrhd** [comment]
Bookmarks work right so you can use javascript to do the hacks on mobile with a bookmark ill show you

**Comment by NameIsA** [comment]
Yeah, we can do script-based hacks, but it would require a complete recode of WCM- JS bookmarklets can't modify requests like PHEx does.

**Comment by irhrhd** [comment]
Well there is a different way but its not working
![AE8FD1E0-711D-4AA3-AF51-D6EF52EA9C60](https://user-images.githubusercontent.com/62729648/109897237-43fb5880-7c47-11eb-938d-597bea0924be.png) 
https://caiorss.github.io/bookmarklet-maker/

**Comment by NameIsA** [comment]
> Well there is a different way but its not working
> ![AE8FD1E0-711D-4AA3-AF51-D6EF52EA9C60](https://user-images.githubusercontent.com/62729648/109897237-43fb5880-7c47-11eb-938d-597bea0924be.png)
> https://caiorss.github.io/bookmarklet-maker/

The way PHEx works is much more complicated than you think. It works by directly modifying the Prodigy source code in a way that JS running via console/bookmarklets cannot do. We can use script-based hacks via bookmarklets, but Will's Cheat Menu would have to be entirely recoded.

**Comment by irhrhd** [comment]
Let me help you recode it

**Comment by irhrhd** [comment]
Please

**Comment by irhrhd** [comment]
I have a code editor now on my ipad and i can do stuff now

**Comment by NameIsA** [comment]
We probably will not recode it, unless we have to. We have a lot of options and we need to decide on the most efficient and sophisticated method.

**Comment by irhrhd** [comment]
If it requires jailbreak then ripp meeee

**Comment by NameIsA** [comment]
> Another method that (surprisingly) works on mobile is bookmarklets, you can run javascript with bookmarks by prepending javascript:
> 
> of course this is limited to script-based hacks, but...

It does work, the only issue is what I said earlier:
> The way PHEx works is much more complicated than you think. It works by directly modifying the way your computer interpets Prodigy source code in a way that JS running via console/bookmarklets cannot do. We can use script-based hacks via bookmarklets, but Will's Cheat Menu would have to be entirely recoded.

So we would have to do a lot of re-coding. It's possible, but it would be best to do something easier.

**Comment by NameIsA** [comment]
> If it requires jailbreak then ripp meeee

It likely will not, as most users cannot use an iOS jailbreak.

**Comment by irhrhd** [comment]
Oh thank gosh

**Comment by PatheticMustan** [comment]
It's not an issue with jailbreak, ios just plain doesn't support chrome extensions.
If we could host a modified version of prodigy with the gamefiles already injected, that would also work....

**Comment by NameIsA** [comment]
> It's not an issue with jailbreak, ios just plain doesn't support chrome extensions.
> If we could host a modified version of prodigy with the gamefiles already injected, that would also work....

but that's something they could DMCA

**Comment by PatheticMustan** [comment]
Yeah ik, was just thinking about solutions

**Comment by NameIsA** [comment]
600th issue or pr (500th is deleted or sum sad)

**Comment by NameIsA** [comment]
well i've replied to all the hundred big boi numbers i really need to find a hobby

**Comment by NameIsA** [comment]
bump

**Comment by irhrhd** [comment]
Bump whut

**Comment by ChickenOnYT** [comment]
im just reminding people that have replied here that we need to work on this

**Comment by irhrhd** [comment]
Oh okay im working on solutions

**Comment by ChickenOnYT** [comment]
we'll either do tampermonkey or website thing

**Comment by irhrhd** [comment]
Oh im working on bookmarklets i guess ill stop

**Comment by ChickenOnYT** [comment]
> Oh im working on bookmarklets i guess ill stop

we could do that but it would be too complicated

**Comment by ChickenOnYT** [comment]
https://github.com/Prodigy-Hacking/Tokenify this might work if we make the user solve a captcha then we just send the captcha into prodigy

**Comment by irhrhd** [comment]
Oh okay i wouldnt be able to do tampermonkey ill just try to do the
bookmarklets

**Comment by ChickenOnYT** [comment]
we will have a website where you can create/modify accounts with the username and password

**Comment by irhrhd** [comment]
Ah okay

**Comment by PatheticMustan** [comment]
> Recode WCM to use script-based hacks and it's injected via a bookmarklet
not possible, it's just not usable without modifying the game files

**Comment by ChickenOnYT** [comment]
ok

**Comment by UntrustableRus** [comment]
I'll take on this issue, using a method that you didn't list.

**Comment by ChickenOnYT** [comment]
add that to this issue pls

**Comment by UntrustableRus** [comment]
> add that to this issue pls

New issue: #694

**Comment by ChickenOnYT** [comment]
mk
