### ISSUE TITLE
[HR]Summon ID

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#602]
**Describe the hack in 5 words or less:**
spawn entities by entity ID

**Have you made sure this hack isn't available yet?**
yes, i have made sure

**Comment by PixelMMO** [comment]
it would be cool to have a hack in the menu that you could summon entities like the titan, monsters, NPCs, etc by typing the ID connected to that entity allowing you to summon monsters and People anywhere.

**Comment by NameIsA** [comment]
> it would be cool to have a hack in the menu that you could summon entities like the titan, monsters, NPCs, etc by typing the ID connected to that entity allowing you to summon monsters and People anywhere.

i mean yeah but it wouldnt show up for other players because of how prodigy works

**Comment by PixelMMO** [comment]
ok

**Comment by PixelMMO** [comment]
but still

**Comment by NameIsA** [comment]
i mean yeah we can but not for a while

**Comment by SomeCodingCoolGuy** [comment]
Most of the Prodigy community don't even know the ID for Shadow entities. You could put a ID hack guide for newbies who install the extension.

**Comment by SomeCodingCoolGuy** [comment]
> > it would be cool to have a hack in the menu that you could summon entities like the titan, monsters, NPCs, etc by typing the ID connected to that entity allowing you to summon monsters and People anywhere.
> 
> i mean yeah but it wouldnt show up for other players because of how prodigy works
Hmm... good point.

**Comment by SomeCodingCoolGuy** [comment]
Anyway, the Summon ID idea is great, in my opinion, but the PMGH team would need to put some more work into that.

**Comment by PatheticMustan** [comment]
no

**Comment by mickealw15** [comment]
i want to summon luminite

**Comment by LeoBadeaux** [comment]
> I might be interpreting this wrong but, this seems to be a niche client-side hack just for cosmetics. I think this issue should just be closed, because fixing the current broken hacks is more important.

Yes, and we would likely need to write a bunch of code to import the character into the game canvas element.
