### ISSUE TITLE
patheticmustan i need to talk to you

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#608]

**Comment by PixelMMO** [comment]
when i try to open https://prodigyhacking.com/extension it says that there is insecure content on the page, can you help me get into it please

**Comment by CyberXVI** [comment]
lemme see a picture pls
i think i know how to fix it

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/110002922-e6691980-7ce3-11eb-9bcd-39d10e0c3d85.png)

**Comment by irhrhd** [comment]
Use this proxy https://yeet-was-here.herokuapp.com/

**Comment by CyberXVI** [comment]
when i click on it, it makes me download something

**Comment by irhrhd** [comment]
Use the proxy then see if it works

**Comment by PixelMMO** [comment]
not working

**Comment by PixelMMO** [comment]
its not working

**Comment by NameIsA** [comment]
@PatheticMustan

**Comment by NameIsA** [comment]
school filter or something

**Comment by irhrhd** [comment]
![D5EC2051-9C9F-4619-9F01-B7CAFB31C0DB](https://user-images.githubusercontent.com/62729648/110003493-499a8200-7ccb-11eb-879c-8e9335c38ae6.png)
![BE007D32-EEC1-4F0E-9ABB-E4F4AB2140C5](https://user-images.githubusercontent.com/62729648/110003543-5323ea00-7ccb-11eb-8ed9-4d567af1db2b.jpeg)

**Comment by PixelMMO** [comment]
> school filter or something

probably

**Comment by PixelMMO** [comment]
that?

**Comment by irhrhd** [comment]
Yes thats it

**Comment by irhrhd** [comment]
So it does work

**Comment by PixelMMO** [comment]
i downloaded that from PHEx.zip

**Comment by PatheticMustan** [comment]
I'll look at it when I get home.

**Comment by PixelMMO** [comment]
ok

**Comment by PixelMMO** [comment]
i got PHEx.zip from https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/README.md

**Comment by PatheticMustan** [comment]
ok
