### ISSUE TITLE
its working for me

### ISSUE THREAD

**Issue by alvzboys2** [Prodigy-Hacking/ProdigyMathGameHacking#609]
its working for me
![image](https://user-images.githubusercontent.com/79719521/110018427-44eac380-7cf5-11eb-827c-eef1d7275c7d.png)

_Originally posted by @PixelMMO in https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/issues/493#issuecomment-790867317_

**Comment by NameIsA** [comment]
just reply on that issue dont make a new issue
