### ISSUE TITLE
anyway

### ISSUE THREAD

**Issue by NameIsA** [Prodigy-Hacking/ProdigyMathGameHacking#610]
gonna be inactive for a while because im trying to find new things to do

**Comment by NX721** [comment]
Ok

**Comment by NX721** [comment]
Me too 
![image](https://user-images.githubusercontent.com/77288637/110032758-859f0880-7d06-11eb-9488-bfc10c532c8e.png)
![image](https://user-images.githubusercontent.com/77288637/110032784-8cc61680-7d06-11eb-9525-469cecae43de.png)
![image](https://user-images.githubusercontent.com/77288637/110032873-abc4a880-7d06-11eb-9afc-127e342b974c.png)

**Comment by TheSchmede** [comment]
Some odd mail you got there.
lol

**Comment by NameIsA** [comment]
will be a bit active tho

just not as much

**Comment by PatheticMustan** [comment]
epic, ty for being active, @NameIsA!

**Comment by NameIsA** [comment]
yw :D
