### ISSUE TITLE
Prodigy Is Offline

### ISSUE THREAD

**Issue by LandynM1030** [Prodigy-Hacking/ProdigyMathGameHacking#611]
Error Code 72?

![Screenshot 2021-03-04 at 2 19 07 PM](https://user-images.githubusercontent.com/80073253/110038815-2258aa80-7cf5-11eb-99e7-02a8f58cc559.png)

Error Code 72

*Sorry if i'm an idiot*

**Comment by irhrhd** [comment]
No your fine your not an idiot

**Comment by irhrhd** [comment]
Hey can you try logging in again for me please

**Comment by PatheticMustan** [comment]
try again please

**Comment by irhrhd** [comment]
Sorry @PatheticMustan for trying to help i just really want to but i cant cause i cant use discord

**Comment by NameIsA** [comment]
@LandynM1030 if this happens again open console and screenshot errors. but if it doesnt keep happening, just tell us and close this issue.
