### ISSUE TITLE
Where is the arena point website

### ISSUE THREAD

**Issue by irhrhd** [Prodigy-Hacking/ProdigyMathGameHacking#619]
Arena point website?

**Comment by PixelMMO** [comment]
good question, ive been wanting to hack my arena points but idk where the page is to do it

**Comment by PixelMMO** [comment]
@ArcerionDev please send the link to the arena point tab

**Comment by NameIsA** [comment]
its a WIP or sum

**Comment by NameIsA** [comment]
@PatheticMustan @ArcerionDev can you close this
