### ISSUE TITLE
its not really a rack but can you see if you can rename something fer me :3

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#621]
**Describe the thing in 5 words or less:**
DRUGS

**please rename this item to drugs**
![image](https://user-images.githubusercontent.com/79719521/110141270-fbf14880-7da2-11eb-84c9-6428beda13e3.png)

**Comment by PixelMMO** [comment]
who knows what they will grow into XD

**Comment by PixelMMO** [comment]
sounds like drugs to me LOL

**Comment by ArcerionDev** [comment]
hahahahahahaha

no

**Comment by NameIsA** [comment]
drugs

**Comment by NameIsA** [comment]
i have some xanax if you want it

im high on xanax

**Comment by NameIsA** [comment]
> who knows what they will grow into XD

THEY WILL GROW INTO METH

PRODIGY METH GAME

**Comment by ArcerionDev** [comment]
***locks conversation***
