### ISSUE TITLE
[BUG] shops wont open

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#623]
***Description***
when i try to open a shop it says that shops are closed

***Images***
![image](https://user-images.githubusercontent.com/79719521/110150954-da498e80-7dad-11eb-8e2d-70956969a4f7.png)
![image](https://user-images.githubusercontent.com/79719521/110151052-fb11e400-7dad-11eb-9d1c-873977d9d35d.png)

**Comment by NameIsA** [comment]
403 means forbidden. could you screenshot your entire console?

**Comment by ArcerionDev** [comment]
hmm

**Comment by PixelMMO** [comment]
i did
![image](https://user-images.githubusercontent.com/79719521/110151145-1d0b6680-7dae-11eb-8a6c-ea551d25554b.png)
that popped up when i tried to open a shop

**Comment by ArcerionDev** [comment]
I don't think it's inventory related

**Comment by NameIsA** [comment]
also, i've seen this happen to people randomly for no apparent cause, could you try to log out and login again?

**Comment by ArcerionDev** [comment]
wait no

**Comment by ArcerionDev** [comment]
first

**Comment by NameIsA** [comment]
> i did
> ![image](https://user-images.githubusercontent.com/79719521/110151145-1d0b6680-7dae-11eb-8a6c-ea551d25554b.png)
> that popped up when i tried to open a shop

anything else in the console? there's usually more in there

**Comment by ArcerionDev** [comment]
go onto the "network" tab

**Comment by PixelMMO** [comment]
i already tried and it didnt work

**Comment by NameIsA** [comment]
> i already tried and it didnt work

okie

**Comment by ArcerionDev** [comment]
and type in `https://api.prodigygame.com/game-store-api` and find the one in red

**Comment by ArcerionDev** [comment]
then

**Comment by PatheticMustan** [comment]
can anybody else replicate?

**Comment by ArcerionDev** [comment]
screenshot the "response" tab when you click on that

**Comment by NameIsA** [comment]
> can anybody else replicate?

im in school rn

**Comment by ArcerionDev** [comment]
> can anybody else replicate?

haven't tried

**Comment by ArcerionDev** [comment]
will look

**Comment by PatheticMustan** [comment]
for gods sake, Arc
one message please

**Comment by NameIsA** [comment]
> go onto the "network" tab

in the ctrl+shift+i thing right?

**Comment by NameIsA** [comment]
> for gods sake, Arc
> one message please

^^^^

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/110151378-66f44c80-7dae-11eb-8de9-53c6855b5509.png)

**Comment by NameIsA** [comment]
@PixelMMO hacker tag or something????

**Comment by PixelMMO** [comment]
wait

**Comment by NameIsA** [comment]
go to ctrl+shift+i thing

go to network tab in the popup thing

type `https://api.prodigygame.com/game-store-api` into filter

right click a random one, copy, copy all as fetch

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/110151527-9b680880-7dae-11eb-86e4-35633ec28418.png)
![image](https://user-images.githubusercontent.com/79719521/110151592-a6bb3400-7dae-11eb-8c87-5bcbc7271753.png)
![image](https://user-images.githubusercontent.com/79719521/110151639-b8044080-7dae-11eb-822c-59206bd61c5b.png)

**Comment by ArcerionDev** [comment]
wait no

**Comment by NameIsA** [comment]
> go to ctrl+shift+i thing
> 
> go to network tab in the popup thing
> 
> type `https://api.prodigygame.com/game-store-api` into filter
> 
> right click a random one, click copy, click copy all as fetch
> 
> paste the code added to your clipboard here

do this @PixelMMO

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/110151784-e2ee9480-7dae-11eb-950a-bb5859264732.png)

**Comment by NameIsA** [comment]
darn it ok @PixelMMO

**Comment by ArcerionDev** [comment]
he must have closed out

**Comment by PixelMMO** [comment]
she*

**Comment by ArcerionDev** [comment]
![image](https://user-images.githubusercontent.com/60945964/110151896-044f8080-7daf-11eb-81cd-c0bbd1e8b8f2.png)
works fine for me

**Comment by NameIsA** [comment]
> ![image](https://user-images.githubusercontent.com/60945964/110151896-044f8080-7daf-11eb-81cd-c0bbd1e8b8f2.png)
> works fine for me

i know, i think there's another issue give me a moment

**Comment by ArcerionDev** [comment]
> she*

oh you're a she ok

**Comment by PixelMMO** [comment]
one sec

**Comment by NameIsA** [comment]
@PixelMMO refresh, open console, login, do the same thing i just told you to do

DO IN THAT ORDER

**Comment by PixelMMO** [comment]
its working now wtf

**Comment by PatheticMustan** [comment]
sad, alright

**Comment by NameIsA** [comment]
> its working now wtf

ah okay

this has happened to me and my friends before 

not really sure what causes it
