### ISSUE TITLE
Walk through boundaries in Harmony Island.

### ISSUE THREAD

**Issue by TheSchmede** [Prodigy-Hacking/ProdigyMathGameHacking#624]
I've wanted to walk through boundaries for ever but that could get me banned. So I got the idea of being able to walk through the boundaries in Harmony Island because nobody can see that.

**Comment by PatheticMustan** [comment]
that would actually be pretty cool....

**Comment by NameIsA** [comment]
i have never seen anyone get banned except bobby fancywoman accounts so i dont think theres a lot to risk

**Comment by NameIsA** [comment]
i litterally used to have an account that has the same username that my github account used to have and prodigy didnt ban it lol

**Comment by PixelMMO** [comment]
> I've wanted to walk through boundaries for ever but that could get me banned. So I got the idea of being able to walk through the boundaries in Harmony Island because nobody can see that.

play offline

**Comment by UntrustableRus** [comment]
I think this should be a feature for all worlds, maybe?
