### ISSUE TITLE
Drag around position/size WCM

### ISSUE THREAD

**Issue by NameIsA** [Prodigy-Hacking/ProdigyMathGameHacking#627]
**Is your feature request related to a problem? Please describe.**
Not much of a problem, I just don't like how much space it takes up sometimes.

**Describe the solution you'd like**
read the title kek

**Describe alternatives you've considered**
idk

**Additional context**
im fat

**Comment by PixelMMO** [comment]
YES

**Comment by PixelMMO** [comment]
PLEASE

**Comment by ArcerionDev** [comment]
ok easy enough

**Comment by ArcerionDev** [comment]
you should be good to go

**Comment by ArcerionDev** [comment]
nevermind

**Comment by ArcerionDev** [comment]
![image](https://user-images.githubusercontent.com/60945964/110155486-aec9a280-7db3-11eb-9ca0-ebff4f1b3dd9.png)
you now have a big white box, wahoo
