### ISSUE TITLE
[BUG] there are 2 disable monster encounters buttons

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#628]
***Description***:
there are two buttons for the same thing

***Images***:
![image](https://user-images.githubusercontent.com/79719521/110153085-90ae7300-7db0-11eb-9d18-73dd5428927a.png)

**additional info**
neither of them work

**Comment by ArcerionDev** [comment]
A:
this is really odd
B:
you need to go to a different area then back in order for it to work

**Comment by PixelMMO** [comment]
i did but it still didnt work

**Comment by PixelMMO** [comment]
and one of them replaces **clothing vibe** btw

**Comment by ArcerionDev** [comment]
oh I see

**Comment by ArcerionDev** [comment]
the second one skips enemy turn in battle

**Comment by ArcerionDev** [comment]
oops idk why I put "Disable monster enounters" for that one

**Comment by PixelMMO** [comment]
ok

**Comment by ArcerionDev** [comment]
but there ya go

**Comment by PixelMMO** [comment]
rename it tho please

**Comment by NameIsA** [comment]
yes rename it

**Comment by ArcerionDev** [comment]
I will jeez

**Comment by NameIsA** [comment]
ok

**Comment by ArcerionDev** [comment]
there done

**Comment by NameIsA** [comment]
ty
