### ISSUE TITLE
[BUG] menu resizing bugging out

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#629]
***Description***:
when i try to close the menu when its my entire screen it doesnt close all the way

***Images***:
![image](https://user-images.githubusercontent.com/79719521/110158159-06b5d880-7db7-11eb-982e-181df90ad724.png)

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/110158251-21884d00-7db7-11eb-9e05-29a652a0db84.png)
the arrow says its closed

**Comment by PixelMMO** [comment]
@ArcerionDev

**Comment by PixelMMO** [comment]
ty

**Comment by ArcerionDev** [comment]
oops
