### ISSUE TITLE
can someone send screenshots and the location on the interactive map please

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#630]

**Comment by PixelMMO** [comment]
what i mean is like this
![image](https://user-images.githubusercontent.com/79719521/110159920-51d0eb00-7db9-11eb-9f32-d2ad8a1210f4.png)
A1

**Comment by NX721** [comment]
No that would be too big for the menu

**Comment by ArcerionDev** [comment]
it's probably possible to give the location though, not looking into it though
