### ISSUE TITLE
Quality of life

### ISSUE THREAD

**Issue by PixelMMO** [Prodigy-Hacking/ProdigyMathGameHacking#634]
**Describe the hack in 59422 words or less:**
you should make <instant kill> and <PVP health> switches like <skip enemy turn> and <disable enemy encounters>

**Have you made sure this hack isn't available yet?**
yes i have made sure

**Comment by ArcerionDev** [comment]
switches for what

**Comment by PixelMMO** [comment]
instant kill and PVP health

**Comment by PixelMMO** [comment]
and OWO bc ide like to be able to turn it off

**Comment by ArcerionDev** [comment]
ok

**Comment by PixelMMO** [comment]
@PatheticMustan the menu broke i cant scroll

**Comment by BoredFishRE** [comment]
> 
> 
> and OWO bc ide like to be able to turn it off

not possible. Just reload.

**Comment by NameIsA** [comment]
it could be possible

just store the old text and the owo text and then swap them in and out

**Comment by BoredFishRE** [comment]
All of the text? A. That would 100% crash the VPS, doubt 2gb of ram can handle that, B. way too much effort for a joke.

**Comment by NameIsA** [comment]
> All of the text? A. That would 100% crash the VPS, doubt 2gb of ram can handle that, B. way too much effort for a joke.

it could be stored in local storage or a variable not vps

**Comment by ArcerionDev** [comment]
why would you store it in the vps lol

**Comment by ArcerionDev** [comment]
and it's like 20k characters

**Comment by ArcerionDev** [comment]
if that crashes the vps that's kinda sad, since the gamemin is over 50k

**Comment by NameIsA** [comment]
> why would you store it in the vps lol
> and it's like 20k characters
> if that crashes the vps that's kinda sad, since the gamemin is over 50k

^^^

**Comment by ChickenOnYT** [comment]
why was this closed

**Comment by PatheticMustan** [comment]
they're talking about togglable hacks, which already exist

**Comment by ChickenOnYT** [comment]
ah
