### ISSUE TITLE
bruh uh

### ISSUE THREAD

**Issue by NameIsA** [Prodigy-Hacking/ProdigyMathGameHacking#643]
im not sure which thing but malwarebytes keeps detecting some random extension as harmful and it isnt saying which one but i have a feeling its prodigymathgamehacking because it detects it every day even after i tell it to remove the extension

**Comment by NameIsA** [comment]
ok i think MB is just high because it never removes anything and i have like 3 extensions that are pretty well-known

**Comment by PatheticMustan** [comment]
maybe we're secretly hacking your computer >:D
woooo! Spooky!

**Comment by NameIsA** [comment]
bruh
