### ISSUE TITLE
i used the hack yesterday now i cant use it the game wont load when its on can you please help me[BUG]

### ISSUE THREAD

**Issue by chick111** [Prodigy-Hacking/ProdigyMathGameHacking#644]
***Description***:

***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
install and set up this extensions
https://chrome.google.com/webstore/detail/setupvpn-lifetime-free-vp/oofgbpoabipfcfjapgnbbjjaenockbdp?hl=en-US
then try again

**Comment by ArcerionDev** [comment]
to setup: press "english", then press "create an account" on here:
![image](https://user-images.githubusercontent.com/60945964/110214986-59ee6080-7e75-11eb-991d-63cb39861cbd.png)
after, check all the check boxes and press "register"
![image](https://user-images.githubusercontent.com/60945964/110215006-7e4a3d00-7e75-11eb-857f-0f85ffcedc24.png)
then press "let's start" 
![image](https://user-images.githubusercontent.com/60945964/110215022-8dc98600-7e75-11eb-8e2f-46bfbcc6133b.png)
then find your country and click on it
![image](https://user-images.githubusercontent.com/60945964/110215034-9c17a200-7e75-11eb-8d9b-a830d590d7ed.png)
and then try loading prodigy again

**Comment by NameIsA** [comment]
![image](https://user-images.githubusercontent.com/61570792/110215716-25bc7500-7e60-11eb-8cfc-5dc1f16f2932.png)
it's happening to my friends too

**Comment by NameIsA** [comment]
![image](https://user-images.githubusercontent.com/61570792/110215751-47b5f780-7e60-11eb-85c5-0942ac5bcf91.png)

**Comment by ArcerionDev** [comment]
oh

**Comment by ArcerionDev** [comment]
hacks are down lol

**Comment by NameIsA** [comment]
mk

**Comment by NX721** [comment]
![image](https://user-images.githubusercontent.com/77288637/110236158-44734800-7f02-11eb-99d0-d45732d7305d.png)
No I can play normally

**Comment by NX721** [comment]
![image](https://user-images.githubusercontent.com/77288637/110236177-5ce36280-7f02-11eb-904e-7cb4723be38a.png)

**Comment by NameIsA** [comment]
alr

**Comment by BoredFishRE** [comment]
Wow is this an issue or an email

**Comment by BoredFishRE** [comment]
i'm closing this.
