### ISSUE TITLE
Add VPN into PHEx

### ISSUE THREAD

**Issue by ArcerionDev** [Prodigy-Hacking/ProdigyMathGameHacking#645]
An interesting idea, would probably help out with issues across the board if we were to build in a vpn directly into the extension.

**Comment by NameIsA** [comment]
yes

**Comment by TheSchmede** [comment]
Good Idea!
Really Good Idea!
Extremely Good Idea!
Incredibly Good Idea!
I can't think of anything else...

**Comment by irhrhd** [comment]
Yes very good idea well it cant be a bad idea if Arcy said it

**Comment by NameIsA** [comment]
where do the vpn servers come from

botnets? they sound cool I mean what

**Comment by PatheticMustan** [comment]
no

unless somebody is willing to let us use their servers, not willing to implement
not worth it either

**Comment by irhrhd** [comment]
Wait wait wait pick me pick me i have a proposal to make

**Comment by NameIsA** [comment]
> no
> 
> unless somebody is willing to let us use their servers, not willing to implement
> not worth it either

why not use botnets?

**Comment by irhrhd** [comment]
Im working on a vpn just let me finish it

**Comment by BoredFishRE** [comment]
> > no
> > unless somebody is willing to let us use their servers, not willing to implement
> > not worth it either
> 
> why not use botnets?

A. Probably 90% of all antiviruses will have a stroke. B. Microsoft will DEFINITELY not let the extension on the store if it pointed to a botnet.

**Comment by NameIsA** [comment]
> > > no
> > > unless somebody is willing to let us use their servers, not willing to implement
> > > not worth it either
> > 
> > 
> > why not use botnets?
> 
> A. Probably 90% of all antiviruses will have a stroke. B. Microsoft will DEFINITELY not let the extension on the store if it pointed to a botnet.

i know i was being sarcastic

**Comment by irhrhd** [comment]
Im working on a vpn with the node unblocker proxy dev

**Comment by BoredFishRE** [comment]
@irhrhd where are you gonna even host it

**Comment by irhrhd** [comment]
I dont know yet maybe heroku probably not im working on that

**Comment by ArcerionDev** [comment]
I'm thinking that we might be able to piggyback off of setupvpn's servers

**Comment by NameIsA** [comment]
smart how unethical on a scale of 1-10 better not be below 5

**Comment by ArcerionDev** [comment]
Nah not unethical it's free to use

**Comment by NameIsA** [comment]
oh yay

**Comment by ChickenOnYT** [comment]
bump because arc's idea might work

**Comment by PatheticMustan** [comment]
highly advise against, but if you want to add it..?

**Comment by ChickenOnYT** [comment]
> highly advise against, but if you want to add it..?

i wanna add it lol

**Comment by TheSchmede** [comment]
ADD IT!!!!

**Comment by ChickenOnYT** [comment]
ok
