### ISSUE TITLE
[HR] Pet Hack

### ISSUE THREAD

**Issue by irhrhd** [Prodigy-Hacking/ProdigyMathGameHacking#648]
**Describe the hack in 5 words or less:**

Pet hack 
**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes
————————————————————————————————————————
Make it so you can get pets by the id like Pet id [26] specific pets

**Comment by NameIsA** [comment]
ok cool @PatheticMustan @ArcerionDev

**Comment by LeoBadeaux** [comment]
Closed after 1 week from stale notice.
