### ISSUE TITLE
[BUG]Not loading.

### ISSUE THREAD

**Issue by TheSchmede** [Prodigy-Hacking/ProdigyMathGameHacking#650]
***Description***:
It is not fully loading.
Again.

***Replication***:
Just start Prodigy and it will not load. The bar will get halfway full then not go any further.

***Images***:

***Additional Errors***:

**Comment by ChickenOnYT** [comment]
hacks are down

**Comment by ChickenOnYT** [comment]
@PatheticMustan @ArcerionDev close this

**Comment by TheSchmede** [comment]
Damn it.

**Comment by PatheticMustan** [comment]
Check again, should be up
