### ISSUE TITLE
[BUG]When I try to give myself runes, nothing happens.

### ISSUE THREAD

**Issue by Aurora270** [Prodigy-Hacking/ProdigyMathGameHacking#651]
***Description***:

***Replication***:
So after I click on the thing and insert how many I want, the green checkmark on the bottom doesn't appear and I don't get the runes.

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
yeah trying to fix

**Comment by ArcerionDev** [comment]
give me a mo
