### ISSUE TITLE
PHEx cleanup

### ISSUE THREAD

**Issue by ConnorAhern** [Prodigy-Hacking/ProdigyMathGameHacking#654]
Okay, so, we need to just make `disableIntegrity.js` something like `contentScript.js`, then remove all the bulky garbage. For instance, we don't need "debug" to be an option in the public extension, just make a modified version of it where it uses localhost.

**Comment by PatheticMustan** [comment]
yeah, I think it would also be cool to have multiple builds of the extension

**Comment by ChickenOnYT** [comment]
wdym

**Comment by UntrustableRus** [comment]
They want me working on PHEx but when I try to they tell me they don't want to have to go through the approval process again

**Comment by PatheticMustan** [comment]
sad
