### ISSUE TITLE
Update instructions to include chrome web store

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#658]
see title, this issue is up for grabs

**Comment by ChickenOnYT** [comment]
wait until google reviews my 20 character desscription update that's been pending for 3 days so that i can upload the bug fix on the chrome web store that will also take 3 days to be reviewed

**Comment by BoredFishRE** [comment]
We have ownership of extension now, will wait until they approve changes I made.

**Comment by ChickenOnYT** [comment]
mk
