### ISSUE TITLE
It wont let me open my pets or it will get me out [BUG]

### ISSUE THREAD

**Issue by munchyluvsphex** [Prodigy-Hacking/ProdigyMathGameHacking#664]
***Description***:PLEASE HELP will be pog

***Replication***:

***Images***:

***Additional Errors***:

**Comment by munchyluvsphex** [comment]
how am i supposed to open console

**Comment by munchyluvsphex** [comment]
it wont even let me

**Comment by ChickenOnYT** [comment]
https://www.youtube.com/watch?v=yMHz0v1Wsjc

**Comment by ChickenOnYT** [comment]
i cant find a good video that isnt stretched out for ads that tells you how to open console

**Comment by munchyluvsphex** [comment]
oh well my pc is bad so i cant take a screen shot

**Comment by munchyluvsphex** [comment]
tommorow i can be on a playable laptop

**Comment by ChickenOnYT** [comment]
ah yes that's an issue with authentication or something like that

**Comment by munchyluvsphex** [comment]
is there any way to fix it and how does it happen?

**Comment by munchyluvsphex** [comment]
oh ok thanks you!

**Comment by munchyluvsphex** [comment]
thank*

**Comment by ChickenOnYT** [comment]
no need to close this because it's an ongoing issue
