### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by munchyluvsphex** [Prodigy-Hacking/ProdigyMathGameHacking#667]
***Description***:
if you were to put a code such as 
//Level 100
function level100() {
PIXI.game.prodigy.player.data.level=100;
}

level100();

would they get your account info

***Replication***:

***Images***:

***Additional Errors***:

**Comment by munchyluvsphex** [comment]
@ArcerionDev @ChickenOnYT

**Comment by PatheticMustan** [comment]
no lmao
