### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by spityou** [Prodigy-Hacking/ProdigyMathGameHacking#669]
hello it is still stuck loading and what happened to the redirector hack its gone off the page it looks like.

![Screenshot 2021-03-09 at 12 06 42 PM](https://user-images.githubusercontent.com/70118398/110531481-7508dc80-80d0-11eb-99bd-9c66fed6ee93.png)

**Comment by ChickenOnYT** [comment]
did you use the one from the chrome web store? its broken. if you didnt use that one @ArcerionDev @PatheticMustan HELP US

**Comment by spityou** [comment]
> did you use the one from the chrome web store? its broken. if you didnt use that one @ArcerionDev @PatheticMustan HELP US

no i did not use that one for the chrome web store i just downloaded the zip file and and turned on developer mode and dragged the file in

**Comment by ChickenOnYT** [comment]
ah ok crap

**Comment by spityou** [comment]
do you want to hear a story? well i am going to to tell it anyways i have found out how to block all school proxys all you have to do is go to chrome experiments and search proxy on there and there should be a proxy there enable those two proxys and then reset you computer and then they will be enabled and then if you are on a school computer it will say that the security is suffering it won't get you much but it will get you enough security to sign out of your school provided google account and if you look up relay relay is a school web filter and it blocks everything and only real schools can download it and even this works on relay i have relay on my school computer.

**Comment by spityou** [comment]
> > do you want to hear a story? well i am going to to tell it anyways i have found out how to block all school proxys all you have to do is go to chrome experiments and search proxy on there and there should be a proxy there enable those two proxys and then reset you computer and then they will be enabled and then if you are on a school computer it will say that the security is suffering it won't get you much but it will get you enough security to sign out of your school provided google account and if you look up relay relay is a school web filter and it blocks everything and only real schools can download it and even this works on relay i have relay on my school computer.
> 
> bruh that only works for ones using the chrome blocker crap

what you mean chrome blocker just sign out of you class google account or try developer mode my pressing esc + the reload button and the power button at the same time and the first time i did this i could login to any google account but i didn't do that and signed in to the school google account but when i tryed do the same thing it would only allow my to sign in to the school google account so if you never did that before do it and you should be able to sign in to any google account and if you sign in to the school google account it will never allow you to do it again and just delete the school google account then power off and power on the computer

**Comment by ChickenOnYT** [comment]
> > > do you want to hear a story? well i am going to to tell it anyways i have found out how to block all school proxys all you have to do is go to chrome experiments and search proxy on there and there should be a proxy there enable those two proxys and then reset you computer and then they will be enabled and then if you are on a school computer it will say that the security is suffering it won't get you much but it will get you enough security to sign out of your school provided google account and if you look up relay relay is a school web filter and it blocks everything and only real schools can download it and even this works on relay i have relay on my school computer.
> > 
> > 
> > bruh that only works for ones using the chrome blocker crap
> 
> what you mean chrome blocker just sign out of you class google account or try developer mode my pressing esc + the reload button and the power button at the same time and the first time i did this i could login to any google account but i didn't do that and signed in to the school google account but when i tryed do the same thing it would only allow my to sign in to the school google account so if you never did that before do it and you should be able to sign in to any google account and if you sign in to the school google account it will never allow you to do it again and just delete the school google account then power off and power on the computer

isnt very helpful for people who use microsoft products or who have network-based blocking stuff or anything that wouldnt be affected by google chrome

**Comment by PatheticMustan** [comment]
try again, @spityou. Hacks were down earlier today.

**Comment by spityou** [comment]
> > > > do you want to hear a story? well i am going to to tell it anyways i have found out how to block all school proxys all you have to do is go to chrome experiments and search proxy on there and there should be a proxy there enable those two proxys and then reset you computer and then they will be enabled and then if you are on a school computer it will say that the security is suffering it won't get you much but it will get you enough security to sign out of your school provided google account and if you look up relay relay is a school web filter and it blocks everything and only real schools can download it and even this works on relay i have relay on my school computer.
> > > 
> > > 
> > > bruh that only works for ones using the chrome blocker crap
> > 
> > 
> > what you mean chrome blocker just sign out of you class google account or try developer mode my pressing esc + the reload button and the power button at the same time and the first time i did this i could login to any google account but i didn't do that and signed in to the school google account but when i tryed do the same thing it would only allow my to sign in to the school google account so if you never did that before do it and you should be able to sign in to any google account and if you sign in to the school google account it will never allow you to do it again and just delete the school google account then power off and power on the computer
> 
> isnt very helpful for people who use microsoft products or who have network-based blocking stuff or anything that wouldnt be affected by google chrome

it does work the only reason it would not work for network-based stuff is because you have to sign out of the school google account and it won't work for school that have microsoft stuff but most school that i have been to all had chromebooks and a lot of schools i think are switching to chromebook because they are the "cheapest"

**Comment by UntrustableRus** [comment]
He's factory resetting the chrome book, therefore unenrolling it from his school's GSuite organization.

**Comment by spityou** [comment]
> He's factory resetting the chrome book, therefore unenrolling it from his school's GSuite organization.

correct
