### ISSUE TITLE
Outdated Hack

### ISSUE THREAD

**Issue by Pokeroni** [Prodigy-Hacking/ProdigyMathGameHacking#672]
Whenever I load up the hack it says it is outdated but I can't update it when I redownload can someone help me?

**Comment by irhrhd** [comment]
You have to get the new updated extension

**Comment by irhrhd** [comment]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/PHEx/build/extension.zip

**Comment by irhrhd** [comment]
It was updated today

**Comment by PatheticMustan** [comment]
istg it should automatically bring up the update page...????

**Comment by NX721** [comment]
@Pokeroni

**Comment by BoredFishRE** [comment]
closing this, no response from author
