### ISSUE TITLE
Let PHEx modify its own game files

### ISSUE THREAD

**Issue by elikiller** [Prodigy-Hacking/ProdigyMathGameHacking#673]
***Description***:Extension loading on halfway then stopping even when i use the bookmarklet with this code: javascript:console.log=console.clear=console.dir=_=>{}

***Replication***:

***Images***:
![Capture](https://user-images.githubusercontent.com/78311005/110659008-2cb0f380-8190-11eb-8187-c2bc9c52c26c.PNG)

***Additional Errors***:

**Comment by elikiller** [comment]
blocked on this school computer
and then how do i make it work?

**Comment by elikiller** [comment]
I tried using the extension but it's staying on halfway

**Comment by ChickenOnYT** [comment]
ah if prodigyhacking.ml is blocked its probs not possible atm 

we're working on a solution for this

**Comment by elikiller** [comment]
wait, I can't use the hacks?

**Comment by elikiller** [comment]
![image](https://user-images.githubusercontent.com/78311005/110659970-13f50d80-8191-11eb-8268-61c7bffd305b.png)
what's this mean?

**Comment by elikiller** [comment]
uh how

**Comment by ChickenOnYT** [comment]
> ![image](https://user-images.githubusercontent.com/78311005/110659970-13f50d80-8191-11eb-8268-61c7bffd305b.png)
> what's this mean?

it means your school blocked hacks

**Comment by BoredFishRE** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/78311005/110659970-13f50d80-8191-11eb-8268-61c7bffd305b.png)
> what's this mean?

what version is the extension

**Comment by ChickenOnYT** [comment]
> uh how

you cant _yet_, we're going to find a solution for this common problem very soon

**Comment by ChickenOnYT** [comment]
> > ![image](https://user-images.githubusercontent.com/78311005/110659970-13f50d80-8191-11eb-8268-61c7bffd305b.png)
> > what's this mean?
> 
> what version is the extension

read the error, it says failed to fetch, its bc its blocked

**Comment by elikiller** [comment]
ohh by my school or smthn else?

**Comment by elikiller** [comment]
would a vpn let me bypass maybe?

**Comment by elikiller** [comment]
:(((( there's no way to use the hacks :'(

**Comment by ChickenOnYT** [comment]
> would a vpn let me bypass maybe?

yes try setupvpn

**Comment by elikiller** [comment]
ok ty :)

**Comment by ChickenOnYT** [comment]
choose any

**Comment by elikiller** [comment]
it's not working it says to download the desktop client so i did but when i tried to install it it said it was blocked by my admin :(

**Comment by ChickenOnYT** [comment]
ah the vpn must be blocked

we're still working on this yknow

**Comment by elikiller** [comment]
ye ik

**Comment by elikiller** [comment]
like i wonder if it's possible to make an unblockable unblocker

**Comment by elikiller** [comment]
imma try one thing brb

**Comment by irhrhd** [comment]
proxyforschools.herokuapp.com its a proxy that me and the dev updated
recently

**Comment by elikiller** [comment]
xDDDDD

**Comment by BoredFishRE** [comment]
you have to do https

**Comment by elikiller** [comment]
![image](https://user-images.githubusercontent.com/78311005/110665027-f8403600-8195-11eb-872f-95babc31ac91.png)

**Comment by kidmike** [comment]
its not loading same

**Comment by elikiller** [comment]
ughhhhh

**Comment by kidmike** [comment]
whats wrong

**Comment by elikiller** [comment]
WHAT'S WRONG?????

**Comment by ChickenOnYT** [comment]
wait its fine for me wtf

**Comment by BoredFishRE** [comment]
?

**Comment by kidmike** [comment]
some body trying to kill you u see this i dont mess with scary movies

**Comment by kidmike** [comment]
u dont know what wrong

**Comment by kidmike** [comment]
s;

**Comment by PatheticMustan** [comment]
There's no way to make "unblockable" hacks, we can just add a ton of domains and hope at least one of them work.

**Comment by ChickenOnYT** [comment]
i mean like the no website redirector thing

**Comment by PatheticMustan** [comment]
Hmm, yeah ig, but that comes with its own set of issues, like how would we update it?

**Comment by ChickenOnYT** [comment]
fixed yet?

**Comment by PatheticMustan** [comment]
unfortunately the only way I can see doing this would be some *weird* shit.

either a really big refactor is required, moving all the stuff in redirector to phex, or locally hosting redirector

**Comment by PatheticMustan** [comment]
both of which aren't due until 2.3.0, we should probably focus on issues the people who use it normally are facing

**Comment by ChickenOnYT** [comment]
alright

**Comment by ChickenOnYT** [comment]
i sorta feel like if a school wants to block hacks that's up to them

**Comment by PatheticMustan** [comment]
Not planning on implementing
