### ISSUE TITLE
[BUG]I can not install the new version.

### ISSUE THREAD

**Issue by TheSchmede** [Prodigy-Hacking/ProdigyMathGameHacking#674]
***Description***:
I downloaded the new version of the extension and put it in my extensions but it said failed to unzip. So then I tried the load unpacked but I was unable to click on the right file.

***Replication***:
Try to download the new version at: https://sourceforge.net/projects/prodigyhacking/files/2.0.2/PHEx%20Version%202.0.2.zip/download

***Images***:
![Screen Shot 2021-03-10 at 8 14 40 AM](https://user-images.githubusercontent.com/66804076/110660735-b5239a00-8178-11eb-90b0-232cd6e8a770.png)

***Additional Errors***:

**Comment by ChickenOnYT** [comment]
you dont unzip

**Comment by elikiller** [comment]
me neither. No I didn't unzip it I just dragged it in

**Comment by hostedposted** [comment]
try downloading it from https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/PHEx/build/extension.zip?raw=true.

**Comment by ChickenOnYT** [comment]
please wait until the new version is published to the chrome web store

**Comment by TheSchmede** [comment]
Ok

**Comment by TheSchmede** [comment]
Nice, it worked.
