### ISSUE TITLE
[BUG] I cannot install the new version of the app. 

### ISSUE THREAD

**Issue by userofprodigy** [Prodigy-Hacking/ProdigyMathGameHacking#675]
I have tried over and over again to update the extension but i am unable to. I made a youtube video explaining my problem and a video recording. Link: https://youtu.be/kj7MYcwu5uE
Thank you! :)

**Comment by ChickenOnYT** [comment]
please wait until the new version is published to the chrome web store

**Comment by userofprodigy** [comment]
> please wait until the new version is published to the chrome web store

okay, thanks

**Comment by ChickenOnYT** [comment]
can you close this issue btw
