### ISSUE TITLE
[BUG] it still don't work

### ISSUE THREAD

**Issue by spityou** [Prodigy-Hacking/ProdigyMathGameHacking#679]
it still not loading and i re-downloaded it too 
![Screenshot 2021-03-10 at 2 07 40 PM](https://user-images.githubusercontent.com/70118398/110704833-5f67e580-81aa-11eb-8fad-fbc38f4a37e8.png)

**Comment by BoredFishRE** [comment]
Can you visit https://prodigyhacking.ml?

**Comment by spityou** [comment]
> Can you visit https://prodigyhacking.ml?

no

**Comment by BoredFishRE** [comment]
Is it blocked? If so, hacks will not work.

**Comment by spityou** [comment]
> Is it blocked? If so, hacks will not work.

why and what happened to the redirector hack that was on here that worked

**Comment by BoredFishRE** [comment]
This works the same way the redirector worked, it's just we packed it into an extension so we can more easily do things, and the old way stopped working. We've been gaining popularity, and schools start blocking our URL to prevent cheating

**Comment by spityou** [comment]
> This works the same way the redirector worked, it's just we packed it into an extension so we can more easily do things, and the old way stopped working. We've been gaining popularity, and schools start blocking our URL to prevent cheating

how did the old way stop working?

**Comment by BoredFishRE** [comment]
the extensions we used had changed in ways that prevented it from working correctly.

**Comment by spityou** [comment]
but what is on https://prodigyhacking.ml exactly

**Comment by BoredFishRE** [comment]
Our custom game.min.js

**Comment by spityou** [comment]
> the extensions we used had changed in ways that prevented it from working correctly.

i got the redirector hack to work with the https://prodigyhacking.ml site the only problem is this 
![Screenshot 2021-03-10 at 2 29 02 PM](https://user-images.githubusercontent.com/70118398/110706639-0a799e80-81ad-11eb-9a47-7155761f0f01.png)

**Comment by spityou** [comment]
shou

> Our custom game.min.js

should i close this

**Comment by BoredFishRE** [comment]
stop

**Comment by PatheticMustan** [comment]
will consider releasing a way to self-host redirector

**Comment by ArcerionDev** [comment]
> will consider releasing a way to self-host redirector

try using https://npmjs.com/plant

**Comment by ArcerionDev** [comment]
it's a browser friendly webserver creator

**Comment by ArcerionDev** [comment]
so you can get the compiled version using unpkg or smth
