### ISSUE TITLE
[BUG] ït wîłl ñøt łêt mę ūßë ñêw ûpdãtë! ît šãÿś ërrør..! hëłp mêh. 

### ISSUE THREAD

**Issue by sammypuyoy** [Prodigy-Hacking/ProdigyMathGameHacking#680]
***Description***:

***Replication***:

***Images***:

***Additional Errors***:

**Comment by sammypuyoy** [comment]
Fix the new cheat menu it says error its a terrible bug.

**Comment by ChickenOnYT** [comment]
The extension is outdated, wait until the updated one is published.

**Comment by TheSchmede** [comment]
> Fix the new cheat menu it says error its a terrible bug.

Dude chill!!!!!!

**Comment by ArcerionDev** [comment]
in order to get an utd extension, either get the one from https://prodigyhacking.com/extension , or get the one on the webstore from [here](https://chrome.google.com/webstore/detail/prodigyhacking/gjabpajagbgoifbkflgojeojmnlmioea)

**Comment by PatheticMustan** [comment]
is /extension even updated

**Comment by BoredFishRE** [comment]
idk if it's pointing to the right place anymore, will change if it isn't

**Comment by BoredFishRE** [comment]
https://prodigyhacking.com/extension was pointing to wrong place, fixed now

**Comment by UntrustableRus** [comment]
Chill with the accent marks, as someone who primarily speaks a language that uses accent marks it's very hard to read the title without my brain thinking it's French
