### ISSUE TITLE
[BUG] Outdated extension

### ISSUE THREAD

**Issue by GamingWithDestiny** [Prodigy-Hacking/ProdigyMathGameHacking#682]
***Description***:It says outdated version and when it wasn't outdated it wouldnt save anything on account not all pets or anything

***Replication***:Description***:It says outdated version and when it wasn't outdated it wouldnt save anything on account not all pets or anything

***Images***:
![Screenshot 2021-03-11 at 12 17 16 PM](https://user-images.githubusercontent.com/80478578/110827104-bd0c3880-8263-11eb-84b1-ef308f351ff6.png)

***Additional Errors***:Description***:It says outdated version and when it wasn't outdated it wouldnt save anything on account not all pets or anything

**Comment by ChickenOnYT** [comment]
i keep getting the wrong answer to this so ask @ArcerionDev

**Comment by ChickenOnYT** [comment]
@PatheticMustan @ArcerionDev could you rename this issue to something more meaningful apparently my triager permissions dont let me rename things

**Comment by CRobbins0867** [comment]
@GamingWithDestiny did you try saving or no?

**Comment by PatheticMustan** [comment]
(hint: maybe clicking "ok" takes you to the update page)

**Comment by PatheticMustan** [comment]
wait nevermind, I'll actually fix this

**Comment by GamingWithDestiny** [comment]
like yeah i tried  like actually

**Comment by GamingWithDestiny** [comment]
So like when is it going to be fixed any date or time

**Comment by ChickenOnYT** [comment]
like a few days to a week

we're people too, we have school and stuff

**Comment by GamingWithDestiny** [comment]
Ok cool just asking

**Comment by ArcerionDev** [comment]
Ok so there are two issues in this. 
A: Go to https://prodigyhacking.com/extension to get the latest extension version
B: The not saving issue is a separate issue.

If the extension version doesn't match the number here: https://prodigyhacking.ml/version , go to the above link to update it!

**Comment by GamingWithDestiny** [comment]
what is closed

**Comment by GamingWithDestiny** [comment]
what the crap i cant scroll on menu my gees

**Comment by ChickenOnYT** [comment]
@NX721 do you have a solution
