### ISSUE TITLE
i would like to apply to be a triager  

### ISSUE THREAD

**Issue by CRobbins0867** [Prodigy-Hacking/ProdigyMathGameHacking#684]
@PatheticMustan  Can i apply to be a triager? I am on this respiratory a lot so i would be good for the job !

**Comment by irhrhd** [comment]
Its spelled repository!

**Comment by CRobbins0867** [comment]
oh sorry i was typing so fast because i really want to be a triager

**Comment by ArcerionDev** [comment]
respiratory

**Comment by NX721** [comment]
Lmao
