### ISSUE TITLE
Add a chat to WCM

### ISSUE THREAD

**Issue by CyberXVI** [Prodigy-Hacking/ProdigyMathGameHacking#685]
**Describe the hack in 5 words or less:**
Say anything via chat.

**(Optional) Additional information**
N/A

**Have you made sure this hack isn't available yet? (Yes/No)**
Yes.

**Comment by CRobbins0867** [comment]
that would be a good idea i guess

**Comment by CyberXVI** [comment]
@ArcerionDev 
@PatheticMustan

**Comment by ChickenOnYT** [comment]
we were working on this once then it kinda died

**Comment by ChickenOnYT** [comment]
didnt mean to assign it

**Comment by ArcerionDev** [comment]
yeah so this isn't possbile

**Comment by ArcerionDev** [comment]
let me show you why

**Comment by ChickenOnYT** [comment]
no remember our custom chat thing

**Comment by ArcerionDev** [comment]
not sure if that really worked

**Comment by ArcerionDev** [comment]
anyway

**Comment by ArcerionDev** [comment]
look

**Comment by ArcerionDev** [comment]
prodigy sends a websocket request with a payload like this 
![image](https://user-images.githubusercontent.com/60945964/110856737-03728f00-8286-11eb-8f7e-f94160408a17.png)

**Comment by ArcerionDev** [comment]
so it gives the id of the chat phrase, which is stored in an array.

**Comment by ChickenOnYT** [comment]
> not sure if that really worked

it would've worked but it was like making our own chat service that WCM added into prodigy

**Comment by ArcerionDev** [comment]
since that we can't edit the chat phrases serverside, it won't exist for other people, so it basically will be that we're sending a raw number that doesn't have an assigned phrase

**Comment by ArcerionDev** [comment]
> > not sure if that really worked
> 
> it would've worked but it was like making our own chat service that WCM added into prodigy

oh I thought you meant that really old thing

**Comment by ArcerionDev** [comment]
idek

**Comment by irhrhd** [comment]
Yeah that would be really hard to do

**Comment by ArcerionDev** [comment]
> Yeah that would be really hard to do

it would be impossible

**Comment by irhrhd** [comment]
Prodigy could make it so you can say what ever you wanted but the
inappropriate words are blocked that would be great if they did

**Comment by ArcerionDev** [comment]
> Prodigy could make it so you can say what ever you wanted but the inappropriate words are blocked that would be great if they did

it would be fairly simple to do

**Comment by ArcerionDev** [comment]
but of course, it's very easy to bypass any language filter

**Comment by irhrhd** [comment]
Yeah it is i know on taming io me and my friend bypassed it it was funny af

**Comment by ArcerionDev** [comment]
ok well this is impossible as of now so closing this

**Comment by ChickenOnYT** [comment]
actually let's just make our own like chat service and embed it into WCM we were going to do it once but it died

**Comment by ArcerionDev** [comment]
alright, but this is a different topic so we can transfer it

**Comment by ChickenOnYT** [comment]
wdym how is it a different topic

well like it a feature request

**Comment by NX721** [comment]
...

**Comment by PatheticMustan** [comment]
LMAO this was ProdigyIRC

if anybody wants to revive ProdigyIRC, it's all public I think

**Comment by ChickenOnYT** [comment]
mk

**Comment by ChickenOnYT** [comment]
i'll revive it actually

**Comment by UntrustableRus** [comment]
Self-assigning this, I can do the backend infrastructure, but @ChickenOnYT you can do front end?

**Comment by ChickenOnYT** [comment]
yes ty

**Comment by UntrustableRus** [comment]
Alright

**Comment by Pathetic-Burger** [comment]
it would be so funny like I would just go like "I AM THE BEST HACKER IN PRODIGY" and they would be like *noot*

**Comment by YamaHacks** [comment]
We had an old "custom chat" with a few built in extra chats, such as "Yama!", "Divine!" etc. It was only shown to people with the extension in the first place, not to mention was causing way too many unnecessary problems.

**Comment by donaldli2020** [comment]
@github-actions How come this is closed?

**Comment by AgrTheDev** [comment]
yk that's a bot and won't respond right?

**Comment by 32n** [comment]
donaldli2020 is a special child, agr.

**Comment by ArcerionDev** [comment]
special ed*

**Comment by afkvido** [comment]
> special ed*

>:D
