### ISSUE TITLE
[HR] Server Side Name Hack

### ISSUE THREAD

**Issue by NX721** [Prodigy-Hacking/ProdigyMathGameHacking#687]
So while playing Prodigy with no hacks I found this person.
![image](https://user-images.githubusercontent.com/77288637/110861898-ccec4280-828c-11eb-9599-0b2da72af9d7.png)
![image](https://user-images.githubusercontent.com/77288637/110861968-e2616c80-828c-11eb-96c8-dc1395d83211.png)
(Look at my top left corner to see that I have no Hacks. )

**Comment by irhrhd** [comment]
Cause they are hacking you can see hackers you know

**Comment by ChickenOnYT** [comment]
Using hacks, it's possible to remove your last name so that it doesn't show up.

**Comment by ChickenOnYT** [comment]
Just use "Change Name" and select "[none]" for some things.

**Comment by NX721** [comment]
How about the last name?

**Comment by ChickenOnYT** [comment]
> How about the last name?

first name: cadence
middle name: [none]
last name: [none]
nickname: [none]

**Comment by PatheticMustan** [comment]
no

**Comment by ChickenOnYT** [comment]
Furthermore, even if this was possible, the whole goal of this repository is that you cannot damage another player's expierence.
