### ISSUE TITLE
unintall hack

### ISSUE THREAD

**Issue by BX161** [Prodigy-Hacking/ProdigyMathGameHacking#692]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ChickenOnYT** [comment]
please provide more information on what you need

**Comment by BX161** [comment]
Hi, I wonder how to unintall the hack because my son couldn't play any math game after intall the hack

**Comment by ChickenOnYT** [comment]
go to chrome://extensions, find "prodigymathgamehacking", and press "remove"

**Comment by BX161** [comment]
Thank you. Let me try.

**Comment by ChickenOnYT** [comment]
guessing this is solved, no new replies for 15 mins
