### ISSUE TITLE
iOS/Android Cheat Menu

### ISSUE THREAD

**Issue by UntrustableRus** [Prodigy-Hacking/ProdigyMathGameHacking#694]
This is for discussion about the iOS/Android cheat menu development.

Alright, so I'll be able to pull it off. If we set up a proxy server, and have it proxy requests and connect to it from the device, we theoretically should be able to modify the JS that the app loads. Tomorrow I'll see if I can get it to show an alert box. I'll be the primary one working on this.

**Comment by ChickenOnYT** [comment]
We already have an issue for this. Discuss in #600.

**Comment by ChickenOnYT** [comment]
> > We already have an issue for this. Discuss in #600.
> 
> I feel like me trying this out deserves an entirely new issue, if you can agree?

hm okay

**Comment by ChickenOnYT** [comment]
also not part of 2.1.0 because that's for bug fixes

**Comment by UntrustableRus** [comment]
> also not part of 2.1.0 because that's for bug fixes

Yeah no problem. Can't wait to work on this tomorrow.

**Comment by ChickenOnYT** [comment]
mk

**Comment by ChickenOnYT** [comment]
honestly, i would be saying all this on discord but they're all kinda upset at me rn im not sure how i offended them

**Comment by UntrustableRus** [comment]
> honestly, i would be saying all this on discord but they're all kinda upset at me rn im not sure how i offended them

You're good.

**Comment by PatheticMustan** [comment]
the cheat menu relies heavily on modified game files... how do you suggest we send the modified gamemin?

**Comment by UntrustableRus** [comment]
> the cheat menu relies heavily on modified game files... how do you suggest we send the modified gamemin?

Proxy

**Comment by elikiller** [comment]
When will out be done @UntrustableRus ?

**Comment by elikiller** [comment]
It*

**Comment by ArcerionDev** [comment]
@elikiller deadline is may 31st

**Comment by elikiller** [comment]
Ok that’s fine cos I’m getting a new chrome book today so maybe it’ll work on that but I won’t have iOS anymore so I won’t be able to use the mobile cheat menu

**Comment by NX721** [comment]
Hi

**Comment by NX721** [comment]
Just so you know you can't scroll the WCM in Prodigy.

**Comment by ChickenOnYT** [comment]
> Just so you know you can't scroll the WCM in Prodigy.

make a new issue

**Comment by NX721** [comment]
yea but i fixed it @ChickenOnYT

**Comment by ChickenOnYT** [comment]
o mk

**Comment by NX721** [comment]
i just pressed ctrl+ - so the buttons shrink and appear enabled the button that enables the size of the WCM and it was fixed

**Comment by ChickenOnYT** [comment]
mk

**Comment by NX721** [comment]
ok?

**Comment by NX721** [comment]
![image](https://user-images.githubusercontent.com/77288637/110992038-6118e100-8343-11eb-8bab-fddce9f8b5c5.png)
Server Overload

**Comment by UntrustableRus** [comment]
Off-topic, please, keep discussion relevant to this issue.

**Comment by NX721** [comment]
Srry

**Comment by UntrustableRus** [comment]
They want me working on PHEx so this is going on the backburner for a little while.

**Comment by UntrustableRus** [comment]
May take a little longer

**Comment by LeoBadeaux** [comment]
Rus is assigned to work on PHEx, and I'll be taking over this issue. I'll work on it when I get home, and I have to figure out how this new hack system works.

**Comment by PatheticMustan** [comment]
Leo/Rus split personality?!?!

**Comment by NX721** [comment]
Lmao

**Comment by PatheticMustan** [comment]
I see how it is, mmhmm alright

**Comment by LeoBadeaux** [comment]
Unfortunately, the program that I was going to attempt to use as a proxy is now paid. We will not be able to do this for now unless we can figure out a way to create our own HTTPS-intercepting proxy.

**Comment by hostedposted** [comment]
what program were you going to use?

**Comment by LeoBadeaux** [comment]
> what program were you going to use?

i forgor 💀
