### ISSUE TITLE
glitch

### ISSUE THREAD

**Issue by BX161** [Prodigy-Hacking/ProdigyMathGameHacking#705]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BX161** [comment]
Hello, 
I would like to know why the prodigy is glitched once starting the battle. I have to restart it again and glitched again. I removed hacking but the issue is still there.

**Comment by NX721** [comment]
Use Fix Battle Crash Before you battle.

**Comment by NX721** [comment]
How is there 3 participants

**Comment by NX721** [comment]
Oh person must have been flagged.

**Comment by ChickenOnYT** [comment]
use fix battle crash like nx721 said
