### ISSUE TITLE
This is not a bug this is a RED FLAG

### ISSUE THREAD

**Issue by Prodigyguy** [Prodigy-Hacking/ProdigyMathGameHacking#706]
My friends recently saw ur hack and now reported it and gave the link away and he also tried ur hack and stayed wow really dude you use this kids can get into lots of trouble or even reseted so he got mad cause he can’t battle anything with the last hack patched he just used it once and tried removing it so he reported it to prodigy and prodigy support team responded with 

On Fri, Mar 12, 2021 at 2:56 PM Prodigy Support <support@prodigygame.com> wrote:

Thank you for contacting Prodigy Customer Support!

Your request (#1052282 (https://prodigygame.zendesk.com/hc/requests/1052282) ) has been set to solved. If your problem persists or you still have questions, not to worry, reply to this email to reopen this request, .
Justin M (Prodigy)
Mar 12, 2021, 5:56 PM EST
Hi there,
Thanks for contacting Prodigy Customer Support - we’d be happy to help!
We’re sorry to hear about the issues you’re experiencing! We’ve taken a look at your child’s account and can see that there were edits made to it. This was done from the player level to try and manually add pets and currency to their account. That would be what’s causing those errors.
Does your child remember trying to edit their account by watching a YouTube tutorial on how to do so that was created by a student? Were they trying to add pets or gold to their account?
We see this from time to time from students who try and hack our program using the Developer Tool in their browser. Some kids create YouTube videos on how to do this that others will follow. The problem is, they end up breaking their accounts in this process.
Unfortunately, we have no way to reverse the damage done to accounts through self-altering. If your child would like to continue playing Prodigy without issues, they would need to create a new account (https://prodigygame.zendesk.com/hc/en-us/articles/205660395-How-To-Create-A-New-Student-Account) going forward.
We appreciate your understanding, and if you need a hand with anything else, please don't hesitate to reopen this ticket by responding to this email.
Sincerely,
Justin
Senior Support Specialist
1-866-585-4655
www.prodigygame.com
Check out our support page (https://prodigygame.zendesk.com/hc/en-us) for guides and solutions to commonly encountered issues!

Mar 10, 2021, 9:40 PM EST

Mar 10, 2021, 2:37 PM EST
My child cannot battle anyone or anything when he gets close to a monster or tries battling people it just stays like that it wont work is something wrong?
Attachment(s)
Screenshot 2021-03-10 at 11.36.31 AM.png (https://prodigygame.zendesk.com/attachments/token/vHh0vusms433DuLN2FyeWT7Yf/?name=Screenshot+2021-03-10+at+11.36.31+AM.png)

I’m

**Comment by DMlightdumProdigy** [comment]
You guys are in serious trouble now... I feel bad

**Comment by Prodigyguy** [comment]
Sorry I have to say this.... but prodigy knows the link to ur hack this is not a joke you can read it again... very sorry this has to happen today.

**Comment by NX721** [comment]
its obvious search up "prodigy hacks" and we are the first result.

**Comment by ChickenOnYT** [comment]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/discussions/16

**Comment by ChickenOnYT** [comment]
read that

**Comment by NX721** [comment]
lmao

**Comment by PatheticMustan** [comment]
yo, pog! Prodigy support responded!

@Prodigyguy, we're aware of these issues, but this is why you're supposed to use alts....
We even warned you in big letters...
![image](https://user-images.githubusercontent.com/35382971/111052739-a4e71580-842b-11eb-97fc-a32092046dc5.png)

**Comment by Prodigyguy** [comment]
At I always use alts same way around but my friend not to Gud sad...

**Comment by Prodigyguy** [comment]
Also tbh how do I close this Not Bug since it's just about my stupid
flipping friend reporting ur hack and I already know your trying to make
the game secure and better but how do I do that since I never in hell use
GitHub.

**Comment by Prodigyguy** [comment]
And also you don’t want to see me spam E ♾ or F ♾ spam till day😂

**Comment by Prodigyguy** [comment]
Also don't make me spam these cuz u might have to scroll deep
