### ISSUE TITLE
Hack detected [BUG]

### ISSUE THREAD

**Issue by Hamza123-png** [Prodigy-Hacking/ProdigyMathGameHacking#710]
Every time I went to prodigy it just doesnt let me get in the game

***Images***: 
![image](https://user-images.githubusercontent.com/74549019/111032423-27df8000-83da-11eb-97fa-087963199923.png)

***Additional Errors***: I cant join

**Comment by ChickenOnYT** [comment]
try again it should be fixed

**Comment by NX721** [comment]
I just reload 3 times and it works for me.
