### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ATimeInSpace** [Prodigy-Hacking/ProdigyMathGameHacking#711]
It won't let me scroll down.
![{7E222DF3-E00B-4792-8A88-D8D1DDE14CE3} png](https://user-images.githubusercontent.com/80608216/111055266-3b263600-8442-11eb-806e-bf037ab7428f.jpg)

It doesn't have the scroll bar for some reason.

**Comment by ATimeInSpace** [comment]
This might be only me though... I'm not sure.

**Comment by CRobbins0867** [comment]
let me try this real quick

**Comment by CRobbins0867** [comment]
it let's me scroll i just have to reset the page but only with the space bar...

**Comment by PatheticMustan** [comment]
pain

**Comment by ATimeInSpace** [comment]
Well okay. I guess I can just use the arrows on the keyboard instead.

**Comment by ATimeInSpace** [comment]
Nope. The arrows don't work either.

**Comment by NX721** [comment]
Press Ctrl - to shrink the menu and enable "Resize Drag" to put the menu to a better size which will unlock the scroll bar.

**Comment by NX721** [comment]
@ATimeInSpace  https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/discussions/714 Go there

**Comment by ATimeInSpace** [comment]
Okay, thanks.

**Comment by ATimeInSpace** [comment]
Oh yay. Its working now. Thanks a lot.
