### ISSUE TITLE
Remove dupe pets/wands

### ISSUE THREAD

**Issue by Lord-Harkon** [Prodigy-Hacking/ProdigyMathGameHacking#715]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NX721** [comment]
(Sigh)

**Comment by Lord-Harkon** [comment]
sorry but it would be helpful to me

**Comment by NX721** [comment]
> sorry but it would be helpful to me

Okay

**Comment by hellonearth311** [comment]
sounds like a good idea!

**Comment by Lord-Harkon** [comment]
thanks hellonearth
i was thinking but didnt want to do something everyone else thought of so....

**Comment by ChickenOnYT** [comment]
ok sounds cool

**Comment by hostedposted** [comment]
I just added this.

**Comment by PatheticMustan** [comment]
next time mention the commit, or title the commit "fix #issuenumber"

**Comment by hostedposted** [comment]
okay
