### ISSUE TITLE
ItemStacker.js is broken

### ISSUE THREAD

**Issue by hellonearth311** [Prodigy-Hacking/ProdigyMathGameHacking#717]
The ItemStacker.js is not working.
Please fix it.

**Comment by ATimeInSpace** [comment]
Can you take a picture for an example?

**Comment by NX721** [comment]
Oops forgot to delete that, @PatheticMustan  Should I delete it?

**Comment by PatheticMustan** [comment]
eh, just leave it for now

**Comment by NX721** [comment]
okay

**Comment by NX721** [comment]
> Can you take a picture for an example?

No need to

**Comment by PatheticMustan** [comment]
Will fix itemstacker

**Comment by hostedposted** [comment]
This should be closed as it's now fixed.
