### ISSUE TITLE
Load unpacked [BUG]

### ISSUE THREAD

**Issue by Hamza123-png** [Prodigy-Hacking/ProdigyMathGameHacking#718]
***Description***: Every time I load the unpacked file and do the installation again it keeps saying its not working

***Replication***:

***Images***:

***Additional Errors***: plz fix it

**Comment by PatheticMustan** [comment]
need more information that "doesn't work". What happens? Does it stop at 50%?

**Comment by NX721** [comment]
@Hamza123-png  Can u screenshot?

**Comment by Hamza123-png** [comment]
It keeps saying the hack will not work and do the steps again, every time I
do them it keeps popping up the message

**Comment by Hamza123-png** [comment]
> need more information that "doesn't work". What happens? Does it stop at 50%?

It keeps displaying messages saying the hack wont work

**Comment by PatheticMustan** [comment]
we need something a bit more specific than that, what does it actually say?

**Comment by UntrustableRus** [comment]
This is more of a #support in Discord question

**Comment by Hamza123-png** [comment]
I dont have discord but it works now

**Comment by Hamza123-png** [comment]
![Uploading image.png…]()

**Comment by Hamza123-png** [comment]
![image](https://user-images.githubusercontent.com/74549019/111360543-3f7d6980-8663-11eb-8715-956e0e12c451.png)

**Comment by Hamza123-png** [comment]
When I click ok it reloades

**Comment by ArcerionDev** [comment]
can you screenshot your chrome://extensions page

**Comment by ArcerionDev** [comment]
@Hamza123-png

**Comment by Hamza123-png** [comment]
ok

**Comment by ArcerionDev** [comment]
and send it?

**Comment by Hamza123-png** [comment]
![image](https://user-images.githubusercontent.com/74549019/111361009-c9c5cd80-8663-11eb-8877-e790c34a0510.png)

**Comment by ArcerionDev** [comment]
yeah you have an outdated version, download a new zip at https://prodigyhacking.com/extension

**Comment by Hamza123-png** [comment]
Ok

**Comment by Hamza123-png** [comment]
THANK YOU

**Comment by ArcerionDev** [comment]
yw

**Comment by ArcerionDev** [comment]
if hacks still don't load, we're aware of it, there's been an issue goin around
