### ISSUE TITLE
[HR] Dino Dig Hack

### ISSUE THREAD

**Issue by hugo875** [Prodigy-Hacking/ProdigyMathGameHacking#721]
**Describe the hack in 5 words or less:**

get extra fossils by digging
**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**
yes

**Comment by NX721** [comment]
Hmm Interesting...

**Comment by NX721** [comment]
But there is already a hack that gives you all fossils @hugo875

**Comment by hugo875** [comment]
> But there is already a hack that gives you all fossils @hugo875

i mean like more fossils to dig when your in the game dino dig in prodigy *more than the limit*

**Comment by ChickenOnYT** [comment]
cool

**Comment by ChickenFlip** [comment]
hi

**Comment by ChickenFlip** [comment]
whats this emoji or emoticon or whatever its called ( ‎╚ ‎═ ‎◢ ‎◣ ‎╝ ‎▓ ‎ﱞﱞﱞﱞﱞ…)

**Comment by hugo875** [comment]
> cool

did you find out yet?

**Comment by hugo875** [comment]
@ChickenOnYT did you find out @ArcerionDev @PatheticMustan @NX721

**Comment by NX721** [comment]
Still figuring...

**Comment by hugo875** [comment]
@PatheticMustan @ChickenOnYT @NX721 this must be hard

**Comment by hugo875** [comment]
@PatheticMustan @ChickenOnYT @NX721 you must of been working hard on this hack request

**Comment by PatheticMustan** [comment]
It's a low priority, due at the end of april...

**Comment by hugo875** [comment]
> It's a low priority, due at the end of april...

ok @PatheticMustan

**Comment by hugo875** [comment]
> It's a low priority, due at the end of april...

i will keep my patience @PatheticMustan

**Comment by NX721** [comment]
Thank You

**Comment by NX721** [comment]
I'm doing a test rn

**Comment by NX721** [comment]
> > It's a low priority, due at the end of april...
> 
> i will keep my patience @PatheticMustan

Ok, then.

**Comment by hugo875** [comment]
> I'm doing a test rn

thank you for telling me.

**Comment by NX721** [comment]
Mk

**Comment by hugo875** [comment]
> I'm doing a test rn

can you tell me the script that your using

**Comment by hugo875** [comment]
@NX721

**Comment by hugo875** [comment]
@NX721

**Comment by NX721** [comment]
> > I'm doing a test rn
> 
> can you tell me the script that your using

Rip it didn't work, crashed the game

**Comment by NX721** [comment]
Yep

**Comment by hugo875** [comment]
no ones working on this anymore @PatheticMustan @ChickenOnYT

**Comment by hugo875** [comment]
@UntrustableRus

**Comment by hugo875** [comment]
because its low priority

**Comment by NX721** [comment]
> because its low priority
Yes it is

**Comment by hugo875** [comment]
@PatheticMustan its past due

**Comment by ArcerionDev** [comment]
can you stop pinging random people we're not taking hack requests anymore

**Comment by donaldli2020** [comment]
ahhhhhhhhhhhh bad bot

**Comment by LeoBadeaux** [comment]
good bot, we can't do this
