### ISSUE TITLE
I think something is here, but IDK what,

### ISSUE THREAD

**Issue by hellonearth311** [Prodigy-Hacking/ProdigyMathGameHacking#722]
**Describe the hack in 5 words or less:**
Maybe a getitem hack?

**(Optional) Additional information**
var SW=SW||{};SW.Storage={},SW.Storage.get=function(t){return JSON.parse(localStorage.getItem(t))},SW.Storage.set=function(t,e){return!!t&&(localStorage.setItem(t,JSON.stringify(e)),!0)};
This is the code I found in the source. I think it might be possible to make it into a hack,

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by hellonearth311** [comment]
it says 2 replies..

**Comment by PixelMMO** [comment]
they already have that, its the advanced version of the get item hack under the inventory hacks tab

**Comment by PixelMMO** [comment]
![image](https://user-images.githubusercontent.com/79719521/111204330-66bd3380-859c-11eb-850a-b140aa6f9a16.png)

**Comment by PixelMMO** [comment]
@hellonearth311

**Comment by PatheticMustan** [comment]
> **Describe the hack in 5 words or less:**
> Maybe a getitem hack?
> 
> **(Optional) Additional information**
> var SW=SW||{};SW.Storage={},SW.Storage.get=function(t){return JSON.parse(localStorage.getItem(t))},SW.Storage.set=function(t,e){return!!t&&(localStorage.setItem(t,JSON.stringify(e)),!0)};
> This is the code I found in the source. I think it might be possible to make it into a hack,
> 
> __Have you made sure this hack isn't available yet?_ (Yes/No)_*
> Yes

no
