### ISSUE TITLE
[BUG] Prodigy not loading, even when I have deleted the extension

### ISSUE THREAD

**Issue by lichessgoodchesscombad** [Prodigy-Hacking/ProdigyMathGameHacking#730]
does not load, even when deleted the extension

**Comment by UN3N0WNGH0ST** [comment]
@PatheticMustan or @ArcerionDev do you know why this is happening

**Comment by PatheticMustan** [comment]
Your account got messed up, what hacks did you use

**Comment by ChickenOnYT** [comment]
enable the hacks then use fix battle crash and fix morph crash

**Comment by UntrustableRus** [comment]
> enable the hacks then use fix battle crash and fix morph crash

He says it's not loading, there's probably something wrong with their account.

**Comment by LandonBoi123** [comment]
My Client Works Fine Without Any Of The Hacks!

**Comment by LandonBoi123** [comment]
> Your account got messed up, what hacks did you use

I didn't use any hacks

**Comment by ChickenOnYT** [comment]
make another issue dont hijack this one

**Comment by hellonearth311** [comment]
Hi, I think what happened was his account was reviewed by Prodigy Staff (this is very rare) and classified as a hacked account possibly because the immense amount of gold.
If you have a LOT of gold with hacks, like 99999999999999999999 or something like that, they know it would take thousands/millions/billions/trillions of years to get that much gold even if you got 100 gold per second.
As you may know, prodigy has been around for only a few years.
The universe is 13 billion years old.
That is why it is totally and utterly IMPOSSIBLE to get that much gold without hacks.

**Comment by PatheticMustan** [comment]
Doubt doubt doubt, it's probably just that his account has some glitched pets or morph

**Comment by Hamza123-png** [comment]
I made a teacher account, used that to make 40 alts per second
and then just keep using those alts to annoy prodigy XD
it works cuz you just need to click a few buttons to make an account as a teacher

**Comment by Hamza123-png** [comment]
The alts were "students"

**Comment by NX721** [comment]
> Hi, I think what happened was his account was reviewed by Prodigy Staff (this is very rare) and classified as a hacked account possibly because the immense amount of gold.
> If you have a LOT of gold with hacks, like 99999999999999999999 or something like that, they know it would take thousands/millions/billions/trillions of years to get that much gold even if you got 100 gold per second.
> As you may know, prodigy has been around for only a few years.
> The universe is 13 billion years old.
> That is why it is totally and utterly IMPOSSIBLE to get that much gold without hacks.

Doubt That's it.

**Comment by ChickenOnYT** [comment]
> > Hi, I think what happened was his account was reviewed by Prodigy Staff (this is very rare) and classified as a hacked account possibly because the immense amount of gold.
> > If you have a LOT of gold with hacks, like 99999999999999999999 or something like that, they know it would take thousands/millions/billions/trillions of years to get that much gold even if you got 100 gold per second.
> > As you may know, prodigy has been around for only a few years.
> > The universe is 13 billion years old.
> > That is why it is totally and utterly IMPOSSIBLE to get that much gold without hacks.
> 
> Doubt That's it.

prodigy has been around since like 2011 or something too

yeah prodigy never bans anyone lol

**Comment by PatheticMustan** [comment]
@lichessgoodchesscombad, screenshot the errors you have, and tell us what hacks you used.

any off topic comments on this post will be deleted, and I will put you on a wall of shame

**Comment by ArcerionDev** [comment]
> Hi, I think what happened was his account was reviewed by Prodigy Staff (this is very rare) and classified as a hacked account possibly because the immense amount of gold.
> If you have a LOT of gold with hacks, like 99999999999999999999 or something like that, they know it would take thousands/millions/billions/trillions of years to get that much gold even if you got 100 gold per second.
> As you may know, prodigy has been around for only a few years.
> The universe is 13 billion years old.
> That is why it is totally and utterly IMPOSSIBLE to get that much gold without hacks.

there's no reason why they would review the account specifically, prodigy has over 10 million accounts, and it would be incredibly difficult to look through every single one

**Comment by PatheticMustan** [comment]
but it would be trivial to look up all the accounts with lots of gold, or trialmaster gear...?

**Comment by Catornado** [comment]
i had something similar, the arena wouldn't load for me

**Comment by PatheticMustan** [comment]
Closed until OP tells us what hacks they used with screenshot of the error
