### ISSUE TITLE
[BUG]Prodigy not loading with extension after update. Please Fix.

### ISSUE THREAD

**Issue by HyperDiaper** [Prodigy-Hacking/ProdigyMathGameHacking#733]
***Description***: The Prodigy Math Game won't load unless I delete the extension. I did everything right and after update it doesn't work.

***Replication***:

***Images***:

***Additional Errors***:

**Comment by Hamza123-png** [comment]
Same just got the new one and it shows this ...

![image](https://user-images.githubusercontent.com/74549019/111362046-bbc47c80-8664-11eb-8bb8-50193c11d47b.png)

**Comment by Hamza123-png** [comment]
For very long now

**Comment by ChickenOnYT** [comment]
is offline be patient
