### ISSUE TITLE
Not able to join with new update [BUG]

### ISSUE THREAD

**Issue by Hamza123-png** [Prodigy-Hacking/ProdigyMathGameHacking#734]
***Description***: When I try to join it sticks me on the loading screen and I cant  join

***Replication***:

***Images***: 
![image](https://user-images.githubusercontent.com/74549019/111363973-11018d80-8667-11eb-8a88-8211cc3a7fab.png)

***Additional Errors***:

**Comment by ChickenOnYT** [comment]
hacks are down be patient

**Comment by Hamza123-png** [comment]
But it still doesn't work

**Comment by ChickenOnYT** [comment]
i know be patient we're working on it
