### ISSUE TITLE
[BUG] Prodigy won't load with the extention

### ISSUE THREAD

**Issue by LandonBoi123** [Prodigy-Hacking/ProdigyMathGameHacking#735]
***Are you trying to get my account info? anyways this won't even let me into prodigy so please fix it!***:

***Replication***:

***Images***: https://www.mediafire.com/view/nnnc3scjto9n8gi/Play_Prodigy_-_Google_Chrome_3_16_2021_3_28_51_PM.png/file

***Additional Errors***:

**Comment by ChickenOnYT** [comment]
> Are you trying to get my account info? anyways this won't even let me into prodigy so please fix it!:

the hacks are down we litterally told you to use an alt regardless so if you listened to us you shouldnt worry about that google reviews the source code of all extensions on the web store so im pretty sure the largest technology company in the world would notice if we were hacking you
