### ISSUE TITLE
Idea on how to fix the whole mobile cheat menu DMCA app store play store thingy..

### ISSUE THREAD

**Issue by hellonearth311** [Prodigy-Hacking/ProdigyMathGameHacking#746]
We can make an app has a popup  that always stays on your screen no matter what at the click of a button in the app.
We just add the same code into the Mobile WCM and click a button in the app to activate it.
Then we login to prodigy and boom!
Hack away!

**Comment by ChickenOnYT** [comment]
ty for the suggestion

**Comment by ChickenOnYT** [comment]
i need a review from you 3

**Comment by UntrustableRus** [comment]
I'm still confused what they're saying, either way, it's not an app, it's going to be a proxy

**Comment by ChickenOnYT** [comment]
ah i see ok
