### ISSUE TITLE
Our mobile WCM developing.

### ISSUE THREAD

**Issue by hellonearth311** [Prodigy-Hacking/ProdigyMathGameHacking#748]
Can someone tell me where to help develop?
I want to help the PMGH repo in some way.
Thanks. 
(I've found a simple way to (maybe) pull this off with that Proxy Server).
Thanks,
hellonearth311.

**Comment by NX721** [comment]
Add a file and make a pull req @hellonearth311

**Comment by PatheticMustan** [comment]
If you want, you can ask @UntrustableRus, who's working on it most

**Comment by hellonearth311** [comment]
Alright, thx.
