### ISSUE TITLE
[HR] Enable all functions while waiting on titan battle

### ISSUE THREAD

**Issue by hellonearth311** [Prodigy-Hacking/ProdigyMathGameHacking#750]
Make a hack in WCM that lets you do things you can't do while waiting for a team titan battle to start.
Yes, it is not currently available.

**Comment by Hamza123-png** [comment]
That makes no sense 

¯\(°_o)/¯

**Comment by NX721** [comment]
Oh you mean enable all options while starting a team battle. 
Will look into it.

**Comment by hellonearth311** [comment]
thx

**Comment by hellonearth311** [comment]
i think it's also WCM..

**Comment by NX721** [comment]
But if we do this what if someone travels, and it crashes the game?

**Comment by hellonearth311** [comment]
Just make it so the Map is still disabled.
Everything else is enabled,

**Comment by NX721** [comment]
> Just make it so the Map is still disabled.
> Everything else is enabled,

Hey did u make a discord acc?

**Comment by NX721** [comment]
> i think it's also WCM..

I meant we "will" not wcm

**Comment by PatheticMustan** [comment]
> > i think it's also WCM..
> 
> I meant we "will" not wcm

what
