### ISSUE TITLE
[BUG] Hosting redirector does not work.

### ISSUE THREAD

**Issue by hostedposted** [Prodigy-Hacking/ProdigyMathGameHacking#756]
***Description***:
I tried hosting redirector, but when I go to http://localhost:1337 the page never loads. 

***Replication***:
Run redirector using node.

**Comment by NX721** [comment]
We will fix it. Thank you for telling us.

**Comment by NX721** [comment]
Use the WCM for now.

**Comment by hugo875** [comment]
i don't use redirector anymore

**Comment by hugo875** [comment]
i use wcm

**Comment by hostedposted** [comment]
I use wcm but I like hosting it my self. Instead of using https://prodigyhacking.ml.

**Comment by PatheticMustan** [comment]
> _**Description**_:
> I tried hosting redirector, but when I go to http://localhost:1337 the page never loads.
> 
> _**Replication**_:
> Run redirector using node.

Are there any errors?

**Comment by PatheticMustan** [comment]
Oh yes, uh... that might need to be updated

**Comment by PatheticMustan** [comment]
Does locking an issue allow the OP to post?

**Comment by hostedposted** [comment]
> Does locking an issue allow the OP to post?

According to this [link](https://docs.github.com/en/github/building-a-strong-community/locking-conversations#:~:text=Repository%20owners%20and%20collaborators%2C%20and,to%20defuse%20a%20heated%20interaction.&text=Locking%20a%20conversation%20creates%20a,read%20access%20to%20the%20repository):

While a conversation is locked, only people with write access and repository owners and collaborators can add, hide, and delete comments.

So the OP can not post.

**Comment by hostedposted** [comment]
Just saw that redirector was replaced with P-NP.

**Comment by PatheticMustan** [comment]
Sorry, we should probably update the docs
