### ISSUE TITLE
[BUG] When reset character on an alt acc it dosnt show on another device  what you have done on another device.

### ISSUE THREAD

**Issue by ThatOneKid958GitHubIsASs** [Prodigy-Hacking/ProdigyMathGameHacking#761]
***When I go on an alt I put everything possible and click reset and go to another device or the same device it just shows that I’m lvl 1 and I don’t have s#$* at all. ***:

***idk what this is supposed to be***:

***No images no cap not trying this on my main ***:

***Reset button issue***:

**Comment by ThatOneKid958GitHubIsASs** [comment]
Was this supposed to happen cuz I tried this on alt got everything. Came back reset. Change name and got everything and came back. And when I came back once again I’m lvl 1 and my alt dosnt got any hack that I put on. Either u don’t care or it’s a real issue.

**Comment by NX721** [comment]
If Save Character doesn't work then Battle!
I mean wtf

**Comment by PatheticMustan** [comment]
after doing hacks, just walk around or something. It should save after a battle, or buying a thing
