### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by achen6067** [Prodigy-Hacking/ProdigyMathGameHacking#762]
***Description***:
Y'all fricken said it was fixed but it still loads half way for me

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/80373897/111734037-9fd0fe80-884f-11eb-981a-70a4693b85f6.png)

***Additional Errors***:

**Comment by NX721** [comment]
Try doing the steps again or restarting your device.

**Comment by BoredFishRE** [comment]
Please name your bugs and send screenshots of the console.
