### ISSUE TITLE
[MPL] License Violation

### ISSUE THREAD

**Issue by NX721** [Prodigy-Hacking/ProdigyMathGameHacking#763]
I have found someone's channel using the WCM without any credit in all of his videos. He also has 1 of our old files (src_.zip) and he uses many of our hacks, and says that it's fake on @ChickenOnYT updated hack video, saying that it doesn't work, even though he uses it himself.  SO I think he's copyrighting the WCM and taking credit for himself. [http://youtube.com/watch?v=JBvt4P0TGVE] 
 (Link for video see his channel for more violations) (Name is: Prodigy Life with 163 Subscribers)

**Comment by ArcerionDev** [comment]
feel free to dm me, but please don't open an issue for this

**Comment by NX721** [comment]
mk
