### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by doormatt-cool** [Prodigy-Hacking/ProdigyMathGameHacking#764]
If I try to use the extension then the game just won't load. If I don't use the extension then I can play prodigy perfectly fine. Please fix

**Comment by ArcerionDev** [comment]
please send a screenshot of your console when trying to enter the game

**Comment by NX721** [comment]
> If I try to use the extension then the game just won't load. If I don't use the extension then I can play prodigy perfectly fine. Please fix

Try restarting your device, then follow the steps again. If that doesn't work, try entering Prodigy, do a battle and do the installation steps again.

**Comment by ChickenOnYT** [comment]
please try to buy from me on ebay and then see if it works

**Comment by ChickenOnYT** [comment]
jk just do what arc and nx said

**Comment by ChickenOnYT** [comment]
but buying from me isnt that bad of an idea..

**Comment by PatheticMustan** [comment]
@doormatt-cool, please screenshot the errors in console...

**Comment by NX721** [comment]
Or restart ur device

**Comment by PatheticMustan** [comment]
@doormatt-cool I need to know if the error still occurs, and more information about the error itself. Pleaseeeee screenshot, or we'll close this issue

**Comment by PatheticMustan** [comment]
Typo :P

**Comment by NX721** [comment]
😛

**Comment by BoredFishRE** [comment]
No response from user, closing now...
