### ISSUE TITLE
[BUG] Loading local character does not work.

### ISSUE THREAD

**Issue by hostedposted** [Prodigy-Hacking/ProdigyMathGameHacking#767]
***Description***:
When you load character it can not parse playerdata.

***Replication***:
Load playerdata.

***Images***:
![](https://user-images.githubusercontent.com/70211235/111790925-1a723c00-8899-11eb-84a8-4162dc9468f8.JPG)

***Additional Errors***:
I tried hosting willsCheatMenu and stringifying playerdata but then it would give this error:
![](https://user-images.githubusercontent.com/70211235/111791406-8b195880-8899-11eb-98b7-f0693ef971d6.JPG)
and crash prodigy.

**Comment by PatheticMustan** [comment]
confirmed, will fix now

**Comment by hostedposted** [comment]
@PatheticMustan gives this a error: ![](https://user-images.githubusercontent.com/70211235/111791406-8b195880-8899-11eb-98b7-f0693ef971d6.JPG)

**Comment by hostedposted** [comment]
@PatheticMustan Now errors with this:

![](https://user-images.githubusercontent.com/70211235/111802438-5bbc1900-88a4-11eb-9901-d36301d69173.JPG)

**Comment by NX721** [comment]
I made an issue for this already

**Comment by hostedposted** [comment]
Why was the closed? There's no other issue for it

**Comment by PatheticMustan** [comment]
oh heck, alright

**Comment by hostedposted** [comment]
I fixed it by using the api. It's not perfect as we don't have a method of updating the player from the api yet but it works. The commit is https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/807ab1c892ec32798459d17abef0e83ebfdd8ace
