### ISSUE TITLE
[HR] Walk thru walls.

### ISSUE THREAD

**Issue by hellonearth311** [Prodigy-Hacking/ProdigyMathGameHacking#770]
**Describe the hack in 5 words or less:**
Walking thru walls.

**(Optional) Additional information**
Make a WCM toggler that when enabled, lets you walk thru anything.

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes.

**Comment by NX721** [comment]
You mean walk through game borders, and that might be confusing for other players, but we'll look into it.

**Comment by PatheticMustan** [comment]
dupe of #624
