### ISSUE TITLE
New pet in Prodigy "Add Pet" Feature Request

### ISSUE THREAD

**Issue by Nebluff102938888** [Prodigy-Hacking/ProdigyMathGameHacking#771]
Can Prodigy Hacking add "The Ancient" as an Add Pet option? If you can add The Ancient on the Add Pet list that'd be INCREDIBLE!

**Comment by irhrhd** [comment]
Thats not possible just like the titan isnt 🤦‍♂️

**Comment by Nebluff102938888** [comment]
Oh...

**Comment by NX721** [comment]
Not possible, Ancient ID is a boss not a pet ID same with The Titan ID

**Comment by NX721** [comment]
If it was possible, it would break the game.

**Comment by NX721** [comment]
@Nebluff102938888  Close This Please.
