### ISSUE TITLE
Prodigy keeps loading half way when I have the extension on

### ISSUE THREAD

**Issue by achen6067** [Prodigy-Hacking/ProdigyMathGameHacking#773]
***Description***:
Prodigy keeps loading half way can you fix that

***Replication***:

***Images***:
![image](https://user-images.githubusercontent.com/80373897/111841599-950c7d00-88d4-11eb-9d71-183b607e802d.png)

***Additional Errors***:

**Comment by achen6067** [comment]
Oh and here picture of console

![Uploading image.png…]()

**Comment by PatheticMustan** [comment]
oh, now this is an actual error!

Can you attach the gamemin?

**Comment by ChickenOnYT** [comment]
blocked by client. something on their device blocked it.

**Comment by achen2341** [comment]
Sorry for not responding

**Comment by achen2341** [comment]
BoredFish did something so I couldn't say anything and now I decided to make a new account

**Comment by achen2341** [comment]
What is gamemin?

**Comment by achen2341** [comment]
Nevermind I found it here a picture of it

![image](https://user-images.githubusercontent.com/81065431/111894868-b8bee880-89e4-11eb-9051-605229069f5c.png)

**Comment by achen2341** [comment]
Here more picture of the console

![image](https://user-images.githubusercontent.com/81065431/111894910-3551c700-89e5-11eb-9830-3192a37e0206.png)

**Comment by ChickenOnYT** [comment]
its blocked by your computer

**Comment by PatheticMustan** [comment]
> blocked by client. something on their device blocked it.

this is not the error

**Comment by ChickenOnYT** [comment]
oh i see

**Comment by Estar-art** [comment]
i still can not load it up

**Comment by lfmarinescu** [comment]
and i am on a non monitored pc that i bought
so idk why

**Comment by lfmarinescu** [comment]
proof:
![image](https://user-images.githubusercontent.com/63551218/112176841-d2238880-8bce-11eb-8809-f2b95fd068ca.png)

**Comment by PatheticMustan** [comment]
try again, hacks should be online now

**Comment by Epicgamer1708** [comment]
help 
![Screenshot (55)](https://user-images.githubusercontent.com/80921295/112534933-b0b2d000-8d79-11eb-8bbe-409e8c3c6520.png)
