### ISSUE TITLE
[BUG] I can only go in epic arena with Ecplise, Diveodile, and Magmischief.

### ISSUE THREAD

**Issue by hellonearth311** [Prodigy-Hacking/ProdigyMathGameHacking#775]
***Description***:
Any other epic just shows the swirly animation but doesn't teleport me.

***Replication***:
go in the epic arena with the extension

**Comment by NX721** [comment]
Can u show a screenshot @hellonearth311

**Comment by hellonearth311** [comment]
https://user-images.githubusercontent.com/79378144/111881878-a14e1400-8980-11eb-80cd-1911ae354572.mp4

**Comment by PatheticMustan** [comment]
could you show it going into the arena?

**Comment by hellonearth311** [comment]
there u go a video

**Comment by hellonearth311** [comment]
i cant go in the arena.
only magmischief, diveodile, and eclipse

**Comment by hellonearth311** [comment]
i'll show magmischief going in arena.

**Comment by hellonearth311** [comment]
https://user-images.githubusercontent.com/79378144/111882084-8e880f00-8981-11eb-9a4e-42a74175db6a.mp4

**Comment by PatheticMustan** [comment]
oh, wow

**Comment by PatheticMustan** [comment]
Related to #577

**Comment by NX721** [comment]
@PatheticMustan  Seems that this is the error
![image](https://user-images.githubusercontent.com/77288637/112164515-51f82580-8bc4-11eb-8e5f-01c5502026a7.png)

**Comment by lichessgoodchesscombad** [comment]
yes that constantly happens
what about trying delete pets and get all epics and see? it's a hit or miss.

**Comment by ArcerionDev** [comment]
shut up ga

**Comment by ArcerionDev** [comment]
pretending

**Comment by ArcerionDev** [comment]
there

**Comment by ArcerionDev** [comment]
is

**Comment by ArcerionDev** [comment]
activity

**Comment by ArcerionDev** [comment]
go

**Comment by ArcerionDev** [comment]
brr

**Comment by BETPRODIGYHACKER** [comment]
lol

**Comment by donaldli2020** [comment]
uhhhhhhhhh

**Comment by LeoBadeaux** [comment]
Closed, this should be working now (refer to [related issue](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/issues/577#issuecomment-879287281) et seq.
