### ISSUE TITLE
Mobile 

### ISSUE THREAD

**Issue by irhrhd** [Prodigy-Hacking/ProdigyMathGameHacking#778]
I know how to get the hacks on mobile

**Comment by hellonearth311** [comment]
omg tell me :D

**Comment by ChickenOnYT** [comment]
interest

**Comment by irhrhd** [comment]
There is a shortcut that can run javascript like the javascript for hacking

**Comment by UntrustableRus** [comment]
#694 Already 10 issues about mobile.

**Comment by PatheticMustan** [comment]
Bookmarklets aren't anything new...
