### ISSUE TITLE
Prodigy keeps loading half way when I use the extension.zip

### ISSUE THREAD

**Issue by achen2341** [Prodigy-Hacking/ProdigyMathGameHacking#788]
***Description***:
Prodigy loads half way when I use the extension.zip

***Replication***:

***Images***:
Here picture of console

![image](https://user-images.githubusercontent.com/81065431/111913403-585f9380-8a44-11eb-8f3e-39f7c0f1fd27.png)

***Additional Errors***:

**Comment by ChickenOnYT** [comment]
its blocked by your school, nothing we can do about it unless you have another device, feel free to hmu on ebay if you dont have any other devices and wanna buy one

**Comment by PatheticMustan** [comment]
it's not because it's blocked by school

**Comment by PatheticMustan** [comment]
Let's just move to #764
