### ISSUE TITLE
question about the item stacker in the hacks folder

### ISSUE THREAD

**Issue by UN3N0WNGH0ST** [Prodigy-Hacking/ProdigyMathGameHacking#789]
does the item stacker work in the bookmarklet-maker. if so, you could let know how to make it work

**Comment by NX721** [comment]
No @UN3N0WNGH0ST It's patched but we will fix it.

**Comment by UN3N0WNGH0ST** [comment]
oh ok thanks btw do you know around the time it will be fixed

**Comment by NX721** [comment]
Idk but give me ur discord tag and user and i'll imform u
Thx and close this pls!

**Comment by NX721** [comment]
@UN3N0WNGH0ST  Thank you for your support on this issue.

**Comment by UN3N0WNGH0ST** [comment]
okay i have to make a new discord account my was hacked so ill tell you when i did its probably going to be my Github user tho and your welcome

**Comment by NX721** [comment]
Okay My user is NX721 and my tag is #1595

**Comment by UN3N0WNGH0ST** [comment]
okay ill add you when i made my discord account also if its not my actual Github it will be something close

**Comment by NX721** [comment]
K
