### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by hugo875** [Prodigy-Hacking/ProdigyMathGameHacking#792]
***Description***:
cant login to my acc

***Replication***:
cant login to my acc

***Images***:

![image](https://user-images.githubusercontent.com/78926064/112178078-df8d4280-8bcf-11eb-9bd7-a55ab9f53997.png)

***Additional Errors***:

**Comment by Hamza123-png** [comment]
SAME

**Comment by UN3N0WNGH0ST** [comment]
@Hamza123-png @hugo875 same does anyone know why or have any ideas why?

**Comment by NX721** [comment]
Either you have given yourself too much resources and Prodigy has noticed (And disabled your account) or they caught you hacking. (Use an Alt account)

**Comment by NX721** [comment]
@Hamza123-png @UN3N0WNGH0ST @hugo875

**Comment by NX721** [comment]
### _**Make an Alt Account and not your primary one.**_

**Comment by UN3N0WNGH0ST** [comment]
@NX721 i made a discord account and dm you, also i already tried making 2 or 3 new accounts and it's still stuck (btw i tried both the extension method and the google chrome store method

**Comment by NX721** [comment]
Okay @UN3N0WNGH0ST Can u restart ur device

**Comment by UN3N0WNGH0ST** [comment]
yeah i did alreayd but i guess ill do it again and tell you if it works or not

**Comment by UN3N0WNGH0ST** [comment]
oh nvm i just checked the discord and the hacks are down they said

**Comment by PatheticMustan** [comment]
try again, hacks should be up

**Comment by NX721** [comment]
Okay

**Comment by NX721** [comment]
Can someone close this?

**Comment by jakedasnake1** [comment]
Still not loading
<img width="640" alt="Screen Shot 2021-03-23 at 2 54 28 PM" src="https://user-images.githubusercontent.com/62823842/112202679-06f00980-8be8-11eb-8783-a218a321c1a7.png">

**Comment by NX721** [comment]
> Still not loading
> <img alt="Screen Shot 2021-03-23 at 2 54 28 PM" width="640" src="https://user-images.githubusercontent.com/62823842/112202679-06f00980-8be8-11eb-8783-a218a321c1a7.png">

mk mk

**Comment by Hamza123-png** [comment]
I ONLY use an alt but every alt doesn't work even if its new

**Comment by hugo875** [comment]
@NX721 gonna close this

**Comment by hugo875** [comment]
> I ONLY use an alt but every alt doesn't work 
exactly
