### ISSUE TITLE
[HR] I think you should make it so we could control the level of our pets because I'm tired of grinding my epics to level 80.

### ISSUE THREAD

**Issue by WillBillDillPickle** [Prodigy-Hacking/ProdigyMathGameHacking#793]
**Describe the hack in 5 words or less:**

I think you should make it so we could control the level of our pets because I'm tired of grinding my epics to level 80.
**(Optional) Additional information**
Maybe even control the moves it learns. idk.
**Have you made sure this hack isn't available yet?* (Yes/No)**
No.

**Comment by UN3N0WNGH0ST** [comment]
@WillBillDillPickle it was a thing where you could change the pet level and attacks but i do not know what they did to that feature.

**Comment by NX721** [comment]
They juat used `/*` to hide the scrript and not make it active but it's still there

**Comment by ArcerionDev** [comment]
yeah I figured this out dw

**Comment by NX721** [comment]
Ok
