### ISSUE TITLE
Can you make a video about how to update please?

### ISSUE THREAD

**Issue by WillBillDillPickle** [Prodigy-Hacking/ProdigyMathGameHacking#794]
**Is your feature request related to a problem? Please describe.**
I still don't understand how to update. I read the instructions, but when I go back on my main, it still gives me the pop-up. [...]

**Describe the solution you'd like**
I think the solution is that you should make a video about it.

**Describe alternatives you've considered**

**Additional context**

**Comment by PatheticMustan** [comment]
Sorry, we should've added alrernative instructions; we're still waiting on the chrome web store to update.

**Comment by NX721** [comment]
Deleted Emojis 
![image](https://user-images.githubusercontent.com/77288637/112327149-8e428900-8c8b-11eb-9f49-e75ac47ff973.png)

**Comment by BoredFishRE** [comment]
Please don't post off topic stuff.

**Comment by NX721** [comment]
Ok srry

**Comment by PatheticMustan** [comment]
maybe @ArcerionDev can save us with his video editing skills++?

**Comment by Pathetic-Burger** [comment]
I'm kinda good at making videos but I don't feel like doing it rn

**Comment by BoredFishRE** [comment]
never asked...

**Comment by YamaHacks** [comment]
Expect a new video with clearer and more up to date instructions soon

**Comment by ArcerionDev** [comment]
done already
