### ISSUE TITLE
Hack Request 

### ISSUE THREAD

**Issue by NX721** [Prodigy-Hacking/ProdigyMathGameHacking#804]
Heya, I was thinking, that can we make the texture/skin in Lamplight Town the same as the events without making the events happen?

**Comment by NX721** [comment]
I might find this Idk

**Comment by NX721** [comment]
...

**Comment by NX721** [comment]
Yea Arcerion said it was possible

**Comment by LeoBadeaux** [comment]
@PatheticMustan While I was working on mobile cheat menu, I was able to proxy and edit endpoints, and was able to change the current "season", all it does is put the special season button on the bottom bar in the middle that teleports to lamplight town, however all assets are the same.

**Comment by ChickenOnYT** [comment]
deleted a "..." comment

**Comment by ChickenOnYT** [comment]
bump

**Comment by NX721** [comment]
> @PatheticMustan While I was working on mobile cheat menu, I was able to proxy and edit endpoints, and was able to change the current "season", all it does is put the special season button on the bottom bar in the middle that teleports to lamplight town, however all assets are the same.

May I see the script?

**Comment by Time-dragon** [comment]
> bump

We don't bump on GitHub, unless it's a discussion.

**Comment by Time-dragon** [comment]
> bump

We don't bump here on GitHub, as @RedGuy12 said.
