### ISSUE TITLE
[BUG] when I load into prodigy the loading freezes half way through.

### ISSUE THREAD

**Issue by Theismyname** [Prodigy-Hacking/ProdigyMathGameHacking#805]
***Description***:

***Replication***:

***Images***:

***Additional Errors***:

**Comment by BoredFishRE** [comment]
did you get a message?

**Comment by Theismyname** [comment]
What do you mean by that?

**Comment by BoredFishRE** [comment]
when loading, does an error like "An error occurred while connecting to the server" appear?

**Comment by Theismyname** [comment]
No while you are signing in to the account.

**Comment by BoredFishRE** [comment]
yes, that's what I mean. What version of the extension are you on?

**Comment by Theismyname** [comment]
And I have multiple computer's I have tried on all of them and  it is the same outcome.

**Comment by PatheticMustan** [comment]
What version of the extension are you on

**Comment by Theismyname** [comment]
2.0.2 version

**Comment by BoredFishRE** [comment]
Update to 2.0.3

**Comment by Theismyname** [comment]
Thanks, I'll check it out.

**Comment by Theismyname** [comment]
It works thank's so much
