### ISSUE TITLE
Wouldn't it be better if there was obtain all items?

### ISSUE THREAD

**Issue by lichessgoodchesscombad** [Prodigy-Hacking/ProdigyMathGameHacking#809]
otherwise it will take an overwhelming time to achieve that.

**Comment by ArcerionDev** [comment]
alright will add

**Comment by Pathetic-Burger** [comment]
What is "hostedposted"

**Comment by Pathetic-Burger** [comment]
also @lichessgoodchesscombad I think chess.com is better than lichess

**Comment by LeoBadeaux** [comment]
Seems like this is resolved.

**Comment by ChickenOnYT** [comment]
> also @lichessgoodchesscombad I think chess.com is better than lichess

this
