### ISSUE TITLE
Obtain All Items Throws Error

### ISSUE THREAD

**Issue by NX721** [Prodigy-Hacking/ProdigyMathGameHacking#811]
![image](https://user-images.githubusercontent.com/77288637/112511235-9de3cf80-8d68-11eb-9e2d-7a515d68a4b8.png)
That's your Bug Hunter Reporting!

**Comment by NX721** [comment]
@hostedposted Srry that it doesn't work

**Comment by hostedposted** [comment]
Works fine for me.

![](https://user-images.githubusercontent.com/70211235/112530291-a80fc900-8d7c-11eb-959b-f984955f8e76.JPG)

What number did you enter?

**Comment by NX721** [comment]
...

**Comment by Pathetic-Burger** [comment]
............ (... times 4)

**Comment by ArcerionDev** [comment]
will double check, pretty sure this was fixed

**Comment by NX721** [comment]
I think I'll close this now.
