### ISSUE TITLE
Pet Spell Bugs

### ISSUE THREAD

**Issue by MATEMATIK-SOSYE** [Prodigy-Hacking/ProdigyMathGameHacking#812]
***After nearly _one week ago_ of playing in the arena before I signed off***:

I was playing in the arena with the same two pets I always use [_Applepot_ and _Magmischief_]. The spells they had are as follows:

Applepot → **_Focus Spell I_**
Magmischief → **_Unlimited Power_** & **_Royal Roar_**

I do not know what the deal was, but every time I have been playing in the arena that day, the spells were the way they were for a long time, up until I signed off. I then got on the NEXT day to see what happened, then ALL OF A SUDDEN, the spells **vanished** and were, I think marked as _**Ion Cannon**_ and _**Spearcicle Crush**_. This _definitely_ seemed like a bug or invasion to me. I have NO ideya how this happened.

***Additional Errors***:

Not only this, but I brought in my _Embershed_ [water-type & electric-type spells] to test this bug. This _Embershed_ had the following spell:

**_Downpourtal_**

This looked good when viewed from the pet book, but as SOON as it stood by for clashing when the spellbook came up, that spell ALSO **vanished** and was marked as **_Torrent_**.

Now, my account has been fine for many years, and these spells have been in my book for many years, and now they are gone. I could not believe what I saw. At first, I thought it was a bug, then an invasion of privacy. I just did not know what elce to think afterward.

Now, I have a suggestion for you to add to the menu:

__.player.data.spellbook_

If I recall correctly, this command is supposed to give us a complete list of spells in the game from 1 - 94, but somehow did not wourk when I onse tried it. I wonder why the list never showed up. ANYWAY, you should consider adding this button to the menu as well.

**Comment by Hamza123-png** [comment]
IDK it happened to me so I just hacked for different pets

**Comment by ArcerionDev** [comment]
so the thing is
you know the fix battle bug thing?
we're now running it every 15 seconds or so
however
it assigns random spells to the pet team

**Comment by NX721** [comment]
Rip

**Comment by NX721** [comment]
I had a list if what worked and what didn't @ArcerionDev

**Comment by MATEMATIK-SOSYE** [comment]
> so the thing is
> you know the fix battle bug thing?
> we're now running it every 15 seconds or so
> however
> it assigns random spells to the pet team

You should re-enable "Edit Pet" because remember, even when someone claimed it was breaking certain commands, as long as my account has been been wourking, it was STILL wourking, even up to this day. Please re-enable it? I do **not** know what te heck was going on there.

Also, I never ONSE tapped the button, and it STILL re-marked my spells. 🤷🏼‍♂️

**Comment by PatheticMustan** [comment]
> so the thing is
> you know the fix battle bug thing?
> we're now running it every 15 seconds or so
> however
> it assigns random spells to the pet team

Bruh, I told you not to do that

**Comment by PatheticMustan** [comment]
> > so the thing is
> > you know the fix battle bug thing?
> > we're now running it every 15 seconds or so
> > however
> > it assigns random spells to the pet team
> 
> You should re-enable "Edit Pet" because remember, even when someone claimed it was breaking certain commands, as long as my account has been been wourking, it was STILL wourking, even up to this day. Please re-enable it? I do **not** know what the heck was going on there.
> 
> Also, I never ONSE tapped the button, and it STILL re-marked my spells. 🤷🏼‍♂️

Thanks for the detailed bug report, we'll change it quickly.

**Comment by ChickenOnYT** [comment]
> You should re-enable "Edit Pet" because remember, even when someone claimed it was breaking certain commands, as long as my account has been been wourking, it was STILL wourking, even up to this day. Please re-enable it? I do not know what the heck was going on there.

This repository gets like 11k weekly views, yet only 3k people kept the extension installed... not understanding the battle crash has been one of the causes.

**Comment by MATEMATIK-SOSYE** [comment]
> > You should re-enable "Edit Pet" because remember, even when someone claimed it was breaking certain commands, as long as my account has been been wourking, it was STILL wourking, even up to this day. Please re-enable it? I do not know what the heck was going on there.
> 
> This repository gets like 11k weekly views, yet only 3k people kept the extension installed... not understanding the battle crash has been one of the causes. 

I never said that the button was one of the causes. I just mentioned that because someone claimed that the "Edit Pet" option was breaking certain commands, yet for as long as I have tried it, my account has been **flawless**, and I request for the button to be returned. Now, as far as the "Fix Baddle Crash", you said it assigns _random_ spells to the ENTIRE team every time it is touched, correct?

**Comment by PatheticMustan** [comment]
> > You should re-enable "Edit Pet" because remember, even when someone claimed it was breaking certain commands, as long as my account has been been wourking, it was STILL wourking, even up to this day. Please re-enable it? I do not know what the heck was going on there.
> 
> This repository gets like 11k weekly views, yet only 3k people kept the extension installed... not understanding the battle crash has been one of the causes.

3k doesn't include people who manually install

**Comment by NX721** [comment]
I still manually install it tho

**Comment by ChickenOnYT** [comment]
> > > You should re-enable "Edit Pet" because remember, even when someone claimed it was breaking certain commands, as long as my account has been been wourking, it was STILL wourking, even up to this day. Please re-enable it? I do not know what the heck was going on there.
> > 
> > 
> > This repository gets like 11k weekly views, yet only 3k people kept the extension installed... not understanding the battle crash has been one of the causes.
> 
> 3k doesn't include people who manually install

ik, but still, it's worth considering

**Comment by PatheticMustan** [comment]
of course, yeah
