### ISSUE TITLE
I am trying to load it in extensions, but it will sayFailed to load extension from: C:\Users\cjere\Downloads\ProdigyMathGameHacking-master (1).zip. Could not unzip extension for install. IIs there any fix?[BUG]

### ISSUE THREAD

**Issue by B13D4R** [Prodigy-Hacking/ProdigyMathGameHacking#813]
***Description***:

***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
make sure you do nothing with the zip file, just immediately drag it in, don't put it in any extra folders or anything

**Comment by B13D4R** [comment]
i didnt

**Comment by B13D4R** [comment]
i tried downloading extension and -master file
it didnt work

**Comment by B13D4R** [comment]
Failed to load extension from: C:\Users\cjere\AppData\Local\Temp\extension (1)_14232_1872665961. Could not load icon 'assets/x16.png' specified in 'icons'.

**Comment by B13D4R** [comment]
Is anyone answering?

**Comment by hostedposted** [comment]
Where did you download it from?

**Comment by B13D4R** [comment]
Here
I also tried using the old one and it worked

**Comment by hostedposted** [comment]
Try using this one: https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/PHEx/build/extension.zip?raw=true

**Comment by B13D4R** [comment]
I dont need any help i just downloaded the old version and it updated

**Comment by ChickenOnYT** [comment]
wth ok
