### ISSUE TITLE
Save toggler status.

### ISSUE THREAD

**Issue by hostedposted** [Prodigy-Hacking/ProdigyMathGameHacking#817]
Save the status of toggler's on willsCheatMenu.

So if you click toggle membership then reload, it is auto clicked.

**Comment by NX721** [comment]
But that would get us in LEGAL isuues wouldn't it?

**Comment by hostedposted** [comment]
No. I did not mean perm membership I mean something like this for disable monster encounters as it is another toggler.

If you click disable monster encounters then reload prodigy and login for disable monster encounters to be auto clicked.

**Comment by hostedposted** [comment]
Something like this in code:

```js
localStorage.setItem("membership", "false")
membership.onclick(function() {
    localStorage.setItem("membership", "true")
})
if (localStorage.getItem("membership")) {
    membership.click()
}
```
membership being the membership button. And it being for all togglers.

**Comment by PatheticMustan** [comment]
> But that would get us in LEGAL isuues wouldn't it?

no lmao

> Something like this in code:
> 
> ```js
> localStorage.setItem("membership", "false")
> membership.onclick(function() {
>     localStorage.setItem("membership", "true")
> })
> if (localStorage.getItem("membership")) {
>     membership.click()
> }
> ```
> 
> membership being the membership button. And it being for all togglers.

seems like a good idea
