### ISSUE TITLE
Loading Bug [Common]

### ISSUE THREAD

**Issue by AidenTND** [Prodigy-Hacking/ProdigyMathGameHacking#821]
The bar is not going up. My screen turns white for about a minute and then it shows me the loading screen and the bar won't go up.

**Comment by NX721** [comment]
Restart your device

**Comment by Pathetic-Burger** [comment]
it happened to me too

**Comment by BoredFishRE** [comment]
Please name your issues. Can you check if you have the latest version of the extension. the latest one is on the chrome webstore.

**Comment by ArcerionDev** [comment]
please provide a screenshot

**Comment by ArcerionDev** [comment]
of your console

**Comment by CyberXVI** [comment]
When this happened to me they told me to go to this link:https://prodigyhacking.ml/status
If it says error 504 or something then prodigy hax don't work

**Comment by NX721** [comment]
Restart your device.

**Comment by CyberXVI** [comment]
2.0.3

**Comment by BoredFishRE** [comment]
can you visit https://prodigyhacking.ml/version

**Comment by CyberXVI** [comment]
sure
it only says 2.0.3

**Comment by BoredFishRE** [comment]
alright hmmmm. When loading, could you send a screenshot of the console?

**Comment by CyberXVI** [comment]
I am not the one with the problem, @AidenTND is

**Comment by BoredFishRE** [comment]
Oh i misread the first message

**Comment by CyberXVI** [comment]
?

**Comment by BoredFishRE** [comment]
I thought you were having problems lmao

**Comment by CyberXVI** [comment]
ha.

**Comment by PatheticMustan** [comment]
@AidenTND, please tell us what happens when you visit https://prodigyhacking.ml/version

**Comment by Pathetic-Burger** [comment]
When I go to it (cuz the same thing happens to me) it just shows this


![image](https://user-images.githubusercontent.com/81431824/113145176-1ed51800-91fc-11eb-8241-61b8d12c3e85.png)

**Comment by Jackploopy** [comment]
@ArcerionDev  
it does not load for me here is a screenshot it stays there not loading idk why tho :/
![Screenshot 2021-03-31 3 12 20 PM](https://user-images.githubusercontent.com/73369955/113198128-86f32080-9233-11eb-907e-702b66404985.png)

**Comment by BoredFishRE** [comment]
That means that your school blocks the hacks.
