### ISSUE TITLE
Do you know when the get all runes will work?

### ISSUE THREAD

**Issue by B13D4R** [Prodigy-Hacking/ProdigyMathGameHacking#825]

**Comment by B13D4R** [comment]
oh and also can you make a feature to edit pet moves and other stuff

**Comment by LeoBadeaux** [comment]
> oh and also can you make a feature to edit pet moves and other stuff

You can already edit spells.

**Comment by NX721** [comment]
No, we removed it. It updates your pet's spells every 15 sec to avoid battle crash

**Comment by PatheticMustan** [comment]
please, it was only a temporary removal..

**Comment by lichessgoodchesscombad** [comment]
> No, we removed it. It updates your pet's spells every 15 sec to avoid battle crash

just wondering, why does it generate a battle crash?

**Comment by NX721** [comment]
Because the spells are probably outdated.

**Comment by ChickenOnYT** [comment]
@lichessgoodchesscombad chess.com good

**Comment by lichessgoodchesscombad** [comment]
chesscom bad

**Comment by ArcerionDev** [comment]
please keep conversations on topic

**Comment by ChickenOnYT** [comment]
> chesscom bad

chess.com good

**Comment by ChickenOnYT** [comment]
> please keep conversations on topic

fine >:(
