### ISSUE TITLE
Add custom spells to the pets [Feature Request]

### ISSUE THREAD

**Issue by Pathetic-Burger** [Prodigy-Hacking/ProdigyMathGameHacking#827]
**Is your feature request related to a problem? Please describe.**
No, it's not related to a problem

**Describe the solution you'd like**
I want pets to have custom attacks and spells eg. a fire pet has a water attack

**Describe alternatives you've considered**
If not, make us able to name attacks/spells 
**Additional context**
eg. snowfluff uses bjhfkvbfhj attack

**Comment by Pathetic-Burger** [comment]
i think this would be helpful

**Comment by Pathetic-Burger** [comment]
> i think this would be helpful

> i think this would be helpful

**Comment by Pathetic-Burger** [comment]
> > i think this would be helpful
> 
> > i think this would be helpful

> > i think this would be helpful
> 
> > i think this would be helpful

**Comment by Pathetic-Burger** [comment]
>>>>>>>  e

**Comment by Pathetic-Burger** [comment]
>>>>>>>>>>>>>>>>>>>>
>>>
>>>
>>>>>>>>> e

**Comment by Pathetic-Burger** [comment]
> > i think this would be helpful
> 
> > i think this would be helpful

**Comment by BoredFishRE** [comment]
bruh don't spam

**Comment by Pathetic-Burger** [comment]
ok, but can you add it

**Comment by PatheticMustan** [comment]
not possible
