### ISSUE TITLE
Get to the last tower in the Dark Tower

### ISSUE THREAD

**Issue by CyberXVI** [Prodigy-Hacking/ProdigyMathGameHacking#828]
**Is your feature request related to a problem? Please describe.**
No it isn't.

**Describe the solution you'd like**
I want it so next time you go to the dark tower, you will battle the "powerful wizard" on the top floor.
**Describe alternatives you've considered**
I don't understand this

**Comment by Pathetic-Burger** [comment]
That would be cool

**Comment by CyberXVI** [comment]
It really would

**Comment by NX721** [comment]
@CyberXVI Do you mean finishing the tower instanly?

**Comment by CyberXVI** [comment]
I mean like when you click on the button you get teleported. Ex. I was on the first tower, but when i clicked on the "Finish tower" button, i was on the 100th floor battling mira shade

**Comment by CyberXVI** [comment]
@NX721 U THERE?

**Comment by CyberXVI** [comment]
srry caps

**Comment by BoredFishRE** [comment]
We had that, but we had to remove it because it didn't work.

**Comment by Pathetic-Burger** [comment]
oof

but can you re-add it @BoredFishRE?

**Comment by Pathetic-Burger** [comment]
> oof
> 
> but can you re-add it @BoredFishRE?

And fix it?

**Comment by BoredFishRE** [comment]
no. You try to.

**Comment by ArcerionDev** [comment]
damnnn brutal

**Comment by hostedposted** [comment]
You can use this code: ``_.player.data.tower = 100`` to get to floor 100.
