### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Leader01-alt** [Prodigy-Hacking/ProdigyMathGameHacking#834]
B̴̟͎̻͌̓́z̴̻͚̈́͠͝z̸̙͙͕̈́̿͆T̴̝̘̞̽͊͝The B̴̟͎̻͌̓́z̴̻͚̈́͠͝z̸̙͙͕̈́̿͆T̴̝̘̞̽͊͝ loading thing B̴̟͎̻͌̓́z̴̻͚̈́͠͝z̸̙͙͕̈́̿͆T̴̝̘̞̽͊͝slide says B̴̟͎̻͌̓́z̴̻͚̈́͠͝z̸̙͙͕̈́̿͆T̴̝̘̞̽͊͝this notifi-B̴̟͎̻͌̓́z̴̻͚̈́͠͝z̸̙͙͕̈́̿͆T̴̝̘̞̽͊͝-cation:
![2021-03-30 (2)](https://user-images.githubusercontent.com/81653126/113057914-a3338680-917b-11eb-9a77-011e0ea7a85c.png)

**Comment by ChickenOnYT** [comment]
That means 1.) hacks are down 2.) school blocked hacks
