### ISSUE TITLE
 [HR] Teleport walk on the WCM

### ISSUE THREAD

**Issue by Pathetic-Burger** [Prodigy-Hacking/ProdigyMathGameHacking#838]
**Describe the hack in 5 words or less:**
In the WCM add a thing that says "enable teleportation walk"

**(Optional) Additional information**
This is kinda an Idea from the setting walk speed but you just teleport where you click

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes, I have made sure this has not been added

**Comment by LeoBadeaux** [comment]
When change walkspeed is implemented, if you set your walkspeed high enough, it basically will be a teleport. Closed.

**Comment by PatheticMustan** [comment]
LMAOOOO okay

**Comment by NX721** [comment]
Short [HR]
