### ISSUE TITLE
[BUG] why wont harmony island work on any of my devices i have the hack on????

### ISSUE THREAD

**Issue by MichealTheW12-4rd** [Prodigy-Hacking/ProdigyMathGameHacking#859]
***Description***:
Someone know how to fix this???

***Replication***:
Join my org search Luma4Life in orgs

***Images***:

***Additional Errors***:

**Comment by PatheticMustan** [comment]
Harmony Island is currently not supported, we're not exactly sure why

**Comment by MichealTheW12-4rd** [comment]
hey my org ha sonly me would you mind joining it???
Its Luma4Life i support you alot
