### ISSUE TITLE
Join prodigy

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#880]
***Description***:

When i join prodigy is says is has a error conntecting to the server
***Replication***:

***Images***:

***Additional Errors***:

**Comment by ArcerionDev** [comment]
@Protuber please provide a screenshot

**Comment by NX721** [comment]
Yea same, just restart your device and log in again

**Comment by LeoBadeaux** [comment]
Seems like this issue has been resolved, given you've made another issue about a feature request you would need to know all the features therefore you've likely resolved this. Closed.
