### ISSUE TITLE
I want a hack to get all achivements tn prodigy

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#881]
**Describe the hack in 5 words or less:**

**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**

**Comment by ArcerionDev** [comment]
will work on soon

**Comment by hostedposted** [comment]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/e46314f8afa2059ce8d73b54b3a08530a631f095
