### ISSUE TITLE
How do I reset the text from the OWO button?

### ISSUE THREAD

**Issue by RedstoneGuyLol** [Prodigy-Hacking/ProdigyMathGameHacking#887]
I clicked the OWO button and now everything is weird, how do i disable this?

**Comment by ArcerionDev** [comment]
reload

**Comment by UntrustableRus** [comment]
reload

**Comment by RedstoneGuyLol** [comment]
> reload

I tried that...

**Comment by UntrustableRus** [comment]
Then you must have been so lucky to get random owo after manual owo so reload again

**Comment by RedstoneGuyLol** [comment]
> Then you must have been so lucky to get random owo after manual owo so reload again

Ok its back to normal

**Comment by ArcerionDev** [comment]
> Then you must have been so lucky to get random owo after manual owo so reload again

they call him a *madlad*
