### ISSUE TITLE
Help. Is anyone else having this issue? [BUG]

### ISSUE THREAD

**Issue by FlinxDa1** [Prodigy-Hacking/ProdigyMathGameHacking#889]
Hello i am getting the error failed to fetch when I use this.

No I am not using a school computer and my personal computer isn't being used by anyone else.

When it says that failed to fetch then the game doesn't even load!

Can you please help me?

**Comment by FlinxDa1** [comment]
Please help me @PatheticMustan

**Comment by PatheticMustan** [comment]
can you access https://prodigyhacking.ml/ ???

**Comment by ArcerionDev** [comment]
> > can you access https://prodigyhacking.ml/ ???
> 
> Yes. @PatheticMustan

alright, can you send a screenshot of what it says in your console (ctrl+shift+j)?

**Comment by FlinxDa1** [comment]
Okay

**Comment by FlinxDa1** [comment]
Wait, it is working now.

**Comment by ArcerionDev** [comment]
copy the image then do ctrl v

**Comment by FlinxDa1** [comment]
where do i find my sketches

**Comment by FlinxDa1** [comment]
i mean snips

**Comment by FlinxDa1** [comment]
![image](https://user-images.githubusercontent.com/78230425/116721121-f7b06880-a9aa-11eb-98f3-4d719d550540.png)
This is my console.

**Comment by BETPRODIGYHACKER** [comment]
what the heck
