### ISSUE TITLE
[BUG] When I try to buy stuff with coins it won't work

### ISSUE THREAD

**Issue by SakuraKitsunee** [Prodigy-Hacking/ProdigyMathGameHacking#893]
***Description***: When I try to buy stuff with coins for any place on the map it won't work even if I don't get the coins through the cheat menu.(The Academy, Firefly Forest, Skywatch etc.)  

***Replication***: 

***Images***: 
![image](https://user-images.githubusercontent.com/75956379/116788666-c2198700-aa5f-11eb-91d5-3d12554b02db.png)
![image](https://user-images.githubusercontent.com/75956379/116788676-d2c9fd00-aa5f-11eb-9917-b3b746625035.png)

***Additional Errors***:

**Comment by ArcerionDev** [comment]
I'm stupid

**Comment by ArcerionDev** [comment]
one sec fixing

**Comment by GokuUltraInstict13** [comment]
I have this same problem.

**Comment by LeoBadeaux** [comment]
I believe [$cb48bd4](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/cb48bd4bb9d20365d07f49e516d63529b1a9ab15) fixed this
