### ISSUE TITLE
[BUG] Pvp Unresponsive 

### ISSUE THREAD

**Issue by GokuUltraInstict13** [Prodigy-Hacking/ProdigyMathGameHacking#894]
***Description***: Any time I level up to 150 or up I can't Pvp anymore.

It takes forever to load and it normally only takes 1-5 seconds to load.

***Images***:
<img width="1440" alt="Screen Shot 2021-05-02 at 7 36 58 PM" src="https://user-images.githubusercontent.com/78817291/116831499-cb991100-ab7d-11eb-8f69-563b2f44a465.png">

***Additional Errors***: None

**Comment by UntrustableRus** [comment]
Prodigy tries to find somebody close to your level. Since you are hacking, nobody else has that level or any level very close to it so Prodigy can't find anyone to match you up with.

**Comment by GokuUltraInstict13** [comment]
Oh ok, thanks!
