### ISSUE TITLE
[HR] Extra team members

### ISSUE THREAD

**Issue by GokuUltraInstict13** [Prodigy-Hacking/ProdigyMathGameHacking#895]
To have Like more than 3 ppl on your team

(Optional) Additional information: None

**Have you made sure this hack isn't available yet?* (Yes)**

**Comment by GokuUltraInstict13** [comment]
You know how you have your pets 2 on your team, and then yourself, well can you make it so I that we can have **more than**  that? (4,5,6 and so on) 

It kinda sounds _impossible_

**Comment by LeoBadeaux** [comment]
Not exactly sure if it is possible both with displaying it on all clients and people joining, but we'll need to wait for someone who works on the menu  to reply.

**Comment by ArcerionDev** [comment]
impossible, the game simply doesn't have this feature and would be impossible to implement for others to see, and incredibly hard to implement just for the client.
