### ISSUE TITLE
[BUG]Member Hack

### ISSUE THREAD

**Issue by GokuUltraInstict13** [Prodigy-Hacking/ProdigyMathGameHacking#898]
***Description***: It shows everyone has a member but there not a member

***Replication***:

***Images***:
<img width="1440" alt="Screen Shot 2021-05-03 at 12 08 31 PM" src="https://user-images.githubusercontent.com/78817291/116901961-8cfc6880-ac08-11eb-9fdc-573303712bd0.png">

***Additional Info***: I'm the one in the middle, Cody Mythblade.

**Comment by GokuUltraInstict13** [comment]
Not this many people have member because it cost money (unless you have the hacks) so not many people buy it.

**Comment by ArcerionDev** [comment]
yes we're aware of this, we aren't fixing it yet as it's not relevant to the stability of the hacks/game

**Comment by UntrustableRus** [comment]
For further clarification, using this hack does not give everyone on the server membership, it's just a visual bug.
