### ISSUE TITLE
[BUG]Load 

### ISSUE THREAD

**Issue by GokuUltraInstict13** [Prodigy-Hacking/ProdigyMathGameHacking#903]
***Description***: The hacks keep saying: "Oh No! Something went wrong while trying to connect to the server! Try reloading this page. If this error continues to appear, hit ok to join our Discord for support, or create an issue on GitHub. More info TypeError: Failed to fetch. This is normally caused by your school or organization blocking the hacks."

***Replication***: Failed to fetch 

***Images***: None

***Additional Errors***: I reloaded and it did not fix anything

**Comment by NX721** [comment]
Geez Hacks are down

**Comment by LeoBadeaux** [comment]
Hacks seem to be having some intermittent issues these past few days, however, we are looking into it and it seems like this is only happening to some people.

**Comment by NX721** [comment]
> Hacks seem to be having some intermittent issues these past few days, however, we are looking into it and it seems like this is only happening to some people.

Yea it's weird ngl

**Comment by GokuUltraInstict13** [comment]
You have to wait like **5 min to 2 hours** for it to work!

**Comment by ArcerionDev** [comment]
this should be fine now
