### ISSUE TITLE
I would like to be a official Prodigy-Hacking Contributor

### ISSUE THREAD

**Issue by SakuraKitsunee** [Prodigy-Hacking/ProdigyMathGameHacking#912]
I can not go on discord right now but here why I should a Prodigy-Hacking Contributor!! 

------------------------------------------------------------------------------------------------------------------------------------------------------------------

Reasons why I should be a Contributor 

I can code in pretty much all coding languages. (the coding languages i work with JavaScript, Python, C++, HTML, CSS)

I work really well with people and can answer pretty much any question about the hacks and anything else about Prodigy-Hacking 

I’m just a overall hard working person

**Comment by ArcerionDev** [comment]
post some of your projects that you've made with those languages on your github, then we'll see

**Comment by ArcerionDev** [comment]
plus you already have triage access iirc

**Comment by ArcerionDev** [comment]
https://github.com/SakuraKitsunee/fgtg 
why did you just take the index for the arena points generator and just copy it into a markdown file????

**Comment by ArcerionDev** [comment]
it looks like you have 40 repositories and all of them are either not applications or forked from a different repository

**Comment by ArcerionDev** [comment]
I personally don't know if you're suited for collaboration on the repository, but post some of your other projects if you have any, then we'll follow up later.

**Comment by ArcerionDev** [comment]
also html and css are markup languages not coding languages

**Comment by ArcerionDev** [comment]
not to be that guy

**Comment by ArcerionDev** [comment]
but

**Comment by LeoBadeaux** [comment]
Just wait for him to see and reply with previous work.

**Comment by BoredFishRE** [comment]
lmaoooooo
