### ISSUE TITLE
Pets dont get random spells

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#913]
**Describe the hack in 5 words or less:**

**(Optional) Additional information**
 I want a hack that doesn't  random pets spells
**Have you made sure this hack isn't available yet?* (Yes/No)**
No

**Comment by NX721** [comment]
Bruh

**Comment by NX721** [comment]
Just use fix battle crash before you battle.

**Comment by Protuber** [comment]
I did can you shut it you not doing m me any favors

**Comment by ArcerionDev** [comment]
> I did can you shut it you not doing m me any favors

you absolute degenerate you go onto a site with free hacks and beg for more than you already have and when people try to help you're ungrateful as fuck

these are the type of people who make me want to quit this, not gonna lie
say anything disrespectful again and you get blocked from making / commenting on issues
