### ISSUE TITLE
Public Team Meeting / How to go forward

### ISSUE THREAD

**Issue by PatheticMustan** [Prodigy-Hacking/ProdigyMathGameHacking#914]
Rough patches and temporary band-aids have led to low quality of work.
I'm not sure if it's just too much of a hassle to add new functionality, or just a general lack of understanding. Will seems pretty busy, Yama and Bored don't really touch hacks, so it's basically all up to Arc and I. And I've been slacking! So maybe it would be nice to have some new contributors..? What do you think, @ArcerionDev?

**Comment by LeoBadeaux** [comment]
I can keep doing extension development as long as nobody gripes at me every time I do an update. I don't know typescript so I can't work on cheat menu.

**Comment by LeoBadeaux** [comment]
There is a long backlog of feature requests, and I feel we should have people vote on which features they want so we don't have to implement every feature

**Comment by LeoBadeaux** [comment]
I don't know how to compile \shrug

**Comment by ArcerionDev** [comment]
> Might I say, @hostedposted has been doing some great contribution, but of course too early on to invite them.

actually I already did

**Comment by LeoBadeaux** [comment]
BESTPRODIGYHACKER has been impersonating you with their profile picture, not sure what to really do.

**Comment by ArcerionDev** [comment]
um no

**Comment by ArcerionDev** [comment]
![image](https://user-images.githubusercontent.com/60945964/117672119-8aa18d80-b177-11eb-82d6-9a3b70dc24d0.png)

**Comment by LeoBadeaux** [comment]
Yes, it really is just their profile, also I mean't patheticmustan, not you. Really need a voting system for feature requests, kinda sad #1 is still open

**Comment by ArcerionDev** [comment]
oh yeah that's still in development, very confusing stuff, don't know if it's even possible

**Comment by ArcerionDev** [comment]
oh whoopssss

**Comment by ArcerionDev** [comment]
will finish everything for next version

**Comment by BoredFishRE** [comment]
I've been doing things with hacks... occasionally...

**Comment by LeoBadeaux** [comment]
I thought Will left?

**Comment by LeoBadeaux** [comment]
Speaking of that, if so, we do need to rename the hack menu.

**Comment by ArcerionDev** [comment]
any suggestions

**Comment by LeoBadeaux** [comment]
Yeah

**Comment by ArcerionDev** [comment]
prob

**Comment by BoredFishRE** [comment]
I mean, I don't really see some of us making it to the end of the year.

**Comment by LeoBadeaux** [comment]
So, what's the plan?

**Comment by LeoBadeaux** [comment]
Nobody even updates the status.json file and the readme whenever hacks come back up or go down. README still says down from like a week ago.

**Comment by ArcerionDev** [comment]
oops

**Comment by LeoBadeaux** [comment]
Project management do be lacking

**Comment by ArcerionDev** [comment]
rus we don't need you saying how good you are at patching hacks kthx

**Comment by BoredFishRE** [comment]
lmao

**Comment by ArcerionDev** [comment]
hi

**Comment by ArcerionDev** [comment]
good idea

**Comment by BoredFishRE** [comment]
let's just start that now lmao

**Comment by LeoBadeaux** [comment]
Really?

**Comment by LeoBadeaux** [comment]
I guess this project is kinda getting old.

**Comment by LeoBadeaux** [comment]
Yeah

**Comment by LeoBadeaux** [comment]
We fix bugs and patch it but no more new features, plug it up to life support. But what's next, what's afterwards?

**Comment by BoredFishRE** [comment]
idk. Just maintain it from time to time. Move on to other projects.

**Comment by BoredFishRE** [comment]
that's my plan.

**Comment by LeoBadeaux** [comment]
Yes, we would have a voting system, most voted feature each month gets added.

**Comment by LeoBadeaux** [comment]
Mhm.

**Comment by ArcerionDev** [comment]
> We could have a sister company for a different game. Roblox-hacking, Tetretalk-hacking, something like that.

ah yes very pog hacking your own game platform

**Comment by BoredFishRE** [comment]
tbh we could move away from game hacking. Roblox hacking is a real gray area, and there's probably about like 15 others doing it.

**Comment by BoredFishRE** [comment]
> 
> 
> I would work for both sides, not only hacking it but patching them. You guys could be bug bounty hunters.

that's just QA testing.

**Comment by LeoBadeaux** [comment]
Tetretalk is in need of staff so we can absorb you guys.

**Comment by BoredFishRE** [comment]
uh

**Comment by BoredFishRE** [comment]
we're like 150 off of 7k

**Comment by LeoBadeaux** [comment]
Can't lose those members. Tetretalk needs them

**Comment by ArcerionDev** [comment]
why is it over

**Comment by BoredFishRE** [comment]
well, grow the discord should be on that list lmao.

**Comment by BoredFishRE** [comment]
we're so close to 7k

**Comment by LeoBadeaux** [comment]
Closed?

**Comment by PatheticMustan** [comment]
> * Stop taking feature requests
> * Voting system
> * Get more collabs
>   is that it??

ok, no more talky
