### ISSUE TITLE
Hack idea: Become Yeeter

### ISSUE THREAD

**Issue by Emerald-chaos** [Prodigy-Hacking/ProdigyMathGameHacking#923]
**Describe the hack in 5 words or less:**
Turns you into Crystal Monster and names it "Yeeter" (sorry, more than 5 words)

**Have you made sure this hack isn't available yet?* (Yes/No)**

No, but a workaround is name hack (select "yeeter") and Morph hack.

**Comment by LeoBadeaux** [comment]
A little specifically weird, not sure that everybody would want this.

**Comment by LeoBadeaux** [comment]
I don't think Prodigy will let you be named "Yeeter"

**Comment by LeoBadeaux** [comment]
Does name hack show "Yeeter" as an option?

**Comment by NX721** [comment]
> Does name hack show "Yeeter" as an option?

No I don't think so lmfao

**Comment by Emerald-chaos** [comment]
> > Does name hack show "Yeeter" as an option?
> 
> No I don't think so lmfao

You can do custom names.

**Comment by ArcerionDev** [comment]
we aren't making people named yeeter

**Comment by ArcerionDev** [comment]
custom names are *impossible*, they would be invisible to anyone but yourself

**Comment by NX721** [comment]
#687
