### ISSUE TITLE
i want to be level 999999999999999999999999999999999

### ISSUE THREAD

**Issue by minitoonthink0** [Prodigy-Hacking/ProdigyMathGameHacking#928]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/934acb0cc843ae5cbe12faf8242eb8c8d5b9a210/hacks/character/uncapLvl100.js#L2

**Comment by minitoonthink0** [comment]
what is the code to get a will ceat menu

**Comment by ConnorAhern** [comment]
> what is the code to get a will ceat menu

first go to [getavirus.com](https://getavirus.com)
then click all the popups and buttons
ok you have a ceat menu

**Comment by ArcerionDev** [comment]
dck

**Comment by ArcerionDev** [comment]
no

**Comment by ArcerionDev** [comment]
bad
