### ISSUE TITLE
i found a script

### ISSUE THREAD

**Issue by hugo875** [Prodigy-Hacking/ProdigyMathGameHacking#948]
the script is to get more xp from member stars `_.constants.constants["GameConstants.Battle.MEMBER_STARS_PERCENTAGE"] = your number`

**Comment by hugo875** [comment]
@PatheticMustan @ArcerionDev @YamaHacks

**Comment by BoredFishRE** [comment]
Isn't really useful when this exists https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/hacks/character/setLevel.js
