### ISSUE TITLE
[BUG] Trying to update, does not work

### ISSUE THREAD

**Issue by LegendArk1** [Prodigy-Hacking/ProdigyMathGameHacking#949]
***Description***: I am trying to update the Hack following the instructions. I un-installed the hack and re-installed it and pulled it up on the account I use for hacks. The dropdown menu does not appear, I waited five minutes. I unistalled the extension version and then installed the .zip version. This worked, but I'd like to have the extension version back as the .zip says the version is outdated as well. 

***Replication***: Described below

***Images***:

***Additional Errors***: Does not save level when trying to use the .zip file.

**Comment by hostedposted** [comment]
Could you screenshot your console?

**Comment by Protuber** [comment]
same with me

**Comment by LegendArk1** [comment]
Like my page?
![Screenshot 2021-05-15 161006](https://user-images.githubusercontent.com/84231139/118376913-d51c7300-b598-11eb-9ad0-e11808f9a306.png)

**Comment by hostedposted** [comment]
No your console. Press CTRL+SHIFT+I then click console.

**Comment by LegendArk1** [comment]
![Screenshot 2021-05-15 214712](https://user-images.githubusercontent.com/84231139/118382834-293e4c00-b5c7-11eb-809d-d50d4bc302a1.png)

**Comment by hostedposted** [comment]
What extensions do you have? Some extensions do not allow the hacks to work.

**Comment by hostedposted** [comment]
This should be fixed.
