### ISSUE TITLE
[BUG] the hacks dont pop up

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#950]
***Description***:
When I join the game the hacks do not pop up

***Replication***:
It keeps

***Images***:

***Additional Error
it still happened even when I refresh

**Comment by ArcerionDev** [comment]
Make sure you hacr the correct version of the extension installed.

**Comment by Protuber** [comment]
i have the extension on chromne webstore

**Comment by Protuber** [comment]
> Make sure you have the correct version of the extension installed.

**Comment by Protuber** [comment]
i did everything i update the hack every day i don't what happending
