### ISSUE TITLE
[BUG]The hacks are not popping up

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#951]
***Description***:
It happened when I was trying to play prodigy

***Replication***:

Still happens when I reload 
***Images***:
One
![Screenshot (61)](https://user-images.githubusercontent.com/83350992/118371907-5f061500-b574-11eb-84d1-cf0343eb5760.png)

***Additional Errors***:
even when I use the right version it still happens

**Comment by hostedposted** [comment]
What extensions do you have? Some extensions do not allow the hacks to work.

**Comment by Protuber** [comment]
i only have this

**Comment by Protuber** [comment]
i don't get it

**Comment by hostedposted** [comment]
Could you screen shot the console?

**Comment by Protuber** [comment]
i can

**Comment by Protuber** [comment]
this is the console
![Screenshot (62)](https://user-images.githubusercontent.com/83350992/118403892-35152700-b636-11eb-9e31-e6df377c107a.png)

**Comment by Protuber** [comment]
this is the console

**Comment by hostedposted** [comment]
This should be fixed.
