### ISSUE TITLE
[BUG] Achievements not saving

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#958]
***Description***:
 it doesn't save when you reload anything else

***Replication***:
Go to prodigy log  in the press get all achievements to click to save the character and refresh if log back in is still the same

***Images***:
Two

***Additional Errors***:
still happens even when I save

**Comment by iamtheone12345** [comment]
Did you use the "Save Character" hack?

**Comment by Protuber** [comment]
i did do that but is still did the same thing

**Comment by Protuber** [comment]
i did that but is hack don't all save

**Comment by LeoBadeaux** [comment]
Please edit the post to show how to replicate this and provide images, and optionally, additional errors.

**Comment by Protuber** [comment]
Also, why is it every time I make an issue if get solved really quick I don't get it

**Comment by ArcerionDev** [comment]
@Protuber try doing a battle before reloading

**Comment by Protuber** [comment]
ok

**Comment by LeoBadeaux** [comment]
> Also, why is it every time I make an issue if get solved really quick I don't get it

you're not following the format

**Comment by Protuber** [comment]
shut it

**Comment by ArcerionDev** [comment]
> shut it

for future reference, please do follow the issue templates here
![image](https://user-images.githubusercontent.com/60945964/118567065-25373900-b743-11eb-8a05-c6356ffd835f.png)

![image](https://user-images.githubusercontent.com/60945964/118567099-2e280a80-b743-11eb-8ca2-c39da23943b2.png)
then add the correct info in the correct fields

however, if it IS an issue of just someone not knowing where a button is, we *will* also close it

**Comment by LeoBadeaux** [comment]
I'm not trying to be mean, it's just there are a lot of people not following the format and finals are coming up which I have to study and I have to get ready to move so I can be near my university and I got to work on my tetretalk business and do homework etc etc. I'm not trying to be mean to any specific person, just stressful lately.

**Comment by iamtheone12345** [comment]
The only hack that doesn't seem to save is the name-changing hack. The rest seem fine.

**Comment by Protuber** [comment]
ik

**Comment by LeoBadeaux** [comment]
@Protuber Is this issue still occuring? If not, maybe @hostedposted could take a look.

**Comment by ArcerionDev** [comment]
General rule:
Try doing a battle before reloading, that *generally* helps things save, if not, then please follow up

**Comment by Protuber** [comment]
it help it saved now

**Comment by ArcerionDev** [comment]
alright
