### ISSUE TITLE
idk if we have a hack where you can go in all the towers if we dont it will be a cool hack

### ISSUE THREAD

**Issue by yeet3653** [Prodigy-Hacking/ProdigyMathGameHacking#960]
**Describe the hack in 5 words or less:**

**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**

**Comment by LeoBadeaux** [comment]
Please provide more information about the hack- follow the format! At this time, we are not accepting feature requests. D'accord?

**Comment by yeet3653** [comment]
idk what discord is but i can tell u hear

**Comment by LeoBadeaux** [comment]
> idk what discord is but i can tell u hear
> 
> 

It's d'accord, not discord. 2 completely different things.
