### ISSUE TITLE
[HR] Set arena  points

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#961]
**Describe the hack in 5 words or less:**

**(Optional) Additional information**
I want this hack so I can be on the top arena players
**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by SakuraKitsunee** [comment]
@Protuber I'm pretty sure they are not accepting anymore hack requests, but they are doing a voting system on the discord so you can vote for it on the discord, if you want! 😄

**Comment by Protuber** [comment]
i will thanks man

**Comment by Protuber** [comment]
can u send me there disord

**Comment by hostedposted** [comment]
It is impossible to set arena points. It is possible to get 100 points a minute however.

**Comment by hostedposted** [comment]
@Protuber discord is https://discord.gg/XQDfbfq.

Arena point generator will be setup if 100k message's are sent in general this month in the discord.

**Comment by ArcerionDev** [comment]
Nevermind about this im doing it anyway
