### ISSUE TITLE
[HR] Set Arena points

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#968]
**Describe the hack in 5 words or less:**
I think this should be added because I really want to be on the top leaderboards

**(Optional) Additional information**

**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by ArcerionDev** [comment]
This hack is possible, yes

However, Prodigy has a ratelimit of 100 points per minute, which means running it nonstop for the entire month would give you ~4382900 points.
However, you'd have to keep it running all day, and all night.
A month is ~30d so running it nonstop for 3 days would still give you about 438290 points, which usually would bring you to the top, but this really isn't ideal.
So, we're planning on making a site where you can enter your credentials and we'll be giving you arena points even if you shut your device.
However, this is difficult and probably won't be available for a while.
We *are* working on it and hopefully will get it to you by the next arena season.

**Comment by Protuber** [comment]
wow you really toke the time to tell all this

**Comment by ArcerionDev** [comment]
um yes

**Comment by Protuber** [comment]
wait if you add out username and password  it would just give us free points thanks man

**Comment by ArcerionDev** [comment]
that's the plan, it's in development, we have it in https://github.com/Prodigy-Hacking/ArenaPointsHost

**Comment by Protuber** [comment]
ok

**Comment by LeoBadeaux** [comment]
It is a slow progress botting arena points, and we have to learn how it is being ratelimited, we also need the bandwidth and the servers to handle 100+ users botting arena points on our servers. Server costs would be super expensive, and we might have to have a subscription system or something like that. Not easy.

**Comment by ArcerionDev** [comment]
the costs are fine, we have that covered

**Comment by Protuber** [comment]
when i click it you toke me to another same place

**Comment by LeoBadeaux** [comment]
@ArcerionDev Are you sure? We can expect thousands of users to be using this, and Prodigy is going to ratelimit by IP, the singular server you have isn't gonna be able to handle all thousands of people.

**Comment by LeoBadeaux** [comment]
Prodigy will get the IP and will blacklist it. Not to mention this is going to put a bunch of stress of Prodigy's servers as well, so technically it's a DDOS attack.

**Comment by ArcerionDev** [comment]
> Prodigy will get the IP and will blacklist it. Not to mention this is going to put a bunch of stress of Prodigy's servers as well, so technically it's a DDOS attack.

wait i never thought of that

**Comment by ArcerionDev** [comment]
ummmm

**Comment by ArcerionDev** [comment]
hang on maybe we can spoof the request origin somehow

**Comment by Protuber** [comment]
ok

**Comment by LeoBadeaux** [comment]
I've tried looking into how spoofing IP works, and with today's technology and HTTPS it's not that easy.

**Comment by ArcerionDev** [comment]
you are also forgetting that prodigy makes multiple thousand requests to their servers every minute, because of their player base

**Comment by Protuber** [comment]
i dont know  of yall should because  don't  what yall getting in legal trouble

**Comment by ArcerionDev** [comment]
it won't get anyone in legal trouble

**Comment by LeoBadeaux** [comment]
Either way, this still means our server won't be able to handle it all. This is a generic DevOps issue

**Comment by LeoBadeaux** [comment]
Pretty sure prodigy knows we're all just a batch of skids

**Comment by Protuber** [comment]
prodigy already has a lot of people who do arena  battles also do yall think you can get harmony prize coming soon

**Comment by ArcerionDev** [comment]
> Pretty sure prodigy knows we're all just a batch of skids

yes they know we're all sleep deprived teenagers if that's what you mean

**Comment by LeoBadeaux** [comment]
I don't remember what hosting we use for that server, but the server definitely has a bandwidth limit, unless you want to implement kubernetes on hundreds of servers with massive bandwidth which all cost thousands of dollars.

**Comment by Protuber** [comment]
to be honest, prodigy won't know a thing because a lot of people fo battle in the arena

**Comment by Protuber** [comment]
same

**Comment by Protuber** [comment]
the arena points because there was a time I got 1100 arena points

**Comment by Protuber** [comment]
a battle

**Comment by ArcerionDev** [comment]
> They'll be able to detect an IP sending thousands of requests every second.

hopefully will be able to find a way to edit the origin, maybe they accept x-forwarded-for headers xd

I wouldn't be surprised because their captcha doesn't even work

**Comment by LeoBadeaux** [comment]
I feel like they've given up trying to patch the hacks.

**Comment by LeoBadeaux** [comment]
Most of the recent times we went down seems to be updates to the prodigy system that unintentionally patched hacks?

**Comment by ArcerionDev** [comment]
> I feel like they've given up trying to patch the hacks.

yes they occasionally do csp things but nothing significant

I mean *I* could unpatch it and that's saying something

**Comment by ArcerionDev** [comment]
> Most of the recent times we went down seems to be updates to the prodigy system that unintentionally patched hacks?

perhaps intentional perhaps not

**Comment by LeoBadeaux** [comment]
and even like I said spoofing an IP, our tiny server can't handle thousands of users doing this.

**Comment by LeoBadeaux** [comment]
> I mean _I_ could unpatch it and that's saying something

I mean if I worked there I could patch it for good and that's saying something

**Comment by LeoBadeaux** [comment]
Our site is blocked by my school so there's other people in my school district using the hacks, which is interesting. Little do they know that someone in their district works on the very hacks they are using.

**Comment by ArcerionDev** [comment]
> and even like I said spoofing an IP, our tiny server can't handle thousands of users doing this.

I don't actually know about that, because our gamemin gets thousands of requests each day and all of those calls to the gamemin require ~4 additional requests

**Comment by ArcerionDev** [comment]
> Our site is blocked by my school so there's other people in my school district using the hacks, which is interesting. Little do they know that someone in their district works on the very hacks they are using.

wait hang on I thought you were in high school

**Comment by Protuber** [comment]
i mean  it not blocked from out of comptuters

**Comment by LeoBadeaux** [comment]
that's inbound, and user's computers caching the response also helps the servers, we're sending outbound requests in this instance, and it will require a bit more computation on our servers to do an outbound request.

**Comment by LeoBadeaux** [comment]
yes I am

**Comment by Protuber** [comment]
when i try  doing it it said blocked by admin

**Comment by LeoBadeaux** [comment]
The way my area works is all the schools in the area use the same system

**Comment by ArcerionDev** [comment]
> The way my area works is all the schools in the area use the same system

o

**Comment by ArcerionDev** [comment]
> that's inbound, and user's computers caching the response also helps the servers, we're sending outbound requests in this instance, and it will require a bit more computation on our servers to do an outbound request.

um no, we need to make a request to prodigy to find the version, then another to get the gamemin, then another to get te=he publicgamemin

**Comment by LeoBadeaux** [comment]
anything blocked at my high school is blocked at another nearby highschool, middleschool, etc

**Comment by Protuber** [comment]
do yall think yall can get the new prizeses when the harmony isand arena comes

**Comment by LeoBadeaux** [comment]
I'll be in college then, UoT St. George Campus.

**Comment by Protuber** [comment]
wow you senior I just got to middle school in 8th grade

**Comment by LeoBadeaux** [comment]
> do yall think yall can get the new prizeses when the harmony isand arena comes

I can tell you're southern

**Comment by LeoBadeaux** [comment]
Middle school starts at 6th?

**Comment by Protuber** [comment]
i know

**Comment by Protuber** [comment]
when I said i just started middle school I mean I just started 8th grade

**Comment by LeoBadeaux** [comment]
Let me guess, you live in south-eastern USA in texas, alabama, or somewhere nearby. Everyone you meet has a southern accent. You are all anglais.

**Comment by Protuber** [comment]
dude  no

**Comment by LeoBadeaux** [comment]
it's the "y'all" that makes me be able to guess

**Comment by NX721** [comment]
Anglais

**Comment by LeoBadeaux** [comment]
english in french

**Comment by NX721** [comment]
Ik

**Comment by Protuber** [comment]
all i did was make an issue and it got most  chats yet

**Comment by LeoBadeaux** [comment]
I think there's one with more.

**Comment by ArcerionDev** [comment]
stay on topic @LeoBadeaux

**Comment by Protuber** [comment]
thank you

**Comment by Protuber** [comment]
@ArcerionDev

**Comment by LeoBadeaux** [comment]
anyways, we can talk about this on discord later?

**Comment by Protuber** [comment]
ok

**Comment by LeoBadeaux** [comment]
no not you

**Comment by Protuber** [comment]
Jezz

**Comment by LeoBadeaux** [comment]
the outbound bandwidth scaling issue.

**Comment by Protuber** [comment]
ok  you could have just said it niceley

**Comment by ArcerionDev** [comment]
Anyways, with recent issues taken into account

- Get arena points hosting to work

- Make sure we have enough bandwith for ~1000 accounts, I doubt more than that really look at the README.md, which is probably going to be where we display the new site

- Find a way to spoof the origin (Not a must, but just in case Prodigy does actually notice, which is doubtful)

**Comment by ArcerionDev** [comment]
> anyways, we can talk about this on discord later?

sure

**Comment by Protuber** [comment]
you know what funny
