### ISSUE TITLE
[BUG] Basic  water Relic   not showing

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#969]
***Description***:
I just noticed when I was looking through all my relic

***Replication***:
it happens to be it might happened to other people

***Images***:
None

***Additional Errors***:
Still keep  happening even when I do the get all relic hack

**Comment by da638** [comment]
This hapness to me to

**Comment by Protuber** [comment]
it works now but is like the storm relic

**Comment by LeoBadeaux** [comment]
@Protuber It works now? This issue can be closed?

**Comment by Protuber** [comment]
yeah is works now you can close it the only issue is that its the same thing with the basic storm relic

**Comment by da638** [comment]
um sure
