### ISSUE TITLE
can you add a give all items hack

### ISSUE THREAD

**Issue by da638** [Prodigy-Hacking/ProdigyMathGameHacking#970]
**Describe your hack:**

**(Optional) Additional information**

if this hack is not avalible i understand

**Comment by LeoBadeaux** [comment]
(1) We have this already
(2) Feature requests are currently closed
(3) Please follow the format

**Comment by hostedposted** [comment]
@LeoBadeaux We **had** this but it was removed.

**Comment by LeoBadeaux** [comment]
Oh?

**Comment by LeoBadeaux** [comment]
Didn't we have one for each type of item?

**Comment by hostedposted** [comment]
> Didn't we have one for each type of item?


Yes. That was replaced with the selector.

**Comment by LeoBadeaux** [comment]
ah, we should have kept it

**Comment by LeoBadeaux** [comment]
alright well my bad, however feature requests are currently closed right now.

**Comment by da638** [comment]
well ok i was hoping i hope you guys can fix the problems
