### ISSUE TITLE
[BUG]  Loading half way

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#971]
***Description***:
happens when i join  prodigy

***Replication***:
Failed to fetch

***Images***:

***Additional Errors***:
still happens

**Comment by LeoBadeaux** [comment]
Can't confirm right now, bump.

**Comment by YamaHacks** [comment]
Do you have the latest version of the extension?

**Comment by bmoser05** [comment]
it's happening to me too

**Comment by LeoBadeaux** [comment]
@Protuber @bmoser05 Can you guys confirm if any of one of the following websites is blocked by your school?:
 https://prodigyhacking.com
 https://prodigyhacking.ml

**Comment by donaldli2020** [comment]
ahhhhhhhhhhhhhhhhhhhhhhh bad bot

**Comment by LeoBadeaux** [comment]
@Protuber Is this solved? It's been a while

**Comment by LeoBadeaux** [comment]
I assume so. Closed.
