### ISSUE TITLE
I can't do this on iPad

### ISSUE THREAD

**Issue by ViofLe** [Prodigy-Hacking/ProdigyMathGameHacking#972]
Does anyone know. How to do this on iPad? I have no idea. Thanks!

**Comment by AGR-DEVS** [comment]
The only devices you can do this on are Macs, Chromebooks and Windows computers, sorry.

**Comment by ViofLe** [comment]
Ok, thanks. Will mobile be added eventually?

Levi Onyimadu
***@***.***
ハンバ`ガ`は食べ物です

________________________________

**Comment by AGR-DEVS** [comment]
I highly doubt it but there's always a possibility.

**Comment by ArcerionDev** [comment]
we're working on it :D

**Comment by LeoBadeaux** [comment]
I was working on it a bit back but I haven't recently, due to prodigy's recent updates it's making it a little harder to do. However I'll try to work on it some more soon.

**Comment by ViofLe** [comment]
Ok, thanks! :)

Levi Onyimadu
***@***.***
ハンバ`ガ`は食べ物です

________________________________
