### ISSUE TITLE
harmony isand arena not showing  also  where the lastest version

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#978]
***Description***:
It not working or showing

***Replication***:
Go to  prodigy if you a hacker and it won't show

***Images***:

***Additional Errors***:
it still happens

**Comment by hugo875** [comment]
try refreshing

**Comment by hugo875** [comment]
or if you don't have the latest release then get it.

**Comment by hugo875** [comment]
it works for me

**Comment by Protuber** [comment]
i don't have the lasted version i update the hack

**Comment by hugo875** [comment]
oh well

**Comment by hugo875** [comment]
https://sourceforge.net/projects/prodigyhacking/files/2.1.4/extension.zip/download

**Comment by Protuber** [comment]
Thanks you

**Comment by Protuber** [comment]
it still happens

**Comment by BETPRODIGYHACKER** [comment]
please show an screensot

**Comment by ArcerionDev** [comment]
we're aware of this error, we're looking into it.
