### ISSUE TITLE
a

### ISSUE THREAD

**Issue by ConnorAhern** [Prodigy-Hacking/ProdigyMathGameHacking#980]
can someone refactor all my commits into one or something, i dont want to be associated with this repo anymore

**Comment by ConnorAhern** [comment]
also delete this issue once you're done please

thank you

**Comment by LeoBadeaux** [comment]
Reasoning?

**Comment by LeoBadeaux** [comment]
I've sent a friend request on discord so we can consult this matter internally. @ConnorAhern

**Comment by ArcerionDev** [comment]
> can someone refactor all my commits into one or something, i dont want to be associated with this repo anymore

sure
