### ISSUE TITLE
Growing PMGH to more users

### ISSUE THREAD

**Issue by LeoBadeaux** [Prodigy-Hacking/ProdigyMathGameHacking#983]
// Previously created by a previous collaborator, who has requested for association with them to be moved.

# Growing PMGH
Our repository literally had taken off with activity, but now we're only increasing in about 50-100 unique views each month. We need to expand to more users to complete our goal- we're 11% (11k PMGH users out of 100k Prodigy users) of the way there!

## PMGH Website
I feel like if the PMGH website was recoded to be similar to the [PMGH Wiki](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki) and had a lot of SEO changes, then appear higher in Google results, more people would find it, and I feel like we need something simpler than GitHub for an info source, considering everyone _still_ doesn't understand how to hack. (common complaints are not understanding this repository)

## Run ads on YT
You can reach 5k people with like $100. I have money that I can contribute to this. We can target visitors of prodigygame.com who don't visit this repo or our website.

**Comment by BoredFishRE** [comment]
I know ads would be helpful, but we don't have $100 to spend. Hell, I'm barely keeping the VPS afloat.

**Comment by BoredFishRE** [comment]
Also, were getting like 2-3k installs on the extension every day.

**Comment by Protuber** [comment]
SHeesh

**Comment by SakuraKitsunee** [comment]
@PatheticMustan or who ever is the formatting "Growing PMGH to more users" I can help with the YouTube part of it, I can do a sort of thing where I showcase the hacks to show them what to do. I will probably also on a different video, will show how do download the google chrome web store method and the developer mode method.

if there is any other things I can do to help with the YouTube part growing PMGH let me know and if it's possible I will!

**Comment by BoredFishRE** [comment]
We already manage the YouTube fine enough. It's not very important, we want to grow the Github, Extension, Discord, and Website.

**Comment by SakuraKitsunee** [comment]
well is it okay if I showcase the hacks and put the links of the GitHub discord extension etc. or is there anything else you want/ can do?

**Comment by BoredFishRE** [comment]
You can make your own videos, just do the thing in the attributions in docs

**Comment by SakuraKitsunee** [comment]
okay got it!

**Comment by YamaHacks** [comment]
Ads are effectively useless, "reaching 5k people" only shows the ad to 5k people, it by no means guarantees they will click or even see it; not to mention it counts even if they have an ad blocker on, so for about 100 dollars we will maybe get 100 people, which is incredibly bad compared to our current audience. Also, while some more SEO could be good on the website, the look/functionality of it is good.

**Comment by ArcerionDev** [comment]
> Ads are effectively useless, "reaching 5k people" only shows the ad to 5k people, it by no means guarantees they will click or even see it; not to mention it counts even if they have an ad blocker on, so for about 100 dollars we will maybe get 100 people, which is incredibly bad compared to our current audience. Also, while some more SEO could be good on the website, the look/functionality of it is good.

That actually makes a lot of sense
I guess ads aren't really the way to go, however, there are those bots that promote servers, so maybe we should go that route instead if we choose to advertise?

**Comment by BoredFishRE** [comment]
Yeah all ads do is make impressions. Also, ads are very expensive. We would have a 50/50 chance that we would actually hit the audience that cared.

**Comment by ArcerionDev** [comment]
or less

**Comment by ArcerionDev** [comment]
SEO isn't really a must because we already come up first

**Comment by ArcerionDev** [comment]
![Uploading image.png…]()

**Comment by LeoBadeaux** [comment]
I think they mean website SEO

**Comment by LeoBadeaux** [comment]
![image](https://user-images.githubusercontent.com/79180322/119271722-b2a9db80-bbd0-11eb-8f2b-f62c18705c08.png)
We have a good tiktok following, or atleast I'm working on it.

**Comment by ArcerionDev** [comment]
um

**Comment by ArcerionDev** [comment]
what is that platform

**Comment by ArcerionDev** [comment]
oh

**Comment by ArcerionDev** [comment]
do we really need tiktok

**Comment by LeoBadeaux** [comment]
Tiktok

**Comment by ArcerionDev** [comment]
yes I didn't read the bottom text

**Comment by LeoBadeaux** [comment]
more young people on tiktok that probably have prodigy at their school, so a big audience to find. Other people on tiktok have shown off hacks and have gained thousands of views.

**Comment by ArcerionDev** [comment]
> more young people on tiktok that probably have prodigy at their school, so a big audience to find. Other people on tiktok have shown off hacks and have gained thousands of views.

tiktok is blocked in most schools

**Comment by LeoBadeaux** [comment]
yes, but a lot of online students have access to it, and a lot of people have their own phones to use

**Comment by ArcerionDev** [comment]
> yes, but a lot of online students have access to it, and a lot of people have their own phones to use

ok feel free to do it I just don't think it's needed

**Comment by YamaHacks** [comment]
you can have a tiktok just make sure its clear its not an official account

**Comment by bmoser05** [comment]
guys, schools usually block developer mode, and also the extension is blocked, to my extent of my knowledge

so they would need a home computer with extensions NOT blocked (regarding Family link by google if the children use a google account) to be able to install it, dev mode or the extension site

**Comment by LeoBadeaux** [comment]
## The Blockage Issue
Yes, it is true, many schools block developer mode and/or have an extension whitelist which does not allow you to get our extension. We are well aware of this, and there isn't really anything we can do to prevent this from happening. Bookmarklets aren't possible to use for hacking prodigy so that's out of the bag. There aren't any known bypasses to developer mode restrictions or extension whitelist or blacklists, so there really isn't anything we can do about it.

## Expansion
Since there is an issue with many schools not allowing students to download the extension, we are trying to expand to other platforms and create more methods to get the hacks, which is what this post is all about, and to market our product more so more people know about it. Right now there is an issue open that I am assigned to, to open support for mobile devices. I do believe we should come up with more methods for PC though, like I said, but there are no issues opened currently with any concepts in mind for those methods.

## Promotion - Tiktok
The Tiktok account isn't mean't to be seen whilst at school, nobody even uses the web version of Tiktok anyways. The account is official by me since I do work here and am considered an owner of the organization permissions-wise. The Tiktok account isn't just used for promotion of the hacks, but also making sure people who post about the hacks on TIktok credit us properly. There are users on Tiktok posting videos flexing their hacks and the comments are asking how to do it, and the creator of the video won't tell, so the account will reply asking them to watch the latest video on the account to learn how to get the hacks. And the account offers support, allowing people to DM the account with their issue and I will try to help out, if I am unable to do so, I redirect them to our Discord server.

## Promotion - Twitter
One possibility for getting ourselves out there is to create a Twitter account also. We could provide DM support in the Twitter account DMs, and announce new features and such on our Twitter. We could also implement some automation in the Twitter DMs with quick-replies using the Twitter API. I haven't done this but I'm leaving the possibility open out there for a fellow staff member to create an official account.

## Conclusion
With the school year coming to an end and summer break approaching, we can work on these things above, and expand on the ideas.

**Comment by da638** [comment]
um i have a idea you can message me on this email do not use my email for any shading things da740092@gmail.com

**Comment by Time-dragon** [comment]
How do I (who can't get any extensions) get PHEx on my Chromebook?

**Comment by BETPRODIGYHACKER** [comment]
> How do I (who can't get any extensions) get PHEx on my Chromebook?
> edit: unhide this

lol
