### ISSUE TITLE
[BUG] Gett all items not saving

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#985]
***Description***:
So i want in prodigy and when i looked at my items it was back to normal i clicked save   but when i referst and came back it was still like it

***Replication***:
go to the cheat menu and click all items then comeback to prodigy and check you items again

***Images***:
None

***Additional Errors***:
Still happens even when i  doing the same thing

**Comment by ArcerionDev** [comment]
do a battle to save everything. it doesn't matter if you win or not
