### ISSUE TITLE
[HR] Is there by any chance you can set the percentage of runes we collect?

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#988]
**Describe your hack:**

Set Runes Percentage hack
**(Optional) Additional information**
I think this hack would be a  lifesaver to some people
**Have you made sure this hack isn't available yet?* (Yes/No)**
Yes

**Comment by LeoBadeaux** [comment]
Could you please provide more detail on what you mean?

**Comment by Protuber** [comment]
i mean can  we set the percentage  of runes we get  like for example rune 50% hearts  100% hearts can yall add that

**Comment by ArcerionDev** [comment]
actually, we probably could, but it wouldn't affect other people you battle with

**Comment by Protuber** [comment]
WHAT

**Comment by Protuber** [comment]
so you saying if I have an a1000% damage and I go the the harmony and arena it won't affect Them!?!?

**Comment by LeoBadeaux** [comment]
Yes

**Comment by Protuber** [comment]
that  cold LOL!

**Comment by Protuber** [comment]
can you make them affect people

**Comment by LeoBadeaux** [comment]
If we said it can only be a client-side thing, it can only be a client-side thing. EOD.

**Comment by Protuber** [comment]
Dude it idot you can  pass you final but cant learn basic spelling

**Comment by 4evera1one** [comment]
ill see if i can work on this, ill let you know if i make it.

**Comment by LeoBadeaux** [comment]
> ill see if i can work on this, ill let you know if i make it.

you didn't make it didn't you?

**Comment by JeaIousy** [comment]
> > ill see if i can work on this, ill let you know if i make it.
> 
> you didn't make it didn't you?

Nope, its impossible. Prodigy stores the runes with IDs, and the id has the percentage of the rune.
