### ISSUE TITLE
Loads halfway

### ISSUE THREAD

**Issue by bmoser05** [Prodigy-Hacking/ProdigyMathGameHacking#990]
It is loading halfway, and is not loading the prodigy game. please fix. I was able to use for a bit but now doesnt work anymore because it is only loading halfway when I have it installed

**Comment by BETPRODIGYHACKER** [comment]
hhhmm try unstalling and waiting a few minuts

**Comment by AGR-DEVS** [comment]
Hacks are currently down, please wait while admins fix.

**Comment by hostedposted** [comment]
Hacks are now backup.
