### ISSUE TITLE
can battle monsters  not using school computer!

### ISSUE THREAD

**Issue by da638** [Prodigy-Hacking/ProdigyMathGameHacking#993]
when  i try to play some prodigy it just does not let me battle monsters

1-05-25 8 22 06 PM](https://user-images.githubusercontent.com/84422902/119584650-fcdcb980-bd96-11eb-8c66-f7ae521c7b94.png)

what is the point of getting hacks if they dont let you do fun things! not tring to hate copy and paste the link into a new tab and you will see it you can email me at da740092@gmail.com

**Comment by Protuber** [comment]
that happens to me

**Comment by da638** [comment]
i know right

**Comment by da638** [comment]
look at the screen shot

**Comment by Protuber** [comment]
i see it

**Comment by Protuber** [comment]
thanks for pointing this out btw

**Comment by da638** [comment]
yea you welcome

**Comment by Protuber** [comment]
ik

**Comment by Protuber** [comment]
also are you grind of harmony isand arena

**Comment by da638** [comment]
i am actually trying to learn how to hack my birthday is litrally 10 days away and yes

**Comment by Protuber** [comment]
nice

**Comment by da638** [comment]
noice you mean

**Comment by da638** [comment]
i guess we just wait for them and explain

**Comment by Protuber** [comment]
wh=ould you like it you can set runes to any percentage? like for example 25%dmg runes to 1000

**Comment by da638** [comment]
oh so you were the one that request that issue

**Comment by Protuber** [comment]
yeah

**Comment by da638** [comment]
and yea

**Comment by Protuber** [comment]
i think if they add that the arena to would so much easier

**Comment by da638** [comment]
ikr

**Comment by Protuber** [comment]
also  i have to hack to get a lot of food because I was not going tp make it off only 41 cakes

**Comment by da638** [comment]
i litraaly cant even battle my friends becuase i am to op but it dosent work

**Comment by da638** [comment]
haha lol so ture

**Comment by Protuber** [comment]
do you hack to get alot of food

**Comment by da638** [comment]
but there is a hack that you could get infinte food i dont remeber

**Comment by da638** [comment]
i am going to school tommorow but the good thing is that i get to do all my work

**Comment by Protuber** [comment]
nice

**Comment by Protuber** [comment]
i hope you do good at you school work it was fun talking to you

**Comment by da638** [comment]
yea lets be friends

**Comment by da638** [comment]
you fun

**Comment by Protuber** [comment]
thanks

**Comment by da638** [comment]
:)

**Comment by Protuber** [comment]
do you know why funny do you know those temp email in the web store

**Comment by da638** [comment]
what is your faviourte meme

**Comment by Protuber** [comment]
my mee if the coffin dance

**Comment by da638** [comment]
yea i tried to use one but it dint work so i got an offical account

**Comment by da638** [comment]
yo the coffin dance and the oof toghter op

**Comment by Protuber** [comment]
ik

**Comment by da638** [comment]
who is your faviourte channel mines is socks for 1

**Comment by da638** [comment]
i also have a channel

**Comment by Protuber** [comment]
my is stampy and mrbeast

**Comment by da638** [comment]
mr beast gang

**Comment by Protuber** [comment]
what you channel ima sub to you

**Comment by da638** [comment]
my channel name might sound cringe but its called cuitex

**Comment by Protuber** [comment]
ok

**Comment by da638** [comment]
my profile picture is naruto

**Comment by Protuber** [comment]
oof

**Comment by da638** [comment]
hahahahaha

**Comment by da638** [comment]
its crazy how we got to 46 comments already

**Comment by Protuber** [comment]
can you send me the link you your youtube channle

**Comment by da638** [comment]
sure

**Comment by da638** [comment]
give me a sec

**Comment by Protuber** [comment]
k

**Comment by da638** [comment]
how do you send a link

**Comment by da638** [comment]
i do not know

**Comment by Protuber** [comment]
alsi wanna know why you can do it at school it because at school they block the hacks I tried to hack but it was blocked by an admin

**Comment by da638** [comment]
i got it right here https://www.youtube.com/channel/UCo8wIvZXVQRtvO3AaMXCEnw

**Comment by Protuber** [comment]
ok

**Comment by da638** [comment]
oh you in troubleeeeeeeeeeeeeeeee

**Comment by da638** [comment]
i ma uploud next saturday

**Comment by Protuber** [comment]
is that your face of your youtube channel?

**Comment by da638** [comment]
The naruto picture yea

**Comment by Protuber** [comment]
ok

**Comment by da638** [comment]
i only have one video

**Comment by LeoBadeaux** [comment]
If your school doesn't let you get hacks we can't fix that

**Comment by da638** [comment]
have you sub yet

**Comment by da638** [comment]
ahhhhhhhhhhhhhhhhhh

**Comment by Protuber** [comment]
yes'

**Comment by da638** [comment]
oh its you

**Comment by da638** [comment]
so about the issue i posted

**Comment by Protuber** [comment]
and @LeoBadeaux thank you i was telling him school block this hackes

**Comment by da638** [comment]
why did you close it

**Comment by da638** [comment]
i said i dint use my school computer

**Comment by da638** [comment]
i used my home

**Comment by da638** [comment]
computer

**Comment by da638** [comment]
uh dude where are you

**Comment by da638** [comment]
protuber
