### ISSUE TITLE
[BUG]  Battle crashes even when i use fix battle crash

### ISSUE THREAD

**Issue by Protuber** [Prodigy-Hacking/ProdigyMathGameHacking#994]
***Description***:
It happens when joining the harmonyisand arena

***Replication***: Do fix battle and go back

***Images***:

***Additional Errors***:
Still happens

**Comment by da638** [comment]
protuber

**Comment by da638** [comment]
hey

**Comment by da638** [comment]
remeber me

**Comment by Protuber** [comment]
i know you

**Comment by da638** [comment]
hey its you

**Comment by PatheticMustan** [comment]
@Protuber sorry for the super late necro reply, what pets are you using?

**Comment by da638** [comment]
What do you mean?

**Comment by da638** [comment]
i use all petz

**Comment by 4evera1one** [comment]
what pets have you EQUIPPED

**Comment by donaldli2020** [comment]
Check your internet with a new account. If it works okay, the hacks probably broke your account.

**Comment by Treker38** [comment]
> @Protuber sorry for the super late necro reply, what pets are you using?

I assumed this earlier. I switched my Chill & Char for the Squarrel, and now when i go to a enemy, the enemy has the alert icon and goes to my location, but does not go in battle. After that, you can just stand on top of enemies without being detected. However the only difference between this and regular game mode is that you cannot walk into other areas.

**Comment by 4evera1one** [comment]
you might have used edit pet or crystal monster. try to delete hacked pets like crystal monsters and pets that you have used edit pet with.

**Comment by ConnorAhern** [comment]
sex

**Comment by donaldli2020** [comment]
No, no, no!

**Comment by donaldli2020** [comment]
Well, I guess...

**Comment by er509** [comment]
Delete the extension

**Comment by donaldli2020** [comment]
@github-actions is annoying.
*Description:* GitHub should lock down this account so it cannot be used impersonate the bot account
GitHub gives error 404 when I do https://github.com/github-actions

**Comment by 32n** [comment]
@PatheticMustan @ArcerionDev I think it would be safe to close this issue by now. It has led to a lot of off-topic discussion, and we haven't been provided with any helpful information.

**Comment by afkvido** [comment]
> @PatheticMustan @ArcerionDev I think it would be safe to close this issue by now. It has led to a lot of off-topic discussion, and we haven't been provided with any helpful information.

+upvote

**Comment by fingerprint53** [comment]
that true
