### ISSUE TITLE
well its not like there is a problem

### ISSUE THREAD

**Issue by da638** [Prodigy-Hacking/ProdigyMathGameHacking#996]
i want to guys to send me the link of the video to youtube

so that i could make a video about it and spread the word

so if you can send me the video it would be aprticated contact me at da740092@gmail.com

**Comment by Protuber** [comment]
what this issue for

**Comment by da638** [comment]
well to help you guys i guess

**Comment by da638** [comment]
wait its you protuber

**Comment by Protuber** [comment]
yes it me

**Comment by 29wumya** [comment]
Hi, i found the youtube but could not find it again. srry

**Comment by da638** [comment]
i will send you the link here
https://www.youtube.com/channel/UCo8wIvZXVQRtvO3AaMXCEnw

**Comment by da638** [comment]
youtube name might be cringe

**Comment by YamaHacks** [comment]
https://www.youtube.com/channel/UChIRMY6SdQrcADVscWTVv9A Official youtube channel is here
