### ISSUE TITLE
NOT BEING ABLE TO BATTLE ANYTHING

### ISSUE THREAD

**Issue by 29wumya** [Prodigy-Hacking/ProdigyMathGameHacking#999]
I tried many ways but it is not working, even the ways you sugested. It keeps on loading. It's like loading forever.

**Comment by BETPRODIGYHACKER** [comment]
reinstall da extinsion and use fix battele crash before battle then in the next 30-40 seconds go in to a battle

**Comment by da638** [comment]
it dont work

**Comment by YamaHacks** [comment]
Reinstall the extension and make sure that it isn't blocked, make sure to use fix battle crash as well

**Comment by da638** [comment]
can you do it on a school computer?

**Comment by hostedposted** [comment]
Did you use the skip tutorial hack?

**Comment by ShawnC32** [comment]
THIS APPLIED TO SC'S SCHOOL ACCOUNT

**Comment by PatheticMustan** [comment]
maybe you should have made an alt???

**Comment by PatheticMustan** [comment]
@29wumya, please attach errors. otherwise, will close the issue soon

**Comment by da638** [comment]
its still not working

**Comment by ShawnC32** [comment]
What if you used a vpn and battle takes too long?

**Comment by ShawnC32** [comment]
PHEX IS SOMETIMES BROKEN
